from pathlib import Path
import json,html,shutil
ROOT=Path(__file__).resolve().parents[3]
SOURCE_ICON_ID=None
SOURCE_PATH='icon_set/work/solo-hole-audit-100/repairs.json'
AUTHOR='gpt-6'
W=Path(__file__).parent;rows=json.loads((W/'repairs.json').read_text());dest=ROOT/'icon_set/dist/gallery'
notes=["The previous flame pocket only just passed the 2-unit diameter threshold. Its valley is now opened into one broad counter, preserving the flame and brick courses.","The tail no longer overlaps the lower back. It curls visibly outside the body and meets the rump at a real shared endpoint.","A fully filled small head circle hid a pocket. The head is now open, its body gap is exactly 4 units, and the flag clears the float.","The left four hid a long narrow pocket under overlapping ink. It now has an open construction; the zero was repositioned to keep even spacing."]
cards=[]
for r,note in zip(rows,notes):
 m=json.loads((ROOT/'icon_set/dist/qa/solo'/r['icon_id']/'metrics.json').read_text());assert m['status']=='pass',r['icon_id'];holes=m['negative_space']
 cards.append(f'<article><h2>{html.escape(r["parent"])}</h2><div class="pair"><figure><img src="../solo48/{r["parent"]}.svg" onerror="this.onerror=null;this.src=\'../failed/solo48/{r["parent"]}.svg\'"><figcaption>Before</figcaption></figure><figure><img src="../solo48/{r["icon_id"]}.svg"><figcaption>After</figcaption></figure></div><p>{html.escape(note)}</p><p><strong>Spacing, holes and pinches: pass</strong></p><p>{holes["failed_hole_count"]} undersized holes · {holes["pinch_count"]} pinches</p><p><a href="../solo48/{r["icon_id"]}.svg">Revised SVG</a> · <a href="../qa/solo/{r["icon_id"]}/metrics.json">Measurements</a></p></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Hole and tail corrections</title><style>body{font:16px/1.5 system-ui;background:#f6f5f1;color:#222b35;margin:32px}header{max-width:1000px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}article{background:white;padding:22px;border-radius:12px;border:1px solid #ddd}h2{font-size:18px;overflow-wrap:anywhere}.pair{display:flex;gap:26px}figure{margin:10px 0}figure img{width:120px;height:120px}figcaption{font-size:13px}a{color:#255eab}</style><header><h1>Hole and tail corrections</h1><p>The two reported icons are repaired. Rechecking all 100 also found two hidden pockets in the diver and 404 label.</p><p>The pinch checker now tests the actual 4-unit strokes at its configured 1-unit depth. Previously, subtracting the hole-measurement adjustment reduced the check to zero. Numeric thresholds and the circle hole exception are unchanged; pinch failures remain blocking.</p><p><a href="solo-review-batch-100.html">Full updated batch of 100</a></p></header><main>'''+''.join(cards)+'</main></html>'
(dest/'hole-review-batch-100.html').write_text(page)
(W/'REPORT.md').write_text('# Hole and tail follow-up\n\n'+ '\n\n'.join(f'## {r["icon_id"]}\n\n{note}' for r,note in zip(rows,notes))+'\n\nAll four revised icons pass model validation, spacing, holes and authored-stroke pinches without review exemptions. The full 100-icon batch was rechecked. Of 40 QA tests, 38 pass, including the new pinch regression; the two failing existing fixtures are recorded in tests.log and also failed before this turn.\n')
print('Follow-up report saved')
