"""Framed Achievement Certificate.

Symbol plan: Empty rectangular certificate with four quarter-circle corner ornaments generated by shared radius. HRECT_M centerline extremes (4,10)-(44,38); horizontal and vertical symmetry.
"""
from icon_set.model.keyshapes import Keyshape
from icon_set.model.icons.solo._base import Solo48
SOURCE_ICON_ID = '146cf283-3304-46a9-8cae-29ee66a6a52f'
SOURCE_PATH = 'pictographic-primitives/container/certificate_146cf283-3304-46a9-8cae-29ee66a6a52f.svg'
AUTHOR = 'gpt-6'

class Drawing(Solo48):
    icon_id = 'framed-achievement-certificate'
    keyshape = Keyshape.HRECT_M
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'container'
    aliases = ()
    keywords = ('framed', 'achievement', 'certificate')

    def circle(self, name, x, y, r):
        self.add_arc(name+'-a', (x-r,y), (x+r,y), radius_x=r)
        self.add_arc(name+'-b', (x+r,y), (x-r,y), radius_x=r)
        self.add_contour(name, name+'-a', name+'-b', closed=True)

    def rounded_box(self, name, left, top, right, bottom, r):
        self.add_line(name+'-top', (left+r,top), (right-r,top))
        self.add_arc(name+'-tr', (right-r,top), (right,top+r), radius_x=r)
        self.add_line(name+'-right', (right,top+r), (right,bottom-r))
        self.add_arc(name+'-br', (right,bottom-r), (right-r,bottom), radius_x=r)
        self.add_line(name+'-bottom', (right-r,bottom), (left+r,bottom))
        self.add_arc(name+'-bl', (left+r,bottom), (left,bottom-r), radius_x=r)
        self.add_line(name+'-left', (left,bottom-r), (left,top+r))
        self.add_arc(name+'-tl', (left,top+r), (left+r,top), radius_x=r)
        self.add_contour(name, *(name+'-'+part for part in ('top','tr','right','br','bottom','bl','left','tl')), closed=True)

    def build(self):
        left,top,right,bottom,r=4,10,44,38,8
        self.add_polyline('frame',(left,top),(left+r,top),(right-r,top),(right,top),(right,top+r),(right,bottom-r),(right,bottom),(right-r,bottom),(left+r,bottom),(left,bottom),(left,bottom-r),(left,top+r),closed=True)
        for name,start,end in [
         ('top-left',(left+r,top),(left,top+r)),
         ('top-right',(right,top+r),(right-r,top)),
         ('bottom-right',(right-r,bottom),(right,bottom-r)),
         ('bottom-left',(left,bottom-r),(left+r,bottom))]:
            self.add_arc(name,start,end,radius_x=r)
            self.relate('connect',name,'frame')
