from pathlib import Path
import json,html,hashlib
w=Path(__file__).parent;p=json.loads((w/'active-plan.json').read_text());out=Path('icon_set/dist/gallery/remaining-70-review.html')
style='''body{font:15px system-ui;margin:0;background:#f3f4f6;color:#20242a}header{position:sticky;top:0;padding:20px 30px;background:#fff;border-bottom:1px solid #ddd;z-index:2}h1{font-size:24px;margin:0 0 8px}p{margin:8px 0}input{padding:10px;border:1px solid #bbb;border-radius:6px;width:270px}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:16px;padding:24px}article{background:#fff;border-radius:12px;padding:18px}h2{font-size:14px;overflow-wrap:anywhere}.samples{display:flex;justify-content:space-around;text-align:center}.samples svg{width:96px;height:96px;display:block}.samples span{font-size:12px;color:#666}.lines svg{stroke-width:.65}details{margin-top:16px}.small svg{width:48px;height:48px}.native{display:flex;gap:12px;align-items:center;margin-top:14px}.dark{background:#20242a;color:white;padding:6px;border-radius:6px}.light{padding:6px}.pass{color:#187347;font-size:12px}a{color:#185abc}'''
def clean(s):
 import re
 return re.sub(r' id="[^"]*"','',s)
cards=[];rows=[]
for g in p:
 n=g['root'];old=clean((w/'before'/(n+'.svg')).read_text());new=clean((Path('icon_set/dist/solo48')/(n+'.svg')).read_text());cards.append(f'''<article data-name="{html.escape(n)}"><h2>{g['number']}. {html.escape(n)}</h2><p class="pass">Build and overlays passed</p><div class="samples"><div>{old}<span>Before</span></div><div>{new}<span>Final</span></div><div class="lines">{new}<span>Drawing lines</span></div></div><div class="native small"><div class="light">{new}</div><div class="dark">{new}</div><span>Actual size</span></div></article>''');rows.append({'icon_id':n,'number':g['number'],'source':g['target_file'],'published_sha256':hashlib.sha256((Path('icon_set/dist/solo48')/(n+'.svg')).read_bytes()).hexdigest(),'status':'pass'})
out.write_text(f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>70-icon repair review</title><style>{style}</style></head><body><header><h1>70-icon repair review</h1><p>66 originals repaired · 4 discarded · no new versions in this batch</p><p>Discarded: KakaoTalk, LINE, square LINE, Meetup.</p><input id="search" placeholder="Find an icon" aria-label="Find an icon"> <a href="index.html?tab=failed&family=solo">Open failed gallery</a></header><main>{''.join(cards)}</main><script>document.querySelector('#search').addEventListener('input',e=>{{const q=e.target.value.toLowerCase();document.querySelectorAll('article').forEach(a=>a.hidden=!a.dataset.name.includes(q))}});</script></body></html>''')
(w/'completed.json').write_text(json.dumps({'repaired':rows,'discarded':['kakaotalk-logo','line-logo','line-logo-square','meetup-wordmark'],'new_variants':0},indent=2));print(out)
