from pathlib import Path
import json
P=Path(__file__).parent
F={};D={int(k):v for k,v in json.loads((P/'solo-drafts.json').read_text()).items()}
def c(name,family,description):return dict(name=name,family=family,description=description)
def add(i,name,kind,description,reason,components,position=None,question=None):
 F[i]=dict(classification=kind,reason=reason,components=components)
 if position:F[i]['modifier_position']=position
 if question:F[i]['uncertainty']=question
 D[i]=dict(index=i,concept=name,icon_id='review-source-'+str(i),family='solo',description=description,tags=['reference','review','source','outline','drawing','pending'])
def side(i,name,desc,reason,comps,pos):add(i,name,'side_combination',desc,reason,comps,pos)
def box(i,name,desc,reason,comps):add(i,name,'container_combination',desc,reason,comps)
square=c('Rounded Square Frame','container','A blank rounded square enclosure. Exclude all enclosed symbols and marks.')
house=c('Pitched-Roof House','solo','A small house with a pitched roof and central doorway. Exclude the adjacent modifier, chart, hand, or other surrounding elements.')
right=c('Right Arrow','sub','A horizontal shaft ending in a right-facing open arrowhead. Exclude the surrounding enclosure or adjacent subject.')
star=c('Five-Point Star','sub','A single upright five-point star with an empty center. Exclude the podium, house, booklet, and other surrounding objects.')
side(27,'Star Above Pedestal','A five-point star floats above a rectangular pedestal with a broad top slab and two supporting sides.','The star is detached above a complete pedestal and reads as an achievement modifier, rather than an attached structural part.',[c('Plain Pedestal','solo','A rectangular pedestal with a broad flat top slab and upright support sides. Exclude the floating star.'),star],'above, centered over the pedestal')
side(32,'Traveler with Airplane Mark','A walking person carries a rectangular case at the left; a small upright airplane mark floats beside the upper right of the figure.','The traveler is complete with a carried case; the much smaller detached airplane acts as an air-travel qualifier instead of a physically held object.',[c('Walking Traveler with Case','solo','A walking figure with a circular head, outstretched right arm, and rectangular case held at the left. Exclude the floating airplane.'),c('Upright Airplane Mark','sub','A small airplane seen from above, with a straight fuselage, sloping wings, and small tail. Exclude the traveler and case.')],'upper-right, beside the head and shoulder')
side(36,'Person with Right Arrow','A circular head sits above a rounded shoulder block, beside a right-facing arrow.','The detached arrow is a reusable direction modifier applied to a complete person bust.',[c('Plain Person Bust','solo','A circular head above a broad rounded shoulder and torso block. Exclude the arrow.'),right],'right, beside the shoulder')
box(38,'Eye in Triangle','An almond-shaped eye with a round pupil sits inside an upright triangular border.','The eye is an independent symbol enclosed by a separate triangle.',[c('Upright Triangle Frame','container','An empty upright triangular border. Exclude the eye and pupil.'),c('Almond Eye','sub','An almond-shaped eye outline with a circular pupil centered inside. Exclude the surrounding triangle.')])
add(43,'Bone and Leaf','uncertain','A diagonal bone with rounded ends sits beside a pointed leaf with a central vein.','The bone and leaf are separated at a similar scale; the leaf may represent plant remains alongside bone or an ecological modifier.',[c('Diagonal Bone','solo','A bone tilting down to the right, with paired rounded lobes at both ends. Exclude the leaf.'),c('Pointed Leaf','sub','A pointed oval leaf with a central vein and short lower stem. Exclude the bone.')],question='Are these two kinds of organic remains, or is the leaf an ecological modifier applied to the bone? Keep whole-reference generation on hold.')
def typecase(i,name,char,desc):
 add(i,name,'typeface_reuse',desc,'The visible subject is a readable character or punctuation pair; preserve it through typeface reuse.',[c(name,'typeface',f'Reuse the exact character {char!r} from the preferred existing typeface glyph. Preserve its upright arrangement and exclude any invented replacement glyph.')])
typecase(44,'Uppercase Q','Q','A large circular letter Q has a diagonal tail crossing its lower right edge; the source filename names Qualcomm, but the render contains only this character.')
typecase(54,'Closing Double Quotation Mark','”','Two rounded comma-shaped marks sit side by side, with their tails descending and curving left.')
side(49,'Row Lines with Remove Cross','Two horizontal lines sit to the right of a detached diagonal cross.','The cross is a standalone removal modifier placed beside abstract row lines, not a structural part of the lines.',[c('Two Row Lines','sub','Two short horizontal parallel lines with a wide vertical gap. Exclude the cross.'),c('Remove Cross','sub','Two diagonal strokes intersect to form an X-shaped removal mark. Exclude the row lines.')],'left, centered between the two rows')
box(50,'History Mark in Upright Panel','An upright rounded panel surrounds a nearly circular clockwise arrow with clock hands.','The clock-history glyph is distinct from the enclosing panel.',[c('Upright Rounded Panel','container','A blank upright panel with rounded corners. Exclude the history glyph.'),c('Clock History Arrow','sub','A near-circular clockwise arrow wraps around two clock hands, one pointing up and the other down-right. Exclude the panel.')])
box(51,'Clock on Document','A round clock sits within a document with a clipped upper right corner and one line below.','The clock is a separate symbol hosted by the page.',[c('Clipped-Corner Document','container','An upright document with a clipped upper right corner and a short lower text line. Exclude the clock.'),c('Clock with Right-Angled Hands','sub','A circular clock with one hand pointing upward and another pointing right. Exclude the document and text line.')])
side(55,'Descending Bars with Downward Arrow','Three bars descend in height from left to right below a diagonal down-right arrow.','The separated arrow supplies a downward-trend state to independently recognizable bars.',[c('Three Descending Bars','sub','Three rectangular bars decrease in height from left to right on a shared baseline. Exclude the arrow.'),c('Diagonal Down-Right Arrow','sub','A long diagonal shaft ends in an open down-right arrowhead. Exclude the bars.')],'above, sloping down toward the lower right')
side(56,'Tag with Leaf','A diagonal clipped-corner tag with a round hole sits above-left of a separate pointed leaf.','The leaf floats beside a complete tag as an ecological qualifier, without a stem or fastening attaching it to the tag.',[c('Diagonal Blank Tag','solo','A blank tag angled lower-left to upper-right, with clipped shoulders and a round hole near its top. Exclude the leaf.'),c('Ecological Leaf','sub','A pointed leaf with a curved center vein and a short projecting stem. Exclude the tag.')],'lower-right, outside the tag')
side(63,'House with Pointing Hand','A small house sits above a large pointing hand, whose index finger rises at the left of the house.','The raised finger reads as a selecting action beside a complete house glyph, rather than carrying the building.',[house,c('Pointing Hand','sub','A hand with an extended upright index finger, folded remaining fingers, and left-projecting thumb. Exclude the house.')],'lower-left, finger pointing toward the house')
box(66,'Handshake Beneath Roof','A two-handed handshake with squared cuffs sits beneath a detached pitched roof outline.','The roof acts as an open enclosure over a separate handshake symbol.',[c('Open Pitched Roof','container','Two diagonal roof slopes meet at a central apex, open below. Exclude the handshake.'),c('Handshake with Cuffs','sub','Two hands meet in a handshake with squared cuffs at both sides and curved fingers below. Exclude the roof.')])
side(72,'House with Three Rating Stars','Three stars arch above a small house, with the central star larger than the outer two.','The detached stars are a reusable rating modifier above an independently recognizable house.',[house,c('Three Rating Stars','sub','A large central five-point star flanked by two smaller stars at the same lower level. Exclude the house.')],'above the roof, centered')
side(75,'Picture with Retouch Wand','A landscape picture shows two mountain peaks and a round sun; a diagonal wand with radiating marks overlaps its upper right corner.','The wand is a detached editing modifier in a cleared frame corner; the picture frame and landscape content are also independently identifiable.',[c('Picture Frame','container','A rounded square picture enclosure, completing the corner interrupted by the wand. Exclude the landscape and wand.'),c('Mountain and Sun Picture Content','sub','Two overlapping mountain peaks beneath a small round sun at upper left. Exclude the frame and wand.'),c('Retouch Wand','sub','A short diagonal wand with small rays around its upper end. Exclude the picture and frame.')],'upper-right, overlapping a gap in the picture frame')
side(81,'Open Book with Globe','An open book has paired text lines on its pages beneath the visible upper half of a gridded globe.','The globe qualifies the book with a world theme and is a separate symbol above the page edges, rather than a printed page detail.',[c('Open Book with Text Lines','solo','An open book has curved top page edges, a central binding, and two short lines on each page. Exclude the globe.'),c('Wireframe Globe','sub','A round globe with curved meridians and a horizontal latitude line. Complete the portion hidden behind the book; exclude the book.')],'above, lower globe edge occluded by the book')
typecase(82,'Opening Double Quotation Mark','“','Two broad opening quotation marks sit side by side, each curling upward from a rounded lower block.')
side(85,'Resume Page with Person','A document has a small square and two horizontal lines, with a large person figure overlapping its right edge.','The person sits outside the page in a cleared gap, acting as an applicant qualifier rather than a portrait printed inside it.',[c('Resume Page with Placeholder','container','An upright document with a small square at upper left and two horizontal text lines below. Complete the right boundary and exclude the person.'),c('Standing Person Mark','sub','A circular head above a small rounded shoulder block and tapered lower body. Exclude the page.')],'right, overlapping the page boundary')
box(88,'Four-Cell Code Panel','A rounded square surrounds four smaller square cells in a two-by-two grid; the lower right cell has gaps.','The separate code-like four-cell glyph sits within its own enclosure.',[square,c('Four-Cell Code Mark','sub','Four small squares form a two-by-two grid; the lower right square has interrupted sides. Exclude the outer panel.')])
box(94,'People Discussing a House','Two person busts sit below a speech bubble containing a small house.','A house glyph is enclosed by a speech bubble, while the two speakers form a third independently visible subject.',[c('Speech Bubble','container','A rounded rectangular speech bubble with a short downward tail. Exclude the house and people.'),house,c('Two Person Busts','solo','Two circular heads sit above separate curved shoulders at the same level. Exclude the house and speech bubble.')])
side(95,'House with Calculator','A four-key calculator overlaps the lower left of a pitched-roof house, whose outline is interrupted behind it.','The complete calculator acts as a cost-calculation qualifier against the separate house outline.',[house,c('Four-Key Calculator','sub','A rounded square calculator divided into four keys marked plus, minus, multiplication cross, and equals. Exclude the house; these are the physical calculator controls.')],'lower-left, overlapping the house')
side(96,'House with Rising Trend Arrow','A house has an arched doorway and an interrupted lower right edge beside a rising zigzag arrow.','The arrow is a separate increase modifier overlapping a cleared corner of the house.',[house,c('Rising Zigzag Arrow','sub','A line rises, dips once, and rises to an open arrowhead at upper right. Exclude the house.')],'lower-right, overlapping the house corner')
box(97,'House Inside Segmented Circular Chart','A small house sits within a large circular outline with a detached thick quarter segment at upper right.','The house is a separate central glyph inside a chart-like circular enclosure.',[c('Segmented Circular Chart Frame','container','A large circular border with an interrupted upper-right arc and a thick detached quarter-ring segment. Exclude the house.'),house])
box(102,'Right Arrow in Rounded Square','A horizontal right arrow sits in the middle of a rounded square border.','The arrow is an independent direction glyph within the enclosure.',[square,right])
box(103,'Right Arrow Between Brackets','A right-facing arrow sits between two rounded vertical brackets with open top and bottom centers.','The paired brackets form an independent enclosure around the arrow.',[c('Paired Rounded Brackets','container','Left and right vertical brackets with rounded upper and lower turns and open centers above and below. Exclude the arrow.'),right])
typecase(104,'Closing Double Quotation Pair','”','Two thick closing quotation marks sit side by side, with rounded upper blocks and long curved lower tails.')
for i,rounded in [(107,True),(108,False)]:
 side(i,'Rising Bars with Upward Arrow','Three bars increase in height from left to right, with a diagonal up-right arrow above them.','The detached arrow is a reusable increase modifier applied above the bar chart.',[c('Three Rising Bars'+(' with Rounded Tops' if rounded else ''),'sub','Three vertical bars rise in height from left to right, '+('with softly rounded upper corners.' if rounded else 'with square corners.')+' Exclude the arrow.'),c('Diagonal Up-Right Arrow','sub','A straight diagonal shaft ends in an open upper-right arrowhead. Exclude the bars.')],'above, sloping upward toward the right')
for i in [111,118]:box(i,'Cross in Rounded Square','Two diagonal lines form a cross inside a rounded square.','The removal cross is separate from the enclosing frame.',[square,c('Diagonal Cross','sub','Two diagonal strokes meet to form an X-shaped cross. Exclude the frame.')])
box(117,'Barcode in Rounded Panel','Seven thin upright lines of varying lengths sit inside a rounded square panel.','The barcode-like vertical-line glyph is hosted inside a distinct border.',[square,c('Seven-Line Barcode','sub','Seven narrow parallel vertical lines with subtly differing top and bottom positions. Exclude the enclosing panel.')])
box(120,'Star on Booklet Cover','A standing booklet has a sloping rear page visible above its cover, with a star and two text lines on the front.','The star is a separately meaningful rating mark on the booklet enclosure.',[c('Upright Booklet Cover','container','An upright booklet with a rear page angled above the cover and two short lower text lines. Exclude the star.'),star])
box(121,'Envelope in Target Frame','A closed envelope sits within a segmented circular target whose diagonal corner ticks point inward.','The envelope glyph is distinct from the surrounding targeting enclosure.',[c('Segmented Target Frame','container','A circular target formed by four separated arcs and four diagonal corner ticks. Exclude the envelope.'),c('Closed Envelope','sub','A horizontal envelope with rounded corners and a triangular folded flap. Exclude the surrounding target.')])
box(131,'Up Arrow in Rounded Square','An upward arrow is centered within a rounded square border.','The independent arrow is hosted by a separate square enclosure; the source title riser does not describe stairs in the render.',[square,c('Up Arrow','sub','A vertical shaft rises into an open symmetric arrowhead. Exclude the square border.')])
assert len(F)==35,len(F)
assert len(D)==135,len(D)
D[106]['icon_id']='triangle-right-soft-corners';D[113]['icon_id']='t-shirt-round-neck-short-sleeves'
used=set(json.loads((P/'existing-ids.json').read_text())); collisions=[d['icon_id'] for i,d in D.items() if i not in F and d['icon_id'] in used];assert not collisions,collisions
(P/'flagged.json').write_text(json.dumps(F,indent=2)+'\n');(P/'drafts.json').write_text(json.dumps([D[i] for i in range(135)],indent=2)+'\n')
(P/'solo-drafts.json').write_text(json.dumps({i:d for i,d in D.items() if i not in F},indent=2)+'\n')
print('Written 35 review handoffs; all 100 solo IDs are available')
