from pathlib import Path
import json,re
P=Path(__file__).parent
# Descriptions written after inspecting each 320px and 48px reference.
raw='''0|Planet with Small Moon|A large round planet has two curved surface marks and a small circular moon overlapping its upper right edge. The planet remains a plain circular body apart from the two open crater-like arcs.|planet,moon,space,orbit,astronomy,satellite
1|Pleated Fabric Panel|A hanging fabric panel has a broad straight band across its top and long vertical pleats below. The folds end in a gently wavy lower hem, with rounded corners at the outer edges.|pleat,fabric,cloth,fold,curtain,textile
2|Plum with Curved Seam|A round plum has a shallow notch at the top, a curved stem bending left, and a pointed leaf extending right. A long curved seam follows the right side of the fruit toward its base.|plum,fruit,leaf,stem,produce,food
3|Suspended Plumb Bob|A pointed plumb bob hangs vertically from a straight cord through a small rounded attachment. Its wide, slightly shouldered top narrows symmetrically into a long triangular tip below.|plumb,bob,weight,cord,construction,tool
4|Pointed Patch Pocket|An upright patch pocket has a flat open top, straight sides, and a gently pointed lower edge. A shallow curved row of dashed stitching runs just beneath the upper rim.|pocket,patch,clothing,stitch,sewing,garment
5|Police Car with Flashing Beacon|A police car appears from the side with two round wheels beneath a long rounded body. A divided cabin sits above, topped by a small roof beacon with three short radiating light marks.|police,car,beacon,vehicle,patrol,emergency
6|Pomelo with Single Leaf|A large rounded pomelo narrows slightly at the top where a short stem rises. A pointed oval leaf sits beside the stem, while the body remains unmarked and broadly curved below.|pomelo,citrus,fruit,leaf,stem,food
7|Pond with Cattail|A low oval pond contains two short wavy water lines. A single upright cattail grows from the far bank, with a rounded seed head and two narrow leaves curving away from its stem.|pond,cattail,water,reed,wetland,nature
8|Poster with Picture Placeholder|An upright poster has a rounded rectangular outer edge, a blank square picture area near the top, and two short horizontal text lines beneath it. The lower line is shorter than the upper one.|poster,paper,layout,picture,notice,print
9|Powder Jar and Small Heap|An upright jar with a broad rounded lid stands behind a low mound of powder. The mound has a rounded triangular silhouette and overlaps the jar's lower right corner, interrupting its outline.|powder,jar,heap,container,material,storage
10|Primitive Bull Profile|A bull faces left with a long rounded body, a low snout, and two sweeping horns. Four thin legs descend from the belly, with bent hind legs contrasting with the straighter forelegs.|bull,cattle,horn,animal,livestock,profile
11|Printer Producing a Landscape Picture|A wide printer has a rounded body and an upright sheet entering from above, with its upper right corner folded. A square print emerges in front, showing two connected mountain peaks.|printer,picture,photo,paper,print,office
12|Prison Gate with Arched Door|A rounded prison gate has broad horizontal bands at its top and bottom. Vertical bars divide the middle, framing a central arched doorway whose upper curve meets the middle bar.|prison,gate,bars,door,cell,security
13|Planet with Diagonal Ring|A circular planet is crossed by a long elliptical ring running from lower left to upper right. The ring passes in front of the lower part of the globe and reappears behind its upper edge.|planet,ring,saturn,space,astronomy,orbit
14|Opposing Airplanes Seen from Above|Two airplanes are stacked diagonally, with the upper plane facing left and the lower plane facing right. Each has swept wings, a small tail assembly, and a short dashed trail behind it.|airplane,flight,return,travel,aircraft,journey
15|Opposing Airplanes in Profile|Two small airplane profiles face opposite directions on separate levels. The upper aircraft points left and the lower points right, each with a raised wing and tail; a dashed trail follows the lower plane.|airplane,profile,flight,travel,return,aircraft
16|Rounded Equal-Armed Plus|A broad upright plus has four equal-looking arms joined around an open center area of the silhouette. Each arm ends in a softly rounded cap, giving the outline a balanced cross shape.|plus,add,positive,operator,addition,cross
17|Hard Hat Above Roller Conveyor|A domed hard hat with a broad brim and central raised ridge sits above a short conveyor. The conveyor has a rounded horizontal body with three evenly spaced circular rollers visible inside.|helmet,hardhat,conveyor,factory,manufacturing,safety
18|Short-Sleeved Polo Shirt|A front-facing polo shirt has short angled sleeves and a straight lower hem. Two folded collar points meet at the center above a short vertical placket descending onto the plain chest.|polo,shirt,collar,sleeve,clothing,garment
19|Five-Petaled Flower on Stem|A flower faces forward with five broad rounded petals around a small circular center. A slender stem descends beneath the bloom, with one pointed leaf branching left near the bottom.|flower,poppy,petal,stem,leaf,botanical
20|Round Inspection Mirror|A large circular mirror sits on a short straight neck above a narrow upright handle. The mirror face is blank, and the handle has straight sides with a rounded lower end.|mirror,inspection,probe,handle,tool,round
21|Curving Pinworm|A long smooth worm curves through alternating bends, dipping down from the upper left before rising toward the right. Its body has rounded ends and an even, soft ribbon-like thickness.|pinworm,worm,parasite,animal,curve,biology
22|Single Diagonal Feather|A long feather angles from lower left to upper right, with a narrow shaft extending below its pointed vane. A central quill runs partway upward, and a sharp notch breaks the right edge.|feather,plume,quill,bird,vane,writing
23|Plover Standing in Profile|A small plover faces right with a rounded head, pointed beak, and a tiny eye. Its long sloping back leads to a pointed tail, while a curved wing sits above two thin standing legs.|plover,bird,shorebird,wing,beak,wildlife
24|Tadpole with Raised Tail|A tadpole faces left with a broad rounded head and a small circular eye. Its body narrows into a long curved tail that sweeps right and bends upward at the tip.|tadpole,polliwog,amphibian,frog,tail,pond
25|Plywood Panel with Grain|A square wooden panel has rounded corners and a small circular fixing near each corner. Several flowing grain lines cross the face, including an elongated open knot entering from the right edge.|plywood,wood,panel,grain,board,material
26|Pony Facing Left|A pony stands in left-facing profile with a short pointed ear, rounded muzzle, and gently sloping neck. Its long back meets a hanging curved tail, while two broad visible legs support the body.|pony,horse,animal,tail,livestock,equine
28|Banded Oval Planula|An elongated oval organism tapers into rounded ends, with a narrower upper tip. Three curved transverse bands cross its body, following the outward swell of the middle rather than forming straight stripes.|planula,larva,organism,biology,oval,banded
29|Three-Level Winners Podium|A winners podium consists of three adjoining rectangular platforms. The central block rises highest, the right block is intermediate, and the left block is lowest, all meeting on a common baseline.|podium,winner,platform,ranking,award,sport
30|PureScript Chevron Emblem|Three slanted ribbon-like bars are stacked vertically between opposing open chevrons. The middle bar leans opposite to the upper and lower bars, while the left and right chevrons frame the arrangement.|purescript,logo,chevron,emblem,programming,language
31|Curved Smoking Pipe|A smoking pipe has a deep rounded bowl on the left with a flat upper rim. The bowl flows into a slender curved stem that rises to a short open mouthpiece on the right.|pipe,smoking,bowl,stem,tobacco,mouthpiece
33|Outlet Plate with Hexagonal Recess|A rounded square outlet plate surrounds a broad horizontal hexagonal recess with softened corners. The recess is blank, with no visible pin holes or switches inside the outlined opening.|outlet,socket,plate,hexagon,electrical,recess
34|Three-Hole Round Power Socket|A rounded square wall plate contains a large circular socket face. Two small round pin holes sit side by side above a wider semicircular grounding opening, creating a symmetric arrangement.|socket,outlet,electrical,power,plug,wall
35|Police Officer in Peaked Cap|A front-facing police officer has a blank rounded face beneath a peaked cap with a circular badge. The shoulders form a uniform bust, with an open pointed collar, center seam, and round chest badge.|police,officer,uniform,cap,badge,person
37|Upright Pole on Flat Foot|A slender vertical pole rises from the middle of a short horizontal foot. Both the shaft and base are plain straight lines, with no flag, attachments, or ornament visible.|pole,post,stand,upright,support,base
39|Blank Panel with Header Band|An upright rounded panel has a single horizontal divider close to its top. The shallow upper band and larger lower area are both blank, with matching rounded corners around the outer edge.|panel,header,card,frame,blank,layout
40|Arrow Right with Open Point|A long horizontal shaft runs into a right-facing open arrowhead. Two straight diagonal arms meet at the tip, forming a broad symmetric point without an enclosing outline around the shaft.|arrow,right,direction,forward,navigation,pointer
41|Folded Awareness Ribbon|A broad ribbon forms a rounded loop at the top and crosses over itself below. Its two flat-cut tails spread diagonally downward, with the front strand passing from upper right to lower left.|ribbon,awareness,loop,fabric,crossed,support
42|Falling Bomb Above House|A small bomb descends diagonally toward a house, with its rounded nose pointing lower right and angular tail fins above. The house has a pitched roof and arched doorway, with a short motion stroke behind the bomb.|bomb,house,war,airstrike,building,conflict
45|Car Viewed from the Rear|A car appears straight from behind with a broad rounded body and a narrower sloping rear window above. Two tires project below, while short inward-curving marks indicate the rear lights.|car,rear,vehicle,window,tire,transport
46|Coin Purse with Top Clasp|A small coin purse has a rounded lower body that narrows toward its rigid upper frame. A single rounded clasp protrudes at the top center, and the frame follows the sloping shoulders.|purse,coin,clasp,bag,wallet,accessory
47|Arrow Turning Right|An upright arrow rises from the lower left before curving smoothly into a horizontal shaft toward the right. A broad open arrowhead terminates the upper arm, with two diagonal sides meeting at its point.|arrow,right,turn,curve,direction,navigation
48|Four-Patch Quilt|A rounded square quilt is divided into four equal patches by a vertical and horizontal seam. Short curved fold marks appear in the upper left and lower right patches, leaving the opposite patches blank.|quilt,patchwork,blanket,fabric,seam,textile
52|Rounded List Panel|A rounded square panel contains three short horizontal lines stacked vertically with even spacing. The lines are aligned at both ends and sit within a wide blank margin around the panel.|list,panel,document,text,layout,menu
53|Concentric Hexagonal Emblem|A large horizontal hexagon with gently rounded corners surrounds a smaller regular hexagon. A small circle sits at the shared center, producing three nested outlines without connecting lines or other marks.|hexagon,emblem,concentric,center,geometry,symbol
57|Eight-Spoked Circular Wheel|A circular wheel is divided into eight wedge-shaped sections by straight spokes meeting at its center. The outer rim is a single unbroken circle, and no separate central hub is visible.|wheel,spoke,buddhism,circle,religion,symbol
58|Folder Holding Resume Sheet|An open folder with a stepped upper tab holds an upright sheet behind it. The visible page has one short horizontal line and a small square near the upper right corner.|folder,resume,document,paper,office,recruitment
59|Blank Upright Rounded Rectangle|A plain upright rectangular outline has broadly rounded corners and straight sides. Its entire interior is empty, with no color indicator, label, or other mark visible despite the source name.|rectangle,rounded,blank,panel,outline,shape
60|Fishing Reel with Side Crank|A round reel has a smaller circular center and a short handle descending beneath it. A thin crank extends to the right, ending in a small raised rounded grip with a downward trailing line.|reel,fishing,crank,handle,spool,tackle
61|Reason Studios Angular Emblem|A rounded hexagonal outer border surrounds an angular folded ribbon form. The inner shape follows the upper left sides, turns into a right-facing point, and folds down into a long lower triangular face.|reason,studios,logo,hexagon,emblem,ribbon
62|Hand Holding an Open Letter|A hand enters from the lower right and grips an open envelope by its right edge. A letter with one horizontal text line rises above the envelope, whose diagonal folds meet across the front.|letter,envelope,hand,mail,reading,correspondence
64|Two Hands Cupping a House|Two open hands rise on either side of a small house, with fingers upright and palms curving inward beneath it. The house has a pitched roof, an arched doorway, and small gaps at its upper walls.|house,hands,holding,home,property,shelter
65|Two Hands Cupping a Building|Two upturned hands flank a small building with an asymmetric sloping roofline. The building has a tall right section, a shorter left section with horizontal floor marks, and a small upright doorway.|building,hands,holding,property,architecture,shelter
67|Four-Section Radiator|A radiator has four rounded vertical sections joined into one broad body. The upper and lower edges dip between the sections, and two short pipes descend near the outer ends.|radiator,heating,pipe,section,home,appliance
68|Double-Headed Horizontal Arrow|A straight horizontal shaft connects two open arrowheads pointing in opposite directions. The diagonal arms extend equally above and below the shaft, forming a balanced left-right directional mark.|arrow,left,right,horizontal,bidirectional,direction
69|Horizontal Reflection Diagram|Two long thin horizontal bars are separated by a wide gap. A single diagonal line rises rightward from the middle of the lower bar, ending below the upper bar without touching it.|reflection,diagram,horizontal,bar,mirror,geometry
70|Truck Carrying a House|A small flatbed truck faces left with a rounded cab and two visible wheels. A house sits directly on the bed behind the cab, with a pitched roof and a central arched doorway.|truck,house,moving,transport,flatbed,vehicle
71|Explosion Striking a House|An irregular pointed blast overlaps the upper left corner of a house, enclosing a small diagonal capsule-like projectile. The house's roof and wall outlines are interrupted around the explosion, while its arched doorway remains visible.|explosion,house,war,damage,blast,conflict
73|Puzzle Piece with Right Tab|A rounded square puzzle piece has an outward circular tab on its right edge and an inward circular socket at the bottom. The top and left edges remain straight between softly rounded corners.|puzzle,piece,jigsaw,tab,socket,game
74|Measuring Jug with Three Marks|A tapered measuring jug has a pointed pouring spout at the upper left and a squared loop handle on the right. Three short measurement lines descend along the front of the plain body.|jug,measure,pitcher,spout,handle,kitchen
76|Rolling Hills Beneath the Sun|Several overlapping hills form a low landscape beneath a round sun in the upper left. Curved ridgelines rise and fall across the view, with the nearest hill bounded by a straight lower edge.|hill,landscape,sun,countryside,terrain,nature
77|Arrow Right with Long Shaft|A long straight shaft extends horizontally toward a compact right-facing open point. The arrowhead has two evenly angled arms, while the left end remains plain and unadorned.|arrow,right,long,forward,direction,navigation
78|Putty Knife with Broad Blade|A putty knife stands upright with a broad flat-edged blade at the top. The blade's sides curve inward toward a narrow neck, above a short handle with a rounded bottom.|putty,knife,scraper,blade,handle,tool
79|Round Reel and Bent Crank|A circular reel surrounds a smaller circular opening, with a short vertical grip beneath it. A horizontal crank projects rightward and bends up into a rounded end, with a thin line dropping from the bend.|reel,spool,fishing,crank,handle,tackle
80|Railing with Three Uprights|A short railing has broad horizontal top and bottom rails with rounded ends. Three straight vertical supports join the rails, evenly dividing the open space between them into adjoining bays.|railing,rail,fence,balustrade,barrier,upright
83|Overlapping Rounded Panels|Two upright rounded rectangles overlap diagonally. The taller rear panel sits at the upper left, while the smaller front panel covers its lower right corner; both interiors remain blank.|panel,rectangle,overlap,layer,window,shape
84|Three People on Winners Podium|Three simplified people stand behind a stepped winners podium, with the central figure raised highest. Each has a rounded head and curved shoulders, while the podium has a wide base and a tall middle step.|podium,people,winner,ranking,competition,award
86|Portable Radio with Angled Antenna|A portable radio has a low rounded rectangular body with a large circular speaker on the left. A small tuning window and short control line occupy the right, and a slender antenna angles upward.|radio,antenna,speaker,tuner,audio,portable
87|Cupped Hands Beneath a Cross|Two upturned hands rise symmetrically beneath an upright cross, with their fingers open toward its sides. The cross has a long lower stem and short rectangular arms, floating above the inward-curving palms.|cross,hands,prayer,religion,faith,christianity
89|Quail with Curved Crest|A quail stands in right-facing profile, with a plump body, pointed beak, and long curved crest above its head. A sweeping wing line separates the upper body from the belly above two thin legs.|quail,bird,crest,wing,beak,wildlife
90|Quarter-Circle Wedge|A broad quarter-circle shape has straight lower and right sides meeting at a right angle. A single sweeping arc joins their far ends, enclosing a blank wedge with softly rounded corner transitions.|quarter,circle,wedge,sector,geometry,shape
91|Radish with Two Leaves|A round radish tapers into a sharp root at the bottom. A short stem rises from the top center and branches into two large pointed leaves spreading upward to either side.|radish,root,vegetable,leaf,produce,food
92|Hooded Raincoat and Closed Umbrella|A hooded raincoat appears from the front with rounded shoulders and a central opening line. A closed umbrella stands separately to the right as a long tapered canopy with a short shaft protruding above.|raincoat,umbrella,rain,hood,clothing,weather
93|Raspberry with Leaf and Stem|A raspberry is formed from overlapping rounded drupelets that narrow toward the bottom. A single pointed leaf leans left from the top, beside a short curved stem rising to the right.|raspberry,berry,fruit,leaf,stem,food
98|Plain Table with Two Legs|A simple table has a long rectangular tabletop and two thin straight legs set inward from its ends. The view is frontal, with no chair, contents, or additional support visible.|table,refectory,furniture,leg,top,dining
99|Square Mirror with Diagonal Reflections|A plain square mirror has a straight outer border and two diagonal reflection marks inside. The longer stroke sits above and to the left of the shorter one, both slanting upward right.|mirror,reflection,square,glass,frame,surface
100|Reindeer Face with Branching Antlers|A reindeer faces forward with a long rounded muzzle, small dot eyes, and an oval nose. Broad ears project sideways below two branching antlers that rise and spread above its head.|reindeer,deer,antler,face,animal,wildlife
101|Remote Control with Round Buttons|An upright remote control has a rounded rectangular body and a large circular button near the top. Six smaller round buttons form two rows beneath it, with a short pill-shaped button at the bottom.|remote,control,button,device,electronics,handset
105|Arrow Right with Broad Point|A straight horizontal line runs into a large right-facing arrowhead with long diagonal arms. The upper and lower arms meet symmetrically at the tip, leaving the left shaft plain.|arrow,right,point,direction,forward,navigation
106|Rounded Right-Pointing Triangle|A right-pointing triangular outline has rounded corners and an empty interior. Its left edge is nearly vertical, while the upper and lower edges slope toward the softly rounded point at the right.|triangle,play,right,outline,shape,media
109|Reading Glasses Above Closed Book|Round reading glasses sit above a closed book viewed from its spine edge. The glasses have a curved bridge and short outer temples, while two inset horizontal lines show the book's page block.|glasses,book,reading,spectacles,literature,study
110|Wide Rounded Rectangle|A long horizontal rectangle has broad rounded corners and a blank interior. The straight top and bottom edges span most of its width, connected by short upright sides at each end.|rectangle,wide,rounded,frame,blank,shape
112|Panel with Rounded Inset Slot|A rounded square panel surrounds a small horizontal pill-like rectangular inset. Both outlines are empty, with the inset centered and separated from the outer frame by broad margins.|panel,slot,inset,rectangle,frame,layout
113|Plain Short-Sleeved T-Shirt|A plain T-shirt faces forward with a shallow round neckline, two short angled sleeves, and straight sides. Its lower hem is flat, and the chest contains no emblem, pocket, or other mark.|shirt,tshirt,clothing,sleeve,garment,apparel
114|Rail Grid with Three Crossbars|Two upright rails are crossed by three evenly spaced horizontal bars that extend slightly beyond them. A small irregular angled stroke appears at the left middle junction of the otherwise plain grid.|rail,grid,crossbar,fence,structure,framework
115|Open-Edged Puzzle Piece with Socket|A rounded square puzzle piece has a circular inward socket on its right side. Small gaps interrupt the left and lower outlines, while the upper edge and rounded upper corners remain continuous.|puzzle,piece,jigsaw,socket,game,outline
116|Solar Panel Connected to Monitor|A six-cell solar panel sits above and to the left of a blank desktop monitor. A cable descends from the panel and bends into the monitor, which rests on a short stem and flat foot.|solar,panel,monitor,energy,cable,system
119|Rhinoceros Facing Right|A rhinoceros stands in right-facing profile with a heavy rounded body and low head. A large horn projects upward from the snout, a pointed ear rises behind it, and broad legs support the belly.|rhinoceros,rhino,horn,animal,wildlife,mammal
122|Three-Leaf Botanical Sprig|A slender stem branches into three pointed oval leaves, with one upright at the top and two spreading sideways below. Each leaf has a short central vein connected to the branching stem.|sprig,leaf,plant,rhubarb,botanical,stem
123|Barn with Cross-Braced Doors|A barn has a high angular gambrel roof and straight outer walls. A small square loft window sits above a wide doorway, whose two diagonal braces cross across the lower opening.|barn,ranch,farm,door,roof,agriculture
124|Three Open Recycling Arrows|Three bent line arrows follow one another around an open triangular center. Each shaft curves around one corner before ending in an open arrowhead, with clear gaps between the separate arrows.|recycling,recycle,arrow,cycle,reuse,environment
125|Redux Three-Lobed Emblem|Three small circular nodes are joined by sweeping curved lines in a rotating triangular arrangement. Each curve wraps around the outside before meeting the next node, leaving open gaps along the outer silhouette.|redux,logo,node,curve,programming,emblem
126|Framed Three-Shelf Rack|A rounded square outer frame surrounds a smaller rectangular shelving opening. Two horizontal dividers cross the inner opening to create three stacked empty shelves, with a broad margin around the shelving unit.|rack,shelf,storage,frame,furniture,display
127|Plain Circular Ring|A broad circular ring is defined by a large outer circle and a smaller centered opening. Both boundaries are unbroken, with no setting, engraving, or other surface detail visible.|ring,circle,annulus,round,band,shape
128|Two Overlapping Circles|Two equal-looking circular outlines overlap side by side to form a narrow lens at their center. Both full circumferences remain visible, and neither circle contains additional marks or text.|circle,overlap,venn,pair,geometry,diagram
129|Two Stacked Rounded Cards|Two blank rounded square cards are offset diagonally, with the front card sitting higher and to the left. The rear card remains visible along the right and bottom edges of the overlapping pair.|card,copy,stack,duplicate,layer,rectangle
130|Broad Recycling Arrow Loop|Three broad bent arrows form an open triangular recycling loop. Their outlined shafts bend around the corners and end in angular points, with small gaps separating the arrows around the empty center.|recycle,recycling,arrow,loop,reuse,environment
132|Weather Balloon with Instrument Box|A large balloon has a rounded upper body narrowing to a pointed lower neck. A short vertical tether joins the balloon to a small square instrument box hanging directly beneath it.|radiosonde,balloon,weather,instrument,atmosphere,meteorology
133|Person in Profile with Swept Hair|A person's head faces right, with a clear nose, chin, and short neck. Smooth hair sweeps across the forehead, curves around a visible ear, and ends in a flared shoulder-length section behind.|person,profile,hair,head,face,portrait
134|Diagonal Rugby Ball with Lacing|An elongated rugby ball lies diagonally from lower left to upper right, tapering to rounded pointed ends. A long central seam follows its length, crossed by several short evenly spaced laces.|rugby,ball,sport,lace,seam,football'''
drafts={}
for line in raw.splitlines():
 i,name,desc,tags=line.split('|');i=int(i);drafts[i]={'index':i,'concept':name,'icon_id':re.sub('[^a-z0-9]+','-',name.lower()).strip('-'),'family':'solo','description':desc,'tags':tags.split(',')}
assert len(drafts)==100,len(drafts)
(P/'solo-drafts.json').write_text(json.dumps(drafts,indent=2)+'\n')
print('Written',len(drafts),'solo descriptions')
