const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
function element(tag){return {tag,children:[],value:'',disabled:false,textContent:'',append(...xs){this.children.push(...xs)},setAttribute(){},focus(){this.focused=true}};}
const els=new Map();
const context=vm.createContext({document:{createElement:element,getElementById(id){if(!els.has(id))els.set(id,element('div'));return els.get(id)}},Option:function(text,value){return {text,value}}});
const html=fs.readFileSync(__dirname+'/../scripts/templates/primitives.html','utf8');
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];
vm.runInContext(script.slice(0,script.indexOf('\nfor(const [k,l] of Object.entries(REASONS))')),context);
const run=s=>vm.runInContext(s,context);
(async()=>{
 run(`let requests=[],renders=0;renderDetail=()=>renders++;galleryWrite=async(url,options)=>{requests.push(JSON.parse(options.body));return {ok:true,json:async()=>({decisions:{a:{reason:'container',note:'review'}}})}};
 const row={uuid:'a',concept:'Example',state:'generated'};const editor=classificationEditor(row);
 const select=editor.children.find(c=>c.tag==='label').children[0];
 const note=editor.children.find(c=>c.tag==='input');
 const buttons=editor.children.find(c=>c.tag==='div').children;`);
 run("select.value='container';note.value='review';note.oninput()");
 assert.equal(run('classificationDrafts.size'),1);
 await run('buttons[0].onclick()');
 assert.equal(run('requests[0].uuids[0]'),'a');
 assert.equal(run('requests[0].reason'),'container');
 assert.equal(run('statuses.a.reason'),'container');
 assert.equal(run('classificationDrafts.size'),0);
 assert.equal(run('renders'),1);
 run("galleryWrite=async(url,options)=>{requests.push(JSON.parse(options.body));return {ok:true,json:async()=>({decisions:{a:null}})}}");
 await run('buttons[1].onclick()');
 assert.equal(run('requests[1].status'),'todo');
 assert.equal(run('statuses.a'),undefined);
 assert.equal(run('row.state'),'generated','Existing artwork state is preserved');
 run("select.value='other';note.value=''");
 await run('buttons[0].onclick()');
 assert.equal(run('requests.length'),2,'Other requires a note');
 run("select.value='combination';note.value='keep this draft';note.oninput();galleryWrite=async()=>({ok:false,json:async()=>({error:'Cannot save'})})");
 await run('buttons[0].onclick()');
 assert.equal(run('editor.children.at(-1).textContent'),'Cannot save');
 assert.equal(run('classificationDrafts.size'),1,'Failed saves preserve drafts');
 assert.equal(run('buttons[0].disabled'),false);
 console.log('Per-card type/TODO actions, validation, failure recovery and artwork preservation passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
