/* Additional usage templates share the approved-icon editor with the original examples. */
(()=>{
  const nav=(brand,tag,icon,id)=>`<header class="more-nav"><div class="more-brand">${icon(id,'','brand')}<strong>${brand}</strong></div><span>${tag}</span></header>`;
  const heading=(eyebrow,title,description)=>`<div class="more-heading"><p class="kicker">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div>`;
  const footer='<p class="more-footnote">Interactive sample · changes in this example last until reload. Icon choices are saved separately.</p>';
  const iconRow=(items,icon,prefix)=>items.map(([id,label],index)=>`<div>${icon(id,'',prefix+'-'+index)}<span>${label}</span></div>`).join('');
  const templates={
    store:{name:'Online store',subtitle:'Objects worth coming home to',description:'Product illustrations, shopping categories, a bag, and service icons.',
      render({icon}){return `<div class="more-page store-page">${nav('FORM & FIELD','THOUGHTFUL OBJECTS / EVERYDAY LIVING',icon,'retail-shopping-bag')}<section class="shop-hero"><div>${heading('THE EVERYDAY COLLECTION','A little less.<br>A little better.','Useful things. Considered details. Make room for a slower kind of everyday.')}<a class="button" href="#shopProducts">Explore the collection</a></div><div class="shop-hero-art">${icon('armchair','','hero-chair')}<span>GOOD DESIGN.<br>GOOD COMPANY.</span></div></section><div class="shop-services">${iconRow([['box-shipping','Thoughtfully packed'],['ecology-leaf','Made to last'],['heart-shaped-handshake','A personal touch']],icon,'service')}</div><section class="more-section"><div class="more-section-head"><h2>The essentials</h2><button class="more-outline" id="shopBag">Shopping bag <span id="bagCount">0</span></button></div><div class="more-filter-row" aria-label="Product categories"><button data-shop-filter="all" aria-pressed="true">All objects</button><button data-shop-filter="home" aria-pressed="false">At home</button><button data-shop-filter="daily" aria-pressed="false">Everyday carry</button></div><div class="shop-products" id="shopProducts"></div></section>${footer}<dialog class="more-dialog" id="bagDialog" aria-labelledby="bagTitle"><div class="more-section-head"><h2 id="bagTitle">Your shopping bag</h2><button class="more-outline" id="closeBag">Close</button></div><div id="bagItems"></div><p class="bag-total" id="bagTotal"></p><p class="more-footnote">Sample bag. No order or payment is placed.</p><button class="more-outline" id="emptyBag">Empty sample bag</button></dialog></div>`;},
      mount({icon,editor}){
        const products=[['cup','The morning cup','A quiet start to your day.',28,'home','sand'],['armchair','The reading chair','Your new favorite corner.',340,'home','sage'],['standing-lamp','The evening light','A warmer kind of glow.',125,'home','rose'],['bag','The everyday tote','Take the essentials along.',48,'daily','lavender'],['book-open','The idea notebook','A place for passing thoughts.',18,'daily','sage'],['water-kettle-with-lid','The slow kettle','Make a little time for tea.',65,'home','sand']];
        const bag=new Map();let filter='all';const $=id=>document.getElementById(id);
        const refreshBag=()=>{$('bagCount').textContent=[...bag.values()].reduce((a,b)=>a+b,0);$('bagItems').innerHTML=bag.size?[...bag].map(([n,q])=>`<div class="bag-row"><span>${products[n][1]} × ${q}</span><strong>$${products[n][3]*q}</strong></div>`).join(''):'<p>Your bag is empty. Find something you like in the collection.</p>';$('bagTotal').textContent='Subtotal $'+[...bag].reduce((sum,[n,q])=>sum+products[n][3]*q,0);$('emptyBag').disabled=!bag.size;};
        function render(){$('shopProducts').innerHTML=products.map((p,n)=>({p,n})).filter(({p})=>filter==='all'||p[4]===filter).map(({p,n})=>`<article class="shop-product"><div class="product-drawing tone-${p[5]}">${icon(p[0],'','product-'+n)}</div><div class="product-title"><h3>${p[1]}</h3><span>$${p[3]}</span></div><p>${p[2]}</p><button class="more-outline" data-add-product="${n}">Add to bag</button></article>`).join('');document.querySelectorAll('[data-add-product]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.addProduct);bag.set(n,(bag.get(n)||0)+1);refreshBag();b.textContent='Added · '+bag.get(n);});editor.announce();}
        document.querySelectorAll('[data-shop-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.shopFilter;document.querySelectorAll('[data-shop-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});$('shopBag').onclick=()=>{$('bagDialog').showModal();};$('closeBag').onclick=()=>$('bagDialog').close();$('emptyBag').onclick=()=>{bag.clear();refreshBag();render();};render();refreshBag();
      }
    },
    travel:{name:'Travel planner',subtitle:'A little further from ordinary',description:'Destination cards, itinerary stops, packing essentials, and travel navigation.',
      render({icon}){return `<div class="more-page travel-page">${nav('elsewhere','LESS SCROLLING. MORE WANDERING.',icon,'compass')}<section class="travel-hero"><div>${heading('YOUR NEXT CHAPTER','Take the scenic route.','Little escapes and longer adventures. Find a place that makes you feel a little more alive.')}<div class="travel-tags"><span>Open horizons</span><span>Slow mornings</span><span>Good stories</span></div></div><div class="travel-hero-icons">${icon('airplane','','hero-plane')}${icon('mountain-road','','hero-mountain')}${icon('beach-palm-tree-sun','','hero-beach')}</div></section><section class="more-section"><div class="more-section-head"><h2>Where would you rather be?</h2><span id="savedTrips" role="status">0 places saved</span></div><div class="more-filter-row" aria-label="Destination types"><button data-trip-filter="all" aria-pressed="true">Everywhere</button><button data-trip-filter="coast" aria-pressed="false">By the sea</button><button data-trip-filter="nature" aria-pressed="false">Into nature</button><button data-trip-filter="city" aria-pressed="false">City breaks</button></div><div class="destination-grid" id="destinations"></div></section><section class="trip-planner"><div><p class="kicker">A LITTLE PLAN, A LOT OF POSSIBILITY</p><h2>Three days. Your own pace.</h2><div class="more-filter-row" aria-label="Itinerary day">${[1,2,3].map(n=>`<button data-trip-day="${n}" aria-pressed="${n===1}">Day ${n}</button>`).join('')}</div><div id="itinerary"></div></div><aside><h3>Bring the good stuff.</h3><div class="packing-grid">${iconRow([['camera-photography','Curiosity'],['book-open','A good book'],['bag','The essentials'],['compass','A sense of adventure']],icon,'packing')}</div></aside></section>${footer}</div>`;},
      mount({icon,editor}){
        const $=id=>document.getElementById(id),saved=new Set();let filter='all';
        const destinations=[['beach-palm-tree-sun','A slower kind of coast','Algarve, Portugal','coast','sand'],['mountain-road','A breath of mountain air','Dolomites, Italy','nature','sage'],['bank-columns','Streets with a story','Kyoto, Japan','city','rose'],['hammock-on-palm-tree','Nothing on the agenda','Koh Lanta, Thailand','coast','lavender']];
        function render(){$('destinations').innerHTML=destinations.map((p,n)=>({p,n})).filter(({p})=>filter==='all'||p[3]===filter).map(({p,n})=>`<article class="destination"><div class="destination-art tone-${p[4]}">${icon(p[0],'','destination-'+n)}<span>0${n+1} / EXPLORE</span></div><p>${p[2]}</p><h3>${p[1]}</h3><button class="more-outline" data-save-trip="${n}" aria-pressed="${saved.has(n)}">${saved.has(n)?'Saved to your places':'Save this place'}</button></article>`).join('');document.querySelectorAll('[data-save-trip]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.saveTrip);saved.has(n)?saved.delete(n):saved.add(n);$('savedTrips').textContent=saved.size+(saved.size===1?' place saved':' places saved');render();});editor.announce();}
        const plans={1:[['cup','09:00','Start with something local'],['compass','11:00','Get wonderfully lost'],['camera-photography','17:30','Catch the golden hour']],2:[['mountain-road','08:30','Follow the trail'],['book-open','13:00','Pause for a long lunch'],['eight-ray-sun','18:00','Watch the day slow down']],3:[['bag','09:30','Find a little keepsake'],['mail-envelope','12:00','Send a postcard home'],['airplane','16:00','Take the memories with you']]};
        function day(n){$('itinerary').innerHTML=plans[n].map(([id,time,title],i)=>`<div class="itinerary-stop">${icon(id,'','day-'+n+'-'+i)}<time>${time}</time><span>${title}</span></div>`).join('');editor.announce();}
        document.querySelectorAll('[data-trip-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.tripFilter;document.querySelectorAll('[data-trip-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});document.querySelectorAll('[data-trip-day]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-trip-day]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));day(Number(b.dataset.tripDay));});render();day(1);
      }
    },
    learning:{name:'Learning portal',subtitle:'Make room for a new skill',description:'Course illustrations, lesson navigation, learning progress, and achievement badges.',
      render({icon}){return `<div class="more-page learning-page">${nav('OPEN CHAPTER','A LITTLE CURIOSITY GOES A LONG WAY',icon,'academic-graduation-cap')}<section class="learning-banner"><div>${heading('KEEP YOUR CURIOSITY CLOSE','What will you learn today?','Big discoveries begin with small steps. Pick up a new idea, or carry on where you left off.')}<div class="learning-stats"><span><strong>4</strong> courses to explore</span><span><strong id="lessonTotal">0</strong> <span id="lessonLabel">lessons completed</span></span></div></div><div class="learning-emblem">${icon('book-open','','hero-book')}${icon('eight-pointed-star-badge','','hero-badge')}</div></section><section class="more-section"><div class="more-section-head"><h2>Your next discovery</h2><label class="more-search"><span class="sr-only">Search courses</span><input id="courseSearch" type="search" placeholder="Find a course…"></label></div><div class="course-grid" id="courses"></div></section><section class="learning-path"><h2>One good habit. A world of possibility.</h2><div class="learning-steps">${[['compass','Find your direction','Start with a question that interests you.'],['clock','Make a little time','Fifteen minutes can be a good beginning.'],['pencil-sketch-design','Put it into practice','Make something with what you learn.'],['eight-pointed-star-badge','See how far you’ve come','Every small step counts.']].map(([id,title,desc],n)=>`<article>${icon(id,'','path-'+n)}<h3>${title}</h3><p>${desc}</p></article>`).join('')}</div></section>${footer}<dialog class="more-dialog lesson-dialog" id="lessonDialog" aria-labelledby="lessonTitle"><p class="kicker">YOUR NEXT SMALL STEP</p><h2 id="lessonTitle"></h2><p id="lessonText"></p><div class="lesson-example" id="lessonExample"></div><div class="more-section-head"><button class="more-outline" id="closeLesson">Back to courses</button><button class="button" id="completeLesson">Mark lesson complete</button></div></dialog></div>`;},
      mount({icon,editor}){
        const $=id=>document.getElementById(id),completed=new Set();let current=0;
        const courses=[['paintbrush','Finding your visual voice','Design','Start with three shapes and one idea. Explore how form, color, and space work together.','sage'],['camera-photography','Seeing the everyday differently','Photography','Look for a familiar object. Try framing it from three different angles.','sand'],['nodes-connected-angle','Ideas that connect','Communication','Choose one idea. Explain it in a sentence, then represent it with a simple visual.','lavender'],['pencil-sketch-design','A sketch a day','Creativity','Set aside five minutes. Draw something on your desk without lifting your pencil.','rose']];
        function render(){const term=$('courseSearch').value.toLowerCase();const rows=courses.map((p,n)=>({p,n})).filter(({p})=>(p[1]+' '+p[2]).toLowerCase().includes(term));$('courses').innerHTML=rows.length?rows.map(({p,n})=>`<article class="course-card"><div class="course-cover tone-${p[4]}">${icon(p[0],'','course-'+n)}<span>01 / A SMALL BEGINNING</span></div><div class="course-details"><p class="kicker">${p[2]}</p><h3>${p[1]}</h3><div class="course-meta">${icon('clock','','course-time-'+n)}<span>15 minutes · 1 sample lesson</span></div><button class="more-outline" data-start-course="${n}">${completed.has(n)?'Review lesson':'Start learning'}</button>${completed.has(n)?'<span class="completed-note">Lesson completed</span>':''}</div></article>`).join(''):'<p class="more-empty">No courses match your search.</p>';document.querySelectorAll('[data-start-course]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.startCourse);$('lessonTitle').textContent=courses[current][1];$('lessonText').textContent=courses[current][3];$('lessonExample').innerHTML=icon(courses[current][0],'','lesson-'+current);$('completeLesson').disabled=completed.has(current);$('completeLesson').textContent=completed.has(current)?'Completed':'Mark lesson complete';$('lessonDialog').showModal();editor.announce();});$('lessonTotal').textContent=completed.size;$('lessonLabel').textContent=completed.size===1?'lesson completed':'lessons completed';editor.announce();}
        $('courseSearch').oninput=render;$('closeLesson').onclick=()=>$('lessonDialog').close();$('completeLesson').onclick=()=>{completed.add(current);$('lessonDialog').close();render();};render();
      }
    },
    finance:{name:'Finance dashboard',subtitle:'A clearer view of the everyday',description:'Account cards, spending categories, savings goals, and transaction details.',
      render({icon}){return `<div class="more-page finance-page">${nav('pocket','YOUR MONEY, A LITTLE CLEARER',icon,'wallet-clasp')}<section class="more-section"><div class="more-section-head">${heading('YOUR PERSONAL OVERVIEW','A little more peace of mind.','A simple view of where things stand. All figures here are sample data.')}<label class="more-select">Period<select id="financePeriod"><option value="september">September</option><option value="august">August</option></select></label></div><div class="finance-overview"><article class="balance-card">${icon('wallet-clasp','','balance')}<span>Available balance</span><strong id="accountBalance">$8,420.00</strong><div><span>POCKET EVERYDAY</span><span>•••• 4826</span></div></article><div class="cashflow-card"><div>${icon('banknote-simple','','income')}<span>Money in</span><strong id="moneyIn">$4,800</strong></div><div>${icon('coins','','spending')}<span>Money out</span><strong id="moneyOut">$2,140</strong></div></div><article class="savings-card">${icon('mountain-road','','savings')}<span>A little adventure fund</span><strong>$1,650 <small>/ $2,500</small></strong><div class="progress-track"><span style="width:66%"></span></div><p>One step closer to the scenic route.</p></article></div><div class="finance-details"><section class="panel"><div class="more-section-head"><h2>The everyday picture</h2><span>Spending categories</span></div><div id="spendingCategories"></div></section><section class="panel"><h2>Good habits, in the details.</h2><div class="finance-tips">${[['clock','A regular check-in','A little attention goes a long way.'],['target-dot','Something to look forward to','Give your next goal a name.'],['security-shield','A sense of reassurance','A clear view of your everyday accounts.']].map(([id,title,desc],n)=>`<div>${icon(id,'','tip-'+n)}<div><h3>${title}</h3><p>${desc}</p></div></div>`).join('')}</div></section></div><section class="panel transactions"><div class="more-section-head"><h2>Recent activity</h2><label class="more-search"><span class="sr-only">Search transactions</span><input id="transactionSearch" type="search" placeholder="Find a transaction…"></label></div><div id="transactionList"></div></section></section>${footer}</div>`;},
      mount({icon,editor}){
        const $=id=>document.getElementById(id);
        const rows=[['cup','Corner Coffee','Food & drink',8.50],['retail-shopping-bag','The Everyday Store','Shopping',42],['book-open','Open Chapter Books','Learning',24],['airplane','Weekend flights','Travel',36],['banknote-simple','Studio payment','Income',-2400]];
        function render(){const august=$('financePeriod').value==='august';$('accountBalance').textContent=august?'$5,760.00':'$8,420.00';$('moneyIn').textContent=august?'$4,200':'$4,800';$('moneyOut').textContent=august?'$2,460':'$2,140';$('spendingCategories').innerHTML=[['cup','Food & drink',august?42:38],['retail-shopping-bag','Shopping',august?28:26],['airplane','Travel',august?18:22],['book-open','Learning',august?12:14]].map(([id,label,width],n)=>`<div class="spending-row">${icon(id,'','category-'+n)}<span>${label}</span><div><i style="width:${width}%"></i></div><strong>${width}%</strong></div>`).join('');const term=$('transactionSearch').value.toLowerCase();const filtered=rows.map((p,n)=>({p,n})).filter(({p})=>(p[1]+' '+p[2]).toLowerCase().includes(term));$('transactionList').innerHTML=filtered.length?filtered.map(({p,n})=>`<div class="transaction-row">${icon(p[0],'','transaction-'+n)}<div><h3>${p[1]}</h3><span>${p[2]} · ${august?'Aug':'Sep'} ${14-n}</span></div><strong class="${p[3]<0?'positive':''}">${p[3]<0?'+':'−'}$${Math.abs(p[3]).toFixed(2)}</strong></div>`).join(''):'<p class="more-empty">No transactions match your search.</p>';editor.announce();}
        $('financePeriod').onchange=render;$('transactionSearch').oninput=render;render();
      }
    },
    wellness:{name:'Wellness app',subtitle:'A softer rhythm for your day',description:'Daily habits, activity tracking, mood check-ins, and calming icon compositions.',
      render({icon}){return `<div class="more-page wellness-page">${nav('a little better','SMALL MOMENTS. A LITTLE MORE YOU.',icon,'heart-shaped-leaf')}<section class="wellness-hero"><div>${heading('A FRESH LITTLE START','Find your own rhythm.','No perfect days required. Just a little space for the things that help you feel like yourself.')}<div class="wellness-today">${icon('eight-ray-sun','','today')}<span>Today is a good place to begin.</span></div></div><div class="habit-ring" id="habitRing"><div>${icon('heart-flower-stem','','ring')}<strong id="habitProgress">0 / 4</strong><span>little moments today</span></div></div></section><section class="more-section"><div class="more-section-head"><h2>A few things, just for you</h2><button class="more-outline" id="resetHabits">Start fresh</button></div><div class="habit-grid" id="habitGrid"></div></section><section class="mood-section"><div><p class="kicker">A MOMENT TO CHECK IN</p><h2>How’s your day feeling?</h2><p>You don’t have to find the perfect word.</p></div><div class="mood-options">${[['eight-ray-sun','Bright'],['cloud','Quiet'],['flash','Energized'],['heart-shaped-leaf','Taking it slow']].map(([id,label],n)=>`<div>${icon(id,'','mood-'+n)}<button data-mood="${label}" aria-pressed="false">${label}</button></div>`).join('')}</div><p id="moodMessage" role="status">A little attention is a good beginning.</p></section><section class="wellness-note">${icon('book-open','','note')}<blockquote>There is room for a slower kind of progress.</blockquote><span>A small reminder for today</span></section>${footer}</div>`;},
      mount({icon,editor}){const $=id=>document.getElementById(id),done=new Set();const habits=[['cup','A little hydration','Take a moment for a glass of water.','sage'],['person-riding-bicycle','Move your own way','Find a little movement you enjoy.','sand'],['book-open','Feed your curiosity','Make time for a few good pages.','lavender'],['do-not-disturb-sleep-mode','A softer evening','Leave a little room to wind down.','rose']];function render(){$('habitGrid').innerHTML=habits.map(([id,title,desc,tone],n)=>`<article class="habit-card tone-${tone}">${icon(id,'','habit-'+n)}<h3>${title}</h3><p>${desc}</p><button class="more-outline" data-habit="${n}" aria-pressed="${done.has(n)}">${done.has(n)?'Done for today':'Mark as done'}</button></article>`).join('');document.querySelectorAll('[data-habit]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.habit);done.has(n)?done.delete(n):done.add(n);render();});$('habitProgress').textContent=done.size+' / 4';$('habitRing').style.setProperty('--habit-angle',done.size*90+'deg');$('resetHabits').disabled=!done.size;editor.announce();}$('resetHabits').onclick=()=>{done.clear();render();};document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mood]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('moodMessage').textContent=b.dataset.mood+' — a little space to notice how you feel.';});render();}
    },
    events:{name:'Events page',subtitle:'Good ideas, in good company',description:'Conference themes, agenda items, speaker cards, and a personal saved schedule.',
      render({icon}){return `<div class="more-page events-page">${nav('IN GOOD COMPANY','A GATHERING FOR CURIOUS MINDS',icon,'nodes-connected-angle')}<section class="event-hero"><div><p class="kicker">THE CREATIVE WEEKEND / OCTOBER 16–17</p><h1>Meet the people.<br>Find the spark.</h1><p>Two days of fresh perspectives, shared ideas, and the good kind of unexpected.</p><a class="button" href="#eventAgenda">Explore the program</a></div><div class="event-poster"><span>THINK / MAKE / CONNECT</span><div>${['microphone-bc89e360','flash','paintbrush','nodes-connected-angle','eight-pointed-star-badge','book-open'].map((id,n)=>`<div>${icon(id,'','poster-'+n)}</div>`).join('')}</div><strong>GOOD IDEAS<br>NEED COMPANY.</strong></div></section><div class="event-facts">${iconRow([['location-marker-pin','The Foundry, Portland'],['clock','Two days of discovery'],['simple-admission-ticket','A place for every perspective']],icon,'event-fact')}</div><section class="more-section" id="eventAgenda"><div class="more-section-head"><h2>Find your kind of inspiration.</h2><span id="savedSessions" role="status">0 sessions saved</span></div><div class="more-filter-row" aria-label="Program day"><button data-event-day="1" aria-pressed="true">Friday / Day 01</button><button data-event-day="2" aria-pressed="false">Saturday / Day 02</button><button data-event-day="saved" aria-pressed="false">My schedule</button></div><div id="eventSessions"></div></section><section class="event-speakers"><p class="kicker">A FEW FRESH PERSPECTIVES</p><h2>People with something to share.</h2><div>${[['paintbrush','Alex Morgan','Designing with intention'],['camera-photography','Sam Rivera','A different way of seeing'],['pencil-sketch-design','Robin Chen','Making room for ideas']].map(([id,name,topic],n)=>`<article>${icon(id,'','speaker-'+n)}<h3>${name}</h3><p>${topic}</p></article>`).join('')}</div></section>${footer}</div>`;},
      mount({icon,editor}){const $=id=>document.getElementById(id),saved=new Set();let day='1';const sessions=[['microphone-bc89e360','09:30','The beauty of a small beginning','Opening conversation · Main hall','1'],['paintbrush','11:00','Make something that means something','Hands-on workshop · Studio A','1'],['nodes-connected-angle','14:00','Better ideas, together','Roundtable · The Commons','1'],['camera-photography','10:00','Seeing the familiar, differently','Photo walk · Meet at reception','2'],['pencil-sketch-design','12:30','An idea worth keeping','Sketching workshop · Studio B','2'],['eight-pointed-star-badge','16:00','Take the spark with you','Closing conversation · Main hall','2']];function render(){const rows=sessions.map((p,n)=>({p,n})).filter(({p,n})=>day==='saved'?saved.has(n):p[4]===day);$('eventSessions').innerHTML=rows.length?rows.map(({p,n})=>`<article class="session-row"><time>${p[1]}</time>${icon(p[0],'','session-'+n)}<div><h3>${p[2]}</h3><p>${p[3]}${day==='saved'?' · Day '+p[4]:''}</p></div><button class="more-outline" data-save-session="${n}" aria-pressed="${saved.has(n)}">${saved.has(n)?'Saved':'Save session'}</button></article>`).join(''):'<p class="more-empty">Your schedule is open. Save a session from either day to add it here.</p>';document.querySelectorAll('[data-save-session]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.saveSession);saved.has(n)?saved.delete(n):saved.add(n);render();});$('savedSessions').textContent=saved.size+(saved.size===1?' session saved':' sessions saved');editor.announce();}document.querySelectorAll('[data-event-day]').forEach(b=>b.onclick=()=>{day=b.dataset.eventDay;document.querySelectorAll('[data-event-day]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});render();}
    }
  };
  window.PreviewUsageTemplates=templates;
})();
