#!/bin/bash
# Batch 83/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/two-eggs-in-decorated-bowl  source d84437e5-b92a-4000-9da9-a5a11a87f9bb
#   solo/two-hands-cupping-a-building  source 8788efae-9ba8-4acc-a2e4-90bca5c7c8d4
#   solo/two-hands-cupping-a-house  source 507e66fa-7eb5-4d7c-9fd1-641b3c9e27f2
#   solo/two-intersecting-circles-with-central-lens  source 0256307a-ca17-5c2d-9d3e-ca0beffd8ec2
#   solo/two-linked-wifi-routers  source 5a93e8de-6f91-4fe6-b134-63af89e10c77
#   solo/two-mail-envelopes-batch-007-13  source 3b4efb64-ab06-49d1-9d84-ece28a78b1ca
#   solo/two-open-hands-beneath-a-heart  source 2d833c6d-7e3c-4f1d-81d3-751c131f3ff5
#   solo/two-opposing-gamepads  source 17820290-30de-49a4-8c9c-08bc95fae445
#   solo/two-overlapping-document-sheets  source 330e60bf-6b59-465a-9889-8e958e8dc7c3
#   solo/two-person-group-batch-078  source b1111a7d-0e17-480b-bd48-42a1ccc6d651
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Two Eggs in Decorated Bowl' d84437e5-b92a-4000-9da9-a5a11a87f9bb 'pictographic-primitives/holidays/easter egg basket_d84437e5-b92a-4000-9da9-a5a11a87f9bb.svg' \
  'Two hands cupping a building' 8788efae-9ba8-4acc-a2e4-90bca5c7c8d4 'pictographic-primitives/_uncategorized_32/real estate favorite hold building_8788efae-9ba8-4acc-a2e4-90bca5c7c8d4.svg' \
  'Two hands cupping a house' 507e66fa-7eb5-4d7c-9fd1-641b3c9e27f2 'pictographic-primitives/_uncategorized_32/real estate favorite hold house_507e66fa-7eb5-4d7c-9fd1-641b3c9e27f2.svg' \
  'Two intersecting circles with central lens' 0256307a-ca17-5c2d-9d3e-ca0beffd8ec2 'pictographic-primitives/diagrams/boolean or_0256307a-ca17-5c2d-9d3e-ca0beffd8ec2.svg' \
  'Two linked wifi routers' 5a93e8de-6f91-4fe6-b134-63af89e10c77 'pictographic-primitives/technology/mesh wifi_5a93e8de-6f91-4fe6-b134-63af89e10c77.svg' \
  'Two mail envelopes batch 007 13' 3b4efb64-ab06-49d1-9d84-ece28a78b1ca 'pictographic-primitives/emails/envelope back front_3b4efb64-ab06-49d1-9d84-ece28a78b1ca.svg' \
  'Two open hands beneath a heart' 2d833c6d-7e3c-4f1d-81d3-751c131f3ff5 'pictographic-primitives/_uncategorized_33/romance pride lgbt heart protect hand gesture_2d833c6d-7e3c-4f1d-81d3-751c131f3ff5.svg' \
  'Two opposing gamepads' 17820290-30de-49a4-8c9c-08bc95fae445 'pictographic-primitives/video-games/batch-08/one vs one mode 1_17820290-30de-49a4-8c9c-08bc95fae445.svg' \
  'Two overlapping document sheets' 330e60bf-6b59-465a-9889-8e958e8dc7c3 pictographic-primitives/_uncategorized_11/clone_330e60bf-6b59-465a-9889-8e958e8dc7c3.svg \
  'Two person group batch 078' b1111a7d-0e17-480b-bd48-42a1ccc6d651 pictographic-primitives/_uncategorized_39/users_b1111a7d-0e17-480b-bd48-42a1ccc6d651.svg
