#!/bin/bash
# Batch 82/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/traveler-beside-suitcase  source 3b255cf1-988c-4c5f-ad89-86c99e9ec069
#   solo/tree-with-hanging-swing-solo-b016-r02  source a0e1d015-0d2b-46ee-8ddb-cda6d8f61feb
#   solo/treehouse-with-ladder-solo-b016-r02  source 69d37e4e-d972-4edd-9487-a2d5344250c0
#   solo/tuxedo-bow-tie  source f9451716-545e-4b2d-baaa-edadd03ed515
#   solo/twisted-licorice-strands  source 1585cb8b-c5e4-42ee-9bc9-6f53342a6281
#   solo/twisted-rubber-band  source 91e2f3f6-c4ad-5d83-8bfd-298cb0a82a06
#   solo/two-angular-figures-holding-hands  source b1093f49-5d2c-4508-a577-bc47b584a0c8
#   solo/two-childrens-heads  source 1a223ebe-d220-47ec-b404-7d0d6548a1b4
#   solo/two-coin-stacks  source 4b825437-3303-4449-b127-dc34838cb089
#   solo/two-connected-sensors-before-a-tablet  source 04aef027-7699-4c4d-a6e2-afbaea113fbc
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Traveler beside suitcase' 3b255cf1-988c-4c5f-ad89-86c99e9ec069 pictographic-primitives/_uncategorized_19/foreigner_3b255cf1-988c-4c5f-ad89-86c99e9ec069.svg \
  'Tree with hanging swing solo b016 r02' a0e1d015-0d2b-46ee-8ddb-cda6d8f61feb 'pictographic-primitives/kids/family outdoors swing tree_a0e1d015-0d2b-46ee-8ddb-cda6d8f61feb.svg' \
  'Treehouse with ladder solo b016 r02' 69d37e4e-d972-4edd-9487-a2d5344250c0 'pictographic-primitives/kids/family outdoors tree house_69d37e4e-d972-4edd-9487-a2d5344250c0.svg' \
  'Tuxedo bow tie' f9451716-545e-4b2d-baaa-edadd03ed515 pictographic-primitives/_uncategorized_39/tuxedo_f9451716-545e-4b2d-baaa-edadd03ed515.svg \
  'Twisted licorice strands' 1585cb8b-c5e4-42ee-9bc9-6f53342a6281 pictographic-primitives/_uncategorized_25/licorice_1585cb8b-c5e4-42ee-9bc9-6f53342a6281.svg \
  'Twisted rubber band' 91e2f3f6-c4ad-5d83-8bfd-298cb0a82a06 'pictographic-primitives/tools/elastic band_91e2f3f6-c4ad-5d83-8bfd-298cb0a82a06.svg' \
  'Two angular figures holding hands' b1093f49-5d2c-4508-a577-bc47b584a0c8 'pictographic-primitives/_uncategorized_21/group 1_b1093f49-5d2c-4508-a577-bc47b584a0c8.svg' \
  'Two childrens heads' 1a223ebe-d220-47ec-b404-7d0d6548a1b4 'pictographic-primitives/_uncategorized_24/kids head_1a223ebe-d220-47ec-b404-7d0d6548a1b4.svg' \
  'Two coin stacks' 4b825437-3303-4449-b127-dc34838cb089 'pictographic-primitives/_uncategorized_01/accounting coins stack 1_4b825437-3303-4449-b127-dc34838cb089.svg' \
  'Two connected sensors before a tablet' 04aef027-7699-4c4d-a6e2-afbaea113fbc 'pictographic-primitives/_uncategorized_05/aws iot services farm ipad_04aef027-7699-4c4d-a6e2-afbaea113fbc.svg'
