#!/bin/bash
# Batch 58/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/mobile-phone-phones  source 0ccd2887-dbd0-4ab5-a736-e2ba5438da4d
#   solo/mobile-phone-pin  source cd3023f2-6462-458d-9f32-0ee54bf229c9
#   solo/mobile-phone-pound-sign  source a70db137-a446-4f4c-b656-4fea14660981
#   solo/mobile-phone-qr-code-scanner  source de84ba40-054e-4737-9aee-c6a39715be64
#   solo/mobile-phone-record  source dc414e02-3cd1-4dfd-b568-2313b3f5617c
#   solo/mobile-phone-with-lower-bezel  source 8db84bcc-f04b-4b48-8727-a0f4bef6e360
#   solo/mobile-phone-with-yuan-sign  source e5fc6b47-c190-46c3-8229-bcad09cb8d97
#   solo/mobile-phone-woman  source c9fc1e73-299a-4164-b9c1-efd780db953d
#   solo/mobile-screen  source 681f6806-4e88-4938-aaa6-b3047b119931
#   solo/mobile-smartphone-device-solo  source f8d70b1b-fcf7-51cb-94e5-32276b034305
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Mobile phone phones' 0ccd2887-dbd0-4ab5-a736-e2ba5438da4d 'pictographic-primitives/phones/mobile phone_0ccd2887-dbd0-4ab5-a736-e2ba5438da4d.svg' \
  'Mobile phone pin' cd3023f2-6462-458d-9f32-0ee54bf229c9 'pictographic-primitives/other/mobile phone pin_cd3023f2-6462-458d-9f32-0ee54bf229c9.svg' \
  'Mobile phone pound sign' a70db137-a446-4f4c-b656-4fea14660981 'pictographic-primitives/other/mobile phone pound sign_a70db137-a446-4f4c-b656-4fea14660981.svg' \
  'Mobile phone qr code scanner' de84ba40-054e-4737-9aee-c6a39715be64 'pictographic-primitives/other/mobile phone qr code_de84ba40-054e-4737-9aee-c6a39715be64.svg' \
  'Mobile phone record' dc414e02-3cd1-4dfd-b568-2313b3f5617c 'pictographic-primitives/other/mobile phone record_dc414e02-3cd1-4dfd-b568-2313b3f5617c.svg' \
  'Mobile phone with lower bezel' 8db84bcc-f04b-4b48-8727-a0f4bef6e360 'pictographic-primitives/mobile/mobile phone 1_8db84bcc-f04b-4b48-8727-a0f4bef6e360.svg' \
  'Mobile phone with yuan sign' e5fc6b47-c190-46c3-8229-bcad09cb8d97 'pictographic-primitives/other/mobile phone yuan sign_e5fc6b47-c190-46c3-8229-bcad09cb8d97.svg' \
  'Mobile phone woman' c9fc1e73-299a-4164-b9c1-efd780db953d 'pictographic-primitives/other/mobile phone woman_c9fc1e73-299a-4164-b9c1-efd780db953d.svg' \
  'Mobile screen' 681f6806-4e88-4938-aaa6-b3047b119931 'pictographic-primitives/container/mobile screen_681f6806-4e88-4938-aaa6-b3047b119931.svg' \
  'Mobile smartphone device solo' f8d70b1b-fcf7-51cb-94e5-32276b034305 pictographic-primitives/devices/screen_f8d70b1b-fcf7-51cb-94e5-32276b034305.svg
