#!/bin/bash
# Batch 35/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hazard-warning-triangle  source 4a83aac2-4605-5a65-a8e1-970a1c0682c0
#   solo/hbo-logo  source 5e8442fe-8bb0-4705-af7a-bf422ce50632
#   solo/head-and-throat-section-116c496d  source 116c496d-58c8-4b77-9d43-fdb1d84aa352
#   solo/head-field-of-view-top  source 9441b8ec-57df-4f5b-8f53-e4bc68bdb94e
#   solo/head-lock-content-movement  source f9cd92b5-81e6-4ebc-aa40-c2db3af7fac6
#   solo/head-massage  source aab6030d-3db1-4329-b1d0-4d2e7c6cdfbc
#   solo/head-medical-plus-content  source 348cbff9-1f65-4ac0-894f-5968b56f3054
#   solo/head-profile-wearing-broad-protective-mask  source 6125bb03-817d-547b-932c-5f4a4b4f96ed
#   solo/head-profile-with-brain-4c63fd0e  source 4c63fd0e-abca-498d-a2c5-8e8bd6b5f894
#   solo/head-profiles-with-heart  source 26e8f72f-fceb-4a4f-95db-e00ca1a93624
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hazard warning triangle' 4a83aac2-4605-5a65-a8e1-970a1c0682c0 'pictographic-primitives/transportation/hazard warning flasher_4a83aac2-4605-5a65-a8e1-970a1c0682c0.svg' \
  'Hbo logo' 5e8442fe-8bb0-4705-af7a-bf422ce50632 'pictographic-primitives/logos/hbo logo_5e8442fe-8bb0-4705-af7a-bf422ce50632.svg' \
  'Head and throat section 116c496d' 116c496d-58c8-4b77-9d43-fdb1d84aa352 'pictographic-primitives/health/throat problem_116c496d-58c8-4b77-9d43-fdb1d84aa352.svg' \
  'Head field of view top' 9441b8ec-57df-4f5b-8f53-e4bc68bdb94e 'pictographic-primitives/technology/field of view fov top_9441b8ec-57df-4f5b-8f53-e4bc68bdb94e.svg' \
  'Head lock content movement' f9cd92b5-81e6-4ebc-aa40-c2db3af7fac6 'pictographic-primitives/technology/head lock content movement_f9cd92b5-81e6-4ebc-aa40-c2db3af7fac6.svg' \
  'Head massage' aab6030d-3db1-4329-b1d0-4d2e7c6cdfbc 'pictographic-primitives/beauty/thai massage head_aab6030d-3db1-4329-b1d0-4d2e7c6cdfbc.svg' \
  'Head medical plus content' 348cbff9-1f65-4ac0-894f-5968b56f3054 'pictographic-primitives/symbol/head cross_348cbff9-1f65-4ac0-894f-5968b56f3054.svg' \
  'Head profile wearing broad protective mask' 6125bb03-817d-547b-932c-5f4a4b4f96ed 'pictographic-primitives/ecology/air pollution mask_6125bb03-817d-547b-932c-5f4a4b4f96ed.svg' \
  'Head profile with brain 4c63fd0e' 4c63fd0e-abca-498d-a2c5-8e8bd6b5f894 'pictographic-primitives/health/dementia disorder symptoms_4c63fd0e-abca-498d-a2c5-8e8bd6b5f894.svg' \
  'Head profiles with heart' 26e8f72f-fceb-4a4f-95db-e00ca1a93624 'pictographic-primitives/users/empathy authentication heart intersect_26e8f72f-fceb-4a4f-95db-e00ca1a93624.svg'
