#!/bin/bash
# Batch 41/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/horizontal-ruler-with-five-top-ticks  source 8e5cf0f4-16ef-55be-9abb-2b6fd8017da3
#   solo/horizontal-ruler-with-six-ticks  source 7dd79ecc-660d-4f56-b16d-363edb2e64e7
#   solo/horizontal-telephone-receiver  source 791f3e5f-2569-40aa-92db-6d888122af9d
#   solo/horizontal-telescope-component  source da27d8c0-78b0-4a2c-a763-9f3f95ddde79
#   solo/horse-pulling-small-carriage  source 589093c2-50d1-4d6e-b46e-2aef2795cea3
#   solo/horse-rider  source 932e176d-8abb-4412-94f0-22f2542b288a
#   solo/horse-skijoring  source 8a0e37cf-e3ff-4de5-bc93-53ba132c5629
#   solo/horseback-rider  source bebbb6da-7e2b-58de-b56f-770e3a08a34d
#   solo/hot-bean-soup-bowl  source dabc03c2-1e40-59b4-95ba-06eb67d8fe28
#   solo/hourglass-batch-016-08  source 0e18d2c2-7d24-5496-89e8-d0168131b9c5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Horizontal ruler with five top ticks' 8e5cf0f4-16ef-55be-9abb-2b6fd8017da3 pictographic-primitives/design/ruler_8e5cf0f4-16ef-55be-9abb-2b6fd8017da3.svg \
  'Horizontal ruler with six ticks' 7dd79ecc-660d-4f56-b16d-363edb2e64e7 'pictographic-primitives/_uncategorized_33/ruler horizontal_7dd79ecc-660d-4f56-b16d-363edb2e64e7.svg' \
  'Horizontal telephone receiver' 791f3e5f-2569-40aa-92db-6d888122af9d 'pictographic-primitives/phones/phone horizontal_791f3e5f-2569-40aa-92db-6d888122af9d.svg' \
  'Horizontal telescope component' da27d8c0-78b0-4a2c-a763-9f3f95ddde79 'pictographic-primitives/science/distro for opentelemetry preview_da27d8c0-78b0-4a2c-a763-9f3f95ddde79.svg' \
  'Horse pulling small carriage' 589093c2-50d1-4d6e-b46e-2aef2795cea3 pictographic-primitives/_uncategorized_10/carriage_589093c2-50d1-4d6e-b46e-2aef2795cea3.svg \
  'Horse rider' 932e176d-8abb-4412-94f0-22f2542b288a 'pictographic-primitives/sports/sport horse riding_932e176d-8abb-4412-94f0-22f2542b288a.svg' \
  'Horse skijoring' 8a0e37cf-e3ff-4de5-bc93-53ba132c5629 pictographic-primitives/sports/skijoring_8a0e37cf-e3ff-4de5-bc93-53ba132c5629.svg \
  'Horseback rider' bebbb6da-7e2b-58de-b56f-770e3a08a34d 'pictographic-primitives/recreation/outdoors horse_bebbb6da-7e2b-58de-b56f-770e3a08a34d.svg' \
  'Hot bean soup bowl' dabc03c2-1e40-59b4-95ba-06eb67d8fe28 'pictographic-primitives/food/bean soup_dabc03c2-1e40-59b4-95ba-06eb67d8fe28.svg' \
  'Hourglass batch 016 08' 0e18d2c2-7d24-5496-89e8-d0168131b9c5 pictographic-primitives/interface-essential/hourglass_0e18d2c2-7d24-5496-89e8-d0168131b9c5.svg
