#!/bin/bash
# Batch 64/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/person-beside-two-ball-snowman  source 47428121-76fd-443d-8ee2-ab1ad5fe0dda
#   solo/person-curved-paraglider  source 0a243397-1e4d-4449-8817-439c8d8c3f36
#   solo/person-dropping-trash-into-toilet  source 7c784cb7-5aec-47a9-96ef-4c2afb98e94a
#   solo/person-hailing-taxi  source ca1f0358-a511-4c16-94eb-b9779f2e7735
#   solo/person-holding-a-small-bowl  source 144ab7e4-5b62-44f3-80ef-97d4f5319804
#   solo/person-holding-balloon-string  source e35d23a2-caaa-44fe-b722-3d1dffe53b5e
#   solo/person-holding-both-cheeks  source 82588f0d-abae-49d8-810c-3c4ef28dacb3
#   solo/person-holding-horn-to-face  source 507a15ed-aace-4478-ab31-b39936e3a104
#   solo/person-holding-smartphone  source 24fc49f1-a250-5adb-b331-999bec7daf9c
#   solo/person-in-deep-forward-lunge  source 0d4b3c85-3e39-4c0a-bbf1-93535426c84c
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Person beside two ball snowman' 47428121-76fd-443d-8ee2-ab1ad5fe0dda 'pictographic-primitives/_uncategorized_08/build snowman_47428121-76fd-443d-8ee2-ab1ad5fe0dda.svg' \
  'Person curved paraglider' 0a243397-1e4d-4449-8817-439c8d8c3f36 pictographic-primitives/_uncategorized_29/paraglider_0a243397-1e4d-4449-8817-439c8d8c3f36.svg \
  'Person dropping trash into toilet' 7c784cb7-5aec-47a9-96ef-4c2afb98e94a 'pictographic-primitives/_uncategorized_15/do not throw trash toilet_7c784cb7-5aec-47a9-96ef-4c2afb98e94a.svg' \
  'Person hailing taxi' ca1f0358-a511-4c16-94eb-b9779f2e7735 'pictographic-primitives/_uncategorized_37/taxi wave_ca1f0358-a511-4c16-94eb-b9779f2e7735.svg' \
  'Person holding a small bowl' 144ab7e4-5b62-44f3-80ef-97d4f5319804 pictographic-primitives/_uncategorized_06/beggar_144ab7e4-5b62-44f3-80ef-97d4f5319804.svg \
  'Person holding balloon string' e35d23a2-caaa-44fe-b722-3d1dffe53b5e 'pictographic-primitives/_uncategorized_22/hold balloon_e35d23a2-caaa-44fe-b722-3d1dffe53b5e.svg' \
  'Person holding both cheeks' 82588f0d-abae-49d8-810c-3c4ef28dacb3 pictographic-primitives/_uncategorized_33/screamer_82588f0d-abae-49d8-810c-3c4ef28dacb3.svg \
  'Person holding horn to face' 507a15ed-aace-4478-ab31-b39936e3a104 'pictographic-primitives/_uncategorized_07/blow instrument_507a15ed-aace-4478-ab31-b39936e3a104.svg' \
  'Person holding smartphone' 24fc49f1-a250-5adb-b331-999bec7daf9c 'pictographic-primitives/work/meeting smartphone hold_24fc49f1-a250-5adb-b331-999bec7daf9c.svg' \
  'Person in deep forward lunge' 0d4b3c85-3e39-4c0a-bbf1-93535426c84c pictographic-primitives/_uncategorized_26/lunge_0d4b3c85-3e39-4c0a-bbf1-93535426c84c.svg
