#!/bin/bash
# Batch 20/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/four-hexagonal-nanobots  source a4ac6021-31ac-4b55-8c99-d25a6ba3e475
#   solo/four-piece-jigsaw-puzzle  source cab69194-7d72-4ec5-92ef-c43974df941f
#   solo/four-playing-card-suits  source 6c01ed88-1571-4e62-904d-509e18f64c7d
#   solo/framed-woman-user-profile  source f6b0c496-3280-4b18-b7cf-57c44827d9b8
#   solo/front-facing-sitting-frog  source 9550547e-22a0-47b6-b3b3-62de095d8053
#   solo/front-view-car-with-sensor-waves  source 3c675853-e649-4029-b679-cef625fb977e
#   solo/fruit-and-carton-cycle  source 0d2e8b45-430a-4208-bbed-b76c29804bc7
#   solo/full-battery-segmented  source 33faddf4-6c93-4508-bf49-bd5a27dd53af
#   solo/gabled-house-paired-windows  source 947154d2-ba94-40d8-86da-58585ad61c10
#   solo/game-immersive-vr  source a58cb8f2-5a25-594d-a031-72828d14122f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Four hexagonal nanobots' a4ac6021-31ac-4b55-8c99-d25a6ba3e475 'pictographic-primitives/_uncategorized_28/nanobots 1_a4ac6021-31ac-4b55-8c99-d25a6ba3e475.svg' \
  'Four piece jigsaw puzzle' cab69194-7d72-4ec5-92ef-c43974df941f pictographic-primitives/_uncategorized_24/jigsaw_cab69194-7d72-4ec5-92ef-c43974df941f.svg \
  'Four playing card suits' 6c01ed88-1571-4e62-904d-509e18f64c7d 'pictographic-primitives/_uncategorized_10/card game symbols_6c01ed88-1571-4e62-904d-509e18f64c7d.svg' \
  'Framed woman user profile' f6b0c496-3280-4b18-b7cf-57c44827d9b8 'pictographic-primitives/_uncategorized_12/composition window woman_f6b0c496-3280-4b18-b7cf-57c44827d9b8.svg' \
  'Front facing sitting frog' 9550547e-22a0-47b6-b3b3-62de095d8053 pictographic-primitives/_uncategorized_20/frog_9550547e-22a0-47b6-b3b3-62de095d8053.svg \
  'Front view car with sensor waves' 3c675853-e649-4029-b679-cef625fb977e 'pictographic-primitives/_uncategorized_09/car sensor 3_3c675853-e649-4029-b679-cef625fb977e.svg' \
  'Fruit and carton cycle' 0d2e8b45-430a-4208-bbed-b76c29804bc7 'pictographic-primitives/business/supply chain distributor fruit juice_0d2e8b45-430a-4208-bbed-b76c29804bc7.svg' \
  'Full battery segmented' 33faddf4-6c93-4508-bf49-bd5a27dd53af 'pictographic-primitives/mobile/charging battery full_33faddf4-6c93-4508-bf49-bd5a27dd53af.svg' \
  'Gabled house paired windows' 947154d2-ba94-40d8-86da-58585ad61c10 pictographic-primitives/_uncategorized_31/proprietor_947154d2-ba94-40d8-86da-58585ad61c10.svg \
  'Game immersive vr' a58cb8f2-5a25-594d-a031-72828d14122f 'pictographic-primitives/technology/game immersive vr_a58cb8f2-5a25-594d-a031-72828d14122f.svg'
