#!/bin/bash
# Batch 3/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/arrow-turn-right  source 90bda1dc-4ea8-4d9e-aace-a5784e398b7c
#   solo/astronomy-planet-pluto  source 538b81e2-4f12-5deb-8847-decaad176f32
#   solo/astronomy-telescope-stars  source 4a8d494e-32cc-4073-96a3-0c1ca2d67952
#   solo/athlete-pole-vaulting  source 756dc826-ac42-5822-a4ca-d5598175bce1
#   solo/augmented-reality-glasses-with-corner-display  source f3f157a4-4ba4-56cb-af69-39f5c5fe3376
#   solo/autonomous-domed-car-with-signal  source 148a6d3d-6e93-44b0-ad9c-3c3c30856f29
#   solo/baby-bottle-with-handles  source 46fff59c-84bf-4526-bd9b-33201133c81c
#   solo/baby-face-with-bow  source 724c83b9-dfbc-417a-b236-a8b1fd9f3b71
#   solo/bareheaded-delivery-rider-on-scooter  source 9046ec78-1a6b-4029-a2e9-be0d10843436
#   solo/bearded-pirate-behind-a-laptop  source aa4f64c4-a374-44b3-9890-7cd9bfe00eab
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Arrow turn right' 90bda1dc-4ea8-4d9e-aace-a5784e398b7c 'pictographic-primitives/symbol/arrow turn right_90bda1dc-4ea8-4d9e-aace-a5784e398b7c.svg' \
  'Astronomy planet pluto' 538b81e2-4f12-5deb-8847-decaad176f32 'pictographic-primitives/science/astronomy planet pluto_538b81e2-4f12-5deb-8847-decaad176f32.svg' \
  'Astronomy telescope stars' 4a8d494e-32cc-4073-96a3-0c1ca2d67952 'pictographic-primitives/_uncategorized_04/astronomy telescope stars_4a8d494e-32cc-4073-96a3-0c1ca2d67952.svg' \
  'Athlete pole vaulting' 756dc826-ac42-5822-a4ca-d5598175bce1 'pictographic-primitives/sports/athletics pole vault_756dc826-ac42-5822-a4ca-d5598175bce1.svg' \
  'Augmented reality glasses with corner display' f3f157a4-4ba4-56cb-af69-39f5c5fe3376 'pictographic-primitives/devices/device google glass_f3f157a4-4ba4-56cb-af69-39f5c5fe3376.svg' \
  'Autonomous domed car with signal' 148a6d3d-6e93-44b0-ad9c-3c3c30856f29 'pictographic-primitives/_uncategorized_04/auto pilot car signal 1_148a6d3d-6e93-44b0-ad9c-3c3c30856f29.svg' \
  'Baby bottle with handles' 46fff59c-84bf-4526-bd9b-33201133c81c 'pictographic-primitives/babies/milk bottle handle_46fff59c-84bf-4526-bd9b-33201133c81c.svg' \
  'Baby face with bow' 724c83b9-dfbc-417a-b236-a8b1fd9f3b71 'pictographic-primitives/babies/baby girl_724c83b9-dfbc-417a-b236-a8b1fd9f3b71.svg' \
  'Bareheaded delivery rider on scooter' 9046ec78-1a6b-4029-a2e9-be0d10843436 'pictographic-primitives/_uncategorized_14/delivery person motorcycle 1_9046ec78-1a6b-4029-a2e9-be0d10843436.svg' \
  'Bearded pirate behind a laptop' aa4f64c4-a374-44b3-9890-7cd9bfe00eab 'pictographic-primitives/_uncategorized_05/avatar piracy laptop_aa4f64c4-a374-44b3-9890-7cd9bfe00eab.svg'
