#!/bin/bash
# Batch 90/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/waist-wearing-briefs-batch-051  source 4107e406-bbc1-4ebd-9934-68f5e7cbf1f6
#   solo/walk-through-metal-detector-scene  source b5334ab3-65e5-4291-b4ac-0357851cd6f7
#   solo/walker-beside-tactile-paving  source ba6234d6-f75b-454d-b652-1944239a63bc
#   solo/walker-crossing-dashed-border-toward-flag  source 3183f6d9-365e-467a-9fbc-91b1e40ca51d
#   solo/walking-commuter-with-briefcase  source 22bd302b-7cdc-4d13-8f4e-efe2bab54d50
#   solo/walking-unicorn  source a775341a-0e75-4ee2-9369-e05213871fd6
#   solo/wallet-solo-b018  source fc9c205a-fa2d-425c-ad9c-0ff1e334f886
#   solo/warrior-yoga-pose  source 93f177b4-e21d-4e29-b9af-215a348ff47c
#   solo/watermelon-wedge-rind  source 8a129756-fbf5-4dcf-87f5-abd6e50e9d3f
#   solo/weary-face-with-closed-eyes  source b8d89da2-54d1-4105-804a-afde0dcdfa9f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Waist wearing briefs batch 051' 4107e406-bbc1-4ebd-9934-68f5e7cbf1f6 pictographic-primitives/_uncategorized_20/girdle_4107e406-bbc1-4ebd-9934-68f5e7cbf1f6.svg \
  'Walk through metal detector scene' b5334ab3-65e5-4291-b4ac-0357851cd6f7 'pictographic-primitives/travel/security officer scanner beep_b5334ab3-65e5-4291-b4ac-0357851cd6f7.svg' \
  'Walker beside tactile paving' ba6234d6-f75b-454d-b652-1944239a63bc 'pictographic-primitives/_uncategorized_07/blind walk path_ba6234d6-f75b-454d-b652-1944239a63bc.svg' \
  'Walker crossing dashed border toward flag' 3183f6d9-365e-467a-9fbc-91b1e40ca51d 'pictographic-primitives/_uncategorized_13/cross the border_3183f6d9-365e-467a-9fbc-91b1e40ca51d.svg' \
  'Walking commuter with briefcase' 22bd302b-7cdc-4d13-8f4e-efe2bab54d50 'pictographic-primitives/_uncategorized_12/coffee delivery_22bd302b-7cdc-4d13-8f4e-efe2bab54d50.svg' \
  'Walking unicorn' a775341a-0e75-4ee2-9369-e05213871fd6 'pictographic-primitives/video-games/batch-04/fantasy unicorn 1_a775341a-0e75-4ee2-9369-e05213871fd6.svg' \
  'Wallet solo b018' fc9c205a-fa2d-425c-ad9c-0ff1e334f886 pictographic-primitives/other/wallet_fc9c205a-fa2d-425c-ad9c-0ff1e334f886.svg \
  'Warrior yoga pose' 93f177b4-e21d-4e29-b9af-215a348ff47c pictographic-primitives/_uncategorized_40/yoga_93f177b4-e21d-4e29-b9af-215a348ff47c.svg \
  'Watermelon wedge rind' 8a129756-fbf5-4dcf-87f5-abd6e50e9d3f pictographic-primitives/_uncategorized_27/melon_8a129756-fbf5-4dcf-87f5-abd6e50e9d3f.svg \
  'Weary face with closed eyes' b8d89da2-54d1-4105-804a-afde0dcdfa9f 'pictographic-primitives/_uncategorized_18/face weary_b8d89da2-54d1-4105-804a-afde0dcdfa9f.svg'
