#!/bin/bash
# Batch 77/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/standing-bird-with-broad-wing  source eac5adaf-049d-416c-b8c4-a6c582cb514f
#   solo/standing-bull  source e6262825-3337-4a94-b280-238a0b6c97e4
#   solo/standing-cow-profile  source e86bdf40-e8f1-4d65-a5ae-e3b40658db61
#   solo/standing-magpie-with-long-tapered-tail  source a95d2d1a-31f5-494d-8b3c-2e5f9af7dca8
#   solo/standing-mountain-lion-in-profile  source 22e27c10-01b3-4e0b-9a9f-8c3e35390cda
#   solo/standing-nightingale  source 24f05ce6-133d-478e-9ef6-3d75b8bacf70
#   solo/standing-person-rounded-limbs  source c2c89f0b-18a3-4a63-a2bd-e7b45faee034
#   solo/standing-studio-microphone  source 40a82f8e-607c-4a5c-9bd8-2c7172dbb654
#   solo/strapped-suitcase-above-a-conveyor  source c4455d4c-79af-42dd-8eec-2199e03f8d83
#   solo/striped-winged-insect  source 90fc40b4-507f-4dc2-be3c-14fdfadec7e9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Standing bird with broad wing' eac5adaf-049d-416c-b8c4-a6c582cb514f pictographic-primitives/_uncategorized_20/gamebird_eac5adaf-049d-416c-b8c4-a6c582cb514f.svg \
  'Standing bull' e6262825-3337-4a94-b280-238a0b6c97e4 'pictographic-primitives/_uncategorized_25/livestock bull body_e6262825-3337-4a94-b280-238a0b6c97e4.svg' \
  'Standing cow profile' e86bdf40-e8f1-4d65-a5ae-e3b40658db61 pictographic-primitives/_uncategorized_22/heifer_e86bdf40-e8f1-4d65-a5ae-e3b40658db61.svg \
  'Standing magpie with long tapered tail' a95d2d1a-31f5-494d-8b3c-2e5f9af7dca8 pictographic-primitives/_uncategorized_26/magpie_a95d2d1a-31f5-494d-8b3c-2e5f9af7dca8.svg \
  'Standing mountain lion in profile' 22e27c10-01b3-4e0b-9a9f-8c3e35390cda pictographic-primitives/_uncategorized_13/cougar_22e27c10-01b3-4e0b-9a9f-8c3e35390cda.svg \
  'Standing nightingale' 24f05ce6-133d-478e-9ef6-3d75b8bacf70 pictographic-primitives/_uncategorized_28/nightingale_24f05ce6-133d-478e-9ef6-3d75b8bacf70.svg \
  'Standing person rounded limbs' c2c89f0b-18a3-4a63-a2bd-e7b45faee034 pictographic-primitives/_uncategorized_29/omnivore_c2c89f0b-18a3-4a63-a2bd-e7b45faee034.svg \
  'Standing studio microphone' 40a82f8e-607c-4a5c-9bd8-2c7172dbb654 'pictographic-primitives/_uncategorized_27/microphone podcast on air_40a82f8e-607c-4a5c-9bd8-2c7172dbb654.svg' \
  'Strapped suitcase above a conveyor' c4455d4c-79af-42dd-8eec-2199e03f8d83 'pictographic-primitives/_uncategorized_05/baggage line_c4455d4c-79af-42dd-8eec-2199e03f8d83.svg' \
  'Striped winged insect' 90fc40b4-507f-4dc2-be3c-14fdfadec7e9 pictographic-primitives/_uncategorized_21/gnat_90fc40b4-507f-4dc2-be3c-14fdfadec7e9.svg
