#!/bin/bash
# Batch 85/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/upright-eyedropper-releasing-one-drop  source 9b04880c-4624-50fd-b4f4-8585f3d465cb
#   solo/upright-open-end-wrench-batch-064  source e832fdcc-c00d-4547-9cca-63111af74781
#   solo/upright-open-hand-with-joined-fingers  source 2642bb02-0d07-4d75-b214-cde16b5f0ce2
#   solo/upright-open-palm  source fdb048a8-3457-4da6-82b8-34ff113d0649
#   solo/upright-round-eared-rodent  source f5c54c96-084e-42b3-90da-b98178199c09
#   solo/upright-rounded-stick  source f1812b29-5916-4da7-b92a-60c32ffd784f
#   solo/upright-rowing-oar  source 34aabcc5-4e40-404e-a65d-95d9db16546a
#   solo/upright-segmented-caterpillar  source 81d9a460-8b31-4216-99ca-84b48ac5cd1c
#   solo/upright-skeleton-key  source ea151302-d8d0-5050-98de-642329625eee
#   solo/upturned-hands-with-binding-lines  source f194c922-857f-464d-8555-6757619d7ad3
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Upright eyedropper releasing one drop' 9b04880c-4624-50fd-b4f4-8585f3d465cb pictographic-primitives/design/picker_9b04880c-4624-50fd-b4f4-8585f3d465cb.svg \
  'Upright open end wrench batch 064' e832fdcc-c00d-4547-9cca-63111af74781 pictographic-primitives/_uncategorized_22/hardware_e832fdcc-c00d-4547-9cca-63111af74781.svg \
  'Upright open hand with joined fingers' 2642bb02-0d07-4d75-b214-cde16b5f0ce2 pictographic-primitives/_uncategorized_34/skin_2642bb02-0d07-4d75-b214-cde16b5f0ce2.svg \
  'Upright open palm' fdb048a8-3457-4da6-82b8-34ff113d0649 pictographic-primitives/_uncategorized_29/palm_fdb048a8-3457-4da6-82b8-34ff113d0649.svg \
  'Upright round eared rodent' f5c54c96-084e-42b3-90da-b98178199c09 pictographic-primitives/_uncategorized_21/gopher_f5c54c96-084e-42b3-90da-b98178199c09.svg \
  'Upright rounded stick' f1812b29-5916-4da7-b92a-60c32ffd784f pictographic-primitives/_uncategorized_36/stick_f1812b29-5916-4da7-b92a-60c32ffd784f.svg \
  'Upright rowing oar' 34aabcc5-4e40-404e-a65d-95d9db16546a pictographic-primitives/_uncategorized_28/oar_34aabcc5-4e40-404e-a65d-95d9db16546a.svg \
  'Upright segmented caterpillar' 81d9a460-8b31-4216-99ca-84b48ac5cd1c pictographic-primitives/_uncategorized_37/tailbud_81d9a460-8b31-4216-99ca-84b48ac5cd1c.svg \
  'Upright skeleton key' ea151302-d8d0-5050-98de-642329625eee pictographic-primitives/video-games/batch-05/key_ea151302-d8d0-5050-98de-642329625eee.svg \
  'Upturned hands with binding lines' f194c922-857f-464d-8555-6757619d7ad3 'pictographic-primitives/_uncategorized_23/hostage fasten_f194c922-857f-464d-8555-6757619d7ad3.svg'
