#!/bin/bash
# Batch 76/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/spotify-logo-1  source 27baa2fe-8381-4b9b-bb3a-d74e46fadb00
#   solo/sputnik-satellite  source 78fe3b70-a677-407c-a689-55a0827b0ff4
#   solo/square-neck-pinafore-dress  source 14d918d8-50d3-4ebe-98ee-fa95f856b6a2
#   solo/square-parking-slash  source 5f15564f-f916-4d99-9b2e-2bea2bc94e4b
#   solo/square-this-way-up  source 9ebf76c2-ab68-40f7-a75f-c12173488a0a
#   solo/square-wristwatch-solo-ac5e07e4  source ac5e07e4-9e24-406e-8500-ef19796d1933
#   solo/stacked-application-windows  source a0dcec41-38e9-4eb7-945f-4ee748901d7f
#   solo/stacked-duplicate-document-symbol  source c568142f-7cf8-4e1c-abca-02f1d76da1fb
#   solo/staggered-cars-from-above  source 916f15b5-1583-4859-b051-689a5edaf3c7
#   solo/standing-alpaca-in-profile  source 09625729-d47a-4fde-a9a2-61e0c7cfe86e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Spotify logo 1' 27baa2fe-8381-4b9b-bb3a-d74e46fadb00 'pictographic-primitives/_uncategorized_35/spotify logo 1_27baa2fe-8381-4b9b-bb3a-d74e46fadb00.svg' \
  'Sputnik satellite' 78fe3b70-a677-407c-a689-55a0827b0ff4 pictographic-primitives/science/sputnik_78fe3b70-a677-407c-a689-55a0827b0ff4.svg \
  'Square neck pinafore dress' 14d918d8-50d3-4ebe-98ee-fa95f856b6a2 pictographic-primitives/_uncategorized_30/pinafore_14d918d8-50d3-4ebe-98ee-fa95f856b6a2.svg \
  'Square parking slash' 5f15564f-f916-4d99-9b2e-2bea2bc94e4b 'pictographic-primitives/_uncategorized_35/square parking slash_5f15564f-f916-4d99-9b2e-2bea2bc94e4b.svg' \
  'Square this way up' 9ebf76c2-ab68-40f7-a75f-c12173488a0a 'pictographic-primitives/_uncategorized_35/square this way up_9ebf76c2-ab68-40f7-a75f-c12173488a0a.svg' \
  'Square wristwatch solo ac5e07e4' ac5e07e4-9e24-406e-8500-ef19796d1933 'pictographic-primitives/other/smart watch square euro sign_ac5e07e4-9e24-406e-8500-ef19796d1933.svg' \
  'Stacked application windows' a0dcec41-38e9-4eb7-945f-4ee748901d7f 'pictographic-primitives/_uncategorized_03/app window two_a0dcec41-38e9-4eb7-945f-4ee748901d7f.svg' \
  'Stacked duplicate document symbol' c568142f-7cf8-4e1c-abca-02f1d76da1fb 'pictographic-primitives/_uncategorized_13/copy files_c568142f-7cf8-4e1c-abca-02f1d76da1fb.svg' \
  'Staggered cars from above' 916f15b5-1583-4859-b051-689a5edaf3c7 'pictographic-primitives/_uncategorized_07/blind spot lane change assistance_916f15b5-1583-4859-b051-689a5edaf3c7.svg' \
  'Standing alpaca in profile' 09625729-d47a-4fde-a9a2-61e0c7cfe86e pictographic-primitives/_uncategorized_02/alpaca_09625729-d47a-4fde-a9a2-61e0c7cfe86e.svg
