#!/bin/bash
# Batch 25/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-gripping-plain-cup  source 9264b9dc-a5f7-44e5-8956-5e45e3269681
#   solo/hand-gripping-text-card  source ec650a8b-1e1e-43c8-9f94-4878310a6be1
#   solo/hand-harvesting-grain  source 7c9ddd87-89bf-4672-8b55-b3be716fbedd
#   solo/hand-holding-an-open-letter  source 16dbdd7b-9aab-4125-8e6a-77e168539590
#   solo/hand-holding-axe  source 47659966-6bcc-4338-8851-46f26e9cca27
#   solo/hand-holding-banknote  source 5a88b033-48de-5da2-bd8c-9b53bb261082
#   solo/hand-holding-card  source b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe
#   solo/hand-holding-fountain-pen  source 83ff3171-53c2-4300-a683-6306ba8fe250
#   solo/hand-holding-gear  source 9375035c-5b0d-47b1-8a06-a6cd84310dca
#   solo/hand-holding-hammer  source 9c2e6a00-c352-4f4c-97df-5e296d00637d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand gripping plain cup' 9264b9dc-a5f7-44e5-8956-5e45e3269681 'pictographic-primitives/_uncategorized_10/ceramic making_9264b9dc-a5f7-44e5-8956-5e45e3269681.svg' \
  'Hand gripping text card' ec650a8b-1e1e-43c8-9f94-4878310a6be1 'pictographic-primitives/_uncategorized_08/business card hand 2_ec650a8b-1e1e-43c8-9f94-4878310a6be1.svg' \
  'Hand harvesting grain' 7c9ddd87-89bf-4672-8b55-b3be716fbedd 'pictographic-primitives/holidays/reishit katzir feast of firstfruits_7c9ddd87-89bf-4672-8b55-b3be716fbedd.svg' \
  'Hand holding an open letter' 16dbdd7b-9aab-4125-8e6a-77e168539590 'pictographic-primitives/_uncategorized_32/read email hand_16dbdd7b-9aab-4125-8e6a-77e168539590.svg' \
  'Hand holding axe' 47659966-6bcc-4338-8851-46f26e9cca27 'pictographic-primitives/tools/tools axe hold_47659966-6bcc-4338-8851-46f26e9cca27.svg' \
  'Hand holding banknote' 5a88b033-48de-5da2-bd8c-9b53bb261082 'pictographic-primitives/payments/cash payment bills_5a88b033-48de-5da2-bd8c-9b53bb261082.svg' \
  'Hand holding card' b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe 'pictographic-primitives/payments/credit card scan_b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe.svg' \
  'Hand holding fountain pen' 83ff3171-53c2-4300-a683-6306ba8fe250 'pictographic-primitives/work/workflow coaching hand pen_83ff3171-53c2-4300-a683-6306ba8fe250.svg' \
  'Hand holding gear' 9375035c-5b0d-47b1-8a06-a6cd84310dca 'pictographic-primitives/work/workflow teamwork cog hand_9375035c-5b0d-47b1-8a06-a6cd84310dca.svg' \
  'Hand holding hammer' 9c2e6a00-c352-4f4c-97df-5e296d00637d 'pictographic-primitives/tools/tools hammer hold_9c2e6a00-c352-4f4c-97df-5e296d00637d.svg'
