#!/bin/bash
# Batch 37/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/headphones-with-rounded-earcups  source d5c2108b-d4dd-540a-bbca-681acd128bdf
#   solo/heart-eyes-face  source 947547ca-2668-5370-8ab0-93b823725d21
#   solo/heart-leaf-potted-plant  source c669888e-0e1f-5c0a-8970-eb3689be7ae7
#   solo/heart-message-22-solo  source 2a3f04f0-a404-41db-90b7-a6ee5813413b
#   solo/heart-pierced-by-arrow  source 32295af4-defa-5f3c-af21-d930830f3a88
#   solo/heart-set-engagement-ring  source 0e240258-45ce-4bd1-bbcb-cc2aef7950e7
#   solo/heart-user  source e7e97355-bccb-465c-ae55-5037fd70d291
#   solo/hearts-two  source 6188e665-7838-43fa-b5c8-8aecfca95ea0
#   solo/helmet-protection  source 25ee09f6-fd7a-43d2-abe9-d8c92772aab7
#   solo/heroku-logo  source 65983977-44fb-4a2c-a8b7-4af262fab497
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Headphones with rounded earcups' d5c2108b-d4dd-540a-bbca-681acd128bdf pictographic-primitives/audio/headphones_d5c2108b-d4dd-540a-bbca-681acd128bdf.svg \
  'Heart eyes face' 947547ca-2668-5370-8ab0-93b823725d21 'pictographic-primitives/smileys/in love_947547ca-2668-5370-8ab0-93b823725d21.svg' \
  'Heart leaf potted plant' c669888e-0e1f-5c0a-8970-eb3689be7ae7 'pictographic-primitives/decoration/batch-04/indoor plant_c669888e-0e1f-5c0a-8970-eb3689be7ae7.svg' \
  'Heart message 22 solo' 2a3f04f0-a404-41db-90b7-a6ee5813413b 'pictographic-primitives/symbol/messages bubble round heart_2a3f04f0-a404-41db-90b7-a6ee5813413b.svg' \
  'Heart pierced by arrow' 32295af4-defa-5f3c-af21-d930830f3a88 'pictographic-primitives/romance/love heart arrow_32295af4-defa-5f3c-af21-d930830f3a88.svg' \
  'Heart set engagement ring' 0e240258-45ce-4bd1-bbcb-cc2aef7950e7 'pictographic-primitives/_uncategorized_25/lgbt engagement ring_0e240258-45ce-4bd1-bbcb-cc2aef7950e7.svg' \
  'Heart user' e7e97355-bccb-465c-ae55-5037fd70d291 'pictographic-primitives/other/heart user_e7e97355-bccb-465c-ae55-5037fd70d291.svg' \
  'Hearts two' 6188e665-7838-43fa-b5c8-8aecfca95ea0 'pictographic-primitives/symbol/three hearts_6188e665-7838-43fa-b5c8-8aecfca95ea0.svg' \
  'Helmet protection' 25ee09f6-fd7a-43d2-abe9-d8c92772aab7 pictographic-primitives/protection/helmet_25ee09f6-fd7a-43d2-abe9-d8c92772aab7.svg \
  'Heroku logo' 65983977-44fb-4a2c-a8b7-4af262fab497 'pictographic-primitives/logos/heroku logo_65983977-44fb-4a2c-a8b7-4af262fab497.svg'
