#!/bin/bash
# Batch 56/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/magnifying-glass-pill  source 15fc1905-26f1-420c-9167-f58df5f29604
#   solo/map-with-location-pin  source 77035164-f010-491d-b43f-e3c91b10d2d0
#   solo/merge-arrow-nodes  source e601eded-1157-4544-9970-cc41755f1439
#   solo/mexican-hard-shell-taco  source 11528005-432f-4280-ba6c-83b0031fd4c6
#   solo/mobile-phone  source 8bd17abc-608f-4704-a4f0-9369f9c5df3f
#   solo/mobile-phone-70454eff  source 70454eff-c88b-47e2-b376-ad91c78c22f0
#   solo/mobile-phone-bell  source 819857f6-7191-4e86-8585-718826dd7d33
#   solo/mobile-phone-bug  source 600bc5a2-131a-4e43-b134-f5e672684c21
#   solo/mobile-phone-c4f9e2f1  source c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf
#   solo/mobile-phone-check  source 94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Magnifying glass pill' 15fc1905-26f1-420c-9167-f58df5f29604 'pictographic-primitives/other/magnifying glass pill_15fc1905-26f1-420c-9167-f58df5f29604.svg' \
  'Map with location pin' 77035164-f010-491d-b43f-e3c91b10d2d0 'pictographic-primitives/_uncategorized_26/maps pin_77035164-f010-491d-b43f-e3c91b10d2d0.svg' \
  'Merge arrow nodes' e601eded-1157-4544-9970-cc41755f1439 'pictographic-primitives/programing/internet of thing green grass_e601eded-1157-4544-9970-cc41755f1439.svg' \
  'Mexican hard shell taco' 11528005-432f-4280-ba6c-83b0031fd4c6 pictographic-primitives/food/tacos_11528005-432f-4280-ba6c-83b0031fd4c6.svg \
  'Mobile phone' 8bd17abc-608f-4704-a4f0-9369f9c5df3f 'pictographic-primitives/mobile/mobile phone_8bd17abc-608f-4704-a4f0-9369f9c5df3f.svg' \
  'Mobile phone 70454eff' 70454eff-c88b-47e2-b376-ad91c78c22f0 'pictographic-primitives/phones/mobile phone_70454eff-c88b-47e2-b376-ad91c78c22f0.svg' \
  'Mobile phone bell' 819857f6-7191-4e86-8585-718826dd7d33 'pictographic-primitives/other/mobile phone bell_819857f6-7191-4e86-8585-718826dd7d33.svg' \
  'Mobile phone bug' 600bc5a2-131a-4e43-b134-f5e672684c21 'pictographic-primitives/other/mobile phone bug_600bc5a2-131a-4e43-b134-f5e672684c21.svg' \
  'Mobile phone c4f9e2f1' c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf 'pictographic-primitives/phones/mobile phone_c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf.svg' \
  'Mobile phone check' 94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3 'pictographic-primitives/other/mobile phone check_94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3.svg'
