#!/bin/bash
# Batch 32/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hands-cradling-heart  source b2c7c47b-4d63-5df9-a04a-0a0fda69500c
#   solo/hands-cradling-man-with-short-hair  source 06cfdc01-9a51-4704-bf13-9872a6f24dd3
#   solo/hands-cradling-man-with-squared-hair  source 9cfaacff-026a-4070-9a84-684d32d863c5
#   solo/hands-cradling-person  source 472f46bd-39c5-470a-8b6e-204fc077587d
#   solo/hands-cradling-person-with-separate-head  source 24c756f0-4902-4326-bb44-d7c098a9b97e
#   solo/hands-cradling-woman-with-bob  source de56331a-5d11-40f6-a7a1-1943660a276d
#   solo/hands-cradling-woman-with-parted-hair  source 980cf59c-d36f-4ecd-b2a3-868c7b401314
#   solo/hands-cupping-a-profile-head  source efd5cbb3-73a1-456c-9d82-fa7470f26ad4
#   solo/hands-cupping-sphere  source 66991385-e96d-49e5-a043-770baf2d1ecf
#   solo/hands-exchanging-bitcoin  source ef9be51e-2927-4177-9d02-48b17a96d654
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hands cradling heart' b2c7c47b-4d63-5df9-a04a-0a0fda69500c 'pictographic-primitives/romance/love heart hands hold_b2c7c47b-4d63-5df9-a04a-0a0fda69500c.svg' \
  'Hands cradling man with short hair' 06cfdc01-9a51-4704-bf13-9872a6f24dd3 'pictographic-primitives/business/donation charity care person male 1_06cfdc01-9a51-4704-bf13-9872a6f24dd3.svg' \
  'Hands cradling man with squared hair' 9cfaacff-026a-4070-9a84-684d32d863c5 'pictographic-primitives/business/donation charity care person male_9cfaacff-026a-4070-9a84-684d32d863c5.svg' \
  'Hands cradling person' 472f46bd-39c5-470a-8b6e-204fc077587d 'pictographic-primitives/business/customer retention hands_472f46bd-39c5-470a-8b6e-204fc077587d.svg' \
  'Hands cradling person with separate head' 24c756f0-4902-4326-bb44-d7c098a9b97e 'pictographic-primitives/business/donation charity care person_24c756f0-4902-4326-bb44-d7c098a9b97e.svg' \
  'Hands cradling woman with bob' de56331a-5d11-40f6-a7a1-1943660a276d 'pictographic-primitives/business/donation charity care person female_de56331a-5d11-40f6-a7a1-1943660a276d.svg' \
  'Hands cradling woman with parted hair' 980cf59c-d36f-4ecd-b2a3-868c7b401314 'pictographic-primitives/business/donation charity care person female_980cf59c-d36f-4ecd-b2a3-868c7b401314.svg' \
  'Hands cupping a profile head' efd5cbb3-73a1-456c-9d82-fa7470f26ad4 'pictographic-primitives/_uncategorized_33/self care 2_efd5cbb3-73a1-456c-9d82-fa7470f26ad4.svg' \
  'Hands cupping sphere' 66991385-e96d-49e5-a043-770baf2d1ecf 'pictographic-primitives/religion/sphere hand_66991385-e96d-49e5-a043-770baf2d1ecf.svg' \
  'Hands exchanging bitcoin' ef9be51e-2927-4177-9d02-48b17a96d654 'pictographic-primitives/payments/crypto trade_ef9be51e-2927-4177-9d02-48b17a96d654.svg'
