#!/bin/bash
# Batch 19/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/five-interlocking-olympic-rings  source 3c672b26-42c9-4289-a407-8947e0d6a086
#   solo/flip-vertical-down  source f4d5b07b-21ab-4549-8de9-91ff1a0a75bd
#   solo/flowing-data-stream-into-cube  source 8ea46fb3-7a36-440c-ba27-7abf8a868086
#   solo/flying-angel-with-halo  source 43abe71b-f6a9-54a1-882b-385badf68650
#   solo/folded-map-with-location-pin  source 7c2df1dc-523f-47e8-98ed-1291ecbe59b3
#   solo/folder-file-solo  source d7b60535-d86c-4822-a2a7-f6c1499603fc
#   solo/fork-and-knife-dining-symbol-solo  source 96fa9fe4-386f-4d65-8531-a569bd794200
#   solo/fork-spoon-crossed  source 6305d089-5f4e-4d0d-8488-b6bf8ef99e4d
#   solo/fountain-pen-writing-a-flourish  source 0905b5d5-4129-49a6-8741-6664be7184aa
#   solo/four-diamond-flecks  source 3153aa20-491b-49c7-935e-ead102198009
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Five interlocking olympic rings' 3c672b26-42c9-4289-a407-8947e0d6a086 'pictographic-primitives/_uncategorized_29/olympic rings_3c672b26-42c9-4289-a407-8947e0d6a086.svg' \
  'Flip vertical down' f4d5b07b-21ab-4549-8de9-91ff1a0a75bd 'pictographic-primitives/interface-essential/flip vertical down_f4d5b07b-21ab-4549-8de9-91ff1a0a75bd.svg' \
  'Flowing data stream into cube' 8ea46fb3-7a36-440c-ba27-7abf8a868086 'pictographic-primitives/_uncategorized_02/amazon kinesis data stream_8ea46fb3-7a36-440c-ba27-7abf8a868086.svg' \
  'Flying angel with halo' 43abe71b-f6a9-54a1-882b-385badf68650 pictographic-primitives/holidays/angel_43abe71b-f6a9-54a1-882b-385badf68650.svg \
  'Folded map with location pin' 7c2df1dc-523f-47e8-98ed-1291ecbe59b3 'pictographic-primitives/_uncategorized_26/map location_7c2df1dc-523f-47e8-98ed-1291ecbe59b3.svg' \
  'Folder file solo' d7b60535-d86c-4822-a2a7-f6c1499603fc 'pictographic-primitives/other/folder file_d7b60535-d86c-4822-a2a7-f6c1499603fc.svg' \
  'Fork and knife dining symbol solo' 96fa9fe4-386f-4d65-8531-a569bd794200 'pictographic-primitives/state/circle fork knife_96fa9fe4-386f-4d65-8531-a569bd794200.svg' \
  'Fork spoon crossed' 6305d089-5f4e-4d0d-8488-b6bf8ef99e4d 'pictographic-primitives/symbol/spoon and fork_6305d089-5f4e-4d0d-8488-b6bf8ef99e4d.svg' \
  'Fountain pen writing a flourish' 0905b5d5-4129-49a6-8741-6664be7184aa 'pictographic-primitives/content/ink pen write_0905b5d5-4129-49a6-8741-6664be7184aa.svg' \
  'Four diamond flecks' 3153aa20-491b-49c7-935e-ead102198009 pictographic-primitives/_uncategorized_19/fleck_3153aa20-491b-49c7-935e-ead102198009.svg
