#!/bin/bash
# Batch 92/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/wifi-router  source 6e546508-64d0-439a-96ab-0198fec35f57
#   solo/wind-symbol  source 454931eb-a5e3-4335-8500-05f886c12dd7
#   solo/wind-water-elements  source 17db8753-59a6-4065-984b-95a913a56566
#   solo/wine-bottle-and-glass  source 768c410e-ea9e-46bd-825a-ce942cb387dd
#   solo/winged-lion  source 913ea823-995f-439f-bf00-7e196c2b8d57
#   solo/winged-lion-head  source 31adb801-c03d-4489-a2fa-3ecf7a57b89b
#   solo/winged-lion-in-profile  source d518e467-fc65-46ea-a989-a754cb583565
#   solo/winking-face-peeling-sticker  source 4e07c108-ee65-49d8-8b3f-7e814c8e1cc5
#   solo/winking-straw-hat-pirate  source 89ee4b36-d26f-440c-9a51-5ee98f5d876c
#   solo/wired-usb-mouse  source edeebc99-5db6-408a-828d-f317f5d07c5b
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Wifi router' 6e546508-64d0-439a-96ab-0198fec35f57 'pictographic-primitives/networks/router signal_6e546508-64d0-439a-96ab-0198fec35f57.svg' \
  'Wind symbol' 454931eb-a5e3-4335-8500-05f886c12dd7 pictographic-primitives/symbol/wind_454931eb-a5e3-4335-8500-05f886c12dd7.svg \
  'Wind water elements' 17db8753-59a6-4065-984b-95a913a56566 pictographic-primitives/weather/elements_17db8753-59a6-4065-984b-95a913a56566.svg \
  'Wine bottle and glass' 768c410e-ea9e-46bd-825a-ce942cb387dd pictographic-primitives/_uncategorized_40/winery_768c410e-ea9e-46bd-825a-ce942cb387dd.svg \
  'Winged lion' 913ea823-995f-439f-bf00-7e196c2b8d57 pictographic-primitives/animals/leopard_913ea823-995f-439f-bf00-7e196c2b8d57.svg \
  'Winged lion head' 31adb801-c03d-4489-a2fa-3ecf7a57b89b 'pictographic-primitives/video-games/batch-12/winged lion_31adb801-c03d-4489-a2fa-3ecf7a57b89b.svg' \
  'Winged lion in profile' d518e467-fc65-46ea-a989-a754cb583565 'pictographic-primitives/video-games/batch-12/winged lion_d518e467-fc65-46ea-a989-a754cb583565.svg' \
  'Winking face peeling sticker' 4e07c108-ee65-49d8-8b3f-7e814c8e1cc5 'pictographic-primitives/other/retouch sticker_4e07c108-ee65-49d8-8b3f-7e814c8e1cc5.svg' \
  'Winking straw hat pirate' 89ee4b36-d26f-440c-9a51-5ee98f5d876c 'pictographic-primitives/video-games/batch-08/pirate luffy onepiece_89ee4b36-d26f-440c-9a51-5ee98f5d876c.svg' \
  'Wired usb mouse' edeebc99-5db6-408a-828d-f317f5d07c5b 'pictographic-primitives/_uncategorized_24/keyboard usb_edeebc99-5db6-408a-828d-f317f5d07c5b.svg'
