#!/bin/bash
# Batch 6/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/bunny-holding-easter-egg  source 606ec34e-20d1-525e-a765-4f3fca8d3c47
#   solo/burger-beside-drink-cup  source 5d4383cc-7fa3-4af5-b119-dc3b67d08db0
#   solo/burning-crashed-aircraft  source 81f5c526-61a1-4426-afae-2fec80a31cb2
#   solo/camel-pose  source 89df2d47-dd44-58e7-a2f9-f8f36667b21c
#   solo/camera-drone-front  source d66af9da-0871-557c-abb0-a240e310287a
#   solo/camera-image-file  source ed808041-ff02-4ca5-8f86-337d16e29436
#   solo/camera-with-carry-strap  source 08e27f33-65ac-57d2-8a06-756b3779a004
#   solo/camera-with-shaking-lines  source f5ada276-7815-4d75-9ba7-b74ca81c7919
#   solo/camper-behind-flagged-tent  source 5655244e-9c88-42c3-a2be-d90a6fab78b2
#   solo/canoe  source 2f08daf6-071b-5ac7-9717-2239ffbb2925
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Bunny holding easter egg' 606ec34e-20d1-525e-a765-4f3fca8d3c47 'pictographic-primitives/holidays/easter egg bunny_606ec34e-20d1-525e-a765-4f3fca8d3c47.svg' \
  'Burger beside drink cup' 5d4383cc-7fa3-4af5-b119-dc3b67d08db0 'pictographic-primitives/_uncategorized_18/fast food burger drink_5d4383cc-7fa3-4af5-b119-dc3b67d08db0.svg' \
  'Burning crashed aircraft' 81f5c526-61a1-4426-afae-2fec80a31cb2 'pictographic-primitives/war/plane crashed_81f5c526-61a1-4426-afae-2fec80a31cb2.svg' \
  'Camel pose' 89df2d47-dd44-58e7-a2f9-f8f36667b21c 'pictographic-primitives/sports/yoga camel pose_89df2d47-dd44-58e7-a2f9-f8f36667b21c.svg' \
  'Camera drone front' d66af9da-0871-557c-abb0-a240e310287a 'pictographic-primitives/technology/drone camera_d66af9da-0871-557c-abb0-a240e310287a.svg' \
  'Camera image file' ed808041-ff02-4ca5-8f86-337d16e29436 'pictographic-primitives/other/camera file_ed808041-ff02-4ca5-8f86-337d16e29436.svg' \
  'Camera with carry strap' 08e27f33-65ac-57d2-8a06-756b3779a004 'pictographic-primitives/photography/camera carry_08e27f33-65ac-57d2-8a06-756b3779a004.svg' \
  'Camera with shaking lines' f5ada276-7815-4d75-9ba7-b74ca81c7919 'pictographic-primitives/_uncategorized_09/camera settings frame 1_f5ada276-7815-4d75-9ba7-b74ca81c7919.svg' \
  'Camper behind flagged tent' 5655244e-9c88-42c3-a2be-d90a6fab78b2 'pictographic-primitives/_uncategorized_09/camping tent person_5655244e-9c88-42c3-a2be-d90a6fab78b2.svg' \
  Canoe 2f08daf6-071b-5ac7-9717-2239ffbb2925 pictographic-primitives/outdoors/canoe_2f08daf6-071b-5ac7-9717-2239ffbb2925.svg
