#!/bin/bash
# Batch 10/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/computer-typing-keyboard  source 6da646a1-34eb-51f2-af2d-b08aed786a57
#   solo/concert-rock  source 3a11e17f-1153-59b2-b135-910a41a584c7
#   solo/corn-cob-in-open-husk  source 509d8c81-aff0-4d15-9237-c757ac95069a
#   solo/cost-explorer  source f2405205-3905-48f0-b56a-6cbf57184545
#   solo/counterclockwise-circular-arrow-batch-019-08  source 567f7df5-55ba-4b86-8f69-4c5a4f43e848
#   solo/counterclockwise-circular-refresh-arrows-batch-020-03  source 0a11ecc5-12d2-479f-ad50-bf72f2730e09
#   solo/counterclockwise-refresh-arrow  source 77f5a2c6-8120-4350-aa53-7bb00704de7d
#   solo/counterclockwise-synchronize-arrows  source bafc5d96-6820-5892-a08b-927ab58a96ff
#   solo/couple-beside-heart-shaped-balloon  source bb01aec5-8d69-470f-9cde-ccfb72c0af02
#   solo/couple-standing-with-hair  source 8808cfa8-f297-4bd3-a099-3c4ba3f2b025
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Computer typing keyboard' 6da646a1-34eb-51f2-af2d-b08aed786a57 pictographic-primitives/computers/batch-06/keyboard_6da646a1-34eb-51f2-af2d-b08aed786a57.svg \
  'Concert rock' 3a11e17f-1153-59b2-b135-910a41a584c7 'pictographic-primitives/entertainment/concert rock_3a11e17f-1153-59b2-b135-910a41a584c7.svg' \
  'Corn cob in open husk' 509d8c81-aff0-4d15-9237-c757ac95069a pictographic-primitives/_uncategorized_12/cob_509d8c81-aff0-4d15-9237-c757ac95069a.svg \
  'Cost explorer' f2405205-3905-48f0-b56a-6cbf57184545 'pictographic-primitives/other/cost explorer_f2405205-3905-48f0-b56a-6cbf57184545.svg' \
  'Counterclockwise circular arrow batch 019 08' 567f7df5-55ba-4b86-8f69-4c5a4f43e848 'pictographic-primitives/other/go backward_567f7df5-55ba-4b86-8f69-4c5a4f43e848.svg' \
  'Counterclockwise circular refresh arrows batch 020 03' 0a11ecc5-12d2-479f-ad50-bf72f2730e09 pictographic-primitives/other/repeat_0a11ecc5-12d2-479f-ad50-bf72f2730e09.svg \
  'Counterclockwise refresh arrow' 77f5a2c6-8120-4350-aa53-7bb00704de7d 'pictographic-primitives/interface-essential/synchronize refresh arrow_77f5a2c6-8120-4350-aa53-7bb00704de7d.svg' \
  'Counterclockwise synchronize arrows' bafc5d96-6820-5892-a08b-927ab58a96ff 'pictographic-primitives/interface-essential/synchronize arrows_bafc5d96-6820-5892-a08b-927ab58a96ff.svg' \
  'Couple beside heart shaped balloon' bb01aec5-8d69-470f-9cde-ccfb72c0af02 'pictographic-primitives/_uncategorized_14/dating couple balloon_bb01aec5-8d69-470f-9cde-ccfb72c0af02.svg' \
  'Couple standing with hair' 8808cfa8-f297-4bd3-a099-3c4ba3f2b025 'pictographic-primitives/users/multiple man woman 1_8808cfa8-f297-4bd3-a099-3c4ba3f2b025.svg'
