#!/bin/bash
# Batch 71/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/science-apple-gravity  source 3f5c0a54-044c-49ec-b70a-9297048b4eec
#   solo/scissors-cutting-film  source 204c5517-7bf1-4d62-a20e-65036d54c49b
#   solo/scored-bread-loaf  source e29d9ec2-8f36-47bd-baba-22a35e21d40e
#   solo/sea-monster-fish  source a3bce8c0-3b2c-5412-95ae-e3d57af64ace
#   solo/search-bar  source ca339803-3dd7-5813-b3cc-1abd5fbae7be
#   solo/seat-find  source c8e04970-7ef3-408d-aa2e-0b6ea0ec0b65
#   solo/seated-beaver-with-flat-tail  source 24e8edf5-d262-4f32-8f70-02bfa6503ce9
#   solo/seated-buddha-statue  source 9c4fcc62-4575-453e-9566-a7f24bb9a3bd
#   solo/seated-cross-legged-meditator  source 0bd954e0-d5a7-4f63-8f86-8aba221682c2
#   solo/seated-curled-person-solo-2739b613  source 2739b613-55fd-4f47-af97-f5cf90cb523d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Science apple gravity' 3f5c0a54-044c-49ec-b70a-9297048b4eec 'pictographic-primitives/_uncategorized_33/science apple gravity_3f5c0a54-044c-49ec-b70a-9297048b4eec.svg' \
  'Scissors cutting film' 204c5517-7bf1-4d62-a20e-65036d54c49b 'pictographic-primitives/_uncategorized_39/video edit cut_204c5517-7bf1-4d62-a20e-65036d54c49b.svg' \
  'Scored bread loaf' e29d9ec2-8f36-47bd-baba-22a35e21d40e pictographic-primitives/_uncategorized_25/loaf_e29d9ec2-8f36-47bd-baba-22a35e21d40e.svg \
  'Sea monster fish' a3bce8c0-3b2c-5412-95ae-e3d57af64ace 'pictographic-primitives/video-games/batch-03/fantasy leviathan fish_a3bce8c0-3b2c-5412-95ae-e3d57af64ace.svg' \
  'Search bar' ca339803-3dd7-5813-b3cc-1abd5fbae7be 'pictographic-primitives/interface-essential/search bar_ca339803-3dd7-5813-b3cc-1abd5fbae7be.svg' \
  'Seat find' c8e04970-7ef3-408d-aa2e-0b6ea0ec0b65 'pictographic-primitives/_uncategorized_33/seat find_c8e04970-7ef3-408d-aa2e-0b6ea0ec0b65.svg' \
  'Seated beaver with flat tail' 24e8edf5-d262-4f32-8f70-02bfa6503ce9 pictographic-primitives/_uncategorized_06/beaver_24e8edf5-d262-4f32-8f70-02bfa6503ce9.svg \
  'Seated buddha statue' 9c4fcc62-4575-453e-9566-a7f24bb9a3bd 'pictographic-primitives/_uncategorized_24/landmark buddha statue_9c4fcc62-4575-453e-9566-a7f24bb9a3bd.svg' \
  'Seated cross legged meditator' 0bd954e0-d5a7-4f63-8f86-8aba221682c2 pictographic-primitives/_uncategorized_31/pose_0bd954e0-d5a7-4f63-8f86-8aba221682c2.svg \
  'Seated curled person solo 2739b613' 2739b613-55fd-4f47-af97-f5cf90cb523d 'pictographic-primitives/other/poverty person_2739b613-55fd-4f47-af97-f5cf90cb523d.svg'
