#!/bin/bash
# Batch 21/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/ganesha-head  source 13270d5a-f46a-55c2-a6f7-ca5c17dc5aa2
#   solo/gas-f  source 18728730-c932-5c2a-bbae-5f3d79009993
#   solo/gears-and-pins  source 6441c71e-2430-439c-b9ba-705297d8ec05
#   solo/geometric-shapes-in-rounded-square-batch-006-02  source 610733a3-dfd5-42df-9651-d396d039493b
#   solo/girl-beside-balloon  source 496f9e39-2eec-43a0-9970-f46f0bad080b
#   solo/glasses-sun  source 81f3cdea-8b11-5ce2-be37-8b1a02812d9f
#   solo/glider-in-three-quarter-view-batch-057  source 249c7e0d-99c5-4ccf-8b85-f5f836768f7b
#   solo/globe-over-node-in-open-ring  source 47a67469-8ea2-48c7-ae85-82a0c2e8077c
#   solo/goalkeeper-reaching-for-ball  source 974f127b-6a9c-4f4e-b8b2-aaea365c16ef
#   solo/google-assistant-logo  source 9bb2f039-3eaa-4462-836f-2ecb877e1a0e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Ganesha head' 13270d5a-f46a-55c2-a6f7-ca5c17dc5aa2 'pictographic-primitives/holidays/ganesh chaturthi_13270d5a-f46a-55c2-a6f7-ca5c17dc5aa2.svg' \
  'Gas f' 18728730-c932-5c2a-bbae-5f3d79009993 'pictographic-primitives/transportation/gas f_18728730-c932-5c2a-bbae-5f3d79009993.svg' \
  'Gears and pins' 6441c71e-2430-439c-b9ba-705297d8ec05 'pictographic-primitives/programing/internet of thing graph service setting_6441c71e-2430-439c-b9ba-705297d8ec05.svg' \
  'Geometric shapes in rounded square batch 006 02' 610733a3-dfd5-42df-9651-d396d039493b pictographic-primitives/design/shapes_610733a3-dfd5-42df-9651-d396d039493b.svg \
  'Girl beside balloon' 496f9e39-2eec-43a0-9970-f46f0bad080b 'pictographic-primitives/_uncategorized_20/girl ballon_496f9e39-2eec-43a0-9970-f46f0bad080b.svg' \
  'Glasses sun' 81f3cdea-8b11-5ce2-be37-8b1a02812d9f 'pictographic-primitives/accessories/batch-04/glasses sun_81f3cdea-8b11-5ce2-be37-8b1a02812d9f.svg' \
  'Glider in three quarter view batch 057' 249c7e0d-99c5-4ccf-8b85-f5f836768f7b pictographic-primitives/_uncategorized_21/glider_249c7e0d-99c5-4ccf-8b85-f5f836768f7b.svg \
  'Globe over node in open ring' 47a67469-8ea2-48c7-ae85-82a0c2e8077c 'pictographic-primitives/technology/amazon web service cross region data delivery 1_47a67469-8ea2-48c7-ae85-82a0c2e8077c.svg' \
  'Goalkeeper reaching for ball' 974f127b-6a9c-4f4e-b8b2-aaea365c16ef pictographic-primitives/_uncategorized_24/keeper_974f127b-6a9c-4f4e-b8b2-aaea365c16ef.svg \
  'Google assistant logo' 9bb2f039-3eaa-4462-836f-2ecb877e1a0e 'pictographic-primitives/logos/google assistant logo_9bb2f039-3eaa-4462-836f-2ecb877e1a0e.svg'
