#!/bin/bash
# Batch 61/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/oval-amulet-with-teardrop-inset  source 6da45d5c-e173-48d2-b3a9-55d622031360
#   solo/overlapping-chain-rings  source f3554d59-4ee9-5ba8-bc14-5b1324691503
#   solo/overlapping-tragedy-and-comedy-masks  source e22cd911-73e7-45a5-9477-67b78f533035
#   solo/owl-sweeping-brows  source 7b57169e-6f75-4e7a-b1c0-0860a6a44f1f
#   solo/oxygen-mask-in-profile-271fffbf  source 271fffbf-c0f5-4271-aa4c-60ff67604b47
#   solo/padded-infant-car-seat  source c89b9f39-b2b3-4cf2-9e69-42a9bec8626c
#   solo/paint-spray-gun-bottle  source c7b717ca-423a-41ee-ad70-88e50f6aa4d6
#   solo/painted-wall-mural-panel  source c05f1690-f04d-460c-a834-2bdbd5877990
#   solo/pair-of-rounded-house-slippers  source 4862863c-9e5e-4805-9d30-b6bc2429589b
#   solo/pair-of-rubber-boots-batch-051  source 25025168-8453-41bc-837d-12c11e280d6c
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Oval amulet with teardrop inset' 6da45d5c-e173-48d2-b3a9-55d622031360 pictographic-primitives/_uncategorized_03/amulet_6da45d5c-e173-48d2-b3a9-55d622031360.svg \
  'Overlapping chain rings' f3554d59-4ee9-5ba8-bc14-5b1324691503 pictographic-primitives/interface-essential/attachment_f3554d59-4ee9-5ba8-bc14-5b1324691503.svg \
  'Overlapping tragedy and comedy masks' e22cd911-73e7-45a5-9477-67b78f533035 'pictographic-primitives/_uncategorized_26/masks theater_e22cd911-73e7-45a5-9477-67b78f533035.svg' \
  'Owl sweeping brows' 7b57169e-6f75-4e7a-b1c0-0860a6a44f1f pictographic-primitives/_uncategorized_29/owl_7b57169e-6f75-4e7a-b1c0-0860a6a44f1f.svg \
  'Oxygen mask in profile 271fffbf' 271fffbf-c0f5-4271-aa4c-60ff67604b47 'pictographic-primitives/health/oxygen mask head side_271fffbf-c0f5-4271-aa4c-60ff67604b47.svg' \
  'Padded infant car seat' c89b9f39-b2b3-4cf2-9e69-42a9bec8626c 'pictographic-primitives/_uncategorized_05/baby family baby seat car extention_c89b9f39-b2b3-4cf2-9e69-42a9bec8626c.svg' \
  'Paint spray gun bottle' c7b717ca-423a-41ee-ad70-88e50f6aa4d6 'pictographic-primitives/_uncategorized_29/paint sprayer_c7b717ca-423a-41ee-ad70-88e50f6aa4d6.svg' \
  'Painted wall mural panel' c05f1690-f04d-460c-a834-2bdbd5877990 'pictographic-primitives/landmarks/batch-04/east side gallery berlin wall_c05f1690-f04d-460c-a834-2bdbd5877990.svg' \
  'Pair of rounded house slippers' 4862863c-9e5e-4805-9d30-b6bc2429589b pictographic-primitives/_uncategorized_27/moccasins_4862863c-9e5e-4805-9d30-b6bc2429589b.svg \
  'Pair of rubber boots batch 051' 25025168-8453-41bc-837d-12c11e280d6c pictographic-primitives/_uncategorized_20/galoshes_25025168-8453-41bc-837d-12c11e280d6c.svg
