#!/bin/bash
# Batch 89/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/voodoo-doll-with-cross-eyes  source 41a210db-2c37-42ef-baba-2adfb456a545
#   solo/voodoo-doll-with-shoulder-pin  source 3c5477ea-2567-51f0-ada6-871b54935559
#   solo/vr-controller-direction-pad  source 2400f1b4-29ab-57cc-8024-04a0d1460272
#   solo/vr-controller-tracking-window  source 18cfcdec-0823-5e86-8a9f-29b6a04e8e58
#   solo/vr-controller-trigger-button  source a4490b30-7be6-5d25-bd53-1dd893daa628
#   solo/vr-headset-front-view  source d16bbdd4-caba-5737-9a5d-49dbef78c13a
#   solo/vr-headset-profile-solo-019edb66  source 019edb66-6728-4e28-ae42-b3dcaedeee84
#   solo/vr-headset-side-view  source 19d18716-03ac-5472-90fb-a05a4e989ab8
#   solo/vr-headset-video-games  source 427e8988-7e0f-4f0e-930b-42ce7a00bd27
#   solo/vulcan-salute-hand  source e707413f-0adc-48cf-b5cf-de4b6e2e3b22
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Voodoo Doll with Cross Eyes' 41a210db-2c37-42ef-baba-2adfb456a545 'pictographic-primitives/holidays/voodoo doll_41a210db-2c37-42ef-baba-2adfb456a545.svg' \
  'Voodoo Doll with Shoulder Pin' 3c5477ea-2567-51f0-ada6-871b54935559 'pictographic-primitives/holidays/halloween voodoo doll_3c5477ea-2567-51f0-ada6-871b54935559.svg' \
  'Vr controller direction pad' 2400f1b4-29ab-57cc-8024-04a0d1460272 'pictographic-primitives/technology/vr controller_2400f1b4-29ab-57cc-8024-04a0d1460272.svg' \
  'Vr controller tracking window' 18cfcdec-0823-5e86-8a9f-29b6a04e8e58 'pictographic-primitives/technology/vr controller_18cfcdec-0823-5e86-8a9f-29b6a04e8e58.svg' \
  'Vr controller trigger button' a4490b30-7be6-5d25-bd53-1dd893daa628 'pictographic-primitives/technology/vr controller_a4490b30-7be6-5d25-bd53-1dd893daa628.svg' \
  'Vr headset front view' d16bbdd4-caba-5737-9a5d-49dbef78c13a 'pictographic-primitives/technology/meta quest pro_d16bbdd4-caba-5737-9a5d-49dbef78c13a.svg' \
  'Vr headset profile solo 019edb66' 019edb66-6728-4e28-ae42-b3dcaedeee84 'pictographic-primitives/other/vr headset 1_019edb66-6728-4e28-ae42-b3dcaedeee84.svg' \
  'Vr headset side view' 19d18716-03ac-5472-90fb-a05a4e989ab8 'pictographic-primitives/technology/meta quest_19d18716-03ac-5472-90fb-a05a4e989ab8.svg' \
  'Vr headset video games' 427e8988-7e0f-4f0e-930b-42ce7a00bd27 'pictographic-primitives/video-games/vr headset_427e8988-7e0f-4f0e-930b-42ce7a00bd27.svg' \
  'Vulcan salute hand' e707413f-0adc-48cf-b5cf-de4b6e2e3b22 'pictographic-primitives/_uncategorized_39/vulcan salute 2_e707413f-0adc-48cf-b5cf-de4b6e2e3b22.svg'
