#!/bin/bash
# Batch 30/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-supporting-a-heart  source 353c0a3e-5be1-4b87-8e05-ba32a7f03da8
#   solo/hand-supporting-family  source 1123c19a-08d6-416a-bfa1-beb497d65c19
#   solo/hand-swipe-up-gesture  source 2122378f-042e-4e39-bc17-d9bd07419cbd
#   solo/hand-swipe-up-gesture-d98ff112  source d98ff112-975f-484e-8360-e821f5790178
#   solo/hand-swiping-up-gesture  source afe1b28c-6c14-47a6-9d98-c29ac0c4f8b4
#   solo/hand-taking-blister-pill  source 0f507713-b747-5098-b67a-640fe383c7e2
#   solo/hand-touching-multiple-devices  source da217745-f501-41f3-adeb-cb1f2534c16d
#   solo/hand-touching-payment-kiosk  source 3ef6b67e-c42b-4c1d-bcda-1a6c0146046d
#   solo/hand-under-automatic-dryer  source 155a9d36-8aa9-55a7-9cd7-037e9873fa56
#   solo/hand-under-running-water  source a34cf5c7-6f9d-4929-bade-fa576555a44e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand supporting a heart' 353c0a3e-5be1-4b87-8e05-ba32a7f03da8 'pictographic-primitives/_uncategorized_33/romance pride lgbt heart hand holding_353c0a3e-5be1-4b87-8e05-ba32a7f03da8.svg' \
  'Hand supporting family' 1123c19a-08d6-416a-bfa1-beb497d65c19 'pictographic-primitives/_uncategorized_18/family hold_1123c19a-08d6-416a-bfa1-beb497d65c19.svg' \
  'Hand swipe up gesture' 2122378f-042e-4e39-bc17-d9bd07419cbd 'pictographic-primitives/_uncategorized_20/gesture swipe vertical up 2_2122378f-042e-4e39-bc17-d9bd07419cbd.svg' \
  'Hand swipe up gesture d98ff112' d98ff112-975f-484e-8360-e821f5790178 'pictographic-primitives/_uncategorized_20/gesture swipe vertical up 1_d98ff112-975f-484e-8360-e821f5790178.svg' \
  'Hand swiping up gesture' afe1b28c-6c14-47a6-9d98-c29ac0c4f8b4 'pictographic-primitives/_uncategorized_20/gesture tap swipe up 1_afe1b28c-6c14-47a6-9d98-c29ac0c4f8b4.svg' \
  'Hand taking blister pill' 0f507713-b747-5098-b67a-640fe383c7e2 'pictographic-primitives/food/cooking baking tray hand_0f507713-b747-5098-b67a-640fe383c7e2.svg' \
  'Hand touching multiple devices' da217745-f501-41f3-adeb-cb1f2534c16d 'pictographic-primitives/websites/responsive design hand_da217745-f501-41f3-adeb-cb1f2534c16d.svg' \
  'Hand touching payment kiosk' 3ef6b67e-c42b-4c1d-bcda-1a6c0146046d 'pictographic-primitives/payments/self payment touch_3ef6b67e-c42b-4c1d-bcda-1a6c0146046d.svg' \
  'Hand under automatic dryer' 155a9d36-8aa9-55a7-9cd7-037e9873fa56 'pictographic-primitives/wayfinding/automatic hand dryer_155a9d36-8aa9-55a7-9cd7-037e9873fa56.svg' \
  'Hand under running water' a34cf5c7-6f9d-4929-bade-fa576555a44e 'pictographic-primitives/_uncategorized_25/locker room wash hands 1_a34cf5c7-6f9d-4929-bade-fa576555a44e.svg'
