#!/bin/bash
# Batch 62/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/paired-adjustable-suspender-straps  source 403d3b09-28f3-4968-b55e-9f29cb36fbe9
#   solo/paired-plain-shoe-sole-prints  source b0417d52-9012-4fa0-8893-059adb102ede
#   solo/palm-island  source 363923e7-61d2-4227-9a7b-21382da4c901
#   solo/partly-cloudy  source 6f54dfef-a732-45c0-83af-be8ae5456b79
#   solo/pen-writing-looped-signature  source f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5
#   solo/pencil-above-writing-line  source 9831d51b-062f-5589-98b9-8768752474a6
#   solo/pencil-drawing-house-plan-solo-b003-07  source c74c88d8-5693-44d0-8cc1-01e35bd5345e
#   solo/pencil-drawn-squiggle  source 09802860-599e-4eb4-b68f-43ddebc59be7
#   solo/pencil-marking-ballot  source 8baf23d7-4390-4407-a5c3-c22b45141f27
#   solo/people-conflict-1  source ede2fe9e-b299-44e2-90dd-71980708f31f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Paired adjustable suspender straps' 403d3b09-28f3-4968-b55e-9f29cb36fbe9 pictographic-primitives/_uncategorized_37/suspenders_403d3b09-28f3-4968-b55e-9f29cb36fbe9.svg \
  'Paired plain shoe sole prints' b0417d52-9012-4fa0-8893-059adb102ede 'pictographic-primitives/_uncategorized_34/shoe prints_b0417d52-9012-4fa0-8893-059adb102ede.svg' \
  'Palm island' 363923e7-61d2-4227-9a7b-21382da4c901 pictographic-primitives/_uncategorized_23/island_363923e7-61d2-4227-9a7b-21382da4c901.svg \
  'Partly cloudy' 6f54dfef-a732-45c0-83af-be8ae5456b79 'pictographic-primitives/_uncategorized_40/weather snow_6f54dfef-a732-45c0-83af-be8ae5456b79.svg' \
  'Pen writing looped signature' f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5 'pictographic-primitives/files/fill and sign_f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5.svg' \
  'Pencil above writing line' 9831d51b-062f-5589-98b9-8768752474a6 'pictographic-primitives/interface-essential/pencil edit_9831d51b-062f-5589-98b9-8768752474a6.svg' \
  'Pencil drawing house plan solo b003 07' c74c88d8-5693-44d0-8cc1-01e35bd5345e 'pictographic-primitives/construction/project plan pen_c74c88d8-5693-44d0-8cc1-01e35bd5345e.svg' \
  'Pencil drawn squiggle' 09802860-599e-4eb4-b68f-43ddebc59be7 'pictographic-primitives/_uncategorized_30/pen draw 2_09802860-599e-4eb4-b68f-43ddebc59be7.svg' \
  'Pencil marking ballot' 8baf23d7-4390-4407-a5c3-c22b45141f27 pictographic-primitives/school-learning/election_8baf23d7-4390-4407-a5c3-c22b45141f27.svg \
  'People conflict 1' ede2fe9e-b299-44e2-90dd-71980708f31f 'pictographic-primitives/_uncategorized_30/people conflict 1_ede2fe9e-b299-44e2-90dd-71980708f31f.svg'
