#!/bin/bash
# Batch 44/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/images  source 94993cb5-32ce-48f8-ba6f-9fe516a4704d
#   solo/imessage-logo  source 57877e05-412a-4ab7-81af-b1b8f5355989
#   solo/imgur-logo  source f303a1ac-9387-43d7-9138-b3796c7f22b5
#   solo/index-finger-touching-a-phone  source 3730401c-4d35-4b72-a477-2313ba8f23f7
#   solo/infinity-loop  source 44b0abb4-e46a-5a2e-a6a8-e05bdc85c901
#   solo/infinity-loop-solo-batch-025-11  source 4f1c032b-ccc9-5ff8-ab8e-5cdd92d8148d
#   solo/infinity-loop-with-plus-and-minus  source ed08c4ae-cd2f-485c-a2ad-1642f69c286c
#   solo/inflatable-raft-and-paddle  source 92104123-8895-5407-a206-a94ae12de98d
#   solo/information-message-bubble-solo  source e7d4da24-f043-4585-a63c-70bfb89da8a0
#   solo/inkscape-logo  source 284bd116-a688-437f-8349-e9b0799bf5bb
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Images 94993cb5-32ce-48f8-ba6f-9fe516a4704d pictographic-primitives/state/images_94993cb5-32ce-48f8-ba6f-9fe516a4704d.svg \
  'Imessage logo' 57877e05-412a-4ab7-81af-b1b8f5355989 'pictographic-primitives/logos/imessage logo_57877e05-412a-4ab7-81af-b1b8f5355989.svg' \
  'Imgur logo' f303a1ac-9387-43d7-9138-b3796c7f22b5 'pictographic-primitives/logos/imgur logo_f303a1ac-9387-43d7-9138-b3796c7f22b5.svg' \
  'Index finger touching a phone' 3730401c-4d35-4b72-a477-2313ba8f23f7 'pictographic-primitives/_uncategorized_06/bendable phone touch_3730401c-4d35-4b72-a477-2313ba8f23f7.svg' \
  'Infinity loop' 44b0abb4-e46a-5a2e-a6a8-e05bdc85c901 pictographic-primitives/interface-essential/loop_44b0abb4-e46a-5a2e-a6a8-e05bdc85c901.svg \
  'Infinity loop solo batch 025 11' 4f1c032b-ccc9-5ff8-ab8e-5cdd92d8148d 'pictographic-primitives/other/hyperloop symbol_4f1c032b-ccc9-5ff8-ab8e-5cdd92d8148d.svg' \
  'Infinity loop with plus and minus' ed08c4ae-cd2f-485c-a2ad-1642f69c286c 'pictographic-primitives/_uncategorized_04/arduino plus minus_ed08c4ae-cd2f-485c-a2ad-1642f69c286c.svg' \
  'Inflatable raft and paddle' 92104123-8895-5407-a206-a94ae12de98d 'pictographic-primitives/outdoors/sport rafting equipment_92104123-8895-5407-a206-a94ae12de98d.svg' \
  'Information message bubble solo' e7d4da24-f043-4585-a63c-70bfb89da8a0 'pictographic-primitives/messages/messages bubble square information_e7d4da24-f043-4585-a63c-70bfb89da8a0.svg' \
  'Inkscape logo' 284bd116-a688-437f-8349-e9b0799bf5bb 'pictographic-primitives/logos/inkscape logo_284bd116-a688-437f-8349-e9b0799bf5bb.svg'
