#!/bin/bash
# Batch 26/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-holding-heart  source 045520ca-f23a-531a-b54e-ce7bc4cbf52e
#   solo/hand-holding-identity-card-solo-b001-03  source cb16642c-e584-52b6-ae9d-bff1579af112
#   solo/hand-holding-mask  source 5521723a-f61f-58b0-9d3b-7bb857fa845d
#   solo/hand-holding-megaphone  source 5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc
#   solo/hand-holding-open-end-wrench  source 69fd62d6-2807-4c9b-9e1a-35e009d9fd9f
#   solo/hand-holding-paper-airplane  source b3f6c409-ce6d-47c9-92ed-52d3c36236bc
#   solo/hand-holding-rakhi-thread  source 8b38c950-ec94-4fcb-a8d0-90a189601728
#   solo/hand-holding-smartphone-component  source 03153fc4-5884-4120-9394-75c1b95598b0
#   solo/hand-holding-snake  source cc4af31b-ad07-4519-9e2a-a3b2ee7e8834
#   solo/hand-holding-teaspoon  source d2d4de96-ee6e-420e-9d3b-ad79631d2a67
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand holding heart' 045520ca-f23a-531a-b54e-ce7bc4cbf52e 'pictographic-primitives/romance/love heart hold_045520ca-f23a-531a-b54e-ce7bc4cbf52e.svg' \
  'Hand holding identity card solo b001 03' cb16642c-e584-52b6-ae9d-bff1579af112 'pictographic-primitives/apps/digital policies data breach user_cb16642c-e584-52b6-ae9d-bff1579af112.svg' \
  'Hand holding mask' 5521723a-f61f-58b0-9d3b-7bb857fa845d pictographic-primitives/hobbies/cosplay_5521723a-f61f-58b0-9d3b-7bb857fa845d.svg \
  'Hand holding megaphone' 5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc 'pictographic-primitives/work/labor megaphone_5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc.svg' \
  'Hand holding open end wrench' 69fd62d6-2807-4c9b-9e1a-35e009d9fd9f 'pictographic-primitives/business/self service wrench_69fd62d6-2807-4c9b-9e1a-35e009d9fd9f.svg' \
  'Hand holding paper airplane' b3f6c409-ce6d-47c9-92ed-52d3c36236bc pictographic-primitives/hobbies/origami_b3f6c409-ce6d-47c9-92ed-52d3c36236bc.svg \
  'Hand holding rakhi thread' 8b38c950-ec94-4fcb-a8d0-90a189601728 'pictographic-primitives/holidays/raksha bandhan 1_8b38c950-ec94-4fcb-a8d0-90a189601728.svg' \
  'Hand holding smartphone component' 03153fc4-5884-4120-9394-75c1b95598b0 'pictographic-primitives/phones/squeeze sides 1_03153fc4-5884-4120-9394-75c1b95598b0.svg' \
  'Hand holding snake' cc4af31b-ad07-4519-9e2a-a3b2ee7e8834 pictographic-primitives/hobbies/herping_cc4af31b-ad07-4519-9e2a-a3b2ee7e8834.svg \
  'Hand holding teaspoon' d2d4de96-ee6e-420e-9d3b-ad79631d2a67 'pictographic-primitives/food/tea spoon_d2d4de96-ee6e-420e-9d3b-ad79631d2a67.svg'
