#!/bin/bash
# Batch 70/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/rotation-arrow-around-central-circle-batch-013  source 7cf64b00-9120-590b-8cbb-dece46c03d25
#   solo/rounded-square-dash  source 81c70a83-3ed4-4d17-a762-ba61af780c17
#   solo/rounded-staggered-task-bars  source 9b62564b-146e-40a6-b154-9dc3b0f68747
#   solo/row-selected-point  source 888e184a-239b-4644-8a3e-4dd840b12966
#   solo/runner-with-bent-arms  source f719dddb-39cc-47a6-9d4f-87922bcd9830
#   solo/running-person-rounded-silhouette  source e67d265c-c409-4a6f-a8fd-58e1dec4e65f
#   solo/running-person-with-motion-trails  source fa846b07-6bb3-4c07-8266-8826d3da97b9
#   solo/saitama-smiling-head  source 00de027d-6064-4c84-a342-9fe6d6c6667d
#   solo/sanitary-pad  source 31816e20-325b-4b31-8b23-a9a4d37a4bdf
#   solo/scalloped-fleece-with-plain-face-opening  source 858c52c0-c021-48ac-aa6d-6739fbb88ad4
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Rotation arrow around central circle batch 013' 7cf64b00-9120-590b-8cbb-dece46c03d25 'pictographic-primitives/interface-essential/synchronize arrow 2_7cf64b00-9120-590b-8cbb-dece46c03d25.svg' \
  'Rounded square dash' 81c70a83-3ed4-4d17-a762-ba61af780c17 'pictographic-primitives/other/rounded square dash_81c70a83-3ed4-4d17-a762-ba61af780c17.svg' \
  'Rounded staggered task bars' 9b62564b-146e-40a6-b154-9dc3b0f68747 'pictographic-primitives/_uncategorized_40/workflow gantt chart_9b62564b-146e-40a6-b154-9dc3b0f68747.svg' \
  'Row selected point' 888e184a-239b-4644-8a3e-4dd840b12966 'pictographic-primitives/interface-essential/row selected point_888e184a-239b-4644-8a3e-4dd840b12966.svg' \
  'Runner with bent arms' f719dddb-39cc-47a6-9d4f-87922bcd9830 pictographic-primitives/_uncategorized_09/caper_f719dddb-39cc-47a6-9d4f-87922bcd9830.svg \
  'Running person rounded silhouette' e67d265c-c409-4a6f-a8fd-58e1dec4e65f 'pictographic-primitives/_uncategorized_01/aim logo_e67d265c-c409-4a6f-a8fd-58e1dec4e65f.svg' \
  'Running person with motion trails' fa846b07-6bb3-4c07-8266-8826d3da97b9 'pictographic-primitives/wayfinding/safety fire exit 1_fa846b07-6bb3-4c07-8266-8826d3da97b9.svg' \
  'Saitama smiling head' 00de027d-6064-4c84-a342-9fe6d6c6667d 'pictographic-primitives/video-games/batch-08/onepunchman saitama_00de027d-6064-4c84-a342-9fe6d6c6667d.svg' \
  'Sanitary pad' 31816e20-325b-4b31-8b23-a9a4d37a4bdf 'pictographic-primitives/health/sanitary pad_31816e20-325b-4b31-8b23-a9a4d37a4bdf.svg' \
  'Scalloped fleece with plain face opening' 858c52c0-c021-48ac-aa6d-6739fbb88ad4 pictographic-primitives/_uncategorized_34/shearling_858c52c0-c021-48ac-aa6d-6739fbb88ad4.svg
