#!/bin/bash
# Batch 73/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/segmented-crescent-croissant  source ae9a3d91-41ba-425b-bb30-2096c8d8d30c
#   solo/semi-truck-tractor  source bce2f4f1-8b21-461f-9340-829ac98fc9f3
#   solo/shaped-armor-breastplate  source f8e53793-05b3-42da-a1ec-4dba6c2ce3f8
#   solo/shoe-resting-on-open-rack  source 28268293-e5fb-4119-b758-b0cd92d8e4dd
#   solo/shopping-bag-with-attached-tag  source 13e62362-e504-42d4-92b4-09cbc6528e6c
#   solo/shushing-face-with-raised-finger  source 44304182-30e8-43fd-bc78-4dcef5ba1b33
#   solo/shuttlecock-with-three-broad-feathers  source 97335598-fa75-4c18-a90d-4c7cc781b905
#   solo/side-by-side-hug  source e9273110-9f8b-46ca-8cfa-ca10641cf14b
#   solo/side-view-car-with-open-hood  source de4837e9-fc58-4000-be76-deb74b0a3723
#   solo/singing-couple-duet  source 77eda4c7-ef66-4a09-bb3e-bbade9b8a702
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Segmented crescent croissant' ae9a3d91-41ba-425b-bb30-2096c8d8d30c pictographic-primitives/_uncategorized_30/pastry_ae9a3d91-41ba-425b-bb30-2096c8d8d30c.svg \
  'Semi truck tractor' bce2f4f1-8b21-461f-9340-829ac98fc9f3 'pictographic-primitives/_uncategorized_38/truck cargo 1_bce2f4f1-8b21-461f-9340-829ac98fc9f3.svg' \
  'Shaped armor breastplate' f8e53793-05b3-42da-a1ec-4dba6c2ce3f8 pictographic-primitives/_uncategorized_08/breastplate_f8e53793-05b3-42da-a1ec-4dba6c2ce3f8.svg \
  'Shoe resting on open rack' 28268293-e5fb-4119-b758-b0cd92d8e4dd 'pictographic-primitives/_uncategorized_34/shoe rack_28268293-e5fb-4119-b758-b0cd92d8e4dd.svg' \
  'Shopping bag with attached tag' 13e62362-e504-42d4-92b4-09cbc6528e6c 'pictographic-primitives/shopping/shopping bag tag_13e62362-e504-42d4-92b4-09cbc6528e6c.svg' \
  'Shushing face with raised finger' 44304182-30e8-43fd-bc78-4dcef5ba1b33 'pictographic-primitives/_uncategorized_18/face shush_44304182-30e8-43fd-bc78-4dcef5ba1b33.svg' \
  'Shuttlecock with three broad feathers' 97335598-fa75-4c18-a90d-4c7cc781b905 pictographic-primitives/_uncategorized_34/shuttlecock_97335598-fa75-4c18-a90d-4c7cc781b905.svg \
  'Side by side hug' e9273110-9f8b-46ca-8cfa-ca10641cf14b pictographic-primitives/_uncategorized_23/hugger_e9273110-9f8b-46ca-8cfa-ca10641cf14b.svg \
  'Side view car with open hood' de4837e9-fc58-4000-be76-deb74b0a3723 'pictographic-primitives/_uncategorized_09/car hood release_de4837e9-fc58-4000-be76-deb74b0a3723.svg' \
  'Singing couple duet' 77eda4c7-ef66-4a09-bb3e-bbade9b8a702 'pictographic-primitives/entertainment/concert couple duet_77eda4c7-ef66-4a09-bb3e-bbade9b8a702.svg'
