#!/bin/bash
# Batch 11/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/craftsman-holding-a-hammer  source 04ebbce5-fdd2-4c6c-bc45-d497a7339082
#   solo/crane-hook  source 40e56b92-93e6-4122-b70a-f6f602cc3011
#   solo/creeper-face  source 2c8e85ee-be73-4c81-a956-f44ba809e1eb
#   solo/crested-dinosaur-in-left-facing-profile  source 2d6c89c4-e968-4d8b-8072-8bb25e0843ff
#   solo/crossed-fingers-with-extended-thumb-batch-019-13  source ffa5f097-3a06-4fd0-9be9-200d8a58103b
#   solo/crossed-fingers-with-folded-thumb-batch-019-12  source 05f00c7f-9195-41aa-b8b1-c15ae7c59bd3
#   solo/crossed-fork-and-chef-knife  source aba5bfb7-5990-4b45-9606-e4cfe58ad1ea
#   solo/crossed-fork-with-spoon  source 53cd4f82-ae5a-4f7a-8ddd-de64747944f4
#   solo/crossed-wrists-with-closed-hands  source 4d17fb6b-b370-4259-a0ce-98903c9aeaff
#   solo/crowned-visitor-beside-a-tent  source d473ee00-6198-4285-ab1a-64b68f5f176e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Craftsman holding a hammer' 04ebbce5-fdd2-4c6c-bc45-d497a7339082 'pictographic-primitives/_uncategorized_21/greek god hephaestus_04ebbce5-fdd2-4c6c-bc45-d497a7339082.svg' \
  'Crane hook' 40e56b92-93e6-4122-b70a-f6f602cc3011 'pictographic-primitives/shipping/crane hook_40e56b92-93e6-4122-b70a-f6f602cc3011.svg' \
  'Creeper face' 2c8e85ee-be73-4c81-a956-f44ba809e1eb 'pictographic-primitives/_uncategorized_39/video game logo creeper_2c8e85ee-be73-4c81-a956-f44ba809e1eb.svg' \
  'Crested dinosaur in left facing profile' 2d6c89c4-e968-4d8b-8072-8bb25e0843ff 'pictographic-primitives/_uncategorized_15/dinosaur raptor 2_2d6c89c4-e968-4d8b-8072-8bb25e0843ff.svg' \
  'Crossed fingers with extended thumb batch 019 13' ffa5f097-3a06-4fd0-9be9-200d8a58103b 'pictographic-primitives/other/finger crossed_ffa5f097-3a06-4fd0-9be9-200d8a58103b.svg' \
  'Crossed fingers with folded thumb batch 019 12' 05f00c7f-9195-41aa-b8b1-c15ae7c59bd3 'pictographic-primitives/other/finger crossed 1_05f00c7f-9195-41aa-b8b1-c15ae7c59bd3.svg' \
  'Crossed fork and chef knife' aba5bfb7-5990-4b45-9606-e4cfe58ad1ea 'pictographic-primitives/food/symbol fork cross knife_aba5bfb7-5990-4b45-9606-e4cfe58ad1ea.svg' \
  'Crossed fork with spoon' 53cd4f82-ae5a-4f7a-8ddd-de64747944f4 'pictographic-primitives/food/symbol spoon cross fork_53cd4f82-ae5a-4f7a-8ddd-de64747944f4.svg' \
  'Crossed wrists with closed hands' 4d17fb6b-b370-4259-a0ce-98903c9aeaff 'pictographic-primitives/wayfinding/sign language love_4d17fb6b-b370-4259-a0ce-98903c9aeaff.svg' \
  'Crowned visitor beside a tent' d473ee00-6198-4285-ab1a-64b68f5f176e 'pictographic-primitives/_uncategorized_03/amusement park_d473ee00-6198-4285-ab1a-64b68f5f176e.svg'
