#!/bin/bash
# Batch 80/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/three-evergreen-trees  source 309d15f7-00c9-465a-a770-df107f7c15ef
#   solo/three-eyed-demon-goat  source 70ad39c1-8a22-423c-998f-80b1de9c462d
#   solo/three-open-recycling-arrows  source eba86955-13f5-4b0a-a78e-55e6a9fb7a6a
#   solo/three-overlapping-mozzarella-slices-600abb76  source 600abb76-55a0-48a0-9c01-0a94b6498aa6
#   solo/three-people-behind-banner  source b81241aa-ded2-4024-ae80-59ea59c0e043
#   solo/three-people-on-winners-podium  source 43ccfd19-3a54-4d74-99c0-89ec49459bcb
#   solo/three-people-with-central-foreground-figure  source ee7da2e5-378e-466a-b367-d573122d74d0
#   solo/three-person-group  source 65e4d2e2-2f31-4da8-b364-c9d7ecddaa5f
#   solo/three-person-team-busts  source 70088ee7-6460-4eaa-9a2a-4afe242b0f1b
#   solo/three-piece-kebab-skewer-268d30c3  source 268d30c3-e280-4e9e-b635-a834bc354118
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Three evergreen trees' 309d15f7-00c9-465a-a770-df107f7c15ef pictographic-primitives/_uncategorized_19/forest_309d15f7-00c9-465a-a770-df107f7c15ef.svg \
  'Three eyed demon goat' 70ad39c1-8a22-423c-998f-80b1de9c462d 'pictographic-primitives/video-games/batch-02/demon hunter goat head eye_70ad39c1-8a22-423c-998f-80b1de9c462d.svg' \
  'Three open recycling arrows' eba86955-13f5-4b0a-a78e-55e6a9fb7a6a 'pictographic-primitives/_uncategorized_32/recycling symbol_eba86955-13f5-4b0a-a78e-55e6a9fb7a6a.svg' \
  'Three overlapping mozzarella slices 600abb76' 600abb76-55a0-48a0-9c01-0a94b6498aa6 pictographic-primitives/_uncategorized_27/mozzarella_600abb76-55a0-48a0-9c01-0a94b6498aa6.svg \
  'Three people behind banner' b81241aa-ded2-4024-ae80-59ea59c0e043 'pictographic-primitives/_uncategorized_31/protester 1_b81241aa-ded2-4024-ae80-59ea59c0e043.svg' \
  'Three people on winners podium' 43ccfd19-3a54-4d74-99c0-89ec49459bcb 'pictographic-primitives/_uncategorized_32/ranking people first_43ccfd19-3a54-4d74-99c0-89ec49459bcb.svg' \
  'Three people with central foreground figure' ee7da2e5-378e-466a-b367-d573122d74d0 pictographic-primitives/_uncategorized_13/crew_ee7da2e5-378e-466a-b367-d573122d74d0.svg \
  'Three person group' 65e4d2e2-2f31-4da8-b364-c9d7ecddaa5f pictographic-primitives/_uncategorized_38/troop_65e4d2e2-2f31-4da8-b364-c9d7ecddaa5f.svg \
  'Three person team busts' 70088ee7-6460-4eaa-9a2a-4afe242b0f1b pictographic-primitives/_uncategorized_22/horde_70088ee7-6460-4eaa-9a2a-4afe242b0f1b.svg \
  'Three piece kebab skewer 268d30c3' 268d30c3-e280-4e9e-b635-a834bc354118 pictographic-primitives/_uncategorized_24/kebab_268d30c3-e280-4e9e-b635-a834bc354118.svg
