#!/bin/bash
# Batch 66/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/person-reading-newspaper  source babe57e9-dadd-4de6-bc23-187db177304c
#   solo/person-sitting-by-trash-can  source 9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce
#   solo/person-wearing-headphones-in-profile  source 87b4dae7-6d5a-504e-b877-c237378af3a1
#   solo/person-with-angular-heart-torso  source 2aa1a351-da44-44d3-bef9-70273bc4350d
#   solo/person-with-flower  source 53ec9968-774d-4487-a893-11ed69a26520
#   solo/person-with-halo  source 26417ba5-2631-48ff-a294-d0bcf4e7a13e
#   solo/person-with-head-bandage-and-arm-sling  source 483f0053-0d76-4f90-9c4a-d241bc144520
#   solo/person-with-pointed-bandana-face-cover  source 3ae3206f-bd57-4113-91e0-f3d1229102a9
#   solo/person-with-round-hat-and-bob  source 1ac68a90-7c63-4cad-abe7-a2d3bfc53212
#   solo/person-with-side-parted-hair-and-glasses  source 27cefc5a-49c7-5def-9ee4-e76245539d58
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Person reading newspaper' babe57e9-dadd-4de6-bc23-187db177304c 'pictographic-primitives/content/newspaper read_babe57e9-dadd-4de6-bc23-187db177304c.svg' \
  'Person sitting by trash can' 9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce 'pictographic-primitives/users/user homeless poverty_9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce.svg' \
  'Person wearing headphones in profile' 87b4dae7-6d5a-504e-b877-c237378af3a1 'pictographic-primitives/audio/headphones human_87b4dae7-6d5a-504e-b877-c237378af3a1.svg' \
  'Person with angular heart torso' 2aa1a351-da44-44d3-bef9-70273bc4350d 'pictographic-primitives/romance/phone digital well being heart 1_2aa1a351-da44-44d3-bef9-70273bc4350d.svg' \
  'Person with flower' 53ec9968-774d-4487-a893-11ed69a26520 pictographic-primitives/_uncategorized_19/florist_53ec9968-774d-4487-a893-11ed69a26520.svg \
  'Person with halo' 26417ba5-2631-48ff-a294-d0bcf4e7a13e pictographic-primitives/_uncategorized_21/god_26417ba5-2631-48ff-a294-d0bcf4e7a13e.svg \
  'Person with head bandage and arm sling' 483f0053-0d76-4f90-9c4a-d241bc144520 'pictographic-primitives/_uncategorized_05/bandage shoulder head_483f0053-0d76-4f90-9c4a-d241bc144520.svg' \
  'Person with pointed bandana face cover' 3ae3206f-bd57-4113-91e0-f3d1229102a9 'pictographic-primitives/_uncategorized_26/man riot 1_3ae3206f-bd57-4113-91e0-f3d1229102a9.svg' \
  'Person with round hat and bob' 1ac68a90-7c63-4cad-abe7-a2d3bfc53212 'pictographic-primitives/avatars/wide hat girl_1ac68a90-7c63-4cad-abe7-a2d3bfc53212.svg' \
  'Person with side parted hair and glasses' 27cefc5a-49c7-5def-9ee4-e76245539d58 'pictographic-primitives/avatars/woman glasses_27cefc5a-49c7-5def-9ee4-e76245539d58.svg'
