#!/bin/bash
# Batch 91/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/wedding-couple-heart-arch-scene  source 55e06d00-edc0-4555-a59a-bfe50151ffb9
#   solo/wheat-ear-on-stem  source 1388b7e3-83fe-4163-af51-758131c15177
#   solo/wheelchair-fencer  source 028cf4fa-1567-42fd-be63-258e73158b1f
#   solo/wheelchair-with-large-rear-wheel  source 5e279196-338d-47df-9c7e-639098b008bb
#   solo/wheeled-excavator-with-raised-jointed-boom  source 9807802c-4263-4ed0-9917-9adc44389799
#   solo/whole-and-halved-coconut  source 56b93384-adbb-4bc0-859d-6bfa2c2ab4ef
#   solo/whole-and-halved-passion-fruit  source 468502b8-d856-4658-a768-bafd5faaf824
#   solo/whole-lemon-with-single-leaf  source 2ce6dd5a-e886-4158-9462-4ec687e19a2f
#   solo/whole-nutmeg-cut-half  source 339b7781-8241-4f80-b098-a0353a12f2f2
#   solo/wide-tooth-styling-comb  source ec58a5de-f714-4940-bc3c-e16505f17209
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Wedding couple heart arch scene' 55e06d00-edc0-4555-a59a-bfe50151ffb9 'pictographic-primitives/romance/wedding couple_55e06d00-edc0-4555-a59a-bfe50151ffb9.svg' \
  'Wheat ear on stem' 1388b7e3-83fe-4163-af51-758131c15177 pictographic-primitives/_uncategorized_21/gran_1388b7e3-83fe-4163-af51-758131c15177.svg \
  'Wheelchair fencer' 028cf4fa-1567-42fd-be63-258e73158b1f 'pictographic-primitives/_uncategorized_18/fencing 1_028cf4fa-1567-42fd-be63-258e73158b1f.svg' \
  'Wheelchair with large rear wheel' 5e279196-338d-47df-9c7e-639098b008bb 'pictographic-primitives/_uncategorized_27/motorized wheelchair_5e279196-338d-47df-9c7e-639098b008bb.svg' \
  'Wheeled excavator with raised jointed boom' 9807802c-4263-4ed0-9917-9adc44389799 pictographic-primitives/_uncategorized_15/digger_9807802c-4263-4ed0-9917-9adc44389799.svg \
  'Whole and halved coconut' 56b93384-adbb-4bc0-859d-6bfa2c2ab4ef pictographic-primitives/food/coconut_56b93384-adbb-4bc0-859d-6bfa2c2ab4ef.svg \
  'Whole and halved passion fruit' 468502b8-d856-4658-a768-bafd5faaf824 'pictographic-primitives/food/exotic food passion fruit_468502b8-d856-4658-a768-bafd5faaf824.svg' \
  'Whole lemon with single leaf' 2ce6dd5a-e886-4158-9462-4ec687e19a2f pictographic-primitives/_uncategorized_11/citron_2ce6dd5a-e886-4158-9462-4ec687e19a2f.svg \
  'Whole nutmeg cut half' 339b7781-8241-4f80-b098-a0353a12f2f2 pictographic-primitives/_uncategorized_28/nutmeg_339b7781-8241-4f80-b098-a0353a12f2f2.svg \
  'Wide tooth styling comb' ec58a5de-f714-4940-bc3c-e16505f17209 pictographic-primitives/_uncategorized_12/comb_ec58a5de-f714-4940-bc3c-e16505f17209.svg
