#!/bin/bash
# Batch 75/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/smiling-boy-face-reference-41efa512  source 41efa512-77c6-49b9-9e5d-7406a2d96367
#   solo/smiling-boy-in-cap  source 2f3212e0-4927-44c5-94cd-5399ae17ccee
#   solo/smiling-face-hugging-blank-phone  source d6036cf7-bb37-40e5-988a-651ecd81cd5c
#   solo/smiling-flame-face  source a63a01c1-7dea-46ec-ae47-8d900c6183de
#   solo/smiling-tree-trunk-batch-086  source 0e2497bc-6381-4694-8d17-9da0fe023c2e
#   solo/smiling-woman-head-with-bun-and-glasses  source dec0f26b-6bfa-439d-afa0-f23e952da678
#   solo/space-station-with-paired-solar-wings  source 920fba2e-1282-4f3c-a45c-8bd917d8f0f4
#   solo/speaking-profile-with-empty-bubble  source d3d86e97-b873-48ff-bd6b-fc4456184a6e
#   solo/spiral-vortex-in-square-frame  source 40ecea9e-45f2-4285-8c02-e860ff2c94db
#   solo/spool-wrapped-with-thread  source 3794c4a3-1075-45aa-82dc-09c95bb51de3
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Smiling boy face reference 41efa512' 41efa512-77c6-49b9-9e5d-7406a2d96367 'pictographic-primitives/video-games/batch-02/cute male boy charactor_41efa512-77c6-49b9-9e5d-7406a2d96367.svg' \
  'Smiling boy in cap' 2f3212e0-4927-44c5-94cd-5399ae17ccee pictographic-primitives/video-games/batch-07/mario_2f3212e0-4927-44c5-94cd-5399ae17ccee.svg \
  'Smiling face hugging blank phone' d6036cf7-bb37-40e5-988a-651ecd81cd5c 'pictographic-primitives/_uncategorized_16/emoji gaming lover hug iphone_d6036cf7-bb37-40e5-988a-651ecd81cd5c.svg' \
  'Smiling flame face' a63a01c1-7dea-46ec-ae47-8d900c6183de 'pictographic-primitives/_uncategorized_39/video game mario character_a63a01c1-7dea-46ec-ae47-8d900c6183de.svg' \
  'Smiling tree trunk batch 086' 0e2497bc-6381-4694-8d17-9da0fe023c2e 'pictographic-primitives/video-games/batch-07/mario tree_0e2497bc-6381-4694-8d17-9da0fe023c2e.svg' \
  'Smiling woman head with bun and glasses' dec0f26b-6bfa-439d-afa0-f23e952da678 'pictographic-primitives/_uncategorized_21/great grandmother_dec0f26b-6bfa-439d-afa0-f23e952da678.svg' \
  'Space station with paired solar wings' 920fba2e-1282-4f3c-a45c-8bd917d8f0f4 'pictographic-primitives/_uncategorized_35/space station_920fba2e-1282-4f3c-a45c-8bd917d8f0f4.svg' \
  'Speaking profile with empty bubble' d3d86e97-b873-48ff-bd6b-fc4456184a6e pictographic-primitives/_uncategorized_25/linguist_d3d86e97-b873-48ff-bd6b-fc4456184a6e.svg \
  'Spiral vortex in square frame' 40ecea9e-45f2-4285-8c02-e860ff2c94db 'pictographic-primitives/_uncategorized_23/houdini logo_40ecea9e-45f2-4285-8c02-e860ff2c94db.svg' \
  'Spool wrapped with thread' 3794c4a3-1075-45aa-82dc-09c95bb51de3 pictographic-primitives/_uncategorized_18/fiber_3794c4a3-1075-45aa-82dc-09c95bb51de3.svg
