#!/bin/bash
# Batch 81/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/three-round-berries-on-stem  source caa9f497-47bb-4168-ab8e-e78de139cf75
#   solo/three-sugar-cubes-above-deep-spoon  source 5ff5b62c-7e8c-4295-9a82-60061ddaee94
#   solo/three-tower-castle-with-flags  source f3c19f77-a991-4b79-b14f-5d47ca735c7a
#   solo/thumbs-down-hand  source ccfc5e52-667a-4591-9a3a-ef60a2289489
#   solo/thumbs-up-gesture  source a9ba009c-47a7-4e87-ab46-51d15028bca4
#   solo/thunderbolt-charging-power-cable-batch-007-03  source 0df11177-f26b-418b-88d9-7a1b4a229799
#   solo/tilted-keypad-cash-register  source 0c49b262-1334-4719-a58f-965ec30f28ad
#   solo/tilted-square-paint-bucket  source e33b86b4-fa83-4e92-b996-170c46bf04a1
#   solo/toothed-hand-saw-batch-064  source fb9e5252-41fd-4313-ae36-6711e4c93e41
#   solo/traditional-japanese-mochi  source a17c31d9-809a-4249-988f-236acbbe14df
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Three round berries on stem' caa9f497-47bb-4168-ab8e-e78de139cf75 pictographic-primitives/_uncategorized_13/cranberry_caa9f497-47bb-4168-ab8e-e78de139cf75.svg \
  'Three sugar cubes above deep spoon' 5ff5b62c-7e8c-4295-9a82-60061ddaee94 'pictographic-primitives/_uncategorized_16/drinks extra add sugar_5ff5b62c-7e8c-4295-9a82-60061ddaee94.svg' \
  'Three tower castle with flags' f3c19f77-a991-4b79-b14f-5d47ca735c7a 'pictographic-primitives/_uncategorized_03/amusement park castle_f3c19f77-a991-4b79-b14f-5d47ca735c7a.svg' \
  'Thumbs down hand' ccfc5e52-667a-4591-9a3a-ef60a2289489 'pictographic-primitives/_uncategorized_37/thumbs down_ccfc5e52-667a-4591-9a3a-ef60a2289489.svg' \
  'Thumbs up gesture' a9ba009c-47a7-4e87-ab46-51d15028bca4 'pictographic-primitives/_uncategorized_37/thumb up like sparkle_a9ba009c-47a7-4e87-ab46-51d15028bca4.svg' \
  'Thunderbolt charging power cable batch 007 03' 0df11177-f26b-418b-88d9-7a1b4a229799 'pictographic-primitives/electronics/thunderbolt cable_0df11177-f26b-418b-88d9-7a1b4a229799.svg' \
  'Tilted keypad cash register' 0c49b262-1334-4719-a58f-965ec30f28ad 'pictographic-primitives/_uncategorized_10/cash register_0c49b262-1334-4719-a58f-965ec30f28ad.svg' \
  'Tilted square paint bucket' e33b86b4-fa83-4e92-b996-170c46bf04a1 'pictographic-primitives/_uncategorized_12/color bucket 1_e33b86b4-fa83-4e92-b996-170c46bf04a1.svg' \
  'Toothed hand saw batch 064' fb9e5252-41fd-4313-ae36-6711e4c93e41 pictographic-primitives/_uncategorized_22/handsaw_fb9e5252-41fd-4313-ae36-6711e4c93e41.svg \
  'Traditional japanese mochi' a17c31d9-809a-4249-988f-236acbbe14df pictographic-primitives/_uncategorized_27/mochi_a17c31d9-809a-4249-988f-236acbbe14df.svg
