#!/bin/bash
# Batch 23/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/google-sheets-logo  source b10704f2-58af-44bd-849f-dcd977ac9d2f
#   solo/google-shopping-logo  source ef272f31-527b-4b06-8cdb-28e8d4532728
#   solo/google-slides-logo  source 367e5840-c83e-4242-a725-8de6b0acb2c8
#   solo/google-talk-logo  source 1a392865-4569-47ef-8d05-e46454c31157
#   solo/gprs-text  source 378a8b67-3065-5023-b054-9fccecc32c2c
#   solo/graduate-with-two-people  source 3bbdfa95-8a10-4cf0-910a-fb693fb29316
#   solo/grandpa  source 2e10b85b-424e-4558-b38e-c8c3b76d9e52
#   solo/grim-reaper-with-scythe  source 10802c86-44a5-43d2-9258-49fbaaa0c39d
#   solo/grooveshark-logo  source e8555acb-9beb-49f8-8fcb-c5960dfa8ebb
#   solo/gym-logo  source 6061b2ad-a34e-4da4-a716-1952152438f8
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Google sheets logo' b10704f2-58af-44bd-849f-dcd977ac9d2f 'pictographic-primitives/logos/google sheets logo_b10704f2-58af-44bd-849f-dcd977ac9d2f.svg' \
  'Google shopping logo' ef272f31-527b-4b06-8cdb-28e8d4532728 'pictographic-primitives/logos/google shopping logo_ef272f31-527b-4b06-8cdb-28e8d4532728.svg' \
  'Google slides logo' 367e5840-c83e-4242-a725-8de6b0acb2c8 'pictographic-primitives/logos/google slides logo_367e5840-c83e-4242-a725-8de6b0acb2c8.svg' \
  'Google talk logo' 1a392865-4569-47ef-8d05-e46454c31157 'pictographic-primitives/logos/google talk logo_1a392865-4569-47ef-8d05-e46454c31157.svg' \
  'Gprs text' 378a8b67-3065-5023-b054-9fccecc32c2c pictographic-primitives/mobile/gprs_378a8b67-3065-5023-b054-9fccecc32c2c.svg \
  'Graduate with two people' 3bbdfa95-8a10-4cf0-910a-fb693fb29316 'pictographic-primitives/school-learning/study virtual classroom_3bbdfa95-8a10-4cf0-910a-fb693fb29316.svg' \
  Grandpa 2e10b85b-424e-4558-b38e-c8c3b76d9e52 pictographic-primitives/_uncategorized_21/grandpa_2e10b85b-424e-4558-b38e-c8c3b76d9e52.svg \
  'Grim reaper with scythe' 10802c86-44a5-43d2-9258-49fbaaa0c39d 'pictographic-primitives/holidays/grim reaper_10802c86-44a5-43d2-9258-49fbaaa0c39d.svg' \
  'Grooveshark logo' e8555acb-9beb-49f8-8fcb-c5960dfa8ebb 'pictographic-primitives/logos/grooveshark logo_e8555acb-9beb-49f8-8fcb-c5960dfa8ebb.svg' \
  'Gym logo' 6061b2ad-a34e-4da4-a716-1952152438f8 'pictographic-primitives/logos/gym logo_6061b2ad-a34e-4da4-a716-1952152438f8.svg'
