#!/bin/bash
# Batch 59/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/mobile-user-profile  source 07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74
#   solo/money-message-bubble-solo  source 93c99818-8211-47c5-bf92-9fa83e3cab72
#   solo/monitor-heart-beat-touch  source effbc2d1-e5a5-4a1b-88be-7ca24a41a9c1
#   solo/monitor-letters  source dd80ecbb-13f8-47dc-9883-44bd19aa7cc6
#   solo/monitor-math  source 6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13
#   solo/monitor-small-squares  source 1aef3c2a-6d0d-43a2-9616-698d70dc5298
#   solo/multi-directional-expansion-touch-gesture  source 72ae8ec4-64bb-45c4-a5c0-d263a783fa1d
#   solo/multiple-file-folders  source 765a4718-3652-4552-81e5-4d88f99cd8e5
#   solo/music-monitor-and-speaker  source ddfc1e41-af2e-4f27-a89f-8cb60796155a
#   solo/network-5g  source 9dc361bf-d268-4878-852c-ebdc9f66c69b
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Mobile user profile' 07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74 'pictographic-primitives/other/mobile phone user_07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74.svg' \
  'Money message bubble solo' 93c99818-8211-47c5-bf92-9fa83e3cab72 'pictographic-primitives/other/message dollar sign lines_93c99818-8211-47c5-bf92-9fa83e3cab72.svg' \
  'Monitor heart beat touch' effbc2d1-e5a5-4a1b-88be-7ca24a41a9c1 'pictographic-primitives/health/monitor heart beat touch_effbc2d1-e5a5-4a1b-88be-7ca24a41a9c1.svg' \
  'Monitor letters' dd80ecbb-13f8-47dc-9883-44bd19aa7cc6 'pictographic-primitives/other/monitor letters_dd80ecbb-13f8-47dc-9883-44bd19aa7cc6.svg' \
  'Monitor math' 6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13 'pictographic-primitives/other/monitor math_6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13.svg' \
  'Monitor small squares' 1aef3c2a-6d0d-43a2-9616-698d70dc5298 'pictographic-primitives/other/monitor small squares_1aef3c2a-6d0d-43a2-9616-698d70dc5298.svg' \
  'Multi directional expansion touch gesture' 72ae8ec4-64bb-45c4-a5c0-d263a783fa1d 'pictographic-primitives/_uncategorized_20/gesture expand_72ae8ec4-64bb-45c4-a5c0-d263a783fa1d.svg' \
  'Multiple file folders' 765a4718-3652-4552-81e5-4d88f99cd8e5 pictographic-primitives/_uncategorized_19/folders_765a4718-3652-4552-81e5-4d88f99cd8e5.svg \
  'Music monitor and speaker' ddfc1e41-af2e-4f27-a89f-8cb60796155a 'pictographic-primitives/_uncategorized_27/modern music monitor speaker_ddfc1e41-af2e-4f27-a89f-8cb60796155a.svg' \
  'Network 5g' 9dc361bf-d268-4878-852c-ebdc9f66c69b 'pictographic-primitives/technology/network 5g_9dc361bf-d268-4878-852c-ebdc9f66c69b.svg'
