#!/bin/bash
# Batch 93/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/wireless-earbuds-charging-case-batch-001-r2  source 9ae8162b-1fa3-4f3e-a7f2-5375c421b45f
#   solo/woman-in-draped-attire  source cc95eb24-a835-44c4-8b2f-8722e687ddef
#   solo/woman-wearing-a-face-mask  source e1f5e900-261d-4886-9c63-8beef0eb6820
#   solo/woman-wearing-drooping-nightcap  source 573cd435-465f-4569-b444-d50f28ac43d3
#   solo/woman-with-halo  source 51d30682-39f9-5a08-95aa-4743470a5b0c
#   solo/wood-board-with-knot  source cedb9824-d21f-4060-9df0-b542ab84c45a
#   solo/worker-beside-box-on-conveyor  source a73f189d-afeb-4835-99c1-01f3a49dee0f
#   solo/working-from-home  source 44ffdb4d-63c5-4a9d-96a6-0694a78bbb7c
#   solo/wraparound-safety-goggles  source 21eee887-28cb-4e25-b739-4d7134cd9a28
#   solo/xbox-emblem-batch-086  source 94fd09a9-094a-4095-a5b6-0a290483d967
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Wireless earbuds charging case batch 001 r2' 9ae8162b-1fa3-4f3e-a7f2-5375c421b45f 'pictographic-primitives/audio/earpods charge_9ae8162b-1fa3-4f3e-a7f2-5375c421b45f.svg' \
  'Woman in Draped Attire' cc95eb24-a835-44c4-8b2f-8722e687ddef 'pictographic-primitives/holidays/gokul ashtami_cc95eb24-a835-44c4-8b2f-8722e687ddef.svg' \
  'Woman wearing a face mask' e1f5e900-261d-4886-9c63-8beef0eb6820 'pictographic-primitives/_uncategorized_01/air purifier 5_e1f5e900-261d-4886-9c63-8beef0eb6820.svg' \
  'Woman wearing drooping nightcap' 573cd435-465f-4569-b444-d50f28ac43d3 'pictographic-primitives/avatars/pajamas woman_573cd435-465f-4569-b444-d50f28ac43d3.svg' \
  'Woman with halo' 51d30682-39f9-5a08-95aa-4743470a5b0c pictographic-primitives/religion/female_51d30682-39f9-5a08-95aa-4743470a5b0c.svg \
  'Wood board with knot' cedb9824-d21f-4060-9df0-b542ab84c45a 'pictographic-primitives/construction/wood material_cedb9824-d21f-4060-9df0-b542ab84c45a.svg' \
  'Worker beside box on conveyor' a73f189d-afeb-4835-99c1-01f3a49dee0f 'pictographic-primitives/_uncategorized_18/factory manufacturing line worker_a73f189d-afeb-4835-99c1-01f3a49dee0f.svg' \
  'Working from home' 44ffdb4d-63c5-4a9d-96a6-0694a78bbb7c 'pictographic-primitives/_uncategorized_40/work from home user laptop 2_44ffdb4d-63c5-4a9d-96a6-0694a78bbb7c.svg' \
  'Wraparound safety goggles' 21eee887-28cb-4e25-b739-4d7134cd9a28 'pictographic-primitives/_uncategorized_33/safety goggles_21eee887-28cb-4e25-b739-4d7134cd9a28.svg' \
  'Xbox emblem batch 086' 94fd09a9-094a-4095-a5b6-0a290483d967 'pictographic-primitives/video-games/batch-06/logo xbox_94fd09a9-094a-4095-a5b6-0a290483d967.svg'
