#!/bin/bash
# Batch 88/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/virtual-coin-crypto-infinite  source a3462919-e2c3-488f-97ad-cc3959be0886
#   solo/virtual-coin-crypto-iota  source 85afe198-8caf-4a8a-b751-b82fbc6bda8c
#   solo/virtual-reality-visor  source 31bb80bc-c783-4f9b-9edd-e437478a15a7
#   solo/virtual-shopping-fashion-fitting  source fdc676d2-ae16-4a1e-aed2-83f04934bae5
#   solo/visitor-beside-a-ferris-wheel  source 2b9eae9d-fe2c-4ba8-8741-be1b46787fa6
#   solo/voicemail-symbol  source 06fe9ad6-66bf-5efc-9afe-5d64c2e9319b
#   solo/voicemail-symbol-a0009082  source a0009082-705a-5bdd-ae51-8a15a29b9b25
#   solo/volleyball  source 63d71592-7009-4b2f-9fcf-d1f26c3b82ce
#   solo/volleyball-panel-ball  source 81273324-0457-42f4-b9e3-f24d809cec3b
#   solo/volume-control  source f2722b0f-fff4-493b-8f5d-619316ae89e6
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Virtual coin crypto infinite' a3462919-e2c3-488f-97ad-cc3959be0886 'pictographic-primitives/finance/virtual coin crypto infinite_a3462919-e2c3-488f-97ad-cc3959be0886.svg' \
  'Virtual coin crypto iota' 85afe198-8caf-4a8a-b751-b82fbc6bda8c 'pictographic-primitives/finance/virtual coin crypto iota_85afe198-8caf-4a8a-b751-b82fbc6bda8c.svg' \
  'Virtual reality visor' 31bb80bc-c783-4f9b-9edd-e437478a15a7 'pictographic-primitives/combination/vr headset 1_31bb80bc-c783-4f9b-9edd-e437478a15a7.svg' \
  'Virtual shopping fashion fitting' fdc676d2-ae16-4a1e-aed2-83f04934bae5 'pictographic-primitives/technology/virtual shopping fashion fitting_fdc676d2-ae16-4a1e-aed2-83f04934bae5.svg' \
  'Visitor beside a ferris wheel' 2b9eae9d-fe2c-4ba8-8741-be1b46787fa6 'pictographic-primitives/_uncategorized_03/amusement park ferris wheel person_2b9eae9d-fe2c-4ba8-8741-be1b46787fa6.svg' \
  'Voicemail symbol' 06fe9ad6-66bf-5efc-9afe-5d64c2e9319b 'pictographic-primitives/phones/phone actions voice mail_06fe9ad6-66bf-5efc-9afe-5d64c2e9319b.svg' \
  'Voicemail symbol a0009082' a0009082-705a-5bdd-ae51-8a15a29b9b25 'pictographic-primitives/phones/voice mail_a0009082-705a-5bdd-ae51-8a15a29b9b25.svg' \
  Volleyball 63d71592-7009-4b2f-9fcf-d1f26c3b82ce pictographic-primitives/_uncategorized_39/volleyball_63d71592-7009-4b2f-9fcf-d1f26c3b82ce.svg \
  'Volleyball panel ball' 81273324-0457-42f4-b9e3-f24d809cec3b 'pictographic-primitives/sports/volleyball ball_81273324-0457-42f4-b9e3-f24d809cec3b.svg' \
  'Volume control' f2722b0f-fff4-493b-8f5d-619316ae89e6 'pictographic-primitives/audio/volume control_f2722b0f-fff4-493b-8f5d-619316ae89e6.svg'
