#!/bin/bash
# Batch 78/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/studded-soccer-cleat  source 92901ffc-8850-47e1-b64c-7fd71adcc49e
#   solo/sun-and-cloud-with-rain-v2  source 33b4f573-ff3c-49d0-b558-91f25f42f57a
#   solo/sun-and-sunflowers  source 1390e012-2151-49eb-9917-83a27c15c4af
#   solo/sun-appearing-behind-rounded-hill  source 9209ad15-ccc6-48e1-b297-b65ddf79ec66
#   solo/sun-snow-thunderstorm  source d3f2158b-1711-402f-9758-99a2682ee0d0
#   solo/support-agent-with-headphones  source a43a1b34-ba30-51e2-8567-7e92fc1abc1c
#   solo/sweating-face-with-open-mouth  source e7345811-ff31-4d0a-b09b-edeaa642a06e
#   solo/swimming-minnow  source f6111608-d0fc-4660-be8f-16a26d108353
#   solo/synchronize-arrows-search  source df40480b-5166-4148-8ffb-4e38ec361c58
#   solo/tall-rain-boot-with-heel  source 74cb04e1-aad2-49e3-a0a6-99254c186818
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Studded soccer cleat' 92901ffc-8850-47e1-b64c-7fd71adcc49e pictographic-primitives/_uncategorized_11/cleat_92901ffc-8850-47e1-b64c-7fd71adcc49e.svg \
  'Sun and cloud with rain v2' 33b4f573-ff3c-49d0-b558-91f25f42f57a 'pictographic-primitives/_uncategorized_11/cloud sun rain_33b4f573-ff3c-49d0-b558-91f25f42f57a.svg' \
  'Sun and sunflowers' 1390e012-2151-49eb-9917-83a27c15c4af 'pictographic-primitives/nature/outdoors sun plants_1390e012-2151-49eb-9917-83a27c15c4af.svg' \
  'Sun appearing behind rounded hill' 9209ad15-ccc6-48e1-b297-b65ddf79ec66 'pictographic-primitives/_uncategorized_14/day noon_9209ad15-ccc6-48e1-b297-b65ddf79ec66.svg' \
  'Sun snow thunderstorm' d3f2158b-1711-402f-9758-99a2682ee0d0 'pictographic-primitives/_uncategorized_40/weather snow thunder_d3f2158b-1711-402f-9758-99a2682ee0d0.svg' \
  'Support agent with headphones' a43a1b34-ba30-51e2-8567-7e92fc1abc1c 'pictographic-primitives/interface-essential/headphones customer support human_a43a1b34-ba30-51e2-8567-7e92fc1abc1c.svg' \
  'Sweating face with open mouth' e7345811-ff31-4d0a-b09b-edeaa642a06e 'pictographic-primitives/_uncategorized_18/face tongue sweat_e7345811-ff31-4d0a-b09b-edeaa642a06e.svg' \
  'Swimming minnow' f6111608-d0fc-4660-be8f-16a26d108353 pictographic-primitives/_uncategorized_27/minnow_f6111608-d0fc-4660-be8f-16a26d108353.svg \
  'Synchronize arrows search' df40480b-5166-4148-8ffb-4e38ec361c58 'pictographic-primitives/interface-essential/synchronize arrows search_df40480b-5166-4148-8ffb-4e38ec361c58.svg' \
  'Tall rain boot with heel' 74cb04e1-aad2-49e3-a0a6-99254c186818 pictographic-primitives/_uncategorized_07/boot_74cb04e1-aad2-49e3-a0a6-99254c186818.svg
