#!/bin/bash
# Batch 24/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/gymnast-in-split-leg-handstand  source f9c85943-9f04-45d6-8250-b8130ceafc94
#   solo/gymnast-supported-on-horizontal-bar  source 3e406d94-3472-495a-b48a-7dc0d21a13ed
#   solo/hackerone-logo  source 7f3ae56d-9512-45bc-a87b-3692c21e7f5c
#   solo/hand-expansion-touch-gesture  source 52c32e39-3bac-4a0f-8904-0928470decff
#   solo/hand-facing-down-batch-024-02  source acc6f9a7-f1e5-46cf-961e-ce00f3dd0639
#   solo/hand-gesture-swipe-up  source 34ac1798-6cb8-43a2-9504-66d8147d1e43
#   solo/hand-gesture-vertical-swipe-down  source 03865b1d-fc66-475a-9459-24a0071714cf
#   solo/hand-grabbing-square-document  source 6818d5fa-ca7b-4205-ab33-ff7acb27ba99
#   solo/hand-gripping-a-waving-flag  source b50450df-a0b2-4543-acfe-30ea5158a73f
#   solo/hand-gripping-blank-upright-document  source 1996803f-fb1a-423a-9fd2-78b1fe8a9c74
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Gymnast in split leg handstand' f9c85943-9f04-45d6-8250-b8130ceafc94 pictographic-primitives/_uncategorized_21/gymnastics_f9c85943-9f04-45d6-8250-b8130ceafc94.svg \
  'Gymnast supported on horizontal bar' 3e406d94-3472-495a-b48a-7dc0d21a13ed 'pictographic-primitives/_uncategorized_21/gymnastics acrobatic hanging person_3e406d94-3472-495a-b48a-7dc0d21a13ed.svg' \
  'Hackerone logo' 7f3ae56d-9512-45bc-a87b-3692c21e7f5c 'pictographic-primitives/logos/hackerone logo_7f3ae56d-9512-45bc-a87b-3692c21e7f5c.svg' \
  'Hand expansion touch gesture' 52c32e39-3bac-4a0f-8904-0928470decff 'pictographic-primitives/_uncategorized_20/gesture expand 1_52c32e39-3bac-4a0f-8904-0928470decff.svg' \
  'Hand facing down batch 024 02' acc6f9a7-f1e5-46cf-961e-ce00f3dd0639 'pictographic-primitives/other/hand down_acc6f9a7-f1e5-46cf-961e-ce00f3dd0639.svg' \
  'Hand gesture swipe up' 34ac1798-6cb8-43a2-9504-66d8147d1e43 'pictographic-primitives/_uncategorized_20/gesture tap swipe up_34ac1798-6cb8-43a2-9504-66d8147d1e43.svg' \
  'Hand gesture vertical swipe down' 03865b1d-fc66-475a-9459-24a0071714cf 'pictographic-primitives/_uncategorized_20/gesture swipe vertical down 2_03865b1d-fc66-475a-9459-24a0071714cf.svg' \
  'Hand grabbing square document' 6818d5fa-ca7b-4205-ab33-ff7acb27ba99 'pictographic-primitives/interface-essential/drag drop hand_6818d5fa-ca7b-4205-ab33-ff7acb27ba99.svg' \
  'Hand gripping a waving flag' b50450df-a0b2-4543-acfe-30ea5158a73f 'pictographic-primitives/_uncategorized_33/romance pride lesbian lgbt flag hand_b50450df-a0b2-4543-acfe-30ea5158a73f.svg' \
  'Hand gripping blank upright document' 1996803f-fb1a-423a-9fd2-78b1fe8a9c74 'pictographic-primitives/_uncategorized_08/business contract give_1996803f-fb1a-423a-9fd2-78b1fe8a9c74.svg'
