#!/bin/bash
# Batch 13/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/curved-showerhead-water-jets  source a384c77d-8674-4738-9d1b-23923510b862
#   solo/curved-straw-broom-sweeping-dust  source 23b1dce1-01a3-4d0e-9224-6b91d6c92bd5
#   solo/curved-string-of-beads  source ed4699f6-a912-4876-9b67-eba4703923e0
#   solo/cute-lemur-animal-face  source 6b0fa457-2293-4b0b-b837-f3484ee72ffc
#   solo/cyclist-on-a-fully-framed-bicycle  source 816c0a6d-a6b1-4041-9b3e-aa2bb963535f
#   solo/dancer-with-raised-arm-and-bent-knee  source 771cdf79-e59d-4541-bdff-a58073f629be
#   solo/dancing-person-with-music-notes  source 71810c29-2b03-4b67-8fc7-929b40352813
#   solo/dancing-woman-with-music-notes  source 6c6896b3-8871-41eb-bf24-63a28db82e65
#   solo/dash-circle-large-head  source edd1a1a5-5b11-4ec8-9855-ec307205ccb2
#   solo/data-shapes-flowing-to-the-right  source d1e42083-a36c-4e25-bb45-512c8c5a0866
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Curved showerhead water jets' a384c77d-8674-4738-9d1b-23923510b862 'pictographic-primitives/furnitures/light rain sensor_a384c77d-8674-4738-9d1b-23923510b862.svg' \
  'Curved straw broom sweeping dust' 23b1dce1-01a3-4d0e-9224-6b91d6c92bd5 'pictographic-primitives/_uncategorized_08/broom sweep 1_23b1dce1-01a3-4d0e-9224-6b91d6c92bd5.svg' \
  'Curved string of beads' ed4699f6-a912-4876-9b67-eba4703923e0 pictographic-primitives/_uncategorized_06/bead_ed4699f6-a912-4876-9b67-eba4703923e0.svg \
  'Cute lemur animal face' 6b0fa457-2293-4b0b-b837-f3484ee72ffc pictographic-primitives/_uncategorized_25/lemur_6b0fa457-2293-4b0b-b837-f3484ee72ffc.svg \
  'Cyclist on a fully framed bicycle' 816c0a6d-a6b1-4041-9b3e-aa2bb963535f 'pictographic-primitives/_uncategorized_06/bicycle person_816c0a6d-a6b1-4041-9b3e-aa2bb963535f.svg' \
  'Dancer with raised arm and bent knee' 771cdf79-e59d-4541-bdff-a58073f629be pictographic-primitives/_uncategorized_14/dancer_771cdf79-e59d-4541-bdff-a58073f629be.svg \
  'Dancing person with music notes' 71810c29-2b03-4b67-8fc7-929b40352813 'pictographic-primitives/entertainment/party music dance_71810c29-2b03-4b67-8fc7-929b40352813.svg' \
  'Dancing woman with music notes' 6c6896b3-8871-41eb-bf24-63a28db82e65 'pictographic-primitives/entertainment/party music dance woman_6c6896b3-8871-41eb-bf24-63a28db82e65.svg' \
  'Dash circle large head' edd1a1a5-5b11-4ec8-9855-ec307205ccb2 'pictographic-primitives/arrows/dash circle large head_edd1a1a5-5b11-4ec8-9855-ec307205ccb2.svg' \
  'Data shapes flowing to the right' d1e42083-a36c-4e25-bb45-512c8c5a0866 'pictographic-primitives/_uncategorized_02/amazon web service glue data brew visual data preparation_d1e42083-a36c-4e25-bb45-512c8c5a0866.svg'
