#!/bin/bash
# Batch 48/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/jumbo-jet  source 440ed8d8-ba1d-485b-bd8d-a6ae4bdc2513
#   solo/karate-fighting-stance  source 334bfd33-9625-567b-83fd-5ebd4bb19a97
#   solo/karate-high-kick  source 8ec365ec-24ce-4d98-9b7f-1d62e79035fa
#   solo/kayak-and-paddle  source a40dd6b4-7ef7-5a0e-b996-7bd77b8c7cf8
#   solo/kayak-cockpit-paddle  source a056c9dc-e8dd-5493-9902-c9d72635972e
#   solo/kazoo  source e0c7edd3-bf2b-4e89-8471-4b408715e085
#   solo/kendo-practitioner  source 9965479b-3edc-4ede-b411-6d36ce7392de
#   solo/kermit-face  source 4eff967d-5df4-43e4-98a7-d78f84b1fc39
#   solo/keroro-face-in-helmet  source 598d228b-5936-4dbd-bec8-6034163e03d3
#   solo/kettle-with-arch-handle  source c993c3d0-e1c4-4839-9573-2bb3f20d4061
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Jumbo jet' 440ed8d8-ba1d-485b-bd8d-a6ae4bdc2513 'pictographic-primitives/_uncategorized_24/jumbo jet_440ed8d8-ba1d-485b-bd8d-a6ae4bdc2513.svg' \
  'Karate fighting stance' 334bfd33-9625-567b-83fd-5ebd4bb19a97 'pictographic-primitives/sports/martial arts karate_334bfd33-9625-567b-83fd-5ebd4bb19a97.svg' \
  'Karate high kick' 8ec365ec-24ce-4d98-9b7f-1d62e79035fa pictographic-primitives/sports/karate_8ec365ec-24ce-4d98-9b7f-1d62e79035fa.svg \
  'Kayak and paddle' a40dd6b4-7ef7-5a0e-b996-7bd77b8c7cf8 pictographic-primitives/recreation/canoe_a40dd6b4-7ef7-5a0e-b996-7bd77b8c7cf8.svg \
  'Kayak cockpit paddle' a056c9dc-e8dd-5493-9902-c9d72635972e pictographic-primitives/transportation/kayak_a056c9dc-e8dd-5493-9902-c9d72635972e.svg \
  Kazoo e0c7edd3-bf2b-4e89-8471-4b408715e085 pictographic-primitives/_uncategorized_24/kazoo_e0c7edd3-bf2b-4e89-8471-4b408715e085.svg \
  'Kendo practitioner' 9965479b-3edc-4ede-b411-6d36ce7392de pictographic-primitives/_uncategorized_24/kendo_9965479b-3edc-4ede-b411-6d36ce7392de.svg \
  'Kermit face' 4eff967d-5df4-43e4-98a7-d78f84b1fc39 pictographic-primitives/video-games/batch-05/kermit_4eff967d-5df4-43e4-98a7-d78f84b1fc39.svg \
  'Keroro face in helmet' 598d228b-5936-4dbd-bec8-6034163e03d3 'pictographic-primitives/video-games/batch-05/keroro frog alien_598d228b-5936-4dbd-bec8-6034163e03d3.svg' \
  'Kettle with arch handle' c993c3d0-e1c4-4839-9573-2bb3f20d4061 pictographic-primitives/_uncategorized_24/kettle_c993c3d0-e1c4-4839-9573-2bb3f20d4061.svg
