#!/bin/bash
# Batch 46/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/inverted-freestyle-skier-batch-051  source 95760764-05e8-4308-8e26-5b559bc41d45
#   solo/invision-logo  source 6742b2e4-0a48-4b9c-a3b9-fddbfa96da87
#   solo/invoice-in-open-envelope  source 57201c70-c002-40bb-8fad-0abd9f9ca4db
#   solo/iot-pin-markers  source b65f68ff-83c3-5c4a-9b2d-bb76e66ff665
#   solo/irc-galleria-logo  source 5ce8e1ba-097d-4525-a918-6d39f51da6d9
#   solo/islamic-women-hijab-1-avatar  source 2da10a1c-94d1-53ec-a2db-86f6dd5377fd
#   solo/isometric-cube-with-three-circular-nodes  source a1ebcd1c-faf5-4d0c-93f2-8b0f08933387
#   solo/isometric-cube-with-three-linked-hexagons  source 3be3c4f1-7eff-4665-918c-5125daa70608
#   solo/isometric-room-grid-with-central-corner  source c7271d6e-f0dd-599e-a793-70013ffb6b05
#   solo/iterative-workflow-arrows  source 2d6aea0f-956f-475c-983c-4883f1ff0ac5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Inverted freestyle skier batch 051' 95760764-05e8-4308-8e26-5b559bc41d45 'pictographic-primitives/_uncategorized_20/free skiiing 1_95760764-05e8-4308-8e26-5b559bc41d45.svg' \
  'Invision logo' 6742b2e4-0a48-4b9c-a3b9-fddbfa96da87 'pictographic-primitives/logos/invision logo_6742b2e4-0a48-4b9c-a3b9-fddbfa96da87.svg' \
  'Invoice in open envelope' 57201c70-c002-40bb-8fad-0abd9f9ca4db 'pictographic-primitives/payments/invoice mail_57201c70-c002-40bb-8fad-0abd9f9ca4db.svg' \
  'Iot pin markers' b65f68ff-83c3-5c4a-9b2d-bb76e66ff665 'pictographic-primitives/programing/internet of thing analytics services_b65f68ff-83c3-5c4a-9b2d-bb76e66ff665.svg' \
  'Irc galleria logo' 5ce8e1ba-097d-4525-a918-6d39f51da6d9 'pictographic-primitives/logos/irc galleria logo_5ce8e1ba-097d-4525-a918-6d39f51da6d9.svg' \
  'Islamic women hijab 1 avatar' 2da10a1c-94d1-53ec-a2db-86f6dd5377fd 'pictographic-primitives/avatars/islamic women hijab_2da10a1c-94d1-53ec-a2db-86f6dd5377fd.svg' \
  'Isometric cube with three circular nodes' a1ebcd1c-faf5-4d0c-93f2-8b0f08933387 'pictographic-primitives/design/rotate 3d_a1ebcd1c-faf5-4d0c-93f2-8b0f08933387.svg' \
  'Isometric cube with three linked hexagons' 3be3c4f1-7eff-4665-918c-5125daa70608 'pictographic-primitives/design/scale 3d_3be3c4f1-7eff-4665-918c-5125daa70608.svg' \
  'Isometric room grid with central corner' c7271d6e-f0dd-599e-a793-70013ffb6b05 'pictographic-primitives/design/grid perspective_c7271d6e-f0dd-599e-a793-70013ffb6b05.svg' \
  'Iterative workflow arrows' 2d6aea0f-956f-475c-983c-4883f1ff0ac5 'pictographic-primitives/business/workflow scrum_2d6aea0f-956f-475c-983c-4883f1ff0ac5.svg'
