#!/bin/bash
# Batch 84/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/two-piece-bikini-set  source 5002effe-d0b9-44d4-bf7e-f04e426d4473
#   solo/two-slanted-segmented-strips  source c897c956-5934-483f-ac07-2cf2fa325d40
#   solo/two-wheel-cart-with-a-marked-suitcase  source f459a46b-5237-46ac-a92e-22dd7641c816
#   solo/type-a-outlet-with-flattened-circular-recess  source 2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db
#   solo/type-f-outlet-with-two-holes-and-earth-tabs  source a953c01a-331f-443c-b5ed-5756e2821bc2
#   solo/uniform-shirt-with-two-pockets  source 591915da-b4b5-4520-b0bf-1658414b5875
#   solo/unrolled-paper-right-curl  source 0f4ecb94-3a73-4380-95f8-a8bd0a7bf26d
#   solo/upper-femur-bone  source dca4fa68-7ac6-48ea-a638-a69464a645a6
#   solo/upright-acoustic-guitar  source 39f10ef4-8250-4acb-b0ce-eaee10f3b757
#   solo/upright-bacterium-with-two-inclusions  source df4d94f3-62a3-40bb-bee9-f07c0c7fdb90
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Two piece bikini set' 5002effe-d0b9-44d4-bf7e-f04e426d4473 pictographic-primitives/_uncategorized_06/bikini_5002effe-d0b9-44d4-bf7e-f04e426d4473.svg \
  'Two slanted segmented strips' c897c956-5934-483f-ac07-2cf2fa325d40 pictographic-primitives/crime/scene_c897c956-5934-483f-ac07-2cf2fa325d40.svg \
  'Two wheel cart with a marked suitcase' f459a46b-5237-46ac-a92e-22dd7641c816 'pictographic-primitives/_uncategorized_05/baggage cart 2_f459a46b-5237-46ac-a92e-22dd7641c816.svg' \
  'Type a outlet with flattened circular recess' 2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db 'pictographic-primitives/electronics/power outlet type a_2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db.svg' \
  'Type f outlet with two holes and earth tabs' a953c01a-331f-443c-b5ed-5756e2821bc2 'pictographic-primitives/electronics/power outlet type f_a953c01a-331f-443c-b5ed-5756e2821bc2.svg' \
  'Uniform shirt with two pockets' 591915da-b4b5-4520-b0bf-1658414b5875 pictographic-primitives/_uncategorized_18/fatigues_591915da-b4b5-4520-b0bf-1658414b5875.svg \
  'Unrolled paper right curl' 0f4ecb94-3a73-4380-95f8-a8bd0a7bf26d 'pictographic-primitives/other/blueprint 1_0f4ecb94-3a73-4380-95f8-a8bd0a7bf26d.svg' \
  'Upper femur bone' dca4fa68-7ac6-48ea-a638-a69464a645a6 pictographic-primitives/_uncategorized_22/hip_dca4fa68-7ac6-48ea-a638-a69464a645a6.svg \
  'Upright acoustic guitar' 39f10ef4-8250-4acb-b0ce-eaee10f3b757 pictographic-primitives/_uncategorized_21/guitars_39f10ef4-8250-4acb-b0ce-eaee10f3b757.svg \
  'Upright bacterium with two inclusions' df4d94f3-62a3-40bb-bee9-f07c0c7fdb90 pictographic-primitives/_uncategorized_05/bacterium_df4d94f3-62a3-40bb-bee9-f07c0c7fdb90.svg
