#!/bin/bash
# Batch 52/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/leaping-dog-with-ball  source 4796ac23-c435-44ff-88be-e29fc6d01cfc
#   solo/leaping-hammerhead-solo  source 81d0c757-f2c2-5412-a942-65c0af7e738d
#   solo/left-facing-delivery-truck-with-stacked-boxes  source 257f0887-6008-495a-a55c-320487647db3
#   solo/left-facing-duck-with-folded-wing  source 9eadf921-3174-4221-866e-2c3028f77fdf
#   solo/left-facing-hen-with-split-crest  source 5ee8a983-7ca0-48b0-a3c8-3fbe81bd8f23
#   solo/left-facing-person-sneezing  source f2e9b73a-cb3b-4ba3-9a35-136a976c9aec
#   solo/left-facing-woolly-sheep  source 5c049f6f-b79e-4713-88e1-5895f98597e6
#   solo/left-pointing-hand  source 613648dc-20be-585d-afa1-d151dcec0e93
#   solo/left-pointing-hand-with-raised-thumb  source ea54b202-0f96-50db-97dc-1884a36b2fb9
#   solo/left-profile-with-lobed-brain  source 6e501462-4458-4ee8-918b-3b9b1c8dded4
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Leaping dog with ball' 4796ac23-c435-44ff-88be-e29fc6d01cfc 'pictographic-primitives/pets/dog bring ball training_4796ac23-c435-44ff-88be-e29fc6d01cfc.svg' \
  'Leaping hammerhead solo' 81d0c757-f2c2-5412-a942-65c0af7e738d 'pictographic-primitives/animals/shark hammer fish_81d0c757-f2c2-5412-a942-65c0af7e738d.svg' \
  'Left facing delivery truck with stacked boxes' 257f0887-6008-495a-a55c-320487647db3 'pictographic-primitives/delivery/delivery truck packages_257f0887-6008-495a-a55c-320487647db3.svg' \
  'Left facing duck with folded wing' 9eadf921-3174-4221-866e-2c3028f77fdf pictographic-primitives/_uncategorized_15/drake_9eadf921-3174-4221-866e-2c3028f77fdf.svg \
  'Left facing hen with split crest' 5ee8a983-7ca0-48b0-a3c8-3fbe81bd8f23 'pictographic-primitives/_uncategorized_11/chicken animal_5ee8a983-7ca0-48b0-a3c8-3fbe81bd8f23.svg' \
  'Left facing person sneezing' f2e9b73a-cb3b-4ba3-9a35-136a976c9aec pictographic-primitives/_uncategorized_34/sneeze_f2e9b73a-cb3b-4ba3-9a35-136a976c9aec.svg \
  'Left facing woolly sheep' 5c049f6f-b79e-4713-88e1-5895f98597e6 pictographic-primitives/_uncategorized_27/mouton_5c049f6f-b79e-4713-88e1-5895f98597e6.svg \
  'Left pointing hand' 613648dc-20be-585d-afa1-d151dcec0e93 'pictographic-primitives/interface-essential/hand pointer left_613648dc-20be-585d-afa1-d151dcec0e93.svg' \
  'Left pointing hand with raised thumb' ea54b202-0f96-50db-97dc-1884a36b2fb9 'pictographic-primitives/interface-essential/hand pointer left_ea54b202-0f96-50db-97dc-1884a36b2fb9.svg' \
  'Left profile with lobed brain' 6e501462-4458-4ee8-918b-3b9b1c8dded4 pictographic-primitives/_uncategorized_28/neurobiologist_6e501462-4458-4ee8-918b-3b9b1c8dded4.svg
