#!/bin/bash
# Batch 87/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/vertical-swipe-gesture  source 29be15de-fd49-4163-972a-6f0743088f4e
#   solo/vertical-temperature-measurement-gauge-batch-032  source 35927974-2629-44d6-b1c5-b8e9cce40d6f
#   solo/veterinary-paw-content  source de729c05-6cce-4720-a0be-a92e22cd665a
#   solo/vibrating-mobile-device-solo-b004-14  source e5eda811-8fbc-4a56-bb99-a31e94e69ea2
#   solo/victory-hand  source e092cced-a3af-49d1-b7d5-7eb03a1a3b03
#   solo/video-camera-with-top-microphone  source fb1a1229-1d12-4164-bc27-d4819233933e
#   solo/video-cba8c0da  source cba8c0da-97a3-4786-8e5c-d74b9dd80be2
#   solo/video-conference-monitor  source ec2d4eb4-b488-4b60-b260-7de322e396fd
#   solo/virtual-coin-crypto-cardano  source bdc115ba-5634-462f-867b-442517f1252f
#   solo/virtual-coin-crypto-digibyte  source c1d5f52e-e959-4a98-8aa2-0ce4e5a583cc
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Vertical swipe gesture' 29be15de-fd49-4163-972a-6f0743088f4e 'pictographic-primitives/_uncategorized_20/gesture swipe vertical 1_29be15de-fd49-4163-972a-6f0743088f4e.svg' \
  'Vertical temperature measurement gauge batch 032' 35927974-2629-44d6-b1c5-b8e9cce40d6f pictographic-primitives/other/thermometer_35927974-2629-44d6-b1c5-b8e9cce40d6f.svg \
  'Veterinary paw content' de729c05-6cce-4720-a0be-a92e22cd665a 'pictographic-primitives/state/paw print with a cross_de729c05-6cce-4720-a0be-a92e22cd665a.svg' \
  'Vibrating mobile device solo b004 14' e5eda811-8fbc-4a56-bb99-a31e94e69ea2 'pictographic-primitives/container/rectangle stacked_e5eda811-8fbc-4a56-bb99-a31e94e69ea2.svg' \
  'Victory hand' e092cced-a3af-49d1-b7d5-7eb03a1a3b03 'pictographic-primitives/_uncategorized_38/toys finger_e092cced-a3af-49d1-b7d5-7eb03a1a3b03.svg' \
  'Video camera with top microphone' fb1a1229-1d12-4164-bc27-d4819233933e 'pictographic-primitives/_uncategorized_09/camera professional_fb1a1229-1d12-4164-bc27-d4819233933e.svg' \
  'Video cba8c0da' cba8c0da-97a3-4786-8e5c-d74b9dd80be2 pictographic-primitives/symbol/video_cba8c0da-97a3-4786-8e5c-d74b9dd80be2.svg \
  'Video conference monitor' ec2d4eb4-b488-4b60-b260-7de322e396fd 'pictographic-primitives/other/monitor person_ec2d4eb4-b488-4b60-b260-7de322e396fd.svg' \
  'Virtual coin crypto cardano' bdc115ba-5634-462f-867b-442517f1252f 'pictographic-primitives/money/virtual coin crypto cardano_bdc115ba-5634-462f-867b-442517f1252f.svg' \
  'Virtual coin crypto digibyte' c1d5f52e-e959-4a98-8aa2-0ce4e5a583cc 'pictographic-primitives/money/virtual coin crypto digibyte_c1d5f52e-e959-4a98-8aa2-0ce4e5a583cc.svg'
