#!/bin/bash
# Batch 40/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/horizontal-blind-with-right-pull  source 8cae4a5a-3789-5381-a527-c8750fce7a6f
#   solo/horizontal-bullet-with-separate-base  source 802be2b5-f78d-4ecb-9c7b-5e7019a0f0c6
#   solo/horizontal-chain-connection  source 30888bf2-0b8e-56fe-982b-a281e9af88e2
#   solo/horizontal-chain-link  source b4c96571-b91a-5c18-ae5c-9991078d4792
#   solo/horizontal-discharge-pipe-above-two-wave-rows  source dc6d6d2c-1086-4a91-b19c-cf01bbb00c04
#   solo/horizontal-handshake-with-cuff  source 0788c931-6c1a-4eae-bd4d-d84eeef4e11a
#   solo/horizontal-measurement-markers-solo  source 5e331499-062d-4a4a-965e-e100d55ce756
#   solo/horizontal-mobile  source 5d7a8076-edd9-440d-ab8b-f7981e5386e4
#   solo/horizontal-mobile-solo  source ada6dde6-1dce-4251-86a0-6555bb862052
#   solo/horizontal-position-shift  source 86dda6f0-7614-4dc9-a730-e1f0bac0dc02
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Horizontal blind with right pull' 8cae4a5a-3789-5381-a527-c8750fce7a6f 'pictographic-primitives/building/blinds horizontal closed_8cae4a5a-3789-5381-a527-c8750fce7a6f.svg' \
  'Horizontal bullet with separate base' 802be2b5-f78d-4ecb-9c7b-5e7019a0f0c6 pictographic-primitives/_uncategorized_08/bullet_802be2b5-f78d-4ecb-9c7b-5e7019a0f0c6.svg \
  'Horizontal chain connection' 30888bf2-0b8e-56fe-982b-a281e9af88e2 pictographic-primitives/interface-essential/hyperlink_30888bf2-0b8e-56fe-982b-a281e9af88e2.svg \
  'Horizontal chain link' b4c96571-b91a-5c18-ae5c-9991078d4792 pictographic-primitives/interface-essential/hyperlink_b4c96571-b91a-5c18-ae5c-9991078d4792.svg \
  'Horizontal discharge pipe above two wave rows' dc6d6d2c-1086-4a91-b19c-cf01bbb00c04 'pictographic-primitives/ecology/pollution faucet water_dc6d6d2c-1086-4a91-b19c-cf01bbb00c04.svg' \
  'Horizontal handshake with cuff' 0788c931-6c1a-4eae-bd4d-d84eeef4e11a 'pictographic-primitives/_uncategorized_21/global colaboration handshake_0788c931-6c1a-4eae-bd4d-d84eeef4e11a.svg' \
  'Horizontal measurement markers solo' 5e331499-062d-4a4a-965e-e100d55ce756 'pictographic-primitives/other/measurement markers_5e331499-062d-4a4a-965e-e100d55ce756.svg' \
  'Horizontal mobile' 5d7a8076-edd9-440d-ab8b-f7981e5386e4 'pictographic-primitives/container/horizontal mobile_5d7a8076-edd9-440d-ab8b-f7981e5386e4.svg' \
  'Horizontal mobile solo' ada6dde6-1dce-4251-86a0-6555bb862052 'pictographic-primitives/container/horizontal mobile_ada6dde6-1dce-4251-86a0-6555bb862052.svg' \
  'Horizontal position shift' 86dda6f0-7614-4dc9-a730-e1f0bac0dc02 'pictographic-primitives/_uncategorized_01/align middle move horizontal_86dda6f0-7614-4dc9-a730-e1f0bac0dc02.svg'
