#!/bin/bash
# Batch 45/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/inline-skate  source a010f79f-3ca0-5f51-8cbf-bd0c35154343
#   solo/inline-skater  source 630e00b6-b3a3-4ec4-9e34-5b14d7140829
#   solo/intellij-idea-logo  source f4752828-8f41-472e-a48e-c509754917dd
#   solo/interior-wall-with-door-and-window  source 15d7928a-0a97-4ec4-b4c0-f21360f062be
#   solo/interlocking-chain-link-symbol-solo  source 55bd9f6e-12a9-4d3a-9646-c1852d270efe
#   solo/interlocking-handshake  source e18ed81a-df3e-442f-9876-54ac0d744866
#   solo/interlocking-s-emblem  source e67f8d26-5a13-4179-830d-68e3d196c80a
#   solo/interrupted-overlapping-square-outlines  source be8dae84-5405-4802-81b7-35e3f6f8f7f4
#   solo/intersecting-circles-with-angular-inner-segment  source ea7a2587-afc3-5980-b5c6-35471cead545
#   solo/intertwined-snakes  source 3746d55b-f09e-427d-9fe4-ccb75164b650
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Inline skate' a010f79f-3ca0-5f51-8cbf-bd0c35154343 pictographic-primitives/sports/rollerblades_a010f79f-3ca0-5f51-8cbf-bd0c35154343.svg \
  'Inline skater' 630e00b6-b3a3-4ec4-9e34-5b14d7140829 'pictographic-primitives/sports/rollerblades person_630e00b6-b3a3-4ec4-9e34-5b14d7140829.svg' \
  'Intellij idea logo' f4752828-8f41-472e-a48e-c509754917dd 'pictographic-primitives/logos/intellijidea logo_f4752828-8f41-472e-a48e-c509754917dd.svg' \
  'Interior wall with door and window' 15d7928a-0a97-4ec4-b4c0-f21360f062be pictographic-primitives/_uncategorized_23/interior_15d7928a-0a97-4ec4-b4c0-f21360f062be.svg \
  'Interlocking chain link symbol solo' 55bd9f6e-12a9-4d3a-9646-c1852d270efe 'pictographic-primitives/other/attached file_55bd9f6e-12a9-4d3a-9646-c1852d270efe.svg' \
  'Interlocking handshake' e18ed81a-df3e-442f-9876-54ac0d744866 pictographic-primitives/_uncategorized_11/clasp_e18ed81a-df3e-442f-9876-54ac0d744866.svg \
  'Interlocking s emblem' e67f8d26-5a13-4179-830d-68e3d196c80a 'pictographic-primitives/_uncategorized_36/squarespace logo_e67f8d26-5a13-4179-830d-68e3d196c80a.svg' \
  'Interrupted overlapping square outlines' be8dae84-5405-4802-81b7-35e3f6f8f7f4 'pictographic-primitives/_uncategorized_30/pathfinder outline_be8dae84-5405-4802-81b7-35e3f6f8f7f4.svg' \
  'Intersecting circles with angular inner segment' ea7a2587-afc3-5980-b5c6-35471cead545 'pictographic-primitives/diagrams/boolean and_ea7a2587-afc3-5980-b5c6-35471cead545.svg' \
  'Intertwined snakes' 3746d55b-f09e-427d-9fe4-ccb75164b650 pictographic-primitives/culture/batch-04/snakes_3746d55b-f09e-427d-9fe4-ccb75164b650.svg
