#!/bin/bash
# Batch 43/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hurricane-oil-lantern  source e26b4fae-5159-5626-a3fd-b6d33103328d
#   solo/hydroelectric-dam  source 6411cee5-9e14-533a-9adf-d5bcd2213734
#   solo/hyperloop-pod-speed-lines  source 0b674991-fc01-44ec-9571-1f5372072662
#   solo/hypnotized-face  source e67e67e8-fb33-47eb-a330-05cfafa37994
#   solo/hyves-logo  source a08dce58-bc2a-4e25-bd53-f469ccddb795
#   solo/i-love-you-hand-gesture  source 5a3ae175-815d-4ada-bbd0-26b81be8cd4e
#   solo/iced-drink-with-two-cubes-and-bent-straw  source 4daf9729-9636-5534-8214-749f5664cd5b
#   solo/ichthys-fish  source 4b380f58-586b-45bc-8749-b86c9b2f3e5c
#   solo/icon-dock-logo  source 86d17ebe-c3ae-4a94-8c7a-9c8ac9f66d3a
#   solo/icq-logo  source f289aab6-b93c-4599-9b13-2dec09ddb559
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hurricane oil lantern' e26b4fae-5159-5626-a3fd-b6d33103328d 'pictographic-primitives/outdoors/outdoors flame lantern_e26b4fae-5159-5626-a3fd-b6d33103328d.svg' \
  'Hydroelectric dam' 6411cee5-9e14-533a-9adf-d5bcd2213734 'pictographic-primitives/landmarks/batch-07/water dam_6411cee5-9e14-533a-9adf-d5bcd2213734.svg' \
  'Hyperloop pod speed lines' 0b674991-fc01-44ec-9571-1f5372072662 'pictographic-primitives/technology/hyperloop speed_0b674991-fc01-44ec-9571-1f5372072662.svg' \
  'Hypnotized face' e67e67e8-fb33-47eb-a330-05cfafa37994 pictographic-primitives/smileys/hypnotized_e67e67e8-fb33-47eb-a330-05cfafa37994.svg \
  'Hyves logo' a08dce58-bc2a-4e25-bd53-f469ccddb795 'pictographic-primitives/logos/hyves logo_a08dce58-bc2a-4e25-bd53-f469ccddb795.svg' \
  'I love you hand gesture' 5a3ae175-815d-4ada-bbd0-26b81be8cd4e 'pictographic-primitives/wayfinding/sign language love_5a3ae175-815d-4ada-bbd0-26b81be8cd4e.svg' \
  'Iced drink with two cubes and bent straw' 4daf9729-9636-5534-8214-749f5664cd5b 'pictographic-primitives/drinks/coffee coldbrew_4daf9729-9636-5534-8214-749f5664cd5b.svg' \
  'Ichthys fish' 4b380f58-586b-45bc-8749-b86c9b2f3e5c pictographic-primitives/animals/fish_4b380f58-586b-45bc-8749-b86c9b2f3e5c.svg \
  'Icon dock logo' 86d17ebe-c3ae-4a94-8c7a-9c8ac9f66d3a 'pictographic-primitives/logos/icon dock logo_86d17ebe-c3ae-4a94-8c7a-9c8ac9f66d3a.svg' \
  'Icq logo' f289aab6-b93c-4599-9b13-2dec09ddb559 'pictographic-primitives/logos/icq logo_f289aab6-b93c-4599-9b13-2dec09ddb559.svg'
