#!/bin/bash
# Batch 34/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/handshake  source 533cf846-1648-4bd0-a7f9-03a05d166f40
#   solo/handshake-with-shirt-cuffs  source 291c6be8-564b-4357-96fd-484a347b7dbd
#   solo/handshake-with-short-cuffs  source 3c74c12e-dcf2-4f93-8b36-cb2b5335f9e3
#   solo/hanging-boxing-bag  source 9e7027bc-55fb-5645-8aae-23b189e7f236
#   solo/hanging-toilet-paper-roll  source f361cec1-680c-41d1-8ef8-1055d54cab23
#   solo/happy-chat-bubbles  source 8d648ec6-1ff1-4de1-a5b4-4e9f74b89aef
#   solo/happy-face-with-sideways-tongue  source a2b16bc0-fda9-42be-8b90-0bef7d9dc58b
#   solo/harp  source c34bbf3c-dbfc-52d8-9c2d-c0bac391ca8b
#   solo/hat-lady-cowboy-avatar  source 8e5f188b-2874-56f0-8538-ccc3b48f76fc
#   solo/hatchet  source 6ab36fdc-b442-5f9f-afc2-c43f74bf4130
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Handshake 533cf846-1648-4bd0-a7f9-03a05d166f40 pictographic-primitives/symbol/handshake_533cf846-1648-4bd0-a7f9-03a05d166f40.svg \
  'Handshake with shirt cuffs' 291c6be8-564b-4357-96fd-484a347b7dbd 'pictographic-primitives/business/deal handshake_291c6be8-564b-4357-96fd-484a347b7dbd.svg' \
  'Handshake with short cuffs' 3c74c12e-dcf2-4f93-8b36-cb2b5335f9e3 'pictographic-primitives/business/deal handshake_3c74c12e-dcf2-4f93-8b36-cb2b5335f9e3.svg' \
  'Hanging boxing bag' 9e7027bc-55fb-5645-8aae-23b189e7f236 'pictographic-primitives/sports/boxing bag hanging_9e7027bc-55fb-5645-8aae-23b189e7f236.svg' \
  'Hanging toilet paper roll' f361cec1-680c-41d1-8ef8-1055d54cab23 'pictographic-primitives/wayfinding/toilet paper_f361cec1-680c-41d1-8ef8-1055d54cab23.svg' \
  'Happy chat bubbles' 8d648ec6-1ff1-4de1-a5b4-4e9f74b89aef 'pictographic-primitives/_uncategorized_12/conversation smile type_8d648ec6-1ff1-4de1-a5b4-4e9f74b89aef.svg' \
  'Happy face with sideways tongue' a2b16bc0-fda9-42be-8b90-0bef7d9dc58b 'pictographic-primitives/_uncategorized_17/face grin tongue_a2b16bc0-fda9-42be-8b90-0bef7d9dc58b.svg' \
  Harp c34bbf3c-dbfc-52d8-9c2d-c0bac391ca8b pictographic-primitives/music/harp_c34bbf3c-dbfc-52d8-9c2d-c0bac391ca8b.svg \
  'Hat lady cowboy avatar' 8e5f188b-2874-56f0-8538-ccc3b48f76fc 'pictographic-primitives/avatars/hat lady cowboy_8e5f188b-2874-56f0-8538-ccc3b48f76fc.svg' \
  Hatchet 6ab36fdc-b442-5f9f-afc2-c43f74bf4130 'pictographic-primitives/tools/tools axe_6ab36fdc-b442-5f9f-afc2-c43f74bf4130.svg'
