#!/bin/bash
# Batch 94/94: 3 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/y-junction-with-diamond-ends  source be7a207d-fbb5-43cc-8ca3-45bc04189f5c
#   solo/yoshi-in-profile  source 4b9d53a0-2f4e-5d75-b4d6-6d8256b65546
#   solo/yuan-currency-money-bill-solo  source 5fe07eb3-8a47-4dac-8a74-c9f75cebee8a
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Y junction with diamond ends' be7a207d-fbb5-43cc-8ca3-45bc04189f5c 'pictographic-primitives/_uncategorized_09/cable split_be7a207d-fbb5-43cc-8ca3-45bc04189f5c.svg' \
  'Yoshi in profile' 4b9d53a0-2f4e-5d75-b4d6-6d8256b65546 'pictographic-primitives/video-games/batch-07/mario yoshi_4b9d53a0-2f4e-5d75-b4d6-6d8256b65546.svg' \
  'Yuan currency money bill solo' 5fe07eb3-8a47-4dac-8a74-c9f75cebee8a 'pictographic-primitives/other/money bill yuan_5fe07eb3-8a47-4dac-8a74-c9f75cebee8a.svg'
