#!/bin/bash
# Batch 36/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/head-scarf-tie-avatar  source d91b104f-4bd1-4359-bf72-c9162bc1c67b
#   solo/head-with-monocle  source 8c354f7c-447b-4033-85e4-6924e236563c
#   solo/head-wrapped-in-a-face-veil  source 4f15286f-0f07-429b-991b-cb705d4c651c
#   solo/head-wrapped-in-bandage  source e5d36fda-d12e-4a2d-a970-b3258b3fc57c
#   solo/headache-profile-27b13dec  source 27b13dec-64c9-52f3-b0c7-06e23b9be3cf
#   solo/headache-profile-955af99e  source 955af99e-4ca7-4122-9d20-02138f6d605b
#   solo/headphone-listener-reading-an-open-book  source 8f662247-0935-46b5-ba77-cc454f1bafe3
#   solo/headphone-listener-with-cigarette  source bc938aa3-95bd-4a96-b283-3c27b08596d6
#   solo/headphones-with-long-cable  source 3166725a-0332-4cff-bea4-228fc51449c2
#   solo/headphones-with-portable-player  source 32ab4ed8-b548-4a61-956b-a99332d1684d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Head scarf tie avatar' d91b104f-4bd1-4359-bf72-c9162bc1c67b 'pictographic-primitives/avatars/head scarf tie_d91b104f-4bd1-4359-bf72-c9162bc1c67b.svg' \
  'Head with monocle' 8c354f7c-447b-4033-85e4-6924e236563c 'pictographic-primitives/smileys/face with monocle_8c354f7c-447b-4033-85e4-6924e236563c.svg' \
  'Head wrapped in a face veil' 4f15286f-0f07-429b-991b-cb705d4c651c 'pictographic-primitives/_uncategorized_05/avatar islamic women niqab 2_4f15286f-0f07-429b-991b-cb705d4c651c.svg' \
  'Head wrapped in bandage' e5d36fda-d12e-4a2d-a970-b3258b3fc57c 'pictographic-primitives/_uncategorized_17/face head bandage_e5d36fda-d12e-4a2d-a970-b3258b3fc57c.svg' \
  'Headache profile 27b13dec' 27b13dec-64c9-52f3-b0c7-06e23b9be3cf 'pictographic-primitives/health/medical condition head pain_27b13dec-64c9-52f3-b0c7-06e23b9be3cf.svg' \
  'Headache profile 955af99e' 955af99e-4ca7-4122-9d20-02138f6d605b 'pictographic-primitives/health/head pain_955af99e-4ca7-4122-9d20-02138f6d605b.svg' \
  'Headphone listener reading an open book' 8f662247-0935-46b5-ba77-cc454f1bafe3 'pictographic-primitives/_uncategorized_04/audio book headphones person_8f662247-0935-46b5-ba77-cc454f1bafe3.svg' \
  'Headphone listener with cigarette' bc938aa3-95bd-4a96-b283-3c27b08596d6 'pictographic-primitives/audio/music genre smoke_bc938aa3-95bd-4a96-b283-3c27b08596d6.svg' \
  'Headphones with long cable' 3166725a-0332-4cff-bea4-228fc51449c2 'pictographic-primitives/audio/headphones cable_3166725a-0332-4cff-bea4-228fc51449c2.svg' \
  'Headphones with portable player' 32ab4ed8-b548-4a61-956b-a99332d1684d 'pictographic-primitives/music/walkman headphones_32ab4ed8-b548-4a61-956b-a99332d1684d.svg'
