#!/bin/bash
# Batch 28/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-passing-capsule  source 37a4523d-3384-4c79-9494-a5cfb681f4f0
#   solo/hand-patting-dog  source ef1c856a-063a-4941-92f0-78189ee7aba9
#   solo/hand-pinching-acupuncture-needle  source 219024ce-9973-4736-8ba2-b73e81755a00
#   solo/hand-pinching-chip  source 7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02
#   solo/hand-playing-pad-controller  source 2e9ddede-2e59-4491-8fa8-b1f79514c010
#   solo/hand-playing-yoyo  source 28a605e6-a545-47ed-ae21-f45557bb8374
#   solo/hand-pointing-at-3d-cube-solo  source ec7d49e5-85a7-4bad-943c-fff9ce408048
#   solo/hand-pointing-down-batch-024-04  source 5a80cb54-e04f-5e41-ba53-6892a6852f05
#   solo/hand-pointing-up  source 6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9
#   solo/hand-pointing-up-solo-batch-024-06  source ab1c71ce-8bff-570d-963d-b5b83249a9ae
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand passing capsule' 37a4523d-3384-4c79-9494-a5cfb681f4f0 'pictographic-primitives/crime/drugs dealer_37a4523d-3384-4c79-9494-a5cfb681f4f0.svg' \
  'Hand patting dog' ef1c856a-063a-4941-92f0-78189ee7aba9 'pictographic-primitives/pets/dog side patting good_ef1c856a-063a-4941-92f0-78189ee7aba9.svg' \
  'Hand pinching acupuncture needle' 219024ce-9973-4736-8ba2-b73e81755a00 'pictographic-primitives/_uncategorized_01/acupuncture hand_219024ce-9973-4736-8ba2-b73e81755a00.svg' \
  'Hand pinching chip' 7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02 'pictographic-primitives/programing/chip hold_7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02.svg' \
  'Hand playing pad controller' 2e9ddede-2e59-4491-8fa8-b1f79514c010 'pictographic-primitives/music/modern music mix touch_2e9ddede-2e59-4491-8fa8-b1f79514c010.svg' \
  'Hand playing yoyo' 28a605e6-a545-47ed-ae21-f45557bb8374 'pictographic-primitives/kids/playing yoyo_28a605e6-a545-47ed-ae21-f45557bb8374.svg' \
  'Hand pointing at 3d cube solo' ec7d49e5-85a7-4bad-943c-fff9ce408048 'pictographic-primitives/state/hand point cube_ec7d49e5-85a7-4bad-943c-fff9ce408048.svg' \
  'Hand pointing down batch 024 04' 5a80cb54-e04f-5e41-ba53-6892a6852f05 'pictographic-primitives/other/hand pointer bottom_5a80cb54-e04f-5e41-ba53-6892a6852f05.svg' \
  'Hand pointing up' 6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9 'pictographic-primitives/wayfinding/finger point 1_6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9.svg' \
  'Hand pointing up solo batch 024 06' ab1c71ce-8bff-570d-963d-b5b83249a9ae 'pictographic-primitives/other/hand pointer top_ab1c71ce-8bff-570d-963d-b5b83249a9ae.svg'
