#!/bin/bash
# Batch 16/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/dragon-boat-with-diagonal-paddle  source c0bf18ec-ef26-4887-96a5-9b72b4465109
#   solo/drifting-jellyfish  source ef0702b0-d65f-5955-8954-f383064a984c
#   solo/dripping-grease-with-steam  source 93228c89-e24c-437d-8bd6-93a43a073feb
#   solo/dripping-honey-dipper-batch-011-14  source 938032ae-5024-5ede-94da-88527f48269f
#   solo/driver-bust-behind-circular-steering-wheel  source 9ebabdd4-e0a0-4c38-a81f-00e33ec2cc64
#   solo/dual-mesh-wireless-routers  source 080c193b-0809-4e52-843c-538aec12a350
#   solo/east  source ad12d3ce-dd3a-4c8e-9db3-83b54c4a1c0b
#   solo/easter-egg-wrapped-with-ribbon-bow  source ec0f499f-1e04-4366-8584-5678287d169a
#   solo/egg-bacon-and-sausage-breakfast  source 9cd5bf77-b0ca-4e59-86ca-62d4b29d41fd
#   solo/electrical-power-generator-component  source 87aae996-0ff2-4205-ac86-1266ba89328e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Dragon boat with diagonal paddle' c0bf18ec-ef26-4887-96a5-9b72b4465109 'pictographic-primitives/_uncategorized_15/dragon boat_c0bf18ec-ef26-4887-96a5-9b72b4465109.svg' \
  'Drifting jellyfish' ef0702b0-d65f-5955-8954-f383064a984c pictographic-primitives/animals/jellyfish_ef0702b0-d65f-5955-8954-f383064a984c.svg \
  'Dripping grease with steam' 93228c89-e24c-437d-8bd6-93a43a073feb pictographic-primitives/_uncategorized_21/grease_93228c89-e24c-437d-8bd6-93a43a073feb.svg \
  'Dripping honey dipper batch 011 14' 938032ae-5024-5ede-94da-88527f48269f pictographic-primitives/food/honey_938032ae-5024-5ede-94da-88527f48269f.svg \
  'Driver bust behind circular steering wheel' 9ebabdd4-e0a0-4c38-a81f-00e33ec2cc64 pictographic-primitives/_uncategorized_16/driver_9ebabdd4-e0a0-4c38-a81f-00e33ec2cc64.svg \
  'Dual mesh wireless routers' 080c193b-0809-4e52-843c-538aec12a350 'pictographic-primitives/_uncategorized_27/mesh wifi router_080c193b-0809-4e52-843c-538aec12a350.svg' \
  East ad12d3ce-dd3a-4c8e-9db3-83b54c4a1c0b pictographic-primitives/weather/east_ad12d3ce-dd3a-4c8e-9db3-83b54c4a1c0b.svg \
  'Easter egg wrapped with ribbon bow' ec0f499f-1e04-4366-8584-5678287d169a 'pictographic-primitives/_uncategorized_16/easter egg ribbon_ec0f499f-1e04-4366-8584-5678287d169a.svg' \
  'Egg bacon and sausage breakfast' 9cd5bf77-b0ca-4e59-86ca-62d4b29d41fd 'pictographic-primitives/_uncategorized_08/breakfast english_9cd5bf77-b0ca-4e59-86ca-62d4b29d41fd.svg' \
  'Electrical power generator component' 87aae996-0ff2-4205-ac86-1266ba89328e 'pictographic-primitives/science/elecricity power_87aae996-0ff2-4205-ac86-1266ba89328e.svg'
