#!/bin/bash
# Batch 74/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/single-leaf-tangerine  source 1d826cc1-7a34-4a4b-b35e-3e9afb31ff55
#   solo/single-neutral-actions-process  source 9c7a9373-6b14-416c-b4ee-37335d7a0f46
#   solo/single-serpent-around-a-staff  source 3726d96a-f376-4f85-be5e-b05615cdd3f9
#   solo/six-grape-bunch  source 595ebb35-2692-477a-a87b-7507db3ad2a5
#   solo/six-legged-termite  source dcf3dc20-cda5-4cd3-8879-8526bc0339b2
#   solo/skirt-beside-tailor-square  source cb351c07-8fc6-42c1-8471-f516ff46710f
#   solo/small-bird-with-short-angular-legs  source 19d5cc07-c7f1-475e-a0d6-14960a6a634c
#   solo/smart-television-remote  source 5c8baa98-9caf-4e80-a3b7-730034f73d7b
#   solo/smart-tv-and-phone  source 77e358dc-c96c-49a8-995c-75ae3db00556
#   solo/smart-watch-square-dollar-sign  source 22b0de95-e0f5-450b-9f1f-9e0284263be7
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Single leaf tangerine' 1d826cc1-7a34-4a4b-b35e-3e9afb31ff55 pictographic-primitives/_uncategorized_37/tangerine_1d826cc1-7a34-4a4b-b35e-3e9afb31ff55.svg \
  'Single neutral actions process' 9c7a9373-6b14-416c-b4ee-37335d7a0f46 'pictographic-primitives/_uncategorized_34/single neutral actions process_9c7a9373-6b14-416c-b4ee-37335d7a0f46.svg' \
  'Single serpent around a staff' 3726d96a-f376-4f85-be5e-b05615cdd3f9 'pictographic-primitives/_uncategorized_33/rod of asclepius_3726d96a-f376-4f85-be5e-b05615cdd3f9.svg' \
  'Six grape bunch' 595ebb35-2692-477a-a87b-7507db3ad2a5 pictographic-primitives/_uncategorized_21/grape_595ebb35-2692-477a-a87b-7507db3ad2a5.svg \
  'Six legged termite' dcf3dc20-cda5-4cd3-8879-8526bc0339b2 pictographic-primitives/_uncategorized_37/termite_dcf3dc20-cda5-4cd3-8879-8526bc0339b2.svg \
  'Skirt beside tailor square' cb351c07-8fc6-42c1-8471-f516ff46710f 'pictographic-primitives/_uncategorized_18/fashion design measuring_cb351c07-8fc6-42c1-8471-f516ff46710f.svg' \
  'Small bird with short angular legs' 19d5cc07-c7f1-475e-a0d6-14960a6a634c pictographic-primitives/_uncategorized_16/eaglet_19d5cc07-c7f1-475e-a0d6-14960a6a634c.svg \
  'Smart television remote' 5c8baa98-9caf-4e80-a3b7-730034f73d7b 'pictographic-primitives/_uncategorized_27/modern tv remote smart_5c8baa98-9caf-4e80-a3b7-730034f73d7b.svg' \
  'Smart tv and phone' 77e358dc-c96c-49a8-995c-75ae3db00556 'pictographic-primitives/_uncategorized_34/smart tv and phone_77e358dc-c96c-49a8-995c-75ae3db00556.svg' \
  'Smart watch square dollar sign' 22b0de95-e0f5-450b-9f1f-9e0284263be7 'pictographic-primitives/other/smart watch square dollar sign_22b0de95-e0f5-450b-9f1f-9e0284263be7.svg'
