#!/bin/bash
# Batch 60/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/ocd-disorder-symptoms-2  source 9bf327e4-22cd-4f46-a740-34545d603a6f
#   solo/online-doctor-laptop-facetime  source bc0dbbdb-7b2e-4bb7-b53e-d84b9f2a2265
#   solo/open-drainage-channel  source bee047c3-d480-4b1e-8469-37570947d8bd
#   solo/open-end-wrench-batch-04  source 8b71e7e7-15cf-4d31-8c76-295ef5576f53
#   solo/open-horseshoe  source 707aefe4-5cb6-4a10-8642-455a8f4143eb
#   solo/open-infinity-loop-batch-015-02  source 1739e39c-1f28-5f58-b32d-18e847e5acf6
#   solo/open-jaw-mechanic-wrench  source c6d942f0-d85e-49d4-a8eb-fa312e540764
#   solo/open-palm  source 34742654-3e4d-515b-b7f0-70369a08b5c2
#   solo/open-palm-hand-14e0f209-1f73-4be1-9637-df2de37b666b  source 14e0f209-1f73-4be1-9637-df2de37b666b
#   solo/opened-cocoa-pod-with-three-seeds  source a38a1dfc-66a1-438a-847f-a5131386c188
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Ocd disorder symptoms 2' 9bf327e4-22cd-4f46-a740-34545d603a6f 'pictographic-primitives/_uncategorized_28/ocd disorder symptoms 2_9bf327e4-22cd-4f46-a740-34545d603a6f.svg' \
  'Online doctor laptop facetime' bc0dbbdb-7b2e-4bb7-b53e-d84b9f2a2265 'pictographic-primitives/_uncategorized_29/online doctor laptop facetime_bc0dbbdb-7b2e-4bb7-b53e-d84b9f2a2265.svg' \
  'Open drainage channel' bee047c3-d480-4b1e-8469-37570947d8bd pictographic-primitives/_uncategorized_09/canal_bee047c3-d480-4b1e-8469-37570947d8bd.svg \
  'Open end wrench batch 04' 8b71e7e7-15cf-4d31-8c76-295ef5576f53 'pictographic-primitives/other/flash wrench_8b71e7e7-15cf-4d31-8c76-295ef5576f53.svg' \
  'Open horseshoe' 707aefe4-5cb6-4a10-8642-455a8f4143eb pictographic-primitives/_uncategorized_22/hoof_707aefe4-5cb6-4a10-8642-455a8f4143eb.svg \
  'Open infinity loop batch 015 02' 1739e39c-1f28-5f58-b32d-18e847e5acf6 pictographic-primitives/interface-essential/loop_1739e39c-1f28-5f58-b32d-18e847e5acf6.svg \
  'Open jaw mechanic wrench' c6d942f0-d85e-49d4-a8eb-fa312e540764 'pictographic-primitives/_uncategorized_31/pipe wrench_c6d942f0-d85e-49d4-a8eb-fa312e540764.svg' \
  'Open palm' 34742654-3e4d-515b-b7f0-70369a08b5c2 'pictographic-primitives/wayfinding/hand stop_34742654-3e4d-515b-b7f0-70369a08b5c2.svg' \
  'Open Palm Hand' 14e0f209-1f73-4be1-9637-df2de37b666b pictographic-primitives/holidays/hand_14e0f209-1f73-4be1-9637-df2de37b666b.svg \
  'Opened cocoa pod with three seeds' a38a1dfc-66a1-438a-847f-a5131386c188 pictographic-primitives/_uncategorized_12/cocoa_a38a1dfc-66a1-438a-847f-a5131386c188.svg
