#!/bin/bash
# Batch 42/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hourglass-with-sand-level-batch-016-15  source 1873be1c-2600-5197-83a2-680121a9a499
#   solo/house-message-bubble-solo  source e05971da-9c03-4db3-a3f0-1963b3e1e1f0
#   solo/house-property-value-solo  source ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8
#   solo/house-with-chimney-reference-batch-015-09  source 48ea3c6c-5c29-50ff-bdb7-99895f95d856
#   solo/howling-wolf  source 02bbed8d-19bf-42c9-9539-d93fbda86791
#   solo/html-academy-logo  source e3e43578-3c62-43f6-8174-726b3ea61590
#   solo/human-brain-hemispheres-batch-001-r2  source 4cc51cde-8646-5c24-82c4-d7386922eb24
#   solo/human-head-side-profile-scan-batch-001-r2  source b97885e6-dbf9-5160-931c-e559629ea220
#   solo/human-profile-bust-batch-025-08  source 07e1bb79-331c-4f70-8f6d-2c162b0b2d9a
#   solo/human-skull-symbol  source 30707083-b1bf-4737-b77c-8195d26ecdb5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hourglass with sand level batch 016 15' 1873be1c-2600-5197-83a2-680121a9a499 pictographic-primitives/interface-essential/hourglass_1873be1c-2600-5197-83a2-680121a9a499.svg \
  'House message bubble solo' e05971da-9c03-4db3-a3f0-1963b3e1e1f0 'pictographic-primitives/symbol/massage bubble with house_e05971da-9c03-4db3-a3f0-1963b3e1e1f0.svg' \
  'House property value solo' ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8 'pictographic-primitives/symbol/house dollar_ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8.svg' \
  'House with chimney reference batch 015 09' 48ea3c6c-5c29-50ff-bdb7-99895f95d856 'pictographic-primitives/interface-essential/house chimney_48ea3c6c-5c29-50ff-bdb7-99895f95d856.svg' \
  'Howling wolf' 02bbed8d-19bf-42c9-9539-d93fbda86791 'pictographic-primitives/animals/wolf body howl_02bbed8d-19bf-42c9-9539-d93fbda86791.svg' \
  'Html academy logo' e3e43578-3c62-43f6-8174-726b3ea61590 'pictographic-primitives/logos/html academy logo_e3e43578-3c62-43f6-8174-726b3ea61590.svg' \
  'Human brain hemispheres batch 001 r2' 4cc51cde-8646-5c24-82c4-d7386922eb24 pictographic-primitives/artificial-intelligence/brain_4cc51cde-8646-5c24-82c4-d7386922eb24.svg \
  'Human head side profile scan batch 001 r2' b97885e6-dbf9-5160-931c-e559629ea220 'pictographic-primitives/artificial-intelligence/deepfake side_b97885e6-dbf9-5160-931c-e559629ea220.svg' \
  'Human profile bust batch 025 08' 07e1bb79-331c-4f70-8f6d-2c162b0b2d9a 'pictographic-primitives/other/person 1_07e1bb79-331c-4f70-8f6d-2c162b0b2d9a.svg' \
  'Human skull symbol' 30707083-b1bf-4737-b77c-8195d26ecdb5 'pictographic-primitives/_uncategorized_13/crime tools drugs powder_30707083-b1bf-4737-b77c-8195d26ecdb5.svg'
