#!/bin/bash
# Batch 86/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/upturned-narwhal  source 92c799ca-6aa2-4c2b-b0a0-aee64eb0d86c
#   solo/upturned-offering-hand  source 28ebd0ec-a7a1-4063-b621-7c3eb8b9fd1a
#   solo/user-bust-continuous-outline  source 64e1a8ed-890b-425f-aaa4-63ac66ca5281
#   solo/user-message-about-shopping-bag-batch-007-03  source 7deb173f-122f-4b7f-a54e-6f0fdf1005c3
#   solo/user-profile-selection-cursor-solo  source 742a102d-2547-4878-9ea9-c64ad681d52b
#   solo/uterus-and-ovaries  source 4ad25b43-5ee4-57d0-aa25-71cdcfcb39dd
#   solo/vectors-add-anchor  source eb962df2-7d7e-4704-b588-8cea12d18d62
#   solo/veiled-head-beneath-a-domed-cap  source 35c53f50-e535-49f3-ac90-8d416600029e
#   solo/venus-flytrap-with-leaf  source b27bfeed-a105-4ab7-9c64-52d85a0abb70
#   solo/vertical-ruler-with-six-ticks  source eae67cef-853a-4f4b-ba6d-48257036ab7b
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Upturned narwhal' 92c799ca-6aa2-4c2b-b0a0-aee64eb0d86c pictographic-primitives/_uncategorized_28/narwhal_92c799ca-6aa2-4c2b-b0a0-aee64eb0d86c.svg \
  'Upturned offering hand' 28ebd0ec-a7a1-4063-b621-7c3eb8b9fd1a 'pictographic-primitives/_uncategorized_21/give hand_28ebd0ec-a7a1-4063-b621-7c3eb8b9fd1a.svg' \
  'User bust continuous outline' 64e1a8ed-890b-425f-aaa4-63ac66ca5281 pictographic-primitives/other/person_64e1a8ed-890b-425f-aaa4-63ac66ca5281.svg \
  'User message about shopping bag batch 007 03' 7deb173f-122f-4b7f-a54e-6f0fdf1005c3 'pictographic-primitives/ecommerce/shopping bag user message_7deb173f-122f-4b7f-a54e-6f0fdf1005c3.svg' \
  'User profile selection cursor solo' 742a102d-2547-4878-9ea9-c64ad681d52b 'pictographic-primitives/other/cursor head_742a102d-2547-4878-9ea9-c64ad681d52b.svg' \
  'Uterus and ovaries' 4ad25b43-5ee4-57d0-aa25-71cdcfcb39dd 'pictographic-primitives/health/pregnancy ovary_4ad25b43-5ee4-57d0-aa25-71cdcfcb39dd.svg' \
  'Vectors add anchor' eb962df2-7d7e-4704-b588-8cea12d18d62 'pictographic-primitives/internet/vectors add anchor_eb962df2-7d7e-4704-b588-8cea12d18d62.svg' \
  'Veiled head beneath a domed cap' 35c53f50-e535-49f3-ac90-8d416600029e 'pictographic-primitives/_uncategorized_05/avatar islamic women niqab 1_35c53f50-e535-49f3-ac90-8d416600029e.svg' \
  'Venus flytrap with leaf' b27bfeed-a105-4ab7-9c64-52d85a0abb70 pictographic-primitives/_uncategorized_19/flytrap_b27bfeed-a105-4ab7-9c64-52d85a0abb70.svg \
  'Vertical ruler with six ticks' eae67cef-853a-4f4b-ba6d-48257036ab7b 'pictographic-primitives/_uncategorized_33/ruler vertical_eae67cef-853a-4f4b-ba6d-48257036ab7b.svg'
