#!/bin/bash
# Batch 14/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/design-pen-tool  source cd921e04-704d-5a6b-a478-676cad6d9f2e
#   solo/diagonal-chalk-stick-with-mark  source d68116b9-c9af-4353-a796-1e8f052913d8
#   solo/diagonal-cleaver-with-hanging-hole  source cfcfcb82-64f9-4889-b3e8-32939823d9d7
#   solo/diagonal-handshake  source 135d01ca-c11c-4e70-a645-04b5dbcd9502
#   solo/diagonal-harpoon-spear  source 97bd5405-299a-47fe-be2a-00f4fac42574
#   solo/diagonal-pencil-writing-line  source 0644b6cc-1fdb-4305-a2b0-1f0ca349c382
#   solo/diagonal-raised-fist-and-forearm  source 9270cbcc-52de-4059-a27a-8e0287d0382e
#   solo/diagonal-spotlight-with-flared-head  source 1e247902-0ef3-434f-a4b9-e90a83d10e84
#   solo/dining-table-two-chairs-bowl  source 9cde1498-b4f8-473c-bf34-8b315d13a18e
#   solo/disabled-battery-content-v2  source 49cd19ff-6293-48fa-8d62-d508a17a80ae
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Design pen tool' cd921e04-704d-5a6b-a478-676cad6d9f2e 'pictographic-primitives/design/design pen tool_cd921e04-704d-5a6b-a478-676cad6d9f2e.svg' \
  'Diagonal chalk stick with mark' d68116b9-c9af-4353-a796-1e8f052913d8 pictographic-primitives/_uncategorized_10/chalk_d68116b9-c9af-4353-a796-1e8f052913d8.svg \
  'Diagonal cleaver with hanging hole' cfcfcb82-64f9-4889-b3e8-32939823d9d7 pictographic-primitives/_uncategorized_11/chops_cfcfcb82-64f9-4889-b3e8-32939823d9d7.svg \
  'Diagonal handshake' 135d01ca-c11c-4e70-a645-04b5dbcd9502 'pictographic-primitives/work/workflow teamwork handshake_135d01ca-c11c-4e70-a645-04b5dbcd9502.svg' \
  'Diagonal harpoon spear' 97bd5405-299a-47fe-be2a-00f4fac42574 pictographic-primitives/_uncategorized_22/harpooner_97bd5405-299a-47fe-be2a-00f4fac42574.svg \
  'Diagonal pencil writing line' 0644b6cc-1fdb-4305-a2b0-1f0ca349c382 pictographic-primitives/_uncategorized_36/stylus_0644b6cc-1fdb-4305-a2b0-1f0ca349c382.svg \
  'Diagonal raised fist and forearm' 9270cbcc-52de-4059-a27a-8e0287d0382e 'pictographic-primitives/_uncategorized_04/artificial arm_9270cbcc-52de-4059-a27a-8e0287d0382e.svg' \
  'Diagonal spotlight with flared head' 1e247902-0ef3-434f-a4b9-e90a83d10e84 pictographic-primitives/_uncategorized_35/spotlight_1e247902-0ef3-434f-a4b9-e90a83d10e84.svg \
  'Dining table two chairs bowl' 9cde1498-b4f8-473c-bf34-8b315d13a18e pictographic-primitives/_uncategorized_26/lunchroom_9cde1498-b4f8-473c-bf34-8b315d13a18e.svg \
  'Disabled battery content v2' 49cd19ff-6293-48fa-8d62-d508a17a80ae 'pictographic-primitives/other/slash battery_49cd19ff-6293-48fa-8d62-d508a17a80ae.svg'
