#!/bin/bash
# Batch 1/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/acro-yoga-folded-balance  source 672c58c9-cf49-5d74-ba11-e6398667c047
#   solo/acro-yoga-stacked-bridge  source e90b7491-c523-516a-bb5e-3f47ddbb4cab
#   solo/acro-yoga-supported-balance  source 5240dbe0-19a2-54d5-b0f7-5cc3089e49e4
#   solo/active-sporting-figure  source 62189f84-b3c6-4b58-ba8a-fae03adee313
#   solo/adblue-fluid-level-wave  source ddba64a9-7a33-401d-9571-bce55808907f
#   solo/adjacent-teeth-with-braces  source 4fe6a86e-b26a-405a-9e35-84f3c5a12b9e
#   solo/adult-child-high-five-hands  source b88757c2-b1ab-49df-9283-b755a2874066
#   solo/aerial-yoga-bow-pose  source 4a1112c6-2f20-434b-b756-511460d08610
#   solo/airplane-rising-above-ground-line  source 28bc625b-2596-540d-91c3-fb5e36336a56
#   solo/airplane-taking-off  source 39a4161c-ed3c-5509-8f55-7f29d7d27ec9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Acro yoga folded balance' 672c58c9-cf49-5d74-ba11-e6398667c047 'pictographic-primitives/sports/acro yoga pose_672c58c9-cf49-5d74-ba11-e6398667c047.svg' \
  'Acro yoga stacked bridge' e90b7491-c523-516a-bb5e-3f47ddbb4cab 'pictographic-primitives/sports/acro yoga pose_e90b7491-c523-516a-bb5e-3f47ddbb4cab.svg' \
  'Acro yoga supported balance' 5240dbe0-19a2-54d5-b0f7-5cc3089e49e4 'pictographic-primitives/sports/acro yoga pose_5240dbe0-19a2-54d5-b0f7-5cc3089e49e4.svg' \
  'Active sporting figure' 62189f84-b3c6-4b58-ba8a-fae03adee313 'pictographic-primitives/video-games/batch-12/video game wii_62189f84-b3c6-4b58-ba8a-fae03adee313.svg' \
  'Adblue fluid level wave' ddba64a9-7a33-401d-9571-bce55808907f 'pictographic-primitives/_uncategorized_01/adblue indicator 1_ddba64a9-7a33-401d-9571-bce55808907f.svg' \
  'Adjacent teeth with braces' 4fe6a86e-b26a-405a-9e35-84f3c5a12b9e 'pictographic-primitives/health/dental brace_4fe6a86e-b26a-405a-9e35-84f3c5a12b9e.svg' \
  'Adult child high five hands' b88757c2-b1ab-49df-9283-b755a2874066 'pictographic-primitives/family/play together_b88757c2-b1ab-49df-9283-b755a2874066.svg' \
  'Aerial yoga bow pose' 4a1112c6-2f20-434b-b756-511460d08610 'pictographic-primitives/_uncategorized_01/aerial yoga bow pose_4a1112c6-2f20-434b-b756-511460d08610.svg' \
  'Airplane rising above ground line' 28bc625b-2596-540d-91c3-fb5e36336a56 'pictographic-primitives/travel/plane land_28bc625b-2596-540d-91c3-fb5e36336a56.svg' \
  'Airplane taking off' 39a4161c-ed3c-5509-8f55-7f29d7d27ec9 'pictographic-primitives/travel/plane take off_39a4161c-ed3c-5509-8f55-7f29d7d27ec9.svg'
