#!/bin/bash
# Batch 53/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/leftward-target-control-batch-015-12  source 13494d07-de78-47e1-ad01-183cb6251326
#   solo/leg-massage-therapy-4a608386  source 4a608386-d726-47bd-b174-b25be1ff2bcc
#   solo/leggings-batch-071  source 43492aa9-0df0-44b7-9d64-1b9b1628b0de
#   solo/leopard  source 4ff1165f-25a1-4654-a51e-73e523879edc
#   solo/lgbt-love  source 223c2cf3-707e-5588-bcee-3eb48df2972c
#   solo/lidded-pot-with-rising-steam  source b4d9798a-8d4f-475d-ad7d-dfa1b59c27c2
#   solo/lifeguard-chair  source 91534a08-7547-4ac5-b041-2c876b5b51d6
#   solo/light-bulb-35687e59-ecf7-59ae-9463-52874a252eed  source 35687e59-ecf7-59ae-9463-52874a252eed
#   solo/light-bulb-f6100fd8-d678-44ff-9012-620f880d9c9c  source f6100fd8-d678-44ff-9012-620f880d9c9c
#   solo/lightbulb-speech-bubble  source 92562640-9872-4421-b793-490578e15ce2
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Leftward target control batch 015 12' 13494d07-de78-47e1-ad01-183cb6251326 'pictographic-primitives/interface-essential/cursor move target left_13494d07-de78-47e1-ad01-183cb6251326.svg' \
  'Leg massage therapy 4a608386' 4a608386-d726-47bd-b174-b25be1ff2bcc 'pictographic-primitives/health/thai massage leg_4a608386-d726-47bd-b174-b25be1ff2bcc.svg' \
  'Leggings batch 071' 43492aa9-0df0-44b7-9d64-1b9b1628b0de pictographic-primitives/_uncategorized_38/tights_43492aa9-0df0-44b7-9d64-1b9b1628b0de.svg \
  Leopard 4ff1165f-25a1-4654-a51e-73e523879edc 'pictographic-primitives/_uncategorized_25/leopard 1_4ff1165f-25a1-4654-a51e-73e523879edc.svg' \
  'Lgbt love' 223c2cf3-707e-5588-bcee-3eb48df2972c 'pictographic-primitives/romance/lgbt love_223c2cf3-707e-5588-bcee-3eb48df2972c.svg' \
  'Lidded pot with rising steam' b4d9798a-8d4f-475d-ad7d-dfa1b59c27c2 pictographic-primitives/_uncategorized_13/cooking_b4d9798a-8d4f-475d-ad7d-dfa1b59c27c2.svg \
  'Lifeguard chair' 91534a08-7547-4ac5-b041-2c876b5b51d6 'pictographic-primitives/sports/swimming lifeguard_91534a08-7547-4ac5-b041-2c876b5b51d6.svg' \
  'Light bulb 35687e59 ecf7 59ae 9463 52874a252eed' 35687e59-ecf7-59ae-9463-52874a252eed 'pictographic-primitives/lights/light bulb_35687e59-ecf7-59ae-9463-52874a252eed.svg' \
  'Light bulb f6100fd8 d678 44ff 9012 620f880d9c9c' f6100fd8-d678-44ff-9012-620f880d9c9c 'pictographic-primitives/lights/light bulb_f6100fd8-d678-44ff-9012-620f880d9c9c.svg' \
  'Lightbulb speech bubble' 92562640-9872-4421-b793-490578e15ce2 'pictographic-primitives/_uncategorized_23/idea message_92562640-9872-4421-b793-490578e15ce2.svg'
