#!/bin/bash
# Batch 49/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/key-with-heart-shaped-bow-opening  source a99dc4a0-50a0-4f59-b6d5-d30eb8b0581c
#   solo/keypad-office-telephone  source c56980d4-fcc1-42c9-bdff-b4c9ba3e1d71
#   solo/kimono-sash-belt  source 4837e756-afcf-439b-a2ef-2c90c1a05a91
#   solo/kite-and-bowl-of-sweets-batch-013  source f6afb752-c918-40fd-9be7-5c7a79a0b099
#   solo/kite-beside-small-cloud  source beeba30d-8d4a-48a4-85a6-836e8a238bd0
#   solo/knife-block-two-knives  source 00074a61-3ed9-40d1-8059-4735820ac11b
#   solo/laboratory-microscope-101aaf57-solo  source 101aaf57-5431-5ae4-a7e5-f05c16647c10
#   solo/lake-vessel-signal  source c301559e-579c-4654-91bd-95b3bbcf39dd
#   solo/landscape-picture-media-file-solo  source 41f3ad63-cd17-441d-b26d-945da63c6f7c
#   solo/laptop-small-squares  source 71714a04-dd1b-4fab-90a6-dbd391dacaf5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Key with heart shaped bow opening' a99dc4a0-50a0-4f59-b6d5-d30eb8b0581c 'pictographic-primitives/_uncategorized_26/love heart key_a99dc4a0-50a0-4f59-b6d5-d30eb8b0581c.svg' \
  'Keypad office telephone' c56980d4-fcc1-42c9-bdff-b4c9ba3e1d71 'pictographic-primitives/_uncategorized_30/phone office_c56980d4-fcc1-42c9-bdff-b4c9ba3e1d71.svg' \
  'Kimono sash belt' 4837e756-afcf-439b-a2ef-2c90c1a05a91 pictographic-primitives/_uncategorized_28/obi_4837e756-afcf-439b-a2ef-2c90c1a05a91.svg \
  'Kite and bowl of sweets batch 013' f6afb752-c918-40fd-9be7-5c7a79a0b099 'pictographic-primitives/holidays/makara sankranti_f6afb752-c918-40fd-9be7-5c7a79a0b099.svg' \
  'Kite beside small cloud' beeba30d-8d4a-48a4-85a6-836e8a238bd0 'pictographic-primitives/_uncategorized_29/outdoors kite flying cloud_beeba30d-8d4a-48a4-85a6-836e8a238bd0.svg' \
  'Knife block two knives' 00074a61-3ed9-40d1-8059-4735820ac11b 'pictographic-primitives/_uncategorized_24/knives set_00074a61-3ed9-40d1-8059-4735820ac11b.svg' \
  'Laboratory microscope 101aaf57 solo' 101aaf57-5431-5ae4-a7e5-f05c16647c10 pictographic-primitives/health/microscope_101aaf57-5431-5ae4-a7e5-f05c16647c10.svg \
  'Lake vessel signal' c301559e-579c-4654-91bd-95b3bbcf39dd 'pictographic-primitives/programing/lake formation_c301559e-579c-4654-91bd-95b3bbcf39dd.svg' \
  'Landscape picture media file solo' 41f3ad63-cd17-441d-b26d-945da63c6f7c 'pictographic-primitives/files/image file_41f3ad63-cd17-441d-b26d-945da63c6f7c.svg' \
  'Laptop small squares' 71714a04-dd1b-4fab-90a6-dbd391dacaf5 'pictographic-primitives/other/laptop small squares_71714a04-dd1b-4fab-90a6-dbd391dacaf5.svg'
