#!/bin/bash
# Batch 5/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/braided-yarn-skein  source 5ab9f3b5-03e7-4655-9d6a-e84a5583b790
#   solo/brain-circuit  source 994c360d-a3ef-411d-83b6-1227713cc09e
#   solo/brain-with-undivided-centre  source 505cc1d4-dec0-4492-aadd-1c3ba0a9d545
#   solo/bridge-pose  source ed6cb660-23da-5c6d-9d87-7413118cab56
#   solo/briefcase-carrying-hailing-person  source 459ca9bc-41c3-44a7-bd18-4322e40df660
#   solo/broccoli-and-carrot  source 1833535f-220e-490a-9e51-7058a14ac9db
#   solo/browser-user-profile  source 3a3e4d85-115c-4ccb-82d1-46fd45222b3a
#   solo/browser-with-18-plus-text  source fc5ffdff-80e9-4119-bf62-fb7c515c5aad
#   solo/browser-yuan-sign-solo  source f3a40f08-7124-46f5-9ed2-b85ee4e25e73
#   solo/bunch-of-bananas-batch-010-10  source 01dfab52-1214-532b-8f84-ea5dce7a2998
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Braided yarn skein' 5ab9f3b5-03e7-4655-9d6a-e84a5583b790 pictographic-primitives/hobbies/yarn_5ab9f3b5-03e7-4655-9d6a-e84a5583b790.svg \
  'Brain circuit' 994c360d-a3ef-411d-83b6-1227713cc09e 'pictographic-primitives/_uncategorized_07/brain circuit_994c360d-a3ef-411d-83b6-1227713cc09e.svg' \
  'Brain with undivided centre' 505cc1d4-dec0-4492-aadd-1c3ba0a9d545 'pictographic-primitives/artificial-intelligence/brain 1_505cc1d4-dec0-4492-aadd-1c3ba0a9d545.svg' \
  'Bridge pose' ed6cb660-23da-5c6d-9d87-7413118cab56 'pictographic-primitives/sports/yoga bridge pose_ed6cb660-23da-5c6d-9d87-7413118cab56.svg' \
  'Briefcase carrying hailing person' 459ca9bc-41c3-44a7-bd18-4322e40df660 'pictographic-primitives/_uncategorized_37/taxi wave businessman_459ca9bc-41c3-44a7-bd18-4322e40df660.svg' \
  'Broccoli and carrot' 1833535f-220e-490a-9e51-7058a14ac9db 'pictographic-primitives/symbol/broccoli carrot_1833535f-220e-490a-9e51-7058a14ac9db.svg' \
  'Browser user profile' 3a3e4d85-115c-4ccb-82d1-46fd45222b3a 'pictographic-primitives/other/browser person_3a3e4d85-115c-4ccb-82d1-46fd45222b3a.svg' \
  'Browser with 18 plus text' fc5ffdff-80e9-4119-bf62-fb7c515c5aad 'pictographic-primitives/other/browser with 18+ text_fc5ffdff-80e9-4119-bf62-fb7c515c5aad.svg' \
  'Browser yuan sign solo' f3a40f08-7124-46f5-9ed2-b85ee4e25e73 'pictographic-primitives/other/browser yuan sign right_f3a40f08-7124-46f5-9ed2-b85ee4e25e73.svg' \
  'Bunch of bananas batch 010 10' 01dfab52-1214-532b-8f84-ea5dce7a2998 pictographic-primitives/food/banana_01dfab52-1214-532b-8f84-ea5dce7a2998.svg
