#!/bin/bash
# Batch 22/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/google-hangouts-chat-logo  source 5b2c09bc-ce9d-44af-a66a-8d18d5c67273
#   solo/google-hangouts-meet-logo  source ad553831-37d6-49c3-9e91-05b93acad6fd
#   solo/google-keep-bulb-logo  source 0fc333fe-a7cf-4836-b02f-2467e5c78a5b
#   solo/google-keep-logo  source 71ea2ce0-1304-4572-a64c-16f4b1457b48
#   solo/google-maps-logo  source fa153f72-36bd-4f55-b299-fbbd01a43d85
#   solo/google-optimize-logo  source e542d314-5b0f-4e8e-928d-604b7d3d4044
#   solo/google-pay-logo  source 28593949-3ff4-5bcc-baac-eb689999be7d
#   solo/google-plus-logo  source 21a87bc5-199b-493f-991b-725b026db17b
#   solo/google-plus-lowercase-logo  source 96faaeef-c843-44fa-8d47-77cb3ec2c55b
#   solo/google-podcasts-logo-circle  source b183e77d-95bb-4d82-bf73-d7eac903f274
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Google hangouts chat logo' 5b2c09bc-ce9d-44af-a66a-8d18d5c67273 'pictographic-primitives/logos/google hangouts chat logo_5b2c09bc-ce9d-44af-a66a-8d18d5c67273.svg' \
  'Google hangouts meet logo' ad553831-37d6-49c3-9e91-05b93acad6fd 'pictographic-primitives/logos/google hangouts meet logo_ad553831-37d6-49c3-9e91-05b93acad6fd.svg' \
  'Google keep bulb logo' 0fc333fe-a7cf-4836-b02f-2467e5c78a5b 'pictographic-primitives/logos/google keep logo 1_0fc333fe-a7cf-4836-b02f-2467e5c78a5b.svg' \
  'Google keep logo' 71ea2ce0-1304-4572-a64c-16f4b1457b48 'pictographic-primitives/logos/google keep logo_71ea2ce0-1304-4572-a64c-16f4b1457b48.svg' \
  'Google maps logo' fa153f72-36bd-4f55-b299-fbbd01a43d85 'pictographic-primitives/logos/google maps logo_fa153f72-36bd-4f55-b299-fbbd01a43d85.svg' \
  'Google optimize logo' e542d314-5b0f-4e8e-928d-604b7d3d4044 'pictographic-primitives/logos/google optimize logo_e542d314-5b0f-4e8e-928d-604b7d3d4044.svg' \
  'Google pay logo' 28593949-3ff4-5bcc-baac-eb689999be7d 'pictographic-primitives/logos/google pay_28593949-3ff4-5bcc-baac-eb689999be7d.svg' \
  'Google plus logo' 21a87bc5-199b-493f-991b-725b026db17b 'pictographic-primitives/logos/google plus logo_21a87bc5-199b-493f-991b-725b026db17b.svg' \
  'Google plus lowercase logo' 96faaeef-c843-44fa-8d47-77cb3ec2c55b 'pictographic-primitives/logos/google plus logo 2_96faaeef-c843-44fa-8d47-77cb3ec2c55b.svg' \
  'Google podcasts logo circle' b183e77d-95bb-4d82-bf73-d7eac903f274 'pictographic-primitives/logos/google podcast logo 1_b183e77d-95bb-4d82-bf73-d7eac903f274.svg'
