#!/bin/bash
# Batch 38/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hex-nut-cluster  source e9326841-b6b1-432e-a99d-c2065849139b
#   solo/hexagonal-node-network-component  source 293c7663-04e3-4a88-9038-3812935570a5
#   solo/hidden-visibility-eye-symbol-solo  source 90c55c1b-6141-40f9-8dfb-e0b9bed3cb5e
#   solo/hierarchy-arched-branches  source a46a65c8-4a95-55ac-8668-317d0b3a148f
#   solo/hierarchy-bracket-list  source f31a007d-3a5d-501c-a760-c2b7f61bfea3
#   solo/hierarchy-programing  source 74cd9468-a057-5e62-8b17-2fbc2ef92c08
#   solo/high-column-two-tick-thermometer  source 26bf3af8-64f9-4d16-aa6c-a43c72408de7
#   solo/high-temperature-thermometer  source 1fa52957-1342-499f-9403-f3293476b96f
#   solo/hiker-with-headlamp  source a7ad061e-a477-4a15-993d-a60fd5aa42f9
#   solo/hiker-with-pole-beside-tent  source a5dd1853-85b1-4551-9bed-6d6340338b74
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hex nut cluster' e9326841-b6b1-432e-a99d-c2065849139b 'pictographic-primitives/programing/well architected tools_e9326841-b6b1-432e-a99d-c2065849139b.svg' \
  'Hexagonal node network component' 293c7663-04e3-4a88-9038-3812935570a5 'pictographic-primitives/programing/migration hub_293c7663-04e3-4a88-9038-3812935570a5.svg' \
  'Hidden visibility eye symbol solo' 90c55c1b-6141-40f9-8dfb-e0b9bed3cb5e 'pictographic-primitives/other/eye slash_90c55c1b-6141-40f9-8dfb-e0b9bed3cb5e.svg' \
  'Hierarchy arched branches' a46a65c8-4a95-55ac-8668-317d0b3a148f pictographic-primitives/programing/hierarchy_a46a65c8-4a95-55ac-8668-317d0b3a148f.svg \
  'Hierarchy bracket list' f31a007d-3a5d-501c-a760-c2b7f61bfea3 pictographic-primitives/programing/hierarchy_f31a007d-3a5d-501c-a760-c2b7f61bfea3.svg \
  'Hierarchy programing' 74cd9468-a057-5e62-8b17-2fbc2ef92c08 pictographic-primitives/programing/hierarchy_74cd9468-a057-5e62-8b17-2fbc2ef92c08.svg \
  'High column two tick thermometer' 26bf3af8-64f9-4d16-aa6c-a43c72408de7 'pictographic-primitives/_uncategorized_37/temperature high_26bf3af8-64f9-4d16-aa6c-a43c72408de7.svg' \
  'High temperature thermometer' 1fa52957-1342-499f-9403-f3293476b96f 'pictographic-primitives/food/temperature thermometer high_1fa52957-1342-499f-9403-f3293476b96f.svg' \
  'Hiker with headlamp' a7ad061e-a477-4a15-993d-a60fd5aa42f9 'pictographic-primitives/outdoors/climbing head light_a7ad061e-a477-4a15-993d-a60fd5aa42f9.svg' \
  'Hiker with pole beside tent' a5dd1853-85b1-4551-9bed-6d6340338b74 'pictographic-primitives/_uncategorized_09/camping trekking 2_a5dd1853-85b1-4551-9bed-6d6340338b74.svg'
