#!/bin/bash
# Batch 50/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/laptop-with-tablet-and-phone  source d2708e32-1d86-4bce-a5f3-8d810846d84e
#   solo/laptop-with-two-upright-screens  source 3d2cca23-b331-4167-99c3-f5d15d9a0822
#   solo/laptop-worker-beneath-sun-and-horizon  source 195158ad-68fb-43f8-82c7-2767217ded9c
#   solo/laptop-worker-beside-beach-palm  source 6d4dd61f-6a26-4fe2-9153-8e53f8a73a5d
#   solo/lard-on-tray  source 021f2cff-c2ae-4ed2-ad66-8ee015332b9b
#   solo/large-fish-pursuing-small-fish  source ef3909ee-ca34-4bc7-88ca-385329aa590a
#   solo/large-tooth-beside-upright-toothbrush  source c63435a2-c5ef-4352-9216-a28ed41a6246
#   solo/latex-glove  source 6288b5a8-887b-4031-b7cf-6d2c2cf7edf6
#   solo/lattice-oil-pump-jack  source 4216f978-fc24-48e8-8c36-261313bcdf26
#   solo/laughing-face-with-two-large-tears  source bcd6fbe4-8b3a-4945-a0f1-88cad7e151e2
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Laptop with tablet and phone' d2708e32-1d86-4bce-a5f3-8d810846d84e 'pictographic-primitives/websites/responsive design laptop_d2708e32-1d86-4bce-a5f3-8d810846d84e.svg' \
  'Laptop with two upright screens' 3d2cca23-b331-4167-99c3-f5d15d9a0822 'pictographic-primitives/websites/responsive design laptop_3d2cca23-b331-4167-99c3-f5d15d9a0822.svg' \
  'Laptop worker beneath sun and horizon' 195158ad-68fb-43f8-82c7-2767217ded9c 'pictographic-primitives/_uncategorized_15/digital nomad sun_195158ad-68fb-43f8-82c7-2767217ded9c.svg' \
  'Laptop worker beside beach palm' 6d4dd61f-6a26-4fe2-9153-8e53f8a73a5d 'pictographic-primitives/_uncategorized_15/digital nomad beach_6d4dd61f-6a26-4fe2-9153-8e53f8a73a5d.svg' \
  'Lard on tray' 021f2cff-c2ae-4ed2-ad66-8ee015332b9b pictographic-primitives/_uncategorized_24/lard_021f2cff-c2ae-4ed2-ad66-8ee015332b9b.svg \
  'Large fish pursuing small fish' ef3909ee-ca34-4bc7-88ca-385329aa590a 'pictographic-primitives/_uncategorized_08/business big small fish_ef3909ee-ca34-4bc7-88ca-385329aa590a.svg' \
  'Large tooth beside upright toothbrush' c63435a2-c5ef-4352-9216-a28ed41a6246 pictographic-primitives/_uncategorized_14/dentist_c63435a2-c5ef-4352-9216-a28ed41a6246.svg \
  'Latex glove' 6288b5a8-887b-4031-b7cf-6d2c2cf7edf6 pictographic-primitives/_uncategorized_24/latex_6288b5a8-887b-4031-b7cf-6d2c2cf7edf6.svg \
  'Lattice oil pump jack' 4216f978-fc24-48e8-8c36-261313bcdf26 'pictographic-primitives/_uncategorized_29/oil well_4216f978-fc24-48e8-8c36-261313bcdf26.svg' \
  'Laughing face with two large tears' bcd6fbe4-8b3a-4945-a0f1-88cad7e151e2 'pictographic-primitives/_uncategorized_17/face grin squint tears_bcd6fbe4-8b3a-4945-a0f1-88cad7e151e2.svg'
