#!/bin/bash
# Batch 27/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-holding-two-game-cards  source 9e452a20-d223-431c-a550-2caad608f489
#   solo/hand-holding-wireless-phone  source 67fe58cc-4429-4121-a342-5bd274251e19
#   solo/hand-holding-wrench  source 80b7765d-72c2-4b01-b0bf-6a084aa9bc97
#   solo/hand-inserting-tilted-ballot-into-box  source 060b8775-d227-46ed-8367-77a66c4a5282
#   solo/hand-lowering-a-coin-toward-a-cup  source b756b0fb-ba2c-4349-bad0-de1ee11adb74
#   solo/hand-lowering-diagonal-ballot-toward-slot  source 6dec0eec-6a7b-45e6-8bf4-6d2af8987802
#   solo/hand-lowering-upright-ballot-into-box  source 494983a9-5973-45bd-924f-b941bfe7227c
#   solo/hand-massaging-foot-8ab52d55  source 8ab52d55-ae52-4c12-82e0-c8e7e2dc8409
#   solo/hand-massaging-scalp-17e8bc26  source 17e8bc26-5dd7-4e47-b8f2-9a09c357e6ec
#   solo/hand-over-heat  source e2391138-4aaf-4587-83d5-f636e7ba5379
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand holding two game cards' 9e452a20-d223-431c-a550-2caad608f489 'pictographic-primitives/_uncategorized_10/card game cards hold_9e452a20-d223-431c-a550-2caad608f489.svg' \
  'Hand holding wireless phone' 67fe58cc-4429-4121-a342-5bd274251e19 'pictographic-primitives/phones/wifi transfer hand_67fe58cc-4429-4121-a342-5bd274251e19.svg' \
  'Hand holding wrench' 80b7765d-72c2-4b01-b0bf-6a084aa9bc97 'pictographic-primitives/tools/tools wrench hold_80b7765d-72c2-4b01-b0bf-6a084aa9bc97.svg' \
  'Hand inserting tilted ballot into box' 060b8775-d227-46ed-8367-77a66c4a5282 'pictographic-primitives/_uncategorized_16/election ballot box 2_060b8775-d227-46ed-8367-77a66c4a5282.svg' \
  'Hand lowering a coin toward a cup' b756b0fb-ba2c-4349-bad0-de1ee11adb74 'pictographic-primitives/_uncategorized_06/begging cup give coin_b756b0fb-ba2c-4349-bad0-de1ee11adb74.svg' \
  'Hand lowering diagonal ballot toward slot' 6dec0eec-6a7b-45e6-8bf4-6d2af8987802 'pictographic-primitives/_uncategorized_16/election ballot box 1_6dec0eec-6a7b-45e6-8bf4-6d2af8987802.svg' \
  'Hand lowering upright ballot into box' 494983a9-5973-45bd-924f-b941bfe7227c 'pictographic-primitives/_uncategorized_16/election ballot box 3_494983a9-5973-45bd-924f-b941bfe7227c.svg' \
  'Hand massaging foot 8ab52d55' 8ab52d55-ae52-4c12-82e0-c8e7e2dc8409 'pictographic-primitives/health/massage foot_8ab52d55-ae52-4c12-82e0-c8e7e2dc8409.svg' \
  'Hand massaging scalp 17e8bc26' 17e8bc26-5dd7-4e47-b8f2-9a09c357e6ec 'pictographic-primitives/health/massage head_17e8bc26-5dd7-4e47-b8f2-9a09c357e6ec.svg' \
  'Hand over heat' e2391138-4aaf-4587-83d5-f636e7ba5379 'pictographic-primitives/symbol/hand with flame_e2391138-4aaf-4587-83d5-f636e7ba5379.svg'
