#!/bin/bash
# Batch 69/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/portrait-with-bob-hair-and-pendant-collar-batch-086  source 982bdc1e-36e5-4108-b7e3-97ae6b741259
#   solo/poseidon-holding-trident  source 82fdb403-45fe-4e25-9e15-98892046ca82
#   solo/pregnancy-vagina  source fbfafe1f-782d-4508-b75d-36ed7ad826dd
#   solo/real-estate-market-building-increase  source 4cb4eabd-1bfb-46c2-ab15-0b351ab22677
#   solo/real-estate-market-house-decrease  source 79bf90d8-329d-4a4d-83de-1b10b21a59b2
#   solo/real-estate-market-house-increase  source a9eae52c-5fba-4c26-8ab9-e955eeea7260
#   solo/recycling  source 04c91a4b-2ad8-4cfb-8848-0a6d8807a4cb
#   solo/reflect-left  source c0b25e8b-7627-4856-b90d-2da595ef2528
#   solo/reflect-right  source 0612d818-cafc-45a8-8575-34af044e11de
#   solo/right-indentation-action  source bc08c07e-fd43-4866-85c6-472f38121c0c
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Portrait with bob hair and pendant collar batch 086' 982bdc1e-36e5-4108-b7e3-97ae6b741259 pictographic-primitives/video-games/batch-06/magneto_982bdc1e-36e5-4108-b7e3-97ae6b741259.svg \
  'Poseidon holding trident' 82fdb403-45fe-4e25-9e15-98892046ca82 pictographic-primitives/video-games/batch-09/poseidon_82fdb403-45fe-4e25-9e15-98892046ca82.svg \
  'Pregnancy vagina' fbfafe1f-782d-4508-b75d-36ed7ad826dd 'pictographic-primitives/health/pregnancy vagina_fbfafe1f-782d-4508-b75d-36ed7ad826dd.svg' \
  'Real estate market building increase' 4cb4eabd-1bfb-46c2-ab15-0b351ab22677 'pictographic-primitives/_uncategorized_32/real estate market building increase_4cb4eabd-1bfb-46c2-ab15-0b351ab22677.svg' \
  'Real estate market house decrease' 79bf90d8-329d-4a4d-83de-1b10b21a59b2 'pictographic-primitives/_uncategorized_32/real estate market house decrease_79bf90d8-329d-4a4d-83de-1b10b21a59b2.svg' \
  'Real estate market house increase' a9eae52c-5fba-4c26-8ab9-e955eeea7260 'pictographic-primitives/_uncategorized_32/real estate market house increase_a9eae52c-5fba-4c26-8ab9-e955eeea7260.svg' \
  Recycling 04c91a4b-2ad8-4cfb-8848-0a6d8807a4cb pictographic-primitives/state/recycling_04c91a4b-2ad8-4cfb-8848-0a6d8807a4cb.svg \
  'Reflect left' c0b25e8b-7627-4856-b90d-2da595ef2528 'pictographic-primitives/design/reflect left_c0b25e8b-7627-4856-b90d-2da595ef2528.svg' \
  'Reflect right' 0612d818-cafc-45a8-8575-34af044e11de 'pictographic-primitives/design/reflect right_0612d818-cafc-45a8-8575-34af044e11de.svg' \
  'Right indentation action' bc08c07e-fd43-4866-85c6-472f38121c0c 'pictographic-primitives/_uncategorized_02/align right move_bc08c07e-fd43-4866-85c6-472f38121c0c.svg'
