#!/bin/bash
# Batch 39/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hiking-backpack  source 1b36b69a-6a46-53b0-8fa9-0be915f9f94d
#   solo/hippo-face  source fa6b0258-1bc2-51ef-819c-45e3b36a42d4
#   solo/hockey-player-reference-d95d80d0  source d95d80d0-b910-4819-8ffd-fb7a67b374db
#   solo/holly-leaves-and-berries  source b4a39a92-59f3-4333-bba3-da6c75735b50
#   solo/hologram-cube-projector  source 662b3074-f86b-483a-a095-4f5acc053b0c
#   solo/hologram-video-house-projector  source 81218b42-9d67-4c6c-851c-ea4c4841fcdd
#   solo/hooded-swaddle-with-crossed-blanket-folds-v2  source e0eaa90e-ee21-4ae5-bede-0c17096fa38f
#   solo/horizontal-adhesive-bandage  source 5bea8c48-46a9-4400-81c3-a7b99c361faf
#   solo/horizontal-axial-fuse-with-rounded-end-caps  source 19059222-8a90-50b8-a216-cc1d758bf898
#   solo/horizontal-blind-with-left-pull  source 77c28f48-9238-51ba-ae64-d8f35d09e0b1
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hiking backpack' 1b36b69a-6a46-53b0-8fa9-0be915f9f94d 'pictographic-primitives/outdoors/outdoors backpack_1b36b69a-6a46-53b0-8fa9-0be915f9f94d.svg' \
  'Hippo face' fa6b0258-1bc2-51ef-819c-45e3b36a42d4 pictographic-primitives/animals/hippo_fa6b0258-1bc2-51ef-819c-45e3b36a42d4.svg \
  'Hockey player reference d95d80d0' d95d80d0-b910-4819-8ffd-fb7a67b374db 'pictographic-primitives/_uncategorized_40/winter sport ice hockey_d95d80d0-b910-4819-8ffd-fb7a67b374db.svg' \
  'Holly Leaves and Berries' b4a39a92-59f3-4333-bba3-da6c75735b50 pictographic-primitives/holidays/mistletoe_b4a39a92-59f3-4333-bba3-da6c75735b50.svg \
  'Hologram cube projector' 662b3074-f86b-483a-a095-4f5acc053b0c 'pictographic-primitives/technology/virtual box_662b3074-f86b-483a-a095-4f5acc053b0c.svg' \
  'Hologram video house projector' 81218b42-9d67-4c6c-851c-ea4c4841fcdd 'pictographic-primitives/technology/virtual house_81218b42-9d67-4c6c-851c-ea4c4841fcdd.svg' \
  'Hooded swaddle with crossed blanket folds v2' e0eaa90e-ee21-4ae5-bede-0c17096fa38f 'pictographic-primitives/_uncategorized_05/baby newborn_e0eaa90e-ee21-4ae5-bede-0c17096fa38f.svg' \
  'Horizontal adhesive bandage' 5bea8c48-46a9-4400-81c3-a7b99c361faf pictographic-primitives/_uncategorized_18/fascia_5bea8c48-46a9-4400-81c3-a7b99c361faf.svg \
  'Horizontal axial fuse with rounded end caps' 19059222-8a90-50b8-a216-cc1d758bf898 'pictographic-primitives/electronics/electronics fuse_19059222-8a90-50b8-a216-cc1d758bf898.svg' \
  'Horizontal blind with left pull' 77c28f48-9238-51ba-ae64-d8f35d09e0b1 'pictographic-primitives/building/blinds horizontal open_77c28f48-9238-51ba-ae64-d8f35d09e0b1.svg'
