#!/bin/bash
# Batch 31/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-wash-laundry  source a4f18a57-0c02-4aa1-b46a-d6e8fea6bc96
#   solo/hand-with-iv-bag-13a7d69b  source 13a7d69b-96cf-55d6-9c39-1dfeb0b9a18f
#   solo/hand-with-round-wrist-ornament  source a053cd16-d4e9-4fa2-8cbc-8e8c60de043b
#   solo/handcuff-pair-with-separate-key  source 4a54478b-4849-4373-b597-046376cb8fb9
#   solo/handcuffs-with-arched-connector  source 404190ff-389e-4a15-a7fe-4b448b432ffd
#   solo/handcuffs-with-curved-link  source ad5f17ec-d6f2-402a-8907-dbd8532598e6
#   solo/handlebar-moustache-with-upturned-tips  source 00ac7dca-2cda-4195-b41c-814f500675f8
#   solo/handled-comb-on-diagonal  source dafdca17-4d27-4cd9-935d-01a08f4e53e2
#   solo/handled-diya-oil-lamp  source ce61eef0-26c7-53d5-8b7f-008e608029a0
#   solo/hands-cradling-continuous-person-bust  source ddc30f7b-9b10-45e2-bbee-111110335859
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand wash laundry' a4f18a57-0c02-4aa1-b46a-d6e8fea6bc96 'pictographic-primitives/_uncategorized_25/laundry hand wash_a4f18a57-0c02-4aa1-b46a-d6e8fea6bc96.svg' \
  'Hand with iv bag 13a7d69b' 13a7d69b-96cf-55d6-9c39-1dfeb0b9a18f 'pictographic-primitives/health/transfusion hand_13a7d69b-96cf-55d6-9c39-1dfeb0b9a18f.svg' \
  'Hand with round wrist ornament' a053cd16-d4e9-4fa2-8cbc-8e8c60de043b 'pictographic-primitives/_uncategorized_07/bracelet with hand_a053cd16-d4e9-4fa2-8cbc-8e8c60de043b.svg' \
  'Handcuff pair with separate key' 4a54478b-4849-4373-b597-046376cb8fb9 'pictographic-primitives/_uncategorized_13/crime tools shackle key_4a54478b-4849-4373-b597-046376cb8fb9.svg' \
  'Handcuffs with arched connector' 404190ff-389e-4a15-a7fe-4b448b432ffd pictographic-primitives/crime/handcuffs_404190ff-389e-4a15-a7fe-4b448b432ffd.svg \
  'Handcuffs with curved link' ad5f17ec-d6f2-402a-8907-dbd8532598e6 'pictographic-primitives/crime/tools shackle_ad5f17ec-d6f2-402a-8907-dbd8532598e6.svg' \
  'Handlebar moustache with upturned tips' 00ac7dca-2cda-4195-b41c-814f500675f8 pictographic-primitives/_uncategorized_27/moustache_00ac7dca-2cda-4195-b41c-814f500675f8.svg \
  'Handled comb on diagonal' dafdca17-4d27-4cd9-935d-01a08f4e53e2 'pictographic-primitives/beauty/hair dress comb_dafdca17-4d27-4cd9-935d-01a08f4e53e2.svg' \
  'Handled diya oil lamp' ce61eef0-26c7-53d5-8b7f-008e608029a0 'pictographic-primitives/holidays/karthika deepam_ce61eef0-26c7-53d5-8b7f-008e608029a0.svg' \
  'Hands cradling continuous person bust' ddc30f7b-9b10-45e2-bbee-111110335859 'pictographic-primitives/business/donation charity care person male_ddc30f7b-9b10-45e2-bbee-111110335859.svg'
