#!/bin/bash
# Batch 2/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/airport-signal-antenna  source 58573359-f61e-52a8-b710-7818357fd8e0
#   solo/alien-head-angular-eyes  source 194e70a7-f921-4957-b6e3-e9ba0cf49902
#   solo/alien-head-slanted-eyes  source 3111e4ee-f8d7-5adc-8f71-0cc4e4063457
#   solo/align-top-bottom  source f31f1d33-4050-4371-af56-548e54cec150
#   solo/all-terrain-vehicle-batch-025-14  source b4068396-30fc-5e9b-8eca-c9272d55decc
#   solo/amazon-eventbridge  source 34f87da9-e584-47f7-8fe0-ca66e9aa7da9
#   solo/angled-handlebar-road-bicycle  source 7eea5c25-9b41-4dec-ba5e-91b557120a37
#   solo/armored-hero-with-pointed-helmet-batch-086  source ed5c437b-f1b7-5deb-8e7e-d0d95f2f6077
#   solo/arrow-down-rounded-outline  source 6747c5ea-98ee-4045-b34c-2a968c515c7a
#   solo/arrow-horizontal-with-two-open-heads  source d940547b-c44c-47a1-b2e3-3fd157a39a48
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Airport signal antenna' 58573359-f61e-52a8-b710-7818357fd8e0 'pictographic-primitives/travel/airport signal_58573359-f61e-52a8-b710-7818357fd8e0.svg' \
  'Alien head angular eyes' 194e70a7-f921-4957-b6e3-e9ba0cf49902 'pictographic-primitives/science/fiction alien_194e70a7-f921-4957-b6e3-e9ba0cf49902.svg' \
  'Alien head slanted eyes' 3111e4ee-f8d7-5adc-8f71-0cc4e4063457 pictographic-primitives/science/alien_3111e4ee-f8d7-5adc-8f71-0cc4e4063457.svg \
  'Align top bottom' f31f1d33-4050-4371-af56-548e54cec150 'pictographic-primitives/_uncategorized_02/align top bottom_f31f1d33-4050-4371-af56-548e54cec150.svg' \
  'All terrain vehicle batch 025 14' b4068396-30fc-5e9b-8eca-c9272d55decc 'pictographic-primitives/other/car atv_b4068396-30fc-5e9b-8eca-c9272d55decc.svg' \
  'Amazon eventbridge' 34f87da9-e584-47f7-8fe0-ca66e9aa7da9 'pictographic-primitives/_uncategorized_02/amazon eventbridge_34f87da9-e584-47f7-8fe0-ca66e9aa7da9.svg' \
  'Angled handlebar road bicycle' 7eea5c25-9b41-4dec-ba5e-91b557120a37 'pictographic-primitives/_uncategorized_06/bike parking 2_7eea5c25-9b41-4dec-ba5e-91b557120a37.svg' \
  'Armored hero with pointed helmet batch 086' ed5c437b-f1b7-5deb-8e7e-d0d95f2f6077 'pictographic-primitives/video-games/batch-07/megaman zero_ed5c437b-f1b7-5deb-8e7e-d0d95f2f6077.svg' \
  'Arrow down rounded outline' 6747c5ea-98ee-4045-b34c-2a968c515c7a 'pictographic-primitives/_uncategorized_10/caret down_6747c5ea-98ee-4045-b34c-2a968c515c7a.svg' \
  'Arrow horizontal with two open heads' d940547b-c44c-47a1-b2e3-3fd157a39a48 'pictographic-primitives/_uncategorized_26/look both ways 1_d940547b-c44c-47a1-b2e3-3fd157a39a48.svg'
