#!/bin/bash
# Batch 7/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/canoe-paddler  source fc6689dd-a028-5cb2-b326-1fe893e5518c
#   solo/cao-dai  source 1a804c88-15f7-4476-b406-236f03484b85
#   solo/capped-delivery-rider-on-scooter  source 54079a5b-25ea-4346-8fc4-d2b5f8239da0
#   solo/capped-reader-open-book-b7e8ada0  source b7e8ada0-a5f0-47d0-a735-9243c0a23fb5
#   solo/capsule-switch-with-two-strokes-batch-016-14  source 5aacf220-3104-5628-83e3-8dddf6e85cbc
#   solo/car-beneath-wash-bubbles  source d7783b02-e678-4b5f-a12d-e6dd227ecdd8
#   solo/car-broken-beneath-impact-burst  source 757187c1-fd16-4577-8bb6-b25ad4df2330
#   solo/car-intersection-sensor-waves  source ab4d1610-e735-4977-967a-897386cdcc6d
#   solo/car-on-inclined-ramp  source 400b299b-3d6d-4ea5-900a-c45553cdafda
#   solo/car-on-road  source 6991145f-84e0-41a4-b67e-a6f1b5dd5aba
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Canoe paddler' fc6689dd-a028-5cb2-b326-1fe893e5518c 'pictographic-primitives/recreation/canoe person_fc6689dd-a028-5cb2-b326-1fe893e5518c.svg' \
  'Cao dai' 1a804c88-15f7-4476-b406-236f03484b85 'pictographic-primitives/religion/cao dai_1a804c88-15f7-4476-b406-236f03484b85.svg' \
  'Capped delivery rider on scooter' 54079a5b-25ea-4346-8fc4-d2b5f8239da0 'pictographic-primitives/_uncategorized_14/delivery person motorcycle_54079a5b-25ea-4346-8fc4-d2b5f8239da0.svg' \
  'Capped reader open book b7e8ada0' b7e8ada0-a5f0-47d0-a735-9243c0a23fb5 'pictographic-primitives/_uncategorized_28/muslim reading quraan 3_b7e8ada0-a5f0-47d0-a735-9243c0a23fb5.svg' \
  'Capsule switch with two strokes batch 016 14' 5aacf220-3104-5628-83e3-8dddf6e85cbc 'pictographic-primitives/interface-essential/settings off_5aacf220-3104-5628-83e3-8dddf6e85cbc.svg' \
  'Car beneath wash bubbles' d7783b02-e678-4b5f-a12d-e6dd227ecdd8 'pictographic-primitives/_uncategorized_09/car repair wash 2_d7783b02-e678-4b5f-a12d-e6dd227ecdd8.svg' \
  'Car broken beneath impact burst' 757187c1-fd16-4577-8bb6-b25ad4df2330 'pictographic-primitives/_uncategorized_09/car explode_757187c1-fd16-4577-8bb6-b25ad4df2330.svg' \
  'Car intersection sensor waves' ab4d1610-e735-4977-967a-897386cdcc6d 'pictographic-primitives/transportation/intersection assistant_ab4d1610-e735-4977-967a-897386cdcc6d.svg' \
  'Car on inclined ramp' 400b299b-3d6d-4ea5-900a-c45553cdafda 'pictographic-primitives/_uncategorized_09/car descending control_400b299b-3d6d-4ea5-900a-c45553cdafda.svg' \
  'Car on road' 6991145f-84e0-41a4-b67e-a6f1b5dd5aba 'pictographic-primitives/transportation/traveling on road_6991145f-84e0-41a4-b67e-a6f1b5dd5aba.svg'
