#!/bin/bash
# Batch 12/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/crying-face-with-single-tear  source cb57b7db-4e36-492c-979b-5c7f2457c852
#   solo/cube-with-three-connected-nodes-batch-018-14  source 0d0d1025-1418-574d-b291-75e0e612531c
#   solo/cupped-hands-beneath-casino-chip  source b647b3b3-c8a0-417f-8596-b2a79f452496
#   solo/curled-dragon-emblem  source dee97cb7-c9a3-4759-8226-72d5a88a1f0e
#   solo/curled-dragon-with-two-small-horns  source 740f43e8-d537-4ec2-bbd4-d4ce268b541b
#   solo/curled-fox-flame-emblem  source e904c953-0865-4d74-8329-e7cfe84eaa77
#   solo/curled-handlebar-mustache  source 607a7616-62ea-408b-9089-0b620729ff0d
#   solo/curved-agricultural-field-rows  source 3666c9ff-d6e0-450c-908c-4209907d1997
#   solo/curved-bay-with-two-wave-lines  source 95af3736-8137-457c-a403-3663a17cb3af
#   solo/curved-saxophone  source 5b1bdd1e-b98f-4cd3-8970-9fc4e618a5e9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Crying face with single tear' cb57b7db-4e36-492c-979b-5c7f2457c852 'pictographic-primitives/_uncategorized_18/face sad cry_cb57b7db-4e36-492c-979b-5c7f2457c852.svg' \
  'Cube with three connected nodes batch 018 14' 0d0d1025-1418-574d-b291-75e0e612531c 'pictographic-primitives/other/rotate d_0d0d1025-1418-574d-b291-75e0e612531c.svg' \
  'Cupped hands beneath casino chip' b647b3b3-c8a0-417f-8596-b2a79f452496 'pictographic-primitives/_uncategorized_10/casino chip hold_b647b3b3-c8a0-417f-8596-b2a79f452496.svg' \
  'Curled dragon emblem' dee97cb7-c9a3-4759-8226-72d5a88a1f0e 'pictographic-primitives/video-games/batch-02/dragon sigil_dee97cb7-c9a3-4759-8226-72d5a88a1f0e.svg' \
  'Curled dragon with two small horns' 740f43e8-d537-4ec2-bbd4-d4ce268b541b pictographic-primitives/_uncategorized_15/dragon_740f43e8-d537-4ec2-bbd4-d4ce268b541b.svg \
  'Curled fox flame emblem' e904c953-0865-4d74-8329-e7cfe84eaa77 'pictographic-primitives/_uncategorized_19/firefox logo_e904c953-0865-4d74-8329-e7cfe84eaa77.svg' \
  'Curled handlebar mustache' 607a7616-62ea-408b-9089-0b620729ff0d 'pictographic-primitives/_uncategorized_28/mustache 1_607a7616-62ea-408b-9089-0b620729ff0d.svg' \
  'Curved agricultural field rows' 3666c9ff-d6e0-450c-908c-4209907d1997 pictographic-primitives/_uncategorized_31/plantation_3666c9ff-d6e0-450c-908c-4209907d1997.svg \
  'Curved bay with two wave lines' 95af3736-8137-457c-a403-3663a17cb3af pictographic-primitives/_uncategorized_06/bay_95af3736-8137-457c-a403-3663a17cb3af.svg \
  'Curved saxophone' 5b1bdd1e-b98f-4cd3-8970-9fc4e618a5e9 'pictographic-primitives/_uncategorized_23/instrument saxophone_5b1bdd1e-b98f-4cd3-8970-9fc4e618a5e9.svg'
