#!/bin/bash
# Batch 67/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/person-with-spiritual-enlightenment-symbols  source 8c539ea0-c1e4-4239-86da-777c9408c3f4
#   solo/personal-hotspot-connection  source 28673231-6d46-5446-ab57-4cfa5240085c
#   solo/photo-crop-rotate  source 05a94426-1cba-44df-a701-8939c33872de
#   solo/picker-take  source b4f371c6-c5e7-45dd-8d80-8cefea43094a
#   solo/pickup-beneath-three-pines  source 6dfa119a-7ff9-4daf-b2d5-bc196f42deb1
#   solo/pie-chart-growth-content  source f82a9a59-0712-48ad-b67b-ef47e7c946ad
#   solo/piggy-bank-receiving-coin-batch-018-10  source 35b2e33d-7f76-56bf-a387-22ca75647071
#   solo/pikachu-head  source 0c3a61ea-506a-536d-bd3c-5956c221a50a
#   solo/piping-nozzle-above-icing-dollop  source aff563ce-3eaf-4937-9894-dfe356ba0aa4
#   solo/plane-trip-person  source 5ba1d1e1-9400-4baf-a55c-e0c11aabf158
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Person with spiritual enlightenment symbols' 8c539ea0-c1e4-4239-86da-777c9408c3f4 'pictographic-primitives/_uncategorized_04/asalha puja_8c539ea0-c1e4-4239-86da-777c9408c3f4.svg' \
  'Personal hotspot connection' 28673231-6d46-5446-ab57-4cfa5240085c 'pictographic-primitives/mobile/personal hotspot connection_28673231-6d46-5446-ab57-4cfa5240085c.svg' \
  'Photo crop rotate' 05a94426-1cba-44df-a701-8939c33872de 'pictographic-primitives/design/photo crop rotate_05a94426-1cba-44df-a701-8939c33872de.svg' \
  'Picker take' b4f371c6-c5e7-45dd-8d80-8cefea43094a 'pictographic-primitives/design/picker take_b4f371c6-c5e7-45dd-8d80-8cefea43094a.svg' \
  'Pickup beneath three pines' 6dfa119a-7ff9-4daf-b2d5-bc196f42deb1 'pictographic-primitives/_uncategorized_09/car truck woods_6dfa119a-7ff9-4daf-b2d5-bc196f42deb1.svg' \
  'Pie chart growth content' f82a9a59-0712-48ad-b67b-ef47e7c946ad 'pictographic-primitives/business/pie line graph_f82a9a59-0712-48ad-b67b-ef47e7c946ad.svg' \
  'Piggy bank receiving coin batch 018 10' 35b2e33d-7f76-56bf-a387-22ca75647071 pictographic-primitives/money/piggy_35b2e33d-7f76-56bf-a387-22ca75647071.svg \
  'Pikachu head' 0c3a61ea-506a-536d-bd3c-5956c221a50a 'pictographic-primitives/video-games/batch-08/pokemon pikachu electric mice_0c3a61ea-506a-536d-bd3c-5956c221a50a.svg' \
  'Piping nozzle above icing dollop' aff563ce-3eaf-4937-9894-dfe356ba0aa4 'pictographic-primitives/_uncategorized_13/cookies decirating 2_aff563ce-3eaf-4937-9894-dfe356ba0aa4.svg' \
  'Plane trip person' 5ba1d1e1-9400-4baf-a55c-e0c11aabf158 'pictographic-primitives/_uncategorized_31/plane trip person_5ba1d1e1-9400-4baf-a55c-e0c11aabf158.svg'
