#!/bin/bash
# Batch 79/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/tap-gesture-expand-all-directions  source 3404178e-6c6c-4e81-923b-4c9570a627a0
#   solo/tapered-bucket-with-a-side-handle  source 7e0973fe-db20-429c-947b-12211c874777
#   solo/tapping-finger-with-contact-arc  source 50cbe1ba-1e1e-4117-bf96-2166440858aa
#   solo/tea-leaves-beside-pearl-cluster  source 47b073e7-6d6d-4914-a060-1296929bd372
#   solo/teardrop-pendant-round-loop  source 6cdf2e13-8630-47a9-a6a3-a003f4cecfdb
#   solo/tennis-forehand-player  source 47651662-b3cd-4b7c-a239-c37cd47aa6c6
#   solo/three-armed-fidget-spinner-batch-017-10  source c9d7e3a6-e7cd-53ad-8f0d-95595a117f13
#   solo/three-balaclava-wearers  source b87e413a-6c06-4509-b808-28f85d67c2a6
#   solo/three-blade-propeller  source 5e9a24f0-4fd3-49d4-be80-d5d358e7c9ba
#   solo/three-cell-row  source 0237638d-10fe-435f-be3f-042d60a75995
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Tap gesture expand all directions' 3404178e-6c6c-4e81-923b-4c9570a627a0 'pictographic-primitives/_uncategorized_20/gesture tap expand all direction_3404178e-6c6c-4e81-923b-4c9570a627a0.svg' \
  'Tapered bucket with a side handle' 7e0973fe-db20-429c-947b-12211c874777 'pictographic-primitives/_uncategorized_02/amazon s3 storage_7e0973fe-db20-429c-947b-12211c874777.svg' \
  'Tapping finger with contact arc' 50cbe1ba-1e1e-4117-bf96-2166440858aa 'pictographic-primitives/_uncategorized_20/gesture tap 1_50cbe1ba-1e1e-4117-bf96-2166440858aa.svg' \
  'Tea leaves beside pearl cluster' 47b073e7-6d6d-4914-a060-1296929bd372 'pictographic-primitives/_uncategorized_08/bubble tea leaf_47b073e7-6d6d-4914-a060-1296929bd372.svg' \
  'Teardrop pendant round loop' 6cdf2e13-8630-47a9-a6a3-a003f4cecfdb pictographic-primitives/_uncategorized_30/pendant_6cdf2e13-8630-47a9-a6a3-a003f4cecfdb.svg \
  'Tennis forehand player' 47651662-b3cd-4b7c-a239-c37cd47aa6c6 'pictographic-primitives/_uncategorized_37/tennis forehand_47651662-b3cd-4b7c-a239-c37cd47aa6c6.svg' \
  'Three armed fidget spinner batch 017 10' c9d7e3a6-e7cd-53ad-8f0d-95595a117f13 'pictographic-primitives/kids/toys fidget spinner_c9d7e3a6-e7cd-53ad-8f0d-95595a117f13.svg' \
  'Three balaclava wearers' b87e413a-6c06-4509-b808-28f85d67c2a6 'pictographic-primitives/_uncategorized_37/terrorists 1_b87e413a-6c06-4509-b808-28f85d67c2a6.svg' \
  'Three blade propeller' 5e9a24f0-4fd3-49d4-be80-d5d358e7c9ba pictographic-primitives/transportation/propeller_5e9a24f0-4fd3-49d4-be80-d5d358e7c9ba.svg \
  'Three cell row' 0237638d-10fe-435f-be3f-042d60a75995 'pictographic-primitives/interface-essential/row selected single_0237638d-10fe-435f-be3f-042d60a75995.svg'
