#!/bin/bash
# Batch 72/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/seated-figure-on-curved-rocker  source d50e4120-77d7-422c-a424-5d54b2dccc50
#   solo/seated-guinea-pig-profile  source 46db2b82-01c3-4e59-988e-459cdf0acd6e
#   solo/seated-kangaroo-profile  source 6430919f-654f-425a-b43e-41534d7647dd
#   solo/seated-lapdog  source 797d409f-7759-414b-ad4d-9d0962e69876
#   solo/seated-laptop-user  source cef722b8-fa68-48b5-b19f-fa95f0fa4640
#   solo/seated-long-eared-rabbit  source eb69e986-be04-4fec-80c4-3ab9c58a6853
#   solo/seated-orangutan-front-view  source 014fc7d1-8818-495c-9f61-d1612dae4e23
#   solo/seated-person-beside-front-facing-car  source d870fd26-4ba9-4393-b85f-95ba5e7e4786
#   solo/seated-person-wearing-seatbelt  source b812ce7a-15a2-4fcd-8c93-3c8668ca4201
#   solo/seated-rabbit  source f2173899-be04-4ca5-a7b6-ecd18480de03
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Seated figure on curved rocker' d50e4120-77d7-422c-a424-5d54b2dccc50 pictographic-primitives/_uncategorized_33/rocker_d50e4120-77d7-422c-a424-5d54b2dccc50.svg \
  'Seated guinea pig profile' 46db2b82-01c3-4e59-988e-459cdf0acd6e 'pictographic-primitives/_uncategorized_21/guinea pig_46db2b82-01c3-4e59-988e-459cdf0acd6e.svg' \
  'Seated kangaroo profile' 6430919f-654f-425a-b43e-41534d7647dd 'pictographic-primitives/_uncategorized_21/gowalla logo 1_6430919f-654f-425a-b43e-41534d7647dd.svg' \
  'Seated lapdog' 797d409f-7759-414b-ad4d-9d0962e69876 pictographic-primitives/_uncategorized_24/lapdog_797d409f-7759-414b-ad4d-9d0962e69876.svg \
  'Seated laptop user' cef722b8-fa68-48b5-b19f-fa95f0fa4640 'pictographic-primitives/_uncategorized_40/work from home user sit_cef722b8-fa68-48b5-b19f-fa95f0fa4640.svg' \
  'Seated long eared rabbit' eb69e986-be04-4fec-80c4-3ab9c58a6853 pictographic-primitives/_uncategorized_22/hare_eb69e986-be04-4fec-80c4-3ab9c58a6853.svg \
  'Seated orangutan front view' 014fc7d1-8818-495c-9f61-d1612dae4e23 pictographic-primitives/_uncategorized_29/orangutan_014fc7d1-8818-495c-9f61-d1612dae4e23.svg \
  'Seated person beside front facing car' d870fd26-4ba9-4393-b85f-95ba5e7e4786 'pictographic-primitives/_uncategorized_15/disability in car_d870fd26-4ba9-4393-b85f-95ba5e7e4786.svg' \
  'Seated person wearing seatbelt' b812ce7a-15a2-4fcd-8c93-3c8668ca4201 'pictographic-primitives/_uncategorized_18/fasten seal belt_b812ce7a-15a2-4fcd-8c93-3c8668ca4201.svg' \
  'Seated rabbit' f2173899-be04-4ca5-a7b6-ecd18480de03 pictographic-primitives/_uncategorized_25/leveret_f2173899-be04-4ca5-a7b6-ecd18480de03.svg
