#!/bin/bash
# Batch 55/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/looped-power-cable-79eae0ea  source 79eae0ea-a0a3-48d0-a56a-a874914d50c3
#   solo/love-compatibility  source 13ea8ba1-9370-50ce-9da5-f3a7facdf796
#   solo/low-battery  source 49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8
#   solo/low-battery-level  source 058db2e8-12db-48c2-b344-337f39e8f77d
#   solo/low-battery-level-block  source d6b813e9-7593-44ac-8b7e-dc8a1b2e1275
#   solo/low-crescent-with-two-sparkles  source 2e3cad1b-f9fc-43b2-b7f0-4c06b892a8b9
#   solo/low-temperature-thermometer  source 5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8
#   solo/magnifier-refresh  source cddee393-b2d9-4824-86a6-013321aa73e8
#   solo/magnifying-glass-batch-04  source d2a83b3d-ee41-4915-81af-29e371bfd9b0
#   solo/magnifying-glass-footprints  source 3932acf9-d8a9-4dab-a9e2-4e0a52270bc7
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Looped power cable 79eae0ea' 79eae0ea-a0a3-48d0-a56a-a874914d50c3 'pictographic-primitives/container/circle cable_79eae0ea-a0a3-48d0-a56a-a874914d50c3.svg' \
  'Love compatibility' 13ea8ba1-9370-50ce-9da5-f3a7facdf796 'pictographic-primitives/romance/love compatibility_13ea8ba1-9370-50ce-9da5-f3a7facdf796.svg' \
  'Low battery' 49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8 'pictographic-primitives/mobile/charging battery low_49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8.svg' \
  'Low battery level' 058db2e8-12db-48c2-b344-337f39e8f77d 'pictographic-primitives/devices/charging battery low_058db2e8-12db-48c2-b344-337f39e8f77d.svg' \
  'Low battery level block' d6b813e9-7593-44ac-8b7e-dc8a1b2e1275 'pictographic-primitives/devices/charging battery low_d6b813e9-7593-44ac-8b7e-dc8a1b2e1275.svg' \
  'Low crescent with two sparkles' 2e3cad1b-f9fc-43b2-b7f0-4c06b892a8b9 'pictographic-primitives/_uncategorized_04/astrology stars_2e3cad1b-f9fc-43b2-b7f0-4c06b892a8b9.svg' \
  'Low temperature thermometer' 5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8 'pictographic-primitives/_uncategorized_37/temperature low_5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8.svg' \
  'Magnifier refresh' cddee393-b2d9-4824-86a6-013321aa73e8 'pictographic-primitives/business/seo search_cddee393-b2d9-4824-86a6-013321aa73e8.svg' \
  'Magnifying glass batch 04' d2a83b3d-ee41-4915-81af-29e371bfd9b0 'pictographic-primitives/other/magnifying glass with plus_d2a83b3d-ee41-4915-81af-29e371bfd9b0.svg' \
  'Magnifying glass footprints' 3932acf9-d8a9-4dab-a9e2-4e0a52270bc7 'pictographic-primitives/_uncategorized_27/monitoring activity tracking 2_3932acf9-d8a9-4dab-a9e2-4e0a52270bc7.svg'
