#!/bin/bash
# Batch 54/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/limousine  source 2ac64939-46bf-4dd1-9f96-1b8c0d3a2cd5
#   solo/link-interlocking  source a1310a44-a79e-47db-836c-4e40111ae679
#   solo/linked-circular-handcuffs  source 7c088e36-de93-4207-ba03-087b8bb9a1a3
#   solo/loading-bar  source a1357f44-093c-4bb6-93d6-7521033c44d2
#   solo/loading-bar-1  source a0e10581-e9da-4ad2-86ee-9fb92f7f28f3
#   solo/location-pin-ground  source 632bbd50-870e-4274-87d8-51bc5834f214
#   solo/log-with-sprouting-branch  source 30b670a9-7971-4e04-b58f-1d8270ae7e16
#   solo/long-jumper-above-a-ground-line  source 6f66d874-f536-41dd-bfae-be8151d586ac
#   solo/loop-manual  source 2c06654c-8d06-5a7b-95e0-7f57b63f8bac
#   solo/looped-brass-bugle  source 1c3b1dee-2c1a-4e89-91de-95172d2201db
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Limousine 2ac64939-46bf-4dd1-9f96-1b8c0d3a2cd5 pictographic-primitives/_uncategorized_25/limo_2ac64939-46bf-4dd1-9f96-1b8c0d3a2cd5.svg \
  'Link interlocking' a1310a44-a79e-47db-836c-4e40111ae679 pictographic-primitives/symbol/link_a1310a44-a79e-47db-836c-4e40111ae679.svg \
  'Linked circular handcuffs' 7c088e36-de93-4207-ba03-087b8bb9a1a3 'pictographic-primitives/_uncategorized_18/fantasy medieval bounty hunter 2_7c088e36-de93-4207-ba03-087b8bb9a1a3.svg' \
  'Loading bar' a1357f44-093c-4bb6-93d6-7521033c44d2 'pictographic-primitives/interface-essential/loading bar_a1357f44-093c-4bb6-93d6-7521033c44d2.svg' \
  'Loading bar 1' a0e10581-e9da-4ad2-86ee-9fb92f7f28f3 'pictographic-primitives/interface-essential/loading bar 1_a0e10581-e9da-4ad2-86ee-9fb92f7f28f3.svg' \
  'Location pin ground' 632bbd50-870e-4274-87d8-51bc5834f214 'pictographic-primitives/symbol/location dot_632bbd50-870e-4274-87d8-51bc5834f214.svg' \
  'Log with sprouting branch' 30b670a9-7971-4e04-b58f-1d8270ae7e16 'pictographic-primitives/nature/tree log_30b670a9-7971-4e04-b58f-1d8270ae7e16.svg' \
  'Long jumper above a ground line' 6f66d874-f536-41dd-bfae-be8151d586ac 'pictographic-primitives/_uncategorized_04/athletics long jumping_6f66d874-f536-41dd-bfae-be8151d586ac.svg' \
  'Loop manual' 2c06654c-8d06-5a7b-95e0-7f57b63f8bac 'pictographic-primitives/diagrams/loop manual_2c06654c-8d06-5a7b-95e0-7f57b63f8bac.svg' \
  'Looped brass bugle' 1c3b1dee-2c1a-4e89-91de-95172d2201db pictographic-primitives/_uncategorized_08/brass_1c3b1dee-2c1a-4e89-91de-95172d2201db.svg
