#!/bin/bash
# Batch 65/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/person-in-profile-with-swept-hair  source 479da84f-9f73-458f-9606-5fa1f1bd0088
#   solo/person-in-ski-mask  source 331d4b6a-2a43-520f-b93c-bc9a0f5e1062
#   solo/person-leaving-with-box  source 77081baf-a4c5-46ad-8c21-4259e5d6dc98
#   solo/person-location  source 49e0b9d1-bc0c-4794-9bf3-4015f1ce8d7a
#   solo/person-magnifying-glass  source 50c9d08d-facc-4f2d-8e34-dc7e97caef61
#   solo/person-offering-open-newspaper  source 7d776ef1-4a85-4be3-9307-037a19974435
#   solo/person-on-segway  source f6932898-aa2f-4539-aa63-ecfb633b33be
#   solo/person-raising-dumbbell  source 17bb5f28-c6de-4e45-8379-d4c98addac37
#   solo/person-raising-megaphone-with-sound-rays  source 0538edcd-5de5-4e07-affe-fdfe3d69c7c7
#   solo/person-reaching-toward-vending-machine  source 50d630a7-64c0-44f2-96ce-e8d1b2275c55
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Person in profile with swept hair' 479da84f-9f73-458f-9606-5fa1f1bd0088 pictographic-primitives/_uncategorized_32/redhead_479da84f-9f73-458f-9606-5fa1f1bd0088.svg \
  'Person in ski mask' 331d4b6a-2a43-520f-b93c-bc9a0f5e1062 'pictographic-primitives/crime/tools criminal mask_331d4b6a-2a43-520f-b93c-bc9a0f5e1062.svg' \
  'Person leaving with box' 77081baf-a4c5-46ad-8c21-4259e5d6dc98 'pictographic-primitives/_uncategorized_40/worker lay off fired user sad door box_77081baf-a4c5-46ad-8c21-4259e5d6dc98.svg' \
  'Person location' 49e0b9d1-bc0c-4794-9bf3-4015f1ce8d7a 'pictographic-primitives/_uncategorized_25/location user_49e0b9d1-bc0c-4794-9bf3-4015f1ce8d7a.svg' \
  'Person magnifying glass' 50c9d08d-facc-4f2d-8e34-dc7e97caef61 'pictographic-primitives/other/person magnifying glass_50c9d08d-facc-4f2d-8e34-dc7e97caef61.svg' \
  'Person offering open newspaper' 7d776ef1-4a85-4be3-9307-037a19974435 'pictographic-primitives/_uncategorized_28/newspaper give_7d776ef1-4a85-4be3-9307-037a19974435.svg' \
  'Person on segway' f6932898-aa2f-4539-aa63-ecfb633b33be 'pictographic-primitives/transportation/segway person_f6932898-aa2f-4539-aa63-ecfb633b33be.svg' \
  'Person raising dumbbell' 17bb5f28-c6de-4e45-8379-d4c98addac37 pictographic-primitives/_uncategorized_17/exercise_17bb5f28-c6de-4e45-8379-d4c98addac37.svg \
  'Person raising megaphone with sound rays' 0538edcd-5de5-4e07-affe-fdfe3d69c7c7 'pictographic-primitives/_uncategorized_16/election campaign 3_0538edcd-5de5-4e07-affe-fdfe3d69c7c7.svg' \
  'Person reaching toward vending machine' 50d630a7-64c0-44f2-96ce-e8d1b2275c55 'pictographic-primitives/_uncategorized_16/eat vending machine_50d630a7-64c0-44f2-96ce-e8d1b2275c55.svg'
