#!/bin/bash
# Batch 18/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/figure-broad-rain-poncho  source b55bffa3-4279-4235-9ba3-a7ca76021d61
#   solo/figure-wearing-headscarf-7530ebed  source 7530ebed-b232-49fc-ad48-c6aef81bd2d3
#   solo/filled-taco  source add330ed-f5b1-4bc0-b2c1-655024b39398
#   solo/finger-point  source bae26537-844f-44bd-bc92-cf5af361e501
#   solo/finger-prick-blood-sample  source e3dc0da0-bd87-41fd-95b9-89f6eee043aa
#   solo/finger-raised-to-lips  source a820dc57-f149-4286-95b2-5cae2b1c62e9
#   solo/finger-selecting-map-destination  source 4e54a956-814a-4581-8d3c-be1a087ebdba
#   solo/finger-tap-selection-gesture  source b5fa4080-f0f6-4340-bf42-bbc85e2598c9
#   solo/finger-touching-smartphone  source f5462084-18e8-4a32-940d-898d288894e7
#   solo/fitted-evening-dress-with-thin-straps-batch038  source 4fbea98a-2816-4635-a5e1-79429961146a
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Figure broad rain poncho' b55bffa3-4279-4235-9ba3-a7ca76021d61 pictographic-primitives/_uncategorized_31/poncho_b55bffa3-4279-4235-9ba3-a7ca76021d61.svg \
  'Figure wearing headscarf 7530ebed' 7530ebed-b232-49fc-ad48-c6aef81bd2d3 'pictographic-primitives/_uncategorized_28/muslim man outfit 1_7530ebed-b232-49fc-ad48-c6aef81bd2d3.svg' \
  'Filled taco' add330ed-f5b1-4bc0-b2c1-655024b39398 pictographic-primitives/_uncategorized_37/taco_add330ed-f5b1-4bc0-b2c1-655024b39398.svg \
  'Finger point' bae26537-844f-44bd-bc92-cf5af361e501 'pictographic-primitives/wayfinding/finger point_bae26537-844f-44bd-bc92-cf5af361e501.svg' \
  'Finger prick blood sample' e3dc0da0-bd87-41fd-95b9-89f6eee043aa 'pictographic-primitives/_uncategorized_24/laboratory test blood finger_e3dc0da0-bd87-41fd-95b9-89f6eee043aa.svg' \
  'Finger raised to lips' a820dc57-f149-4286-95b2-5cae2b1c62e9 'pictographic-primitives/_uncategorized_02/allowances silence_a820dc57-f149-4286-95b2-5cae2b1c62e9.svg' \
  'Finger selecting map destination' 4e54a956-814a-4581-8d3c-be1a087ebdba 'pictographic-primitives/travel/travel map finger_4e54a956-814a-4581-8d3c-be1a087ebdba.svg' \
  'Finger tap selection gesture' b5fa4080-f0f6-4340-bf42-bbc85e2598c9 'pictographic-primitives/_uncategorized_19/finger tap_b5fa4080-f0f6-4340-bf42-bbc85e2598c9.svg' \
  'Finger touching smartphone' f5462084-18e8-4a32-940d-898d288894e7 'pictographic-primitives/_uncategorized_19/force touch double tap_f5462084-18e8-4a32-940d-898d288894e7.svg' \
  'Fitted evening dress with thin straps batch038' 4fbea98a-2816-4635-a5e1-79429961146a 'pictographic-primitives/_uncategorized_17/evening wear_4fbea98a-2816-4635-a5e1-79429961146a.svg'
