#!/bin/bash
# Batch 63/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/people-watching-fireworks  source 81bc09b0-75b3-46f8-86d6-9e724b96c820
#   solo/perched-hawk-profile  source 70d3ecde-a67d-4049-8f4c-451837cbd344
#   solo/performance-decrease  source ce30d25b-7e40-45e5-bb67-fb74f54f495f
#   solo/perfume-bottle-squeeze-bulb  source 4bb96c3e-3ae8-4bb5-ab21-636b28bdfaac
#   solo/person-behind-a-balcony-rail  source 327d5345-c195-44af-91bd-d09aeb8a2563
#   solo/person-beneath-rising-smoke-plumes-071c4c52  source 071c4c52-a190-4210-8d8d-e3f3838977f4
#   solo/person-beside-a-beach-bucket  source eb5b93f3-38f0-4db7-9011-9f048e2a1395
#   solo/person-beside-acoustic-guitar  source afc1bcf3-950c-46a6-badb-508c8b07dc93
#   solo/person-beside-mountain-peak  source 5853dc01-f202-4aea-831c-868615df00b7
#   solo/person-beside-tall-pine  source 606380e3-1059-40bf-ae0d-162336f79ab6
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'People watching fireworks' 81bc09b0-75b3-46f8-86d6-9e724b96c820 'pictographic-primitives/_uncategorized_19/fireworks people watch_81bc09b0-75b3-46f8-86d6-9e724b96c820.svg' \
  'Perched hawk profile' 70d3ecde-a67d-4049-8f4c-451837cbd344 pictographic-primitives/_uncategorized_22/hawk_70d3ecde-a67d-4049-8f4c-451837cbd344.svg \
  'Performance decrease' ce30d25b-7e40-45e5-bb67-fb74f54f495f 'pictographic-primitives/_uncategorized_30/performance decrease_ce30d25b-7e40-45e5-bb67-fb74f54f495f.svg' \
  'Perfume bottle squeeze bulb' 4bb96c3e-3ae8-4bb5-ab21-636b28bdfaac pictographic-primitives/_uncategorized_30/perfume_4bb96c3e-3ae8-4bb5-ab21-636b28bdfaac.svg \
  'Person behind a balcony rail' 327d5345-c195-44af-91bd-d09aeb8a2563 'pictographic-primitives/_uncategorized_03/apartment balcony man_327d5345-c195-44af-91bd-d09aeb8a2563.svg' \
  'Person beneath rising smoke plumes 071c4c52' 071c4c52-a190-4210-8d8d-e3f3838977f4 'pictographic-primitives/_uncategorized_04/ashura day of atonement tenth day of muharram_071c4c52-a190-4210-8d8d-e3f3838977f4.svg' \
  'Person beside a beach bucket' eb5b93f3-38f0-4db7-9011-9f048e2a1395 'pictographic-primitives/_uncategorized_06/beach swim_eb5b93f3-38f0-4db7-9011-9f048e2a1395.svg' \
  'Person beside acoustic guitar' afc1bcf3-950c-46a6-badb-508c8b07dc93 'pictographic-primitives/_uncategorized_12/concert guitarist_afc1bcf3-950c-46a6-badb-508c8b07dc93.svg' \
  'Person beside mountain peak' 5853dc01-f202-4aea-831c-868615df00b7 'pictographic-primitives/_uncategorized_09/camping trekking 1_5853dc01-f202-4aea-831c-868615df00b7.svg' \
  'Person beside tall pine' 606380e3-1059-40bf-ae0d-162336f79ab6 'pictographic-primitives/_uncategorized_09/camping trekking tree_606380e3-1059-40bf-ae0d-162336f79ab6.svg'
