#!/bin/bash
# Batch 8/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/car-viewed-from-the-rear  source 2ae26408-156c-43de-9e16-97f3b148035f
#   solo/car-with-two-seated-occupants  source 1f4d1069-f84c-4b28-abe2-500ccee986de
#   solo/cargo-bicycle-rear-box  source 697554f1-3afd-5c1d-87a3-50b358ece127
#   solo/cat-head-affection-component  source 340243a4-2ac7-4e3b-ad02-cba7341dd731
#   solo/celebration-face-party-horn  source db4dd436-0c1b-4e44-a5c2-fb12637a6682
#   solo/championship-belt-reference  source 669aedc6-7742-41bf-85bd-47da4843ea6b
#   solo/charging-battery-flash-empty  source 86ff6696-4ddd-4dd2-abe4-b1bbb2a48273
#   solo/chef-knife-batch-012-04  source 88acc3ca-ec5a-4cec-af6f-f39df121e302
#   solo/circle-colon  source 6a0ef6b0-613d-4883-ad08-e75fd510a4f6
#   solo/circular-emblem-with-banner  source cb339990-49e6-46a8-ad97-83dd4ad21af5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Car viewed from the rear' 2ae26408-156c-43de-9e16-97f3b148035f pictographic-primitives/_uncategorized_32/rear_2ae26408-156c-43de-9e16-97f3b148035f.svg \
  'Car with two seated occupants' 1f4d1069-f84c-4b28-abe2-500ccee986de pictographic-primitives/_uncategorized_10/carpool_1f4d1069-f84c-4b28-abe2-500ccee986de.svg \
  'Cargo bicycle rear box' 697554f1-3afd-5c1d-87a3-50b358ece127 'pictographic-primitives/transportation/bike cargo back_697554f1-3afd-5c1d-87a3-50b358ece127.svg' \
  'Cat head affection component' 340243a4-2ac7-4e3b-ad02-cba7341dd731 'pictographic-primitives/pets/cat breeding_340243a4-2ac7-4e3b-ad02-cba7341dd731.svg' \
  'Celebration face party horn' db4dd436-0c1b-4e44-a5c2-fb12637a6682 'pictographic-primitives/_uncategorized_17/face party_db4dd436-0c1b-4e44-a5c2-fb12637a6682.svg' \
  'Championship belt reference' 669aedc6-7742-41bf-85bd-47da4843ea6b pictographic-primitives/computers/batch-04/keyboard_669aedc6-7742-41bf-85bd-47da4843ea6b.svg \
  'Charging battery flash empty' 86ff6696-4ddd-4dd2-abe4-b1bbb2a48273 'pictographic-primitives/mobile/charging battery flash empty_86ff6696-4ddd-4dd2-abe4-b1bbb2a48273.svg' \
  'Chef knife batch 012 04' 88acc3ca-ec5a-4cec-af6f-f39df121e302 'pictographic-primitives/food/knife 1_88acc3ca-ec5a-4cec-af6f-f39df121e302.svg' \
  'Circle colon' 6a0ef6b0-613d-4883-ad08-e75fd510a4f6 'pictographic-primitives/other/circle colon_6a0ef6b0-613d-4883-ad08-e75fd510a4f6.svg' \
  'Circular emblem with banner' cb339990-49e6-46a8-ad97-83dd4ad21af5 'pictographic-primitives/rewards/intellectual property and tradmark_cb339990-49e6-46a8-ad97-83dd4ad21af5.svg'
