#!/bin/bash
# Batch 9/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/cleaning-worker-with-upright-broom  source 9c89e718-df3d-451b-808f-bb9daab2e5b2
#   solo/clenched-fist-solo-b018  source f9cc745f-989b-5241-9fd0-090475a8c137
#   solo/clock-with-clockwise-return-arrow  source 4ae0f802-0947-49ab-948b-a13314a05022
#   solo/clock-with-counterclockwise-arrival-arrow  source 7420a5ad-20b8-4125-a020-7f6c31b74aac
#   solo/closed-fitness-band-with-two-display-marks  source 1cd0692c-3506-4df2-80d7-66be18de3019
#   solo/cloud-with-moon-and-lightning  source 7eb10cf4-5263-45f8-929d-49906b04ace0
#   solo/clove-bud-with-pointed-sepals  source 2fe3535b-ed46-49bc-ad15-b91d93556dfe
#   solo/clustered-marionberry-with-pointed-leaf  source cd0fd2f9-cb2d-40e6-8f25-806b358d94e5
#   solo/coin-passing-between-two-hands  source 9ce7b101-f5f3-42dc-8957-ebdb317cac31
#   solo/compact-motor-with-opposing-shafts  source 8ca49ab1-e686-42a4-9992-7d74b12cfcf9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Cleaning worker with upright broom' 9c89e718-df3d-451b-808f-bb9daab2e5b2 pictographic-primitives/_uncategorized_23/janitor_9c89e718-df3d-451b-808f-bb9daab2e5b2.svg \
  'Clenched fist solo b018' f9cc745f-989b-5241-9fd0-090475a8c137 'pictographic-primitives/other/hand fist bump_f9cc745f-989b-5241-9fd0-090475a8c137.svg' \
  'Clock with clockwise return arrow' 4ae0f802-0947-49ab-948b-a13314a05022 'pictographic-primitives/_uncategorized_34/snooze return repeat_4ae0f802-0947-49ab-948b-a13314a05022.svg' \
  'Clock with counterclockwise arrival arrow' 7420a5ad-20b8-4125-a020-7f6c31b74aac 'pictographic-primitives/_uncategorized_34/shipping logistic estimate time arrival 1_7420a5ad-20b8-4125-a020-7f6c31b74aac.svg' \
  'Closed fitness band with two display marks' 1cd0692c-3506-4df2-80d7-66be18de3019 'pictographic-primitives/devices/wearable smart watch_1cd0692c-3506-4df2-80d7-66be18de3019.svg' \
  'Cloud with moon and lightning' 7eb10cf4-5263-45f8-929d-49906b04ace0 'pictographic-primitives/_uncategorized_40/weather night snow thunder_7eb10cf4-5263-45f8-929d-49906b04ace0.svg' \
  'Clove bud with pointed sepals' 2fe3535b-ed46-49bc-ad15-b91d93556dfe pictographic-primitives/_uncategorized_11/cloves_2fe3535b-ed46-49bc-ad15-b91d93556dfe.svg \
  'Clustered marionberry with pointed leaf' cd0fd2f9-cb2d-40e6-8f25-806b358d94e5 pictographic-primitives/_uncategorized_26/marionberry_cd0fd2f9-cb2d-40e6-8f25-806b358d94e5.svg \
  'Coin passing between two hands' 9ce7b101-f5f3-42dc-8957-ebdb317cac31 'pictographic-primitives/_uncategorized_06/begging hands give coin_9ce7b101-f5f3-42dc-8957-ebdb317cac31.svg' \
  'Compact motor with opposing shafts' 8ca49ab1-e686-42a4-9992-7d74b12cfcf9 'pictographic-primitives/_uncategorized_16/electronics motor_8ca49ab1-e686-42a4-9992-7d74b12cfcf9.svg'
