#!/bin/bash
# Batch 33/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hands-gripping-wrists  source 6f5654b6-d336-40f6-84c1-e153d3ad1fc3
#   solo/hands-holding-clipboard  source fbccdc7f-b56b-54f5-a0fb-becef5e101fb
#   solo/hands-holding-puzzle-piece  source cafe2d4d-7c9a-454e-8b86-9c5b5f0b2b05
#   solo/hands-passing-a-heart  source 9e38bf7e-dc51-40c4-a6fe-0121c102d036
#   solo/hands-protecting-water  source e4877261-473e-44ea-bd3c-dbd7199f163e
#   solo/hands-shaping-pottery  source 20339a75-190c-4916-aca5-b1978d81d7c4
#   solo/hands-sheltering-a-baby-head  source 0b0f724c-6381-4158-9f19-2b2a426b6450
#   solo/hands-supporting-child  source de2a447f-9464-4dd2-8a82-6bf0842bf389
#   solo/hands-supporting-front-facing-car  source f7acffbb-95f3-4cdd-98e2-2243774f9339
#   solo/hands-supporting-hard-hat  source 20214d85-2a10-45f3-974e-7a15e7241f74
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hands gripping wrists' 6f5654b6-d336-40f6-84c1-e153d3ad1fc3 'pictographic-primitives/work/workflow teamwork hand lock_6f5654b6-d336-40f6-84c1-e153d3ad1fc3.svg' \
  'Hands holding clipboard' fbccdc7f-b56b-54f5-a0fb-becef5e101fb 'pictographic-primitives/work/food delivery order manage_fbccdc7f-b56b-54f5-a0fb-becef5e101fb.svg' \
  'Hands holding puzzle piece' cafe2d4d-7c9a-454e-8b86-9c5b5f0b2b05 'pictographic-primitives/programing/module hands puzzle_cafe2d4d-7c9a-454e-8b86-9c5b5f0b2b05.svg' \
  'Hands passing a heart' 9e38bf7e-dc51-40c4-a6fe-0121c102d036 'pictographic-primitives/business/donation charity hand give heart_9e38bf7e-dc51-40c4-a6fe-0121c102d036.svg' \
  'Hands protecting water' e4877261-473e-44ea-bd3c-dbd7199f163e 'pictographic-primitives/_uncategorized_40/water protection drop hold_e4877261-473e-44ea-bd3c-dbd7199f163e.svg' \
  'Hands shaping pottery' 20339a75-190c-4916-aca5-b1978d81d7c4 'pictographic-primitives/hobbies/crafts pottery_20339a75-190c-4916-aca5-b1978d81d7c4.svg' \
  'Hands sheltering a baby head' 0b0f724c-6381-4158-9f19-2b2a426b6450 'pictographic-primitives/_uncategorized_05/baby guard protect 2_0b0f724c-6381-4158-9f19-2b2a426b6450.svg' \
  'Hands supporting child' de2a447f-9464-4dd2-8a82-6bf0842bf389 'pictographic-primitives/kids/child care_de2a447f-9464-4dd2-8a82-6bf0842bf389.svg' \
  'Hands supporting front facing car' f7acffbb-95f3-4cdd-98e2-2243774f9339 'pictographic-primitives/_uncategorized_09/car insurance hands_f7acffbb-95f3-4cdd-98e2-2243774f9339.svg' \
  'Hands supporting hard hat' 20214d85-2a10-45f3-974e-7a15e7241f74 'pictographic-primitives/_uncategorized_24/labor hands action_20214d85-2a10-45f3-974e-7a15e7241f74.svg'
