#!/bin/bash
# Batch 68/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/pointed-tip-screwdriver  source 48cac8d0-29e6-5bf5-b555-82d52e4397eb
#   solo/police-officer-with-sunglasses-and-pocket  source d0e6dfff-a50a-4157-9cf6-1c2c63ff4cb0
#   solo/policewoman-in-peaked-cap  source fb067a8c-54e2-4cbd-9e43-72f83da66905
#   solo/policewoman-with-circular-cap-badge  source 4bd11fea-9076-4103-9fb2-9403c23d0d9b
#   solo/policewoman-with-round-glasses  source 6b34cbad-4ecd-49c6-8fa7-dde6ddbf9011
#   solo/policewoman-with-rounded-helmet  source 1c9b753f-2008-485b-b32d-95627b609d40
#   solo/policewoman-with-separate-peaked-cap  source bc5c15be-c514-4fc5-b39e-59a22e4eaab4
#   solo/pomegranate-crown-inner-stem  source 0433d43c-dfba-5532-ba7b-627be6c3113b
#   solo/pomelo-with-single-leaf  source f3960946-7472-4368-97d7-b7f1d979eed7
#   solo/pongal-rice-bowl  source bbaec925-1c14-4836-aff1-d01eb58f3463
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Pointed tip screwdriver' 48cac8d0-29e6-5bf5-b555-82d52e4397eb 'pictographic-primitives/tools/tools screwdriver_48cac8d0-29e6-5bf5-b555-82d52e4397eb.svg' \
  'Police officer with sunglasses and pocket' d0e6dfff-a50a-4157-9cf6-1c2c63ff4cb0 'pictographic-primitives/avatars/police man_d0e6dfff-a50a-4157-9cf6-1c2c63ff4cb0.svg' \
  'Policewoman in peaked cap' fb067a8c-54e2-4cbd-9e43-72f83da66905 'pictographic-primitives/avatars/police woman_fb067a8c-54e2-4cbd-9e43-72f83da66905.svg' \
  'Policewoman with circular cap badge' 4bd11fea-9076-4103-9fb2-9403c23d0d9b 'pictographic-primitives/avatars/police woman_4bd11fea-9076-4103-9fb2-9403c23d0d9b.svg' \
  'Policewoman with round glasses' 6b34cbad-4ecd-49c6-8fa7-dde6ddbf9011 'pictographic-primitives/avatars/police woman_6b34cbad-4ecd-49c6-8fa7-dde6ddbf9011.svg' \
  'Policewoman with rounded helmet' 1c9b753f-2008-485b-b32d-95627b609d40 'pictographic-primitives/avatars/police woman_1c9b753f-2008-485b-b32d-95627b609d40.svg' \
  'Policewoman with separate peaked cap' bc5c15be-c514-4fc5-b39e-59a22e4eaab4 'pictographic-primitives/avatars/police woman_bc5c15be-c514-4fc5-b39e-59a22e4eaab4.svg' \
  'Pomegranate crown inner stem' 0433d43c-dfba-5532-ba7b-627be6c3113b pictographic-primitives/food/pomegranate_0433d43c-dfba-5532-ba7b-627be6c3113b.svg \
  'Pomelo with single leaf' f3960946-7472-4368-97d7-b7f1d979eed7 pictographic-primitives/_uncategorized_31/pomelo_f3960946-7472-4368-97d7-b7f1d979eed7.svg \
  'Pongal Rice Bowl' bbaec925-1c14-4836-aff1-d01eb58f3463 pictographic-primitives/holidays/pongal_bbaec925-1c14-4836-aff1-d01eb58f3463.svg
