#!/bin/bash
# Batch 47/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/jaguar  source 2b294370-a335-445e-8511-74cc786c6a8b
#   solo/japanese-woman-avatar  source d8f7770b-d9fb-48cc-9814-dcf0af46b402
#   solo/javelin-thrower  source b1834755-7ac4-419d-9946-381d945149e1
#   solo/jeans-with-front-pockets  source 1e2712a5-c98b-5804-829c-d642a1658577
#   solo/jellyfish-group  source c9bdc48d-a72f-41ce-9b7a-6a465d1111ed
#   solo/jet-ski-rider-jumping-a-wave  source 1f4f73c6-0617-4a56-8e0e-463dcef59a3a
#   solo/judge-gavel-above-small-sound-block  source e6835953-23ed-4f5c-913e-f32e21b6a5c4
#   solo/judge-man  source e8fb8e23-2308-4fdf-ac4b-d8a8d044a6df
#   solo/judge-with-gavel  source 1a5b7cc4-9e67-503a-9bf6-f1cf9ac354ce
#   solo/judge-woman-1-avatar  source 40b98251-aea4-4c5f-93da-0386f9de3967
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Jaguar 2b294370-a335-445e-8511-74cc786c6a8b pictographic-primitives/_uncategorized_23/jaguar_2b294370-a335-445e-8511-74cc786c6a8b.svg \
  'Japanese woman avatar' d8f7770b-d9fb-48cc-9814-dcf0af46b402 'pictographic-primitives/avatars/japanese woman_d8f7770b-d9fb-48cc-9814-dcf0af46b402.svg' \
  'Javelin thrower' b1834755-7ac4-419d-9946-381d945149e1 'pictographic-primitives/sports/javelin throwing_b1834755-7ac4-419d-9946-381d945149e1.svg' \
  'Jeans with front pockets' 1e2712a5-c98b-5804-829c-d642a1658577 'pictographic-primitives/clothes/trousers jeans_1e2712a5-c98b-5804-829c-d642a1658577.svg' \
  'Jellyfish group' c9bdc48d-a72f-41ce-9b7a-6a465d1111ed 'pictographic-primitives/animals/jellyfish group_c9bdc48d-a72f-41ce-9b7a-6a465d1111ed.svg' \
  'Jet ski rider jumping a wave' 1f4f73c6-0617-4a56-8e0e-463dcef59a3a 'pictographic-primitives/recreation/sport jet skiing_1f4f73c6-0617-4a56-8e0e-463dcef59a3a.svg' \
  'Judge gavel above small sound block' e6835953-23ed-4f5c-913e-f32e21b6a5c4 pictographic-primitives/_uncategorized_26/mallet_e6835953-23ed-4f5c-913e-f32e21b6a5c4.svg \
  'Judge man' e8fb8e23-2308-4fdf-ac4b-d8a8d044a6df 'pictographic-primitives/avatars/judge man_e8fb8e23-2308-4fdf-ac4b-d8a8d044a6df.svg' \
  'Judge with gavel' 1a5b7cc4-9e67-503a-9bf6-f1cf9ac354ce 'pictographic-primitives/crime/legal judge_1a5b7cc4-9e67-503a-9bf6-f1cf9ac354ce.svg' \
  'Judge woman 1 avatar' 40b98251-aea4-4c5f-93da-0386f9de3967 'pictographic-primitives/avatars/judge woman_40b98251-aea4-4c5f-93da-0386f9de3967.svg'
