#!/bin/bash
# Batch 29/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-presenting-identity-card  source 0369547d-4203-4fc3-ae0f-00ab63619bad
#   solo/hand-protecting-child  source 11f756c7-99de-41cd-bd1a-f337ce94637f
#   solo/hand-reaching-for-diamond  source bce3f8f6-b015-42a5-94c3-92f3bb3be306
#   solo/hand-reaching-toward-foot  source 06de442e-575d-48bb-ae42-82d8ef6c23c5
#   solo/hand-resting-on-head  source 4077c6c6-c997-4cfb-9962-ebea9a6df687
#   solo/hand-ringing-service-bell  source 03a6657e-e3c0-4963-bdc9-8955e695afe1
#   solo/hand-saw  source f9355663-65dc-4eff-a52d-6442ba084c4a
#   solo/hand-scattering-seeds  source e9cb7e9f-46ac-4f88-9323-6d03d60104e6
#   solo/hand-scrubbing-with-brush  source ae7b2f22-759d-4da2-b10b-25f4390e7bda
#   solo/hand-stealing-identity-card-solo-b005-06  source 3ba267b5-9ca9-4999-a24d-b73d45e0c937
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand presenting identity card' 0369547d-4203-4fc3-ae0f-00ab63619bad 'pictographic-primitives/_uncategorized_08/business card hand 1_0369547d-4203-4fc3-ae0f-00ab63619bad.svg' \
  'Hand protecting child' 11f756c7-99de-41cd-bd1a-f337ce94637f 'pictographic-primitives/_uncategorized_24/kids care 1_11f756c7-99de-41cd-bd1a-f337ce94637f.svg' \
  'Hand reaching for diamond' bce3f8f6-b015-42a5-94c3-92f3bb3be306 'pictographic-primitives/finance/diamond hold_bce3f8f6-b015-42a5-94c3-92f3bb3be306.svg' \
  'Hand reaching toward foot' 06de442e-575d-48bb-ae42-82d8ef6c23c5 'pictographic-primitives/holidays/guru purnima hand_06de442e-575d-48bb-ae42-82d8ef6c23c5.svg' \
  'Hand resting on head' 4077c6c6-c997-4cfb-9962-ebea9a6df687 pictographic-primitives/_uncategorized_30/pat_4077c6c6-c997-4cfb-9962-ebea9a6df687.svg \
  'Hand Ringing Service Bell' 03a6657e-e3c0-4963-bdc9-8955e695afe1 'pictographic-primitives/hotels/reception bell call_03a6657e-e3c0-4963-bdc9-8955e695afe1.svg' \
  'Hand saw' f9355663-65dc-4eff-a52d-6442ba084c4a pictographic-primitives/symbol/saw_f9355663-65dc-4eff-a52d-6442ba084c4a.svg \
  'Hand scattering seeds' e9cb7e9f-46ac-4f88-9323-6d03d60104e6 'pictographic-primitives/farming/seed hand_e9cb7e9f-46ac-4f88-9323-6d03d60104e6.svg' \
  'Hand scrubbing with brush' ae7b2f22-759d-4da2-b10b-25f4390e7bda 'pictographic-primitives/wayfinding/hand brush bubble_ae7b2f22-759d-4da2-b10b-25f4390e7bda.svg' \
  'Hand stealing identity card solo b005 06' 3ba267b5-9ca9-4999-a24d-b73d45e0c937 'pictographic-primitives/crime/identity stolen id card_3ba267b5-9ca9-4999-a24d-b73d45e0c937.svg'
