#!/bin/bash
# Batch 15/94: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/diver-beside-marker-buoy  source 05eae23b-b81d-5ba9-a08b-414daf65ebe4
#   solo/diving-block-weight  source 284b7c04-e252-4531-868f-398d3ef94159
#   solo/dizzy-face-with-spiral-eyes-solo  source aa0c1f8e-f7ca-4bf9-adf6-7f6f74e5b90a
#   solo/dizzy-hypnotized-face-solo  source cf969d29-b35a-425d-bec1-f3067a6600b5
#   solo/document-with-bar-chart  source d48f86f5-12a6-47ce-a5d0-968db65faf5e
#   solo/dog-walker-carrying-hanging-bag  source a86e5b3d-1f7e-4696-be14-0fe51cbed365
#   solo/domed-observatory  source af83b2d3-a6c8-48f0-bf59-777e2e438dbf
#   solo/donkey-pinata-banded-body  source e0d1f866-a25b-58b5-b0e5-584d69347eff
#   solo/downward-reflection-diagram  source 80d9152e-7c3d-4bfe-8c06-1a9d8b17db38
#   solo/drag-gesture-in-all-directions  source fdd66e1b-0160-4f60-bbe1-7da952783381
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Diver beside marker buoy' 05eae23b-b81d-5ba9-a08b-414daf65ebe4 'pictographic-primitives/recreation/diving scuba free diving buoy flag hold_05eae23b-b81d-5ba9-a08b-414daf65ebe4.svg' \
  'Diving block weight' 284b7c04-e252-4531-868f-398d3ef94159 'pictographic-primitives/recreation/diving block weight_284b7c04-e252-4531-868f-398d3ef94159.svg' \
  'Dizzy face with spiral eyes solo' aa0c1f8e-f7ca-4bf9-adf6-7f6f74e5b90a 'pictographic-primitives/_uncategorized_17/face dizzy_aa0c1f8e-f7ca-4bf9-adf6-7f6f74e5b90a.svg' \
  'Dizzy hypnotized face solo' cf969d29-b35a-425d-bec1-f3067a6600b5 'pictographic-primitives/_uncategorized_18/face spiral eyes_cf969d29-b35a-425d-bec1-f3067a6600b5.svg' \
  'Document with bar chart' d48f86f5-12a6-47ce-a5d0-968db65faf5e 'pictographic-primitives/other/file data bars_d48f86f5-12a6-47ce-a5d0-968db65faf5e.svg' \
  'Dog walker carrying hanging bag' a86e5b3d-1f7e-4696-be14-0fe51cbed365 'pictographic-primitives/_uncategorized_15/dog poop clean_a86e5b3d-1f7e-4696-be14-0fe51cbed365.svg' \
  'Domed observatory' af83b2d3-a6c8-48f0-bf59-777e2e438dbf pictographic-primitives/_uncategorized_28/observatory_af83b2d3-a6c8-48f0-bf59-777e2e438dbf.svg \
  'Donkey pinata banded body' e0d1f866-a25b-58b5-b0e5-584d69347eff pictographic-primitives/events/pinata_e0d1f866-a25b-58b5-b0e5-584d69347eff.svg \
  'Downward reflection diagram' 80d9152e-7c3d-4bfe-8c06-1a9d8b17db38 'pictographic-primitives/interface-essential/reflect down_80d9152e-7c3d-4bfe-8c06-1a9d8b17db38.svg' \
  'Drag gesture in all directions' fdd66e1b-0160-4f60-bbe1-7da952783381 'pictographic-primitives/_uncategorized_20/gesture tap all direction_fdd66e1b-0160-4f60-bbe1-7da952783381.svg'
