SOURCE_ICON_ID=None
SOURCE_PATH='icon_set/work/fix-batch-20260929T094854Z/claims.json'
AUTHOR='gpt-6'

REASONS={
0:'Retain the complete drone-and-operator composition, twin rotors and landing gear. Compact assembly contacts and controller spacing are intentional. The operator head-to-shoulder gap is exactly 8 centerline units (4 ink); the optical envelope stays inside the 48px canvas.',
1:'A recognizable handset needs its speaker and home dot in addition to the woman portrait. Compact hair/face/shoulder contacts and spacing within the phone are visually clear at 48px in both themes.',
2:'Retain two wireless arcs, a closed handset and the euro. The lower bezel was removed to give the currency mark readable negative space; compact nested-symbol spacing is accepted after native-size review.',
3:'The plus remains visibly detached from its circular badge, correcting the former crosshair. The 2px inner clearance and compact badge-to-phone spacing preserve the complete circle-add composition.',
4:'Use a slightly larger optical monitor envelope to retain a clearly open shackle above a separate padlock body. The lock and frame remain visibly separated; 48px canvas and 4px strokes are unchanged.',
5:'Preserve two wireless arcs, a headband, two outlined earcups and a boom microphone. Compact 3px earcup openings and signal spacing remain readable at native size.',
6:'The V antennae, mechanical eyes, cheek armor and side housings identify this robot head. Compact facial openings and assembly contacts are intentional and visually distinct at 48px.',
7:'Preserve the reference lion muzzle, open mouth, curved mane and fish-body collar. Organic mouth/contour spacing and small openings are accepted for this recognizable Merlion silhouette.',
8:'Retain six directional curling snakes around a circular face. Small coil openings and hair/face contacts are intentional; reducing to straight stems would lose Medusa meaning.',
9:'The diagonal RAM requires two separate outlined chips and an inset side notch. Native review confirms the chip openings and board gaps remain visible; compact diagonal clearances are retained.',
10:'Retain the globe meridians and side arcs together with a capsule microphone, yoke and stand. Compact globe/microphone spacing preserves both components on the 48px canvas.',
11:'Preserve the distinct headlamp, broad helmet brim, circular jaw and flared hair. Close headwear/hair contacts and small lamp opening are intentional in this portrait.',
12:'Preserve the reference lion muzzle, open mouth, curved mane and fish-body collar. Organic mouth/contour spacing and small openings are accepted for this recognizable Merlion silhouette.',
14:'Keep the recognizable euro with two crossbars inside the phone. The crossbars have a 1px visible gap; native light/dark inspection confirms both and the open C remain legible.',
15:'Preserve both open spanner jaws and a diagonal shaft inside the phone. Compact jaw clearance and real shaft/jaw contacts are intentional. The wider handset uses the VRECT_L optical envelope rather than the earlier VRECT_M declaration.',
16:'Keep the complete small child inside the maternal silhouette. Its head is a 4px solid dot and its visible head-to-torso gap is 2px, accepted explicitly for this miniature nested figure; arms and legs remain separate from the outer dress.',
17:'Keep the phone frame/home control and recognizable scalloped shop awning. Compact scallop openings and shop/frame spacing are intentional and readable at 48px.',
18:'Keep two wireless arcs, a closed handset and an unmistakable pound with curved top, crossbar and baseline. The crowded bezel was omitted; compact currency spacing remains readable.',
19:'Preserve the enclosing maternal body, baby head, diagonal baby body and supporting arm. Close anatomical contacts in the nursing/cradling pose are intentional; the two heads and supported baby remain clearly distinguishable.',
}
OMISSIONS={
0:'Fine controller buttons and fingers reduced to one clear controller stroke. Both rotors and landing supports retained.',
1:'Face features and collar detail omitted to make room for the phone speaker and home control.',
2:'Bottom bezel omitted to enlarge the euro; one crossbar follows the original reference.',
3:'No defining feature omitted; plus detached from circle.',
4:'No defining feature omitted; padlock body and open shackle restored.',
5:'Meeting torso omitted as in the rejected simplification; headset, earcups, microphone and wireless arcs retained.',
6:'Fine mechanical panel lines reduced to angular eyes, cheek armor, chin and side housings.',
7:'Fine animal anatomy omitted; muzzle, mane and fish-body collar retained.',
8:'Snake eyes/tongues omitted; six directionally curled snakes retained.',
9:'No defining chip or notch omitted. Contact pins were not added because the reference does not show them.',
10:'Lower globe latitude detail omitted where the foreground microphone occupies it.',
11:'Facial features omitted as in the original. Headlamp, helmet, jaw and flared hair retained.',
12:'Fine animal anatomy omitted; muzzle, mane and fish-body collar retained.',
13:'Tablet outline interrupted only behind the overlapping phone; both bottom bezels retained.',
14:'No currency feature omitted; two crossbars used for conventional euro recognition.',
15:'Wrench end outlines simplified to two open circular jaws and one diagonal shaft.',
16:'Child outlined head reduced to a solid 4px dot; complete torso, arms and legs retained. Fine maternal hair detail reduced to two tips.',
17:'Four awning scallops reduced to three; phone home control and shop window retained.',
18:'Bottom bezel omitted to enlarge the pound sign; top curve, crossbar and baseline retained.',
19:'Fine hand detail omitted; enclosing maternal body and supported baby retained.',
}
REFS={
0:'Claimed original; shared human_ref/user.svg and full_body_ref.png. Lucide drone original/atomic-debug informs paired rotor construction; front-view layout follows source.',
1:'Claimed original; Lucide smartphone original/atomic-debug for rounded phone and home control; shared human reference for circular portrait anatomy.',
2:'Claimed original; Lucide smartphone original/atomic-debug for closed rounded handset. Currency hand-authored.',
3:'Claimed original; Lucide smartphone original/atomic-debug for handset. Plus and circular badge share an axis.',
4:'Claimed original; Lucide lock-open original/atomic-debug for separate rectangular body and raised open shackle.',
5:'Claimed original; Lucide headset original/atomic-debug for headband, earcups and boom microphone.',
9:'Claimed original controls the diagonal board and chip arrangement. Lucide memory-stick original/atomic-debug informs compact board construction, without importing its different pin arrangement.',
11:'Claimed original; shared human reference for circular jaw/head construction. No useful Lucide match for the miner portrait.',
13:'Claimed original; Lucide smartphone original/atomic-debug for paired rounded devices.',
14:'Claimed original; Lucide smartphone original/atomic-debug. Euro letterform hand-authored.',
15:'Claimed original; Lucide smartphone original/atomic-debug. Diagonal spanner reconstructed from source.',
16:'Claimed original; shared human_ref/user.svg and full_body_ref.png. Nested child uses an explicitly documented miniature-figure spacing exception.',
17:'Claimed original; Lucide smartphone original/atomic-debug for clear handset identity.',
18:'Claimed original; Lucide smartphone original/atomic-debug. Pound letterform hand-authored.',
19:'Claimed original; shared human_ref/user.svg and full_body_ref.png for round heads and coherent curved limbs. Close contacts preserve the source cradling pose.',
}
