from author import make
make(1,'VRECT_L','Rejected rider had an undersized head and rigid boxed torso. Enlarge head, curve the rider into the wheel, soften the handlebar and preserve two speed strokes. Omit smallest speed mark.','''
circle('head',30,9,5)
path('torso',(30,22),[('C',(28,30),(30,25),(29,28))])
path('arm',(30,22),[('L',(36,22)),('A',(40,26),4,4,True),('L',(35,37))])
circle('wheel',28,37,7)
join('torso','arm');join('torso','wheel');join('arm','wheel')
line('speed-top',(8,17),(18,17));line('speed-bottom',(8,25),(16,25))
self.mark_human_figure('rider',head='head',torso='torso-0',torso_junction='start')
''','human_ref/full_body_ref.png; circular head radius5, lower edge14, torso starts22: exact 4 ink gap.')
make(2,'HRECT_L','Rejected machine looked like a narrow cabinet with two dots. Widen the vending face, add a distinct product window and delivery compartment, and soften the reaching arm.','''
circle('head',9,13,5)
line('torso',(9,26),(9,32));poly('legs',(4,40),(9,32),(14,40))
path('arm',(9,26),[('L',(17,30)),('L',(24,30))])
path('machine',(24,30),[('L',(24,11)),('A',(27,8),3,3,True),('L',(41,8)),('A',(44,11),3,3,True),('L',(44,37)),('A',(41,40),3,3,True),('L',(27,40)),('A',(24,37),3,3,True),('L',(24,30))],True)
line('shelf',(24,30),(44,30))
circle('product',34,18,2)
join('torso','legs');join('torso','arm');join('arm','machine');join('shelf','machine');join('shelf','arm')
self.mark_human_figure('person',head='head',torso='torso',torso_junction='start')
''','human_ref/full_body_ref.png: head radius5 and torso26 give exact4 ink gap; rounded rectangular machine.')
make(3,'VRECT_L','Rejected reading figure had a small book and an artificial shoulder loop. Raise and enlarge the open newspaper around the reader, with a shared central fold; omit text too small for clean spacing.','''
circle('head',24,10,6)
poly('paper',(8,24),(24,28),(40,24),(40,40),(24,44),(8,40),closed=True)
line('fold',(24,28),(24,44));join('fold','paper')
''','human_ref/user.svg and Lucide newspaper: broad two-page paper; head bottom16 and nearest page at24 preserve clearance.')
make(4,'SQUARE','Rejected lifter held a horizontal weight with a rigid right-angle arm. Restore the diagonal dumbbell, bent elbow and lunging legs.','''
circle('head',14,11,5)
line('torso',(14,24),(14,32))
poly('left-arm',(14,24),(6,28),(6,32));join('torso','left-arm')
poly('right-arm',(14,24),(26,30),(36,20));join('torso','right-arm')
poly('legs',(6,42),(14,32),(26,34),(26,42));join('torso','legs')
line('bar',(30,14),(36,20));line('bar-b',(36,20),(42,26))
line('weight-a',(26,18),(34,10));line('weight-b',(38,30),(46,22))
join('bar','bar-b');join('right-arm','bar');join('right-arm','bar-b');join('bar','weight-a');join('bar-b','weight-b')
self.mark_human_figure('person',head='head',torso='torso',torso_junction='start')
''','human_ref/full_body_ref.png; reference diagonal dumbbell and lunge. Head radius5 at14,11 torso24 exact4 gap.')
make(5,'VRECT_L','Rejected sling was a symmetric triangle detached from a natural arm. Restore a diagonal head bandage and an asymmetric sling across the torso with an elbow on the left.','''
circle('head',24,12,8)
line('bandage',(17,16),(31,8));join('head','bandage')
path('shoulders',(8,44),[('L',(8,40)),('A',(24,24),16,16,True),('A',(40,40),16,16,True),('L',(40,44))])
join('head','shoulders')
poly('sling',(24,24),(32,44),(16,44));join('sling','shoulders')
path('arm',(8,36),[('L',(8,40)),('A',(12,44),4,4,False),('L',(16,44))]);join('arm','shoulders');join('arm','sling')
''','human_ref/user.svg circular jaw/shoulders, head bottom20 and shoulder top24 touching ink.',extra='    human_construction = "bust"')
