from pathlib import Path
import json
P=Path(__file__).parent;D={int(k):v for k,v in json.loads((P/'solo-drafts.json').read_text()).items()};F={}
def c(n,f,d):return dict(name=n,family=f,description=d)
def add(i,n,kind,desc,reason,cs,pos=None,q=None):
 D[i]=dict(index=i,concept=n,icon_id='review-source-'+str(i),family='solo',description=desc,tags=['reference','review','components','source','draft','handoff'])
 F[i]=dict(classification=kind,reason=reason,components=cs,modifier_position=pos,uncertainty=q)
frame=c('Rounded Square Frame','container','An empty square enclosure with rounded corners. Exclude the enclosed person or check mark.')
add(1,'Person in Rounded Square','container_combination','A plain round-headed person with short sleeve lines stands within a rounded square.','The outer square surrounds a separately recognizable person rather than forming part of the body.',[frame,c('Round-Headed Person Bust','sub','A plain circular head sits above a broad torso with rounded shoulders and two short sleeve seams. Exclude the square enclosure.')])
add(9,'Check in Rounded Square','container_combination','A check with a long rising right arm sits within a rounded square.','The check is a separate status glyph hosted by an empty square enclosure.',[frame,c('Open Check Mark','sub','A check has a short descending left arm and a longer rising right arm. Exclude the rounded square enclosure.')])
add(18,'Speech Bubble with Diagonal Slash','container_combination','A rounded speech bubble with a lower-right tail contains a rising diagonal slash.','The slash is an independent content mark inside the bubble, not a seam or structural feature.',[c('Speech Bubble with Lower-Right Tail','container','A rounded rectangular speech bubble has a pointed tail projecting downward near the right side. Leave the interior blank and exclude the slash.'),c('Rising Diagonal Slash','sub','A straight diagonal stroke rises from lower left to upper right. Exclude the speech bubble and its tail.')])
add(20,'Scissors beside Partial Crossed-Circle Mark','uncertain','Closed scissors stand upright beside an incomplete circular arc joined to a diagonal cross at upper right.','The scissors are recognizable, but the detached arc-and-cross may be a partial female symbol or another diagram; the render does not establish a complete modifier.',[c('Closed Upright Scissors','solo','Two round finger loops sit beneath closed pointed blades, with one diagonal blade seam. Exclude the detached curved arc and cross.'),c('Unresolved Arc-and-Cross Draft','sub','A partial circular arc opens toward the lower left and joins a diagonal stem ending in a cross at upper right. Preserve this visible arrangement as a review draft; exclude the scissors and hold generation until the symbol is identified.')],'above and right of scissors','Is the arc-and-cross an incomplete female symbol accompanying a procedure, or a separate abstract mark? Confirm its identity and intended complete shape before generation.')
for i,hair in [(23,'long straight hair'),(24,'short bobbed hair')]:
 add(i,'Woman with '+hair.title()+' and Empty Circle','uncertain','A front-facing woman with '+hair+' has a blank circle overlapping the lower-right side of her torso.','The circle sits in a badge-like corner position, but no interior mark, arm or attachment establishes whether it is a modifier or a held round object.',[c('Woman with '+hair.title(),'solo','A front-facing woman with '+hair+' has a blank face and curved shoulders above a plain torso. Exclude the overlapping empty circle.'),c('Empty Circular Element','sub','A plain circular outline overlaps the source figure at lower right. Isolate the visible circle and exclude the figure; its badge-versus-object role remains unresolved.')],'lower right, overlapping the torso','Is the circle an empty status badge or an object held beside the figure? No interior detail resolves its meaning; review before generation.')
assert set(D)==set(range(34));(P/'held-indices.json').write_text(json.dumps(sorted(F)));(P/'drafts.json').write_text(json.dumps([D[i] for i in range(34)],indent=2)+'\n');(P/'flagged.json').write_text(json.dumps(F,indent=2)+'\n')
s=(P.parent/'todo-solo-briefs-100-20260920-batch17/package_briefs.py').read_text();s=s.replace('assert len(manifests)==100','assert len(manifests)==28').replace('[0,1,20,24,40,47,48,55,56,65,66,76,95,97,98,118,129,135,153,158,162]','[8,15,16,26]').replace('[21,22,79,80,81,91,92,101,102,103,117,121,122,123,125,126]','[]');(P/'package_briefs.py').write_text(s)
