from pathlib import Path
import json,shutil,cairosvg,sys
ROOT=Path(__file__).resolve().parent;REPO=ROOT.parents[2]
sys.path.insert(0,str(REPO))
rows=json.loads((ROOT/'batch.json').read_text())
omissions=['Both unequal wind strokes retained.', 'Wind sweeps reduced to one curl; two rounded drops retained.', 'Fine bottle details omitted; neck, rounded base, bowl and stem retained.', 'Inner face, tongue and fine feather divisions omitted; paired curved wings, rounded mane and central nose retained.', 'Tiny eyes and secondary feather tiers omitted; narrow pole and broad wings retained.', 'Fine mane scallops, eye and distant legs omitted; wing, tail, muzzle and stepping feet retained.', 'Tooth count reduced to three inner teeth plus the upper and lower ends; rounded spine retained.', 'Tiny smile and ears omitted to keep the eye and wink separated within the face.', 'Plug surface markings omitted; large looping cord, USB plug and scroll wheel retained.', 'Tiny lightning bolt and earbud speaker marks omitted to preserve open stems and case interior.', 'Tiny lightning bolt and earbud speaker marks omitted to preserve open stems and case interior.', 'Fine collar and ears omitted; blank face, bun, swept fringe and shoulders retained.', 'Tiny eyes, smile and collar omitted; rounded bun, swept hair and shoulders retained.', 'Fine fringe, ears and collar omitted; compact round lenses, bridge and bun retained. Lenses read as solid at native size.', 'Fine neck and blouse outline omitted; circular cheeks, swept part, side hair and broad shoulders retained.', 'Fine fringe, ears and neck omitted; bun, round jaw and diagonal garment fold retained.', 'Swept fringe and flared hair ends simplified; long side hair, round face and separate mask edge retained.', 'Roller circles and box tape omitted to keep the narrow conveyor opening clear; curved shoulders and package retained.', 'Fine chair, hand and keyboard omitted; roof, seated figure and sloped laptop retained.', 'Fine neck omitted; swept fringe, turned-out bob ends and closed rounded blouse retained.']
reviews=['Two unequal strokes have closer spacing matching the source; both read cleanly in light and dark.', 'Rounded water drops and the curled wind mark remain separate at 48 px.', 'Rounded bottle base and wider stemmed bowl remain distinct.', 'Mirrored curved wings replace the rabbitlike angular points; simplified rounded mane and nose remain open.', 'Narrow tall pole and broad horizontal wings reproduce the totem proportions.', 'Swept wing, right-facing rounded head, tail and stepping feet remain readable.', 'Rounded spine and uniformly spaced teeth read as a styling comb.', 'Bowed brim, broad crown and wink read clearly; face has room around both eyes.', 'Large loop, outlined plug and capsule mouse remain distinct at native size.', 'Opposed bulbous earbuds and full stems remain open above the rounded case.', 'Opposed bulbous earbuds and full stems remain open above the rounded case.', 'Rounded bun, swept fringe and broad shoulders read as a blank-faced portrait.', 'Bun and parted hair remain distinct; circular jaw touches curved shoulders.', 'Round glasses and bridge are isolated from the cheeks; compact lenses read as solid in both themes.', 'Asymmetric fringe, long sides and curved cheeks preserve the side-parted portrait.', 'Rounded bun and a diagonal fold distinguish the draped garment at native size.', 'Horizontal mask edge divides the round face; long hair encloses it without a central hanging bar.', 'Rounded shoulders, outlined box and separate slim conveyor read distinctly; outlined head has exact 4 px ink clearance to shoulders.', 'Roof, circular head, curved seated shoulders and sloping laptop remain distinct.', 'Turned-out bob ends and closed blouse preserve the original silhouette in both themes.']
for i,r in enumerate(rows,1):
 m=json.loads((ROOT/f'latest-{i}.json').read_text());out=REPO/m['result_dir']
 assert m['validation_status']=='valid' and not m['errors'] and not m['warnings']
 assert m['build_gate']['status']=='pass' and not m['build_gate']['errors'] and not m['build_gate']['warnings']
 h=json.loads((ROOT/(r['key'].replace('/','__')+'.history.json')).read_text())
 from icon_set.scripts.work_queue import disapproval_count
 assert disapproval_count(h)==1
 for label,src in [('reference',REPO/r['reference']),('before',REPO/r['claim_dir']/'before'/(r['icon_id']+'.svg'))]:
  shutil.copyfile(src,out/(label+'.svg'))
  for size in (48,384):
   cairosvg.svg2png(url=str(src),write_to=str(out/f'{label}-{size}.png'),output_width=size,output_height=size,background_color='white')
 m.update(omissions=omissions[i-1],visual_review={'native_light':True,'native_dark':True,'enlarged_light':True,'enlarged_dark':True,'findings':reviews[i-1]},disapprovals_at_claim=1)
 m['keyshape_reason']={'SQUARE':'Square envelope balances the complete subject and its surrounding whitespace.','VRECT_L':'Tall envelope preserves the upright subject with room for internal detail.','HRECT_L':'Wide envelope preserves the landscape silhouette.','HRECT_M':'Compact horizontal envelope keeps the control and side marks together.','VRECT_M':'Narrow upright envelope preserves the comb proportions.','CIRCLE':'Radial envelope preserves the naturally shallow two-line mark.'}[m['keyshape']]
 m['artifacts']=[p.name for p in out.iterdir() if p.is_file() and p.name not in ('result.json','candidate.json')]
 (out/f"{r['icon_id']}.metadata.json").write_text(json.dumps(m,indent=2)+'\n')
 (ROOT/f'latest-{i}.json').write_text(json.dumps(m,indent=2)+'\n')
 (out/'result.json').write_text(json.dumps(m,indent=2)+'\n')
print('20/20 final runs: valid, full gate pass, zero errors/warnings, visual review complete, histories exactly one disapproval.')
