reasons={
3:'Preserve the source tall isometric cube and three equal readable faces. Its ink extends 2px above and below the square keyshape, while remaining 2px inside the canvas. All spacing checks pass.',
4:'Preserve the hand gripping the document with a curved thumb and two text strokes. Removed the thumb/text collision. The two text lines and page bottom have deliberate 2px clear gaps; the hand contour has about 1.76px local clearance and the thumb has about 3.07px. Each remains visually separate at 48px. Natural composition stays 2px inside the canvas.',
5:'Preserve the reference shallow rising hill. Its natural height is 4px less than the horizontal keyshape envelope; stretching it vertically would recreate the rejected steep slope. All spacing checks pass.',
6:'Preserve two distinct people, the carried box and the directing gesture. Both heads have exactly 4px visible head-to-body gap: 20-(8+4)-4=4. Box-to-body clearance is 2px, with about 1.19px beside the near leg. These remain distinct at 48px; the natural composition stays 2px inside the canvas.',
7:'Preserve the side-view monitor, complete desk and standing worker. Removed the doubled arm/table segment. All spacing checks pass, including the exact 4px detached head/body gap. Natural furniture-and-person envelope differs from the standard square keyshape while remaining within the canvas.',
8:'Preserve the pen, two document marks, complete desk and standing worker. Pen contact is intentional; the separate arm passes about 1px above the desk edge and remains visibly clear in both themes. The head/body ink gap is exactly 4px. Natural envelope remains inside the canvas.',
9:'Preserve the continuous curved chair shell, splayed legs and crossbar. The seat has a deliberate 2px open channel, readable at native size. Natural shell proportions extend slightly outside the standard keyshape but stay inside the canvas.',
10:'Preserve the seated worker, side-view monitor, full desk and restored pedestal chair. Leg-to-desk clearance is about 2.2px and remains clearly separated. Exact 4px detached head/body gap is retained; natural composition fits inside the canvas.',
11:'Preserve the laptop, seated worker, full desk and pedestal chair. The laptop-to-desk and foot-to-desk ink gaps are 2px. Both remain visibly open at 48px; the head/body gap remains exactly 4px and the natural envelope stays 2px inside the canvas.',
12:'Preserve the writing pen, document marks, full desk and pedestal chair. Seated leg-to-arm clearance is about 2.28px and leg-to-desk clearance about 2.2px, both visibly open. The detached head/body gap is exactly 4px; natural envelope stays within the canvas.',
13:'Preserve three rounded molecular lobes and clean internal Y boundaries. All spacing checks pass. Natural lobed silhouette has a 44px-wide ink envelope instead of the 40px square keyshape, remaining at least 2px inside the canvas.',
14:'Restore the hollow curved razor handle and broad blade. Widened the handle to remove its initial overlap; its remaining minimum measured internal gap is about 2.54px, while the blade has about 2.74px. Both open channels remain clear at 48px. The natural diagonal drawing stays inside the canvas.',
16:'Preserve a flowing handwritten signature with two unequal smooth arches and open troughs. The remaining local curve clearances are smaller than the general 4px gate but remain visibly open at 48px in both themes. The signature retains a uniform 4px stroke and the exact horizontal keyshape envelope.',
17:'Preserve the broad low domed cap and longer curved stem of the shiitake reference. All spacing checks pass. Natural mushroom envelope is wider and lower than the square keyshape, with all ink at least 2px inside the canvas.',
18:'Preserve the smoothly rounded triangular mushroom cap and flared stem. All spacing checks pass. The natural 44px-square ink envelope stays 2px inside the canvas; reducing the envelope would weaken the open stem.',
19:'Preserve the reference shallow falling hill. Its natural height is 4px less than the horizontal keyshape envelope; stretching it vertically would recreate the rejected steep slope. All spacing checks pass.',
20:'Preserve the round cranium, projecting nose, angry brow, curved attached mouth and open neck. Brow-to-skull clearance is about 2.94px; the short nose return has about 1.65px local clearance. Both are visually distinct. Natural profile extends 2px outside the portrait keyshape on each side but remains inside the canvas.'
}
