#!/usr/bin/env python3
"""Generate browser and documentation mirrors from core/icon_profiles.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from icon_profiles import get_profile, profile_names, source_document, token_box


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FRONTEND = ROOT / "frontend" / "js" / "icon-profiles.js"
DEFAULT_DOCS = ROOT / "docs" / "generated" / "icon-profiles.md"


def browser_source() -> str:
    payload = json.dumps(source_document(), indent=2, ensure_ascii=False)
    return (
        "'use strict';\n\n"
        "// Generated by core/generate_profile_assets.py. Do not edit by hand.\n"
        f"const ICON_PROFILES = Object.freeze({payload});\n"
    )


def markdown_source() -> str:
    lines = [
        "<!-- Generated by core/generate_profile_assets.py. Do not edit by hand. -->",
        "# Generated icon profile reference",
        "",
        "| Type | Design | Ship | Design stroke | Ship stroke | Distinct centerline distance |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name in profile_names():
        profile = get_profile(name)
        lines.append(
            f"| `{name}` | {profile['designCanvas']}×{profile['designCanvas']} | "
            f"{profile['shipCanvas']}×{profile['shipCanvas']} | "
            f"{profile['designStroke']}u | {profile['shipStroke']}px | "
            f"{profile['minimumDistinctCenterlineDistance']}u |"
        )
    lines.extend(["", "## Keyshapes", ""])
    for name in profile_names():
        profile = get_profile(name)
        lines.extend(
            [
                f"### `{name}`",
                "",
                "| Token | Shape | Painted bounds |",
                "| --- | --- | --- |",
            ]
        )
        for token in profile["keyshapes"]:
            left, top, right, bottom = token_box(token, name)
            lines.append(
                f"| `{token['name']}` | {token['shape']} | "
                f"`({left:g},{top:g})…({right:g},{bottom:g})` |"
            )
        lines.append("")
    container = get_profile("container")["containerSlot"]
    lines.extend(
        [
            "## Container slot",
            "",
            f"The canonical slot is `({container['x']},{container['y']})` with size "
            f"`{container['w']}×{container['h']}` and accepts keyshapes from the "
            f"`{container['acceptedProfile']}` profile. Container paint must leave "
            f"a centered `{container['minimumClearSquare']}×{container['minimumClearSquare']}` "
            "square inside this slot completely clear.",
            "",
        ]
    )
    return "\n".join(lines)


def sync(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        return True
    if check:
        print(f"stale generated profile asset: {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frontend", type=Path, default=DEFAULT_FRONTEND)
    parser.add_argument("--docs", type=Path, default=DEFAULT_DOCS)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = (
        sync(args.frontend, browser_source(), args.check),
        sync(args.docs, markdown_source(), args.check),
    )
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
