#!/usr/bin/env python3
"""Generate browser and documentation mirrors from core/icon_profiles.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from icon_profiles import (
    get_profile,
    profile_names,
    source_document,
    token_box,
    validate_container_slot,
)


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FRONTEND = ROOT / "frontend" / "js" / "icon-profiles.js"
DEFAULT_DOCS = ROOT / "docs" / "shared" / "icon-profiles.md"
DEFAULT_TYPE_DOCS_ROOT = ROOT / "docs"
TYPE_DOC_DIRECTORIES = {
    "normal": "icons",
    "sub": "sub-icons",
    "container": "container-icons",
}
GENERATED_NOTICE = "<!-- Generated by core/generate_profile_assets.py. Do not edit by hand. -->"


def bounds_text(bounds, scale: float = 1) -> str:
    left, top, right, bottom = (value * scale for value in bounds)
    return f"`({left:g},{top:g})…({right:g},{bottom:g})`"


def keyshape_lines(name: str) -> list[str]:
    profile = get_profile(name)
    scale = profile["shipCanvas"] / profile["designCanvas"]
    lines = [
        "| Token | Shape | Orientation | Design size | Design painted bounds | Ship painted bounds |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for token in profile["keyshapes"]:
        bounds = token_box(token, name)
        lines.append(
            f"| `{token['name']}` | {token['shape']} | {token['orientation']} | "
            f"{token['width']:g}×{token['height']:g}u | "
            f"{bounds_text(bounds)} | {bounds_text(bounds, scale)} |"
        )
    return lines


def container_slot_lines(profile: dict) -> list[str]:
    slot = profile["containerSlot"]
    scale = profile["shipCanvas"] / profile["designCanvas"]
    accepted = get_profile(slot["acceptedProfile"])
    resolved = [
        validate_container_slot(
            {"containerSlot": {**slot, "acceptedKeyshape": token["name"]}}, profile
        )
        for token in accepted["keyshapes"]
    ]
    protected = resolved[0]["protectedBounds"]
    center = resolved[0]["protectedCenter"]
    clear = slot["minimumClearSquare"]
    lines = [
        f"Accepted profile: `{slot['acceptedProfile']}`. Declare one accepted keyshape "
        "from the table below in `containerSlot.acceptedKeyshape`.",
        "",
        "| Slot property | Design | Ship |",
        "| --- | --- | --- |",
        f"| Origin | `({slot['x']:g},{slot['y']:g})`u | `({slot['x'] * scale:g},{slot['y'] * scale:g})`px |",
        f"| Size | {slot['w']:g}×{slot['h']:g}u | {slot['w'] * scale:g}×{slot['h'] * scale:g}px |",
        f"| Center | `({center['x']:g},{center['y']:g})`u | `({center['x'] * scale:g},{center['y'] * scale:g})`px |",
        f"| Minimum clear square | {clear:g}×{clear:g}u | {clear * scale:g}×{clear * scale:g}px |",
        f"| Protected bounds | {bounds_text(protected)} | {bounds_text(protected, scale)} |",
        "",
        "Container paint must leave the protected square completely clear for every accepted keyshape.",
        "",
        "| Accepted keyshape | Bounds in container design coordinates | Bounds in container ship coordinates |",
        "| --- | --- | --- |",
    ]
    for item in resolved:
        lines.append(
            f"| `{item['acceptedToken']['name']}` | "
            f"{bounds_text(item['acceptedBounds'])} | "
            f"{bounds_text(item['acceptedBounds'], scale)} |"
        )
    return lines


def type_markdown_source(name: str) -> str:
    profile = get_profile(name)
    scale = profile["shipCanvas"] / profile["designCanvas"]
    center = profile["center"]
    distance = profile["minimumDistinctCenterlineDistance"]
    lines = [
        GENERATED_NOTICE,
        f"# `{name}` icon profile",
        "",
        "Generated from [the canonical profile JSON](../../core/icon_profiles.json). "
        "All values below include resolved inheritance; edit the JSON and regenerate this file.",
        "",
        "## Canvas and stroke",
        "",
        "| Property | Design | Ship |",
        "| --- | --- | --- |",
        f"| Canvas | {profile['designCanvas']:g}×{profile['designCanvas']:g}u | {profile['shipCanvas']:g}×{profile['shipCanvas']:g}px |",
        f"| Stroke | {profile['designStroke']:g}u | {profile['shipStroke']:g}px |",
        f"| Center | `({center['x']:g},{center['y']:g})`u | `({center['x'] * scale:g},{center['y'] * scale:g})`px |",
        f"| Minimum distinct centerline distance | {distance:g}u | {distance * scale:g}px |",
        "",
        f"Design-to-ship scale: **{scale:g}×** for coordinates, dimensions, and stroke width.",
        "",
        "## Keyshapes",
        "",
        "Bounds are `(left,top)…(right,bottom)` and include stroke paint. "
        "Each token is centered on the profile center. Circle width and height equal its diameter.",
        "",
        *keyshape_lines(name),
        "",
    ]
    if "containerSlot" in profile:
        lines.extend(["## Container slot", "", *container_slot_lines(profile), ""])
    return "\n".join(lines)


def browser_source() -> str:
    payload = json.dumps(source_document(), indent=2, ensure_ascii=False)
    return (
        "'use strict';\n\n"
        "// Generated by core/generate_profile_assets.py. Do not edit by hand.\n"
        f"const ICON_PROFILES = Object.freeze({payload});\n"
    )


def markdown_source() -> str:
    lines = [
        GENERATED_NOTICE,
        "# Generated icon profile reference",
        "",
        "Generated from [the canonical profile JSON](../../core/icon_profiles.json). "
        "Each type also has a complete generated `profile.md` in its documentation folder.",
        "",
        "| Type | Design | Ship | Design stroke | Ship stroke | Distinct centerline distance |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name in profile_names():
        profile = get_profile(name)
        lines.append(
            f"| `{name}` | {profile['designCanvas']}×{profile['designCanvas']} | "
            f"{profile['shipCanvas']}×{profile['shipCanvas']} | "
            f"{profile['designStroke']}u | {profile['shipStroke']}px | "
            f"{profile['minimumDistinctCenterlineDistance']}u |"
        )
    lines.extend(["", "## Keyshapes", ""])
    for name in profile_names():
        profile = get_profile(name)
        lines.extend(
            [
                f"### `{name}`",
                "",
                "| Token | Shape | Painted bounds |",
                "| --- | --- | --- |",
            ]
        )
        for token in profile["keyshapes"]:
            lines.append(f"| `{token['name']}` | {token['shape']} | {bounds_text(token_box(token, name))} |")
        lines.append("")
    lines.extend(
        [
            "## Container slot",
            "",
            *container_slot_lines(get_profile("container")),
            "",
        ]
    )
    return "\n".join(lines)


def sync(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        return True
    if check:
        print(f"stale generated profile asset: {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frontend", type=Path, default=DEFAULT_FRONTEND)
    parser.add_argument("--docs", type=Path, default=DEFAULT_DOCS, help="aggregate Markdown reference path")
    parser.add_argument(
        "--type-docs-root", type=Path, default=DEFAULT_TYPE_DOCS_ROOT,
        help="root for icons/profile.md, sub-icons/profile.md, and container-icons/profile.md",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        sync(args.frontend, browser_source(), args.check),
        sync(args.docs, markdown_source(), args.check),
    ]
    results.extend(
        sync(args.type_docs_root / TYPE_DOC_DIRECTORIES[name] / "profile.md", type_markdown_source(name), args.check)
        for name in profile_names()
    )
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
