from pathlib import Path
import json
P=Path(__file__).parent
D={int(k):v for k,v in json.loads((P/'solo-drafts.json').read_text()).items()};F={}
def c(n,f,d):return dict(name=n,family=f,description=d)
def add(i,n,k,d,r,cs,pos=None,q=None):
 F[i]=dict(classification=k,reason=r,components=cs)
 if pos:F[i]['modifier_position']=pos
 if q:F[i]['uncertainty']=q
 D[i]=dict(index=i,concept=n,icon_id='review-source-'+str(i),family='solo',description=d,tags=['reference','review','source','outline','drawing','pending'])
def side(i,n,d,r,cs,pos):add(i,n,'side_combination',d,r,cs,pos)
def box(i,n,d,r,cs):add(i,n,'container_combination',d,r,cs)
frame=c('Rounded Square Frame','container','A blank rounded square frame. Exclude the enclosed glyph and all other marks.')
up=c('Upward Trend Arrow','sub','A rising line ends in an open arrowhead pointing upper right. Exclude the animal or other main subject.')
wireless=c('Wireless Signal Arcs','sub','Curved signal arcs expand upward from a short central arc. Exclude the robot, vehicle, or other main subject.')
heart=c('Plain Heart','sub','An upright heart with two rounded lobes and a pointed base. Exclude the surrounding enclosure or rainbow.')
add(0,'Rune-Like Inscription on Standing Stone','uncertain','An upright rounded stone contains an angular character with a vertical stem, upper triangular loop, and lower diagonal leg.','The inner mark resembles a runic letter rather than a pictorial symbol; its exact character must be identified before typeface reuse.',[c('Rounded Standing Stone','container','An upright stone with a domed top, tapering shoulders, and rounded lower corners. Exclude the inscription.'),c('Rune-Like Character','typeface','Preserve the visible upright stem, right-facing triangular upper loop, and descending lower-right leg as identification evidence. It resembles ᚱ; resolve the exact character and existing glyph ID before reuse. Do not invent replacement glyph paths.')],q='Confirm whether the inscription is ᚱ or a stylized Latin R. No preferred ᚱ glyph is present; do not substitute Latin R without resolving the source identity.')
side(5,'Bull with Rising Arrow','A bull faces left with a lowered head and long horn; an arrow rises diagonally behind its back.','The arrow extends beyond a complete bull silhouette and provides a reusable upward-trend modifier.',[c('Charging Bull Facing Left','solo','A bull faces left with its head lowered, a long curved horn, a broad arched back, and bent legs. Exclude the arrow.'),up],'upper-right, emerging behind the back')
box(7,'Scooter Beneath Pitched Roof','A scooter faces right beneath two roof slopes meeting at an apex.','The separate roof acts as an open enclosure hosting the scooter.',[c('Open Pitched Roof','container','Two roof slopes meet at a central apex with the area below open. Exclude the scooter.'),c('Scooter Profile','sub','A right-facing scooter has a rounded seat, curved rear body, low deck, upright handlebar, and two wheels. Exclude the roof.')])
side(12,'Apple with Three Down Arrows','A rounded apple with a short stem floats above three downward arrows.','The arrows are detached action marks below a complete apple, rather than physical fruit details.',[c('Apple with Curved Stem','solo','A rounded apple has shallow notches at top and bottom and a short curved stem. Exclude the arrows.'),c('Three Downward Arrows','sub','Three downward open arrows form a row, with the middle arrow reaching lower. Exclude the apple.')],'below the apple, in a row')
box(20,'Heart in Joined Gender Symbol','A heart sits inside a circle with an upper-right arrow and a lower cross attached.','The joined gender-symbol outline encloses an independent heart glyph.',[c('Joined Gender Symbol Frame','container','A circular border has an arrow projecting upper right and a short cross below. Exclude the heart.'),heart])
add(24,'Rupee Character','typeface_reuse','A rupee character has two upper horizontal strokes, a curved bowl, and a long descending diagonal leg.','The entire subject is the readable currency character ₹ and must use the existing typeface.',[c('Rupee Character','typeface','Reuse exact character ₹ with preferred glyph symbol-rupee from icon_set/typeface/glyphs.json. Preserve its natural proportions; do not draw new currency glyph geometry.')])
box(25,'Road Mark in Highway Shield','A highway shield has a scalloped upper rim, a straight header divider, and two vertical road dashes inside.','The road-center mark is separate content within the shield enclosure.',[c('Highway Shield with Header','container','A shield has two shallow upper dips, a pointed bottom, and a horizontal header divider. Exclude the road dashes.'),c('Two Vertical Road Dashes','sub','Two vertically aligned line segments, the lower longer than the upper. Exclude the shield.')])
box(27,'Left Arrow in Rounded Panel','A short left-pointing arrow sits inside a rounded square panel.','The arrow is an independent navigation symbol inside a distinct frame.',[frame,c('Left Arrow','sub','A horizontal shaft ends at an open left-facing point. Exclude the panel.')])
box(30,'Eye Within Magnifying Glass','A large round lens encloses an almond-shaped eye with a circular pupil, with a diagonal handle below right.','The eye is a separate symbol hosted in the magnifier lens.',[c('Magnifying Glass Enclosure','container','A round empty lens has a straight handle extending diagonally down-right. Exclude the eye.'),c('Almond Eye with Pupil','sub','An almond-shaped eye surrounds a round central pupil. Exclude the magnifying glass.')])
box(33,'Road Within Padlock','A padlock with a tall arched shackle contains a tapered roadway with two center dashes.','The road is independent content within the padlock body.',[c('Padlock Enclosure','container','A rounded rectangular padlock body sits beneath a tall arched shackle. Exclude the road and dashes.'),c('Tapered Road','sub','A roadway narrows upward with two short centerline dashes. Exclude the padlock.')])
box(35,'Standing Figure in Cylindrical Chamber','A simple person with outstretched arms stands within an open cylindrical chamber with curved top and bottom edges.','The figure is distinct content inside the chamber enclosure.',[c('Cylindrical Chamber','container','A broad cylinder has curved upper and lower edges, open-looking front sides, and short wall divisions. Exclude the person.'),c('Standing Figure with Spread Arms','sub','A circular head sits above a horizontal arm bar and a narrow tapered body with a waist line and two leg strokes. Exclude the chamber.')])
side(38,'Person Approaching Seat','A walking person stands left of a seat profile, with a right arrow between them.','A detached arrow supplies direction between two separately identifiable subjects; it is not a chair part or held object.',[c('Walking Person','solo','A round-headed figure walks with spread legs and one arm extended right. Exclude the seat and arrow.'),c('Seat in Side Profile','solo','A bent upright seat back joins a horizontal cushion above a separate rounded foot or base. Exclude the person and arrow.'),c('Right Arrow','sub','A short horizontal line ends in an open right-facing point. Exclude the person and chair.')],'between the person and seat, at shoulder height')
add(43,'Rainbow Above Heart','uncertain','A broad four-arc rainbow sits above a separate upright heart.','Both subjects are separate and similarly prominent; the rainbow could qualify the heart or form an equal symbolic pair.',[c('Four-Arc Rainbow','solo','Four nested semicircular arcs share a horizontal base. Exclude the heart.'),heart],q='Is the rainbow a pride qualifier applied to the heart, or are the two equal subjects of one emblem? Keep the whole reference on hold while retaining both component briefs.')
box(46,'Right Arrow in Rounded Panel','A short right-pointing arrow sits inside a rounded square panel.','The arrow is a separate symbol hosted by the panel.',[frame,c('Right Arrow','sub','A horizontal shaft ends in an open right-facing point. Exclude the panel.')])
add(47,'Flame Trails and Right Arrow','uncertain','A broad right arrow is accompanied by several wavy trails and a small leaf-shaped flame below-left.','Some curves merge toward the arrow shaft, while the lowest flame is detached; this may be an integrated flaming arrow or a direction symbol beside fire.',[c('Broad Right Arrow','sub','A right-pointing arrow has a rounded outlined head and horizontal shaft. Exclude the lower flame strokes.'),c('Wavy Flame Mark','sub','Several wavy rising bands sit above a small pointed flame shape. Exclude the arrowhead and straight shaft.')],q='Determine whether the flames form the arrow tail or independently label a fire direction. Preserve the complete draft; do not force a combined primitive.')
side(48,'Bear Face with Rising Trend','A rounded bear face sits beneath a rising zigzag arrow running toward the upper right.','The arrow is detached from the recognizable bear head and functions as an increase modifier.',[c('Bear Face','solo','A rounded bear face has two small upper ears and a broad divided muzzle at the bottom. Exclude the trend arrow.'),up],'above the head, rising rightward')
side(50,'Robot Arm with Wireless Signal','A two-jointed robot arm reaches diagonally upward to the right beneath wireless arcs.','The separate wireless arcs qualify an independently recognizable robotic arm rather than forming part of its mechanism.',[c('Articulated Robot Arm','solo','Two circular joints connect a diagonal arm segment to an upright support, ending in a short bent tool at the right. Exclude the wireless arcs.'),wireless],'upper-left, above the lower joint')
box(57,'RSS Symbol Within Rounded Tile','A dot and two expanding quarter-circle arcs sit inside a rounded tile whose upper-right corner follows a broad curve.','The RSS glyph is separate content within a tile border.',[c('RSS Tile Frame','container','A tile has rounded lower and upper-left corners and a broad curved upper-right boundary. Exclude the RSS dot and arcs.'),c('RSS Feed Mark','sub','A circular dot sits below-left of two nested quarter-circle broadcast arcs. Exclude the tile.')])
box(64,'Script S in Circle','A flowing script-like S with a small lower loop appears inside a circular border.','The visible content is a letter hosted by a circle; the source logo styling must not trigger new letter geometry.',[c('Circular Letter Frame','container','A plain circular border. Exclude the script S.'),c('Uppercase S Reuse','typeface','Reuse exact uppercase S with preferred letter-s-uppercase from icon_set/typeface/glyphs.json. Retain the source script form as reference evidence, but do not trace a new script glyph.')])
add(69,'Semicolon Character','typeface_reuse','A round dot sits above a curved comma whose tail sweeps down and left.','The subject is the readable punctuation character semicolon.',[c('Semicolon Reuse','typeface','Reuse exact ; with preferred symbol-semicolon from icon_set/typeface/glyphs.json. Preserve its stacked dot-and-comma arrangement and natural metrics; do not invent punctuation paths.')])
side(82,'Car with Wireless Arcs','A car viewed from the front has two round headlights beneath wireless arcs above its roof.','The detached arcs supply a connected-driving state to a complete car silhouette.',[c('Car Viewed from Front','solo','A car front has a sloped windshield, broad rounded body, two circular headlights, and two short tires below. Exclude the wireless arcs.'),c('Two Wireless Arcs','sub','Two shallow nested arcs curve above a shared center. Exclude the car.')],'above the roof, centered')
side(91,'Person with Search Magnifier','A round-headed person has a magnifier overlapping the lower right shoulder.','The lens covers a cleared shoulder gap and is not held by a drawn hand, supporting a search-modifier reading.',[c('Plain Person with Shoulder Outline','solo','A circular head sits above a broad torso with curved shoulders and a short left sleeve line. Complete the shoulder outline and exclude the magnifier.'),c('Search Magnifier','sub','A round blank lens has a short diagonal handle pointing lower right. Exclude the person.')],'lower-right, overlapping the shoulder')
box(100,'Merging Road Arrow in Diamond','A vertical up arrow with a diagonal branch entering from the lower right sits in a rounded diamond sign.','The road direction symbol is independent content inside a diamond enclosure.',[c('Rounded Diamond Sign','container','An empty diamond-shaped sign with softly rounded corners. Exclude the arrow.'),c('Up Arrow with Right Branch','sub','A vertical up arrow has an open point and a diagonal branch joining its shaft from lower right. Exclude the diamond.')])
side(112,'Clock with Sleep Letters','A partial round clock has two hands below two Z letters rising at the upper right.','The detached Z pair is a sleep modifier overlapping a gap in the clock perimeter.',[c('Plain Round Clock','solo','A round clock has one hand pointing left and another down-right. Complete the circumference and exclude the Z letters.'),c('Sleep Z Pair','typeface','Reuse exact text ZZ using preferred letter-z-uppercase twice from icon_set/typeface/glyphs.json. Place the second Z higher and to the right, slightly smaller; exclude the clock. Do not draw new letter paths.')],'upper-right, above the clock hands')
box(114,'Crossed-Out Dollar Coin','A dollar sign sits inside a circle crossed by a rising diagonal slash.','The currency character and negating slash are independent content and modifier within the coin border.',[c('Circular Coin Border','container','A plain circular coin border. Exclude the dollar character and diagonal slash.'),c('Dollar Character Reuse','typeface','Reuse exact $ with preferred symbol-dollar from icon_set/typeface/glyphs.json, centered within the coin. Exclude the circle and slash; do not create glyph paths.'),c('Rising Negation Slash','sub','A straight diagonal slash runs lower-left to upper-right. Exclude the dollar and coin.')])
box(121,'Fragile Parcel with Up Arrow','A rounded parcel has a notched tape strip descending from its top and separate glass and up-arrow marks on its face.','The wineglass and orientation arrow are independently readable shipping symbols hosted on the parcel.',[c('Taped Parcel Face','container','A rounded square parcel has a vertical tape strip with a notched lower end at the top center. Exclude the glass and arrow.'),c('Fragile Wineglass Mark','sub','A small stemmed glass has a narrow bowl, thin stem, and flat foot. Exclude the parcel and arrow.'),c('Up Arrow','sub','A straight upright shaft ends in an open upward point. Exclude the glass and parcel.')])
side(124,'Three People with Notification Bell','Three person busts form a group beneath a large bell with top loop and lower clapper.','The detached bell is a notification modifier above an independently recognizable people group.',[c('Three Person Busts','solo','Three round heads sit above curved shoulders, with the middle figure slightly lower and in front. Exclude the bell.'),c('Notification Bell','sub','A domed bell flares to a flat rim, with a small upper loop and lower round clapper. Exclude the people.')],'above the group, centered')
D[83]['icon_id']='shopfront-single-door-scalloped-canopy'
assert len(F)==27 and len(D)==127
existing=set(json.loads((P/'existing-ids.json').read_text()));assert not [d['icon_id'] for i,d in D.items() if i not in F and d['icon_id'] in existing]
(P/'flagged.json').write_text(json.dumps(F,indent=2)+'\n');(P/'drafts.json').write_text(json.dumps([D[i] for i in range(127)],indent=2)+'\n');(P/'solo-drafts.json').write_text(json.dumps({i:d for i,d in D.items() if i not in F},indent=2)+'\n')
print('100 solo briefs and 27 review handoffs written; IDs checked')
