from pathlib import Path
import json,re
P=Path(__file__).parent
raw='''1|Ruined Wall with Stepped Top|A ruined wall rises in uneven rectangular steps toward the right before dropping to a lower outer edge. A tall arched doorway opens at its base, and a straight ground line extends beyond both sides.|ruin,wall,arch,doorway,building,stone
2|Diagonal Two-Part Eraser|A long eraser lies diagonally from lower left to upper right, with softly rounded corners. A transverse seam divides the shorter lower section from the larger upper section of its plain body.|eraser,rubber,stationery,school,drawing,tool
3|Hooded Person with Blank Face|A front-facing person wears a pointed rounded hood framing an oval blank face. The hood narrows beneath the chin into the jacket's center seam, with curved shoulders and two short sleeve lines below.|hood,person,jacket,face,clothing,portrait
4|Bear with Open Mouth|A bear stands in right-facing profile with a broad rounded back and a small raised ear. Its snout extends over a wide open mouth, while two heavy visible legs descend beneath the body.|bear,animal,mouth,profile,wildlife,mammal
6|Microchip with Twelve Pins|A rounded square chip body surrounds a smaller square central die. Three straight pins extend from each of its four sides, giving the component a balanced outline with evenly spaced terminals.|chip,microchip,semiconductor,processor,electronics,circuit
8|Road Curving to the Right|Two broad curved road edges sweep from the lower left toward the upper right. A broken centerline follows the bend between them, with short dashed markings that flatten as the road turns.|road,curve,highway,bend,traffic,route
9|Winding Route to Round Endpoint|A single route line begins at lower left, bends upward through two smooth turns, and reaches a circular endpoint at upper right. The path is unbroken and has no arrows or intermediate markers.|route,path,endpoint,journey,curve,navigation
10|Nested Rounded Square Frame|A broad rounded square frame surrounds a smaller rounded square opening. Both boundaries are continuous and centered, with an even-looking blank border between the inner opening and outer edge.|frame,shadowbox,square,rounded,border,opening
11|Faceted Gem with Pointed Base|A faceted gemstone has a broad flat crown, sloping upper shoulders, and a sharply pointed lower tip. Triangular facets divide the crown and converge downward through the long lower portion.|gem,ruby,diamond,crystal,facet,jewel
13|Winged Envelope Taking Flight|A closed envelope has a folded triangular flap and paired curved wings attached at its sides. Three vertical motion lines extend below the envelope, with the central line longer than the outer two.|envelope,wing,mail,flight,message,delivery
14|Hand Supporting a Heart|An open hand reaches from the lower left to cradle a large heart. The thumb curves across the heart's lower left edge, while the palm follows beneath its pointed base and rises toward the right.|hand,heart,holding,care,love,support
15|Hand Gripping a Waving Flag|A hand enters from the left and grips an upright flagpole with curled fingers. Above the fist, a blank flag extends right with a stepped wave through its upper and lower edges.|hand,flag,pole,holding,fist,banner
16|Diagonal Scraper with Broad Blade|A scraper angles from lower left to upper right, with a broad straight-edged blade and a narrower rounded handle. A transverse band separates the blade face from its rounded shoulder near the handle.|scraper,blade,handle,tool,putty,repair
17|Two Open Hands Beneath a Heart|Two cupped hands rise symmetrically around a large upright heart. Their palms curve inward beneath its pointed lower end, while long outer fingers reach upward beside the heart's rounded lobes.|hands,heart,care,support,love,holding
18|Hands Cupping a Profile Head|Two open hands curve upward beneath a small head shown in right-facing profile. The head has a rounded crown, projecting nose, short chin, and open neck, floating just above the cupped palms.|head,hands,care,profile,support,person
19|Looped Rope with Two Wraps|A rope forms a tall rounded loop above two thick horizontal wraps at its narrow neck. Two loose ends descend beneath the wraps, curving slightly apart toward the bottom.|rope,loop,knot,cord,tie,wrap
21|Highway Passing Beneath a Bridge|A tapered highway recedes upward with two long lane boundaries along its center. A horizontal bridge crosses in front, interrupting the road edges and lane lines as it spans across the view.|highway,bridge,road,overpass,lane,transport
22|Horizontal Ruler with Six Ticks|A long horizontal ruler has a plain rectangular body and six short measurement ticks rising from its lower edge. The upper half remains blank, without numerals or additional markings.|ruler,measure,tick,stationery,length,tool
23|Saddle with Hanging Stirrup|A saddle has a broad curved seat with raised ends and a shallow dip through the middle. A rounded panel hangs beneath it, followed by a short strap and a small flat-bottomed stirrup.|saddle,stirrup,horse,tack,riding,equipment
26|Diagonal Rocket with Round Window|A rocket points toward the upper right with a tapered nose, circular porthole, and two angular side fins. A small rounded flame trails behind its lower left engine opening.|rocket,space,window,fin,flame,spacecraft
28|Light Bulb and Battery Circuit|A bulb with a forked filament sits above a stepped battery marked with a short minus line. A loose U-shaped wire segment appears at the right; the visible circuit has gaps between its components.|bulb,battery,circuit,wire,electricity,science
29|Circular Magnifier with Straight Handle|A large circular magnifying lens joins a long straight handle at its lower right edge. The lens is empty, and the handle extends diagonally downward without a separate grip or end ornament.|magnifier,lens,search,handle,inspection,tool
31|Eight-Toothed Gear with Round Hub|A gear has eight broad rectangular teeth spaced around a circular body. A large round central opening remains empty, and short concave arcs join the tooth bases around the outer edge.|gear,cog,tooth,hub,machine,mechanical
32|Floating Bar Above Oval Shadow|A slim rounded horizontal bar floats above a broad oval shadow. Both shapes are empty outlines, separated by a clear vertical gap and centered along the same vertical axis.|shadow,bar,oval,floating,object,light
34|Parabola on Coordinate Axes|A smooth upward-opening curve crosses a vertical axis above its intersection with a horizontal axis. The horizontal axis ends in a right-facing arrow, while the curve rises symmetrically on either side.|parabola,axis,graph,curve,mathematics,science
36|Seated Figure on Curved Rocker|A person sits in right-facing profile above a broad upward-curving rocking base. The figure has a round head, a bent arm extending forward, and bent legs descending diagonally to the right.|rocker,person,seated,rocking,figure,balance
37|Plain Person Bust with Sleeve Lines|A round head floats above a broad torso with rounded shoulders and a flat lower edge. Two upright interior lines suggest the arms along the sides of an otherwise blank shirt.|person,bust,torso,head,figure,portrait
39|Branching Roots Below Ground|A thin vertical stem descends from a horizontal ground line into several branching roots. The roots bend outward and fork again near their ends, creating an irregular spreading network beneath the surface.|root,plant,ground,branch,botanical,soil
40|Circle with Rising Diagonal Stroke|A plain circular outline surrounds one diagonal stroke running from lower left to upper right. The stroke stops well inside the circle at both ends, and no other details are visible.|circle,diagonal,stroke,symbol,outline,mark
41|Wraparound Safety Goggles|A wide pair of safety goggles has a continuous outer rim and a broad inner lens opening. Both contours dip around the nose bridge, with short side projections and a small gap along the lower rim.|goggles,safety,lens,protection,eyewear,equipment
42|Rabbit Riding a Kick Scooter|A rabbit-shaped figure faces right on a low kick scooter, with one long upright ear and a rounded snout. Its body meets the deck beside a tall handlebar stem, above two partly outlined wheels.|rabbit,scooter,riding,animal,vehicle,play
44|Raised Fist Wearing a Bracelet|A raised fist has four rounded knuckles across its top and a thumb folded inward across the palm. A broad rounded bracelet encircles the wrist, with two short forearm edges continuing below.|fist,hand,bracelet,wrist,gesture,raised
45|Camper Van with Over-Cab Roof|A camper van faces right with a tall rear cabin and a roof projecting over the cab. A square side window and sloping windshield sit above two round wheels beneath the broad body.|camper,van,rv,vehicle,travel,motorhome
49|Roaring Lion Head in Profile|A lion's head faces right with a broad rounded mane tapering below the neck. A small ear and closed eye sit above a projecting snout, with the open mouth cut deeply into the profile.|lion,roar,head,mane,animal,profile
51|Rocket Passing Above a Globe|A rocket angles upward to the right over a partial globe, with a pointed nose and angular fins. Short exhaust strokes trail behind it, while a curved continent edge appears on the globe below.|rocket,globe,earth,space,flight,planet
52|Single Serpent Around a Staff|A single snake winds around a thin upright staff in several broad curves that taper downward. The staff has a rounded knob at the top and extends below the final turn of the serpent.|serpent,staff,asclepius,medicine,snake,symbol
53|Rolled Sheet with Loose End|A horizontal roll has a spiral opening at the left and a rounded outer end at the right. A loose sheet extends from beneath the roll, forming a flat flap that angles outward to the lower right.|roll,sheet,paper,material,spiral,scroll
54|Room Service Cart with Cloche|A low service cart has a rounded body, two visible wheels, and a curved handle rising on the left. A domed food cover with a small top knob rests above the cart's upper surface.|cart,cloche,service,food,hotel,trolley
55|Rutabaga with Paired Leaves|A rounded rutabaga narrows into a pointed root at its base. A short upright stem joins two broad pointed leaves spreading left and right above the plain bulbous body.|rutabaga,root,vegetable,leaf,produce,food
56|Round-Headed Rivet|A rivet stands upright with a broad domed oval head and a long narrow shaft below. The shaft's straight sides end in a rounded tip, while the head projects equally on either side.|rivet,fastener,head,shaft,metal,hardware
58|Ruler with Triangular Set Square|A tall ruler has six short ticks along its left edge. A right-angled triangular set square joins its lower right side, with the long diagonal rising to meet the ruler midway up.|ruler,triangle,measure,geometry,stationery,set-square
59|Rum Bottle with Blank Label|A squat bottle has rounded shoulders rising into a narrow neck topped by a short cap. Two horizontal lines mark a broad blank label across the lower body, above the rounded base.|rum,bottle,label,cap,drink,container
60|Sad Cat Face with Drooping Eyes|A round cat face has two pointed ears above a softly curved crown. Two short drooping eyelids sit over a broad downturned mouth, with no whiskers or nose visible.|cat,sad,face,ear,emotion,animal
61|Hard Hat and Safety Goggles|A domed hard hat with a broad brim and raised central ridge sits above a separate pair of goggles. The goggles have a wide curved lens outline, a nose notch, and short side straps.|helmet,hardhat,goggles,safety,protection,equipment
62|Sailor Bust with Broad Cap|A front-facing sailor has a blank rounded face beneath a broad angular cap. A short neck joins curved shoulders and a plain uniform, with a rounded collar opening and vertical center seam.|sailor,cap,uniform,person,navy,portrait
63|Sandbag Barrier Before a Sheltered Opening|Five low rounded sandbags overlap in staggered rows before a larger shelter-like structure. The structure has a broad rounded top and an open left section partly obscured by the stacked bags.|sandbag,barrier,shelter,stack,protection,defense
65|Satellite Dish on Triangular Stand|A tilted satellite dish faces upper right, with a wide curved bowl and a straight diagonal rim. A slender arm reaches toward a circular receiver above, while a triangular support stands below.|satellite,dish,receiver,antenna,signal,communication
66|School with Roof Flag and Side Wings|A school has a tall central pitched-roof entrance with an arched doorway and a small flag above its peak. Two lower side wings each contain one square window on either side.|school,building,flag,door,window,education
67|Scientist with Round Glasses|A front-facing scientist has a blank rounded face and circular glasses joined by a short bridge. An open coat with angular lapels spreads over the shoulders around a V-shaped neckline.|scientist,glasses,coat,person,science,portrait
68|Security Camera Watching a Scooter|A scooter faces right beneath a wall-mounted security camera angled toward it from the upper left. The scooter has a rounded seat, curved rear body, low deck, and two visible wheels.|scooter,camera,security,parking,surveillance,vehicle
70|Person Holding Both Cheeks|A large blank rounded head is cupped by two long hands rising along its lower sides. The hands touch the cheeks and continue downward out of view, framing the face symmetrically.|person,head,hands,cheek,scream,gesture
71|Plain Irregular Rock|A squat rock has an uneven polygonal outline with gently rounded changes of direction. Its top rises into a shallow peak, its base is broad, and the interior has no visible markings.|rock,stone,boulder,geology,outline,nature
72|Pointed Sage Leaf|A single pointed leaf angles from lower left to upper right, with one broad curved edge and a straighter opposite edge. A central vein runs from the projecting stem toward the upper tip.|sage,leaf,plant,vein,stem,herb
73|Standing Seagull Facing Right|A seagull stands in right-facing profile with a rounded head, pointed beak, and tiny eye. Its long sloping back leads to a pointed tail, with a curved wing above two straight legs.|seagull,bird,beak,wing,coast,wildlife
74|Upright Sepal with Central Vein|A single upright sepal has a sharp tip and a rounded lower body. A straight central vein extends from near the tip through the base into a short projecting stem below.|sepal,leaf,plant,vein,stem,botanical
75|T-Handled Rod|A long upright rod hangs from the center of a broad horizontal handle. The handle has rounded ends, and the narrow shaft terminates in a rounded lower tip without additional attachments.|rod,handle,shaft,tool,upright,bar
76|Gathered Sack with Flared Mouth|A rounded sack widens toward its lower body and narrows at a pinched neck. Its short upper mouth flares outward with a shallow curved dip along the top edge.|sack,bag,pouch,storage,cloth,container
77|Oval Seed with Curved Seam|A tall oval seed narrows slightly toward its top and has a broadly rounded lower end. One gently wavering seam runs from top to bottom, dividing the otherwise blank body.|seed,grain,plant,seam,oval,botanical
78|Romaine Leaf with Branching Vein|An upright leaf has a pointed tip and a rounded lower outline. A central stem extends below the base, with two short side veins branching diagonally upward within the leaf.|romaine,lettuce,leaf,vein,vegetable,plant
79|Seated Serval in Profile|A seated cat faces left with tall pointed ears, an upright chest, and a rounded haunch. A long tail curls upward on the right, while a short inner curve separates the bent hind leg.|serval,cat,animal,tail,seated,profile
80|Salami with Exposed Cut End|A short salami cylinder lies horizontally with an oval cut face on the left and a tied wrapper tip on the right. Small dots mark the exposed filling on its cut surface.|salami,sausage,food,meat,slice,wrapper
81|Square Room Plan with Small Inset|A rounded square outline contains one smaller plain square near the upper left. The rest of the interior remains empty, and no doorway, furniture, or additional room divisions are visible.|room,plan,square,inset,layout,outline
83|Storefront with Scalloped Awning|A small storefront has a broad canopy with a scalloped lower edge. Beneath it, a plain rectangular facade contains one central rounded doorway, with curved lower corners at the outside walls.|storefront,salon,shop,awning,door,building
84|Scalpel with Curved Cutting Edge|A scalpel lies diagonally from lower left to upper right, with a long rounded handle. Its narrow blade widens along a curved cutting edge before tapering to a sharp lower-left point.|scalpel,blade,handle,surgery,medical,tool
85|Three Upright Saffron Leaves|Three long pointed leaf-like forms spread from a short central stem. The middle leaf rises highest, while the outer pair angle outward and curve inward toward their shared narrow base.|saffron,leaf,plant,sprig,botanical,herb
86|Circular Chart with Three Sectors|A circular outline is divided into three unequal sectors by straight lines meeting near the center. One divider rises vertically, while the other two angle down toward the lower left and right.|chart,pie,sector,circle,diagram,section
87|Long-Handled Scythe|A long narrow handle leans slightly right as it rises into a broad curved blade. The blade sweeps downward to a sharp right-facing tip, with a second curve marking its lower cutting edge.|scythe,blade,handle,farming,harvest,tool
88|Salt Shaker with Broad Cap|A plain salt shaker has a tapered body that widens toward a rounded base. A broad rounded cap rests above its narrow shoulders, with a thin seam between the lid and body.|salt,shaker,cap,container,kitchen,seasoning
89|Two Adjacent Person Busts|Two people appear as circular heads above rounded shoulder blocks. The left figure is slightly taller and wider, with its shoulder overlapping the upper left edge of the smaller right torso.|people,pair,roommate,bust,person,group
90|Plain Rounded Person Profile Mark|A large circular head sits above a broad shoulder block with rounded upper corners and a flat base. The face and torso are entirely blank, without clothing details or other identifying marks.|person,profile,bust,head,avatar,user
92|Vertical Ruler with Six Ticks|A tall narrow ruler has a rectangular body and six short horizontal ticks extending inward from its left edge. Its right side remains plain, and no measurement numbers are visible.|ruler,vertical,measure,tick,length,stationery
93|Seepage Beneath Wavy Layer|A straight horizontal surface line sits above a shallow wavy boundary. Two short wavering vertical lines descend beneath the boundary, suggesting fluid passing down through the layered ground.|seep,seepage,water,layer,ground,flow
94|Folded Sediment Bands|Three long horizontal bands connect through alternating rounded turns, forming a flattened winding shape. The upper band opens at the right, and the lower band extends farther left before curving back.|sediment,layer,fold,geology,band,strata
95|Winding Riverbed with Three Stones|Two irregular curving banks wind from the upper left toward the lower right. Three rounded stones lie beside the lower bends, with their different sizes breaking up the open foreground.|riverbed,river,stone,bank,stream,landscape
96|Narrow Rivulet with Winding Bank|A long flowing S-shaped line bends from the upper left through the center toward the lower left. A shorter curved line appears at the lower right, forming a partial opposite bank.|rivulet,stream,water,bank,curve,flow
97|Router with Round-Tipped Antenna|A low rounded rectangular router body supports a single thin vertical antenna at its center. The antenna ends in a small circle, and the device body has no visible ports or lights.|router,antenna,device,network,wireless,electronics
98|Router Table with Central Tool Post|A worktable has a broad rounded top, two outward-slanting legs, and a horizontal cross brace. A short narrow tool post rises vertically from the center of the tabletop.|router,table,workbench,tool,woodworking,stand
99|Triangle Above Two Circles|A plain upright triangle sits centered above two separate circular outlines. The circles are evenly spaced at the lower left and lower right, with no connecting lines or internal marks.|triangle,circle,geometry,group,shape,diagram
101|Angry Face with Broad Mouth Cover|A round face has two inward-slanting eye strokes above a wide rounded band covering its lower half. The band interrupts the outer face contour at both sides, while a lower chin arc remains visible.|face,mask,cover,angry,expression,emotion
102|Snarling Face with Two Fangs|A rounded square face has sharply slanted brows over small downturned eyes. Its broad open mouth contains two short upper fangs and a curved lower tongue or jaw line.|snarl,face,fang,angry,mouth,expression
103|Shuttlecock with Three Broad Feathers|A shuttlecock angles upward to the right from a round cork base. Three long rounded feather sections fan outward, with the left section rising highest and the right section spreading farthest sideways.|shuttlecock,badminton,feather,cork,sport,equipment
104|Soap Bar with Rising Bubbles|A plain soap bar forms a broad rounded rectangle beneath three bubbles of different sizes. The largest bubble floats at upper left, a smaller one at upper right, and the smallest just above the bar.|soap,bubble,washing,cleaning,bar,hygiene
105|Round Ball with Curving Panel Seams|A circular ball is divided by one horizontal seam and three long curving upright seams. The curved lines bow in different directions, forming broad panels without the small stitch marks of a sewn softball.|ball,seam,panel,sport,round,game
106|Staggered Rectangular Wall Panels|A wide rectangular wall section is divided into three horizontal courses. Vertical joints alternate between the rows, with two broad panels above and below and three panels across the middle.|siding,wall,panel,brick,course,construction
107|Cable Car Cabin Hanging from Wire|A small rounded cabin hangs from a straight overhead cable by a short central hanger. A single rounded rectangular window occupies the front of the otherwise plain enclosed body.|cablecar,cabin,lift,wire,transport,ski
108|Smoking Cigarette with Curl of Smoke|A long horizontal cigarette has a narrow filter band near its right end. A single curved smoke trail rises above that end, bending left before curling back toward the upper edge.|cigarette,smoke,filter,smoking,tobacco,ember
109|Upright Sidewalk Slab on Ground Line|A tall slab has rounded upper corners and straight sides meeting a horizontal ground line. One horizontal divider crosses its lower half, leaving two plain stacked sections within the outline.|sidewalk,slab,paving,ground,panel,construction
110|Soccer Ball with Polygon Panels|A round soccer ball has a central pentagonal panel surrounded by adjoining polygonal sections. Short angled seams continue around the perimeter, forming the familiar interlocking patch pattern across its curved face.|soccer,football,ball,pentagon,panel,sport
111|Clock with Clockwise Return Arrow|A nearly circular clockwise arrow surrounds two clock hands, one pointing up and the other right. The arrowhead sits near the lower right, while a small gap remains near the bottom.|clock,repeat,return,time,arrow,snooze
113|Container Truck in Side View|A delivery truck faces right with a large rectangular cargo container above its rear wheel. Four vertical lines mark the container side, while a short sloping cab sits over the front wheel.|truck,container,freight,delivery,vehicle,logistics
115|Plain Box Delivery Truck|A box truck faces right with a tall rectangular cargo body and a smaller cab. A sloping windshield and horizontal cab division sit above two circular wheels, one beneath each section.|truck,box,delivery,vehicle,cab,transport
116|Long Curved Shoehorn|A long narrow shoehorn lies diagonally from lower left to upper right, widening into a rounded spoon-like end below. Its opposite end is also rounded and contains a tiny hanging hole.|shoehorn,shoe,dressing,handle,accessory,tool
117|Fast Truck with Motion Trails|A small delivery truck faces right with a rounded cargo body and cab above two round wheels. Its left outline opens into short horizontal motion trails that extend behind the vehicle.|truck,fast,delivery,motion,vehicle,shipping
118|Three-Ray Warning Beacon|A domed warning light rises from a broad low base with rounded upper corners. Three short rays spread above the dome, with one vertical line between two diagonal light marks.|beacon,siren,warning,light,alarm,emergency
119|Five-Ray Alarm Beacon|A tall rounded beacon sits on a narrow rectangular base with softened corners. Five separate rays spread around its upper half, including short horizontal rays at the left and right sides.|beacon,alarm,siren,light,warning,emergency
120|Crossed Fringed Shawl|A broad shawl folds around an open upper neckline and crosses diagonally at the front. Its two panels form a pointed lower silhouette, with several straight fringe strands hanging beneath.|shawl,scarf,fringe,wrap,clothing,fabric
122|Person with Monocle and Necktie|A front-facing person has swept hair and a single circular monocle over the right eye area. A pointed shirt collar and narrow necktie sit beneath the blank face, above curved shoulders.|person,monocle,tie,hair,portrait,formal
123|Domed Silo with Horizontal Bands|A tall storage silo has a rounded domed top above a straight-sided body. Three horizontal seams divide the lower section into broad bands, ending at a slightly rounded flat base.|silo,storage,grain,farm,building,agriculture
125|Signet Stamp with Broad Head|A broad rounded rectangular stamp head sits above a short narrow neck that widens into a bulb-shaped grip below. The face of the head is blank, with no lettering or emblem visible.|signet,stamp,seal,handle,grip,office
126|Clock with Counterclockwise Arrival Arrow|Two right-angled clock hands sit within a broad counterclockwise circular arrow. The arrowhead points upward at the left, with a gap separating it from the upper arc of the circle.|clock,arrival,time,arrow,estimate,counterclockwise'''
d={}
for line in raw.splitlines():
 i,n,desc,tags=line.split('|');i=int(i);d[i]=dict(index=i,concept=n,icon_id=re.sub('[^a-z0-9]+','-',n.lower()).strip('-'),family='solo',description=desc,tags=tags.split(','))
assert len(d)==100,len(d)
existing=set(json.loads((P/'existing-ids.json').read_text()));print('Collisions',[(i,x['icon_id']) for i,x in d.items() if x['icon_id'] in existing]);(P/'solo-drafts.json').write_text(json.dumps(d,indent=2)+'\n');print('Held:',[i for i in range(127) if i not in d])
