from pathlib import Path
import json,html,base64,hashlib,collections
W=Path(__file__).parent
SOURCE_ICON_ID=None
SOURCE_PATH='snapshot.json'
AUTHOR='gpt-6'
notes=[
('redraw','Two tiny ring heads float beside one angular merged skeleton; the two supporting people and their torso directions are not readable. Reconstruct both figures from the human action reference and verify each real neck junction.'),
('redraw','The lamp and three beams read as a headlight, but the upper stalk looks accidental and does not clearly communicate adaptation. Resolve that feature into a deliberate recognizable construction; preserve the evenly spaced beams.'),
('redraw','The diagonal bands fan at different angles and intervals; the left boundary changes slope at band junctions. Use one shared band direction and spacing, with deliberate clean intersections at the clipped outer shape.'),
('redraw','Only a diagonal stroke remains. It conveys neither air pollution nor fire; the linked original is also only a stroke. Obtain a complete subject reference before reconstructing this icon.'),
('redraw','The capsule, left vertical bar and lower nub lose the airship tail and gondola. At 48px it reads as a pill above a mound. Restore the airship silhouette and a clear cloud while budgeting their separation.'),
('redraw','A ring with two chevrons and an angular top stalk reads as a face or ornament. The distinctive beak, brows and feather silhouette of the supplied bird have been lost. Rebalance those identifying features.'),
('redraw','Middle leg strokes join into a dense crossbar between the head and abdomen. This still conflicts with the saved request to remove the two middle lines. Reconstruct a clear segmented ant with deliberate leg attachment points.'),
('redraw','The arched back, hanging trunk and block legs read as an elephant. The pointed snout, tail and requested eye are missing. Reconstruct the anteater silhouette; do not approve this as the named animal.'),
('redraw','The outer rim is assembled from equal-radius arcs through points that are not on one common circle: for example (24,42) is 18u from (24,24), while (40,12) is 20u away. This creates uneven curvature; blade turns and openings are also unequal. Use one circular rim and a shared blade construction.'),
('avatar','The headcloth has become a horizontal face stripe and two short sticks. The face is oval (radii 6 and 8) and detached from the shoulders. Rework the identifying cloth and circular jaw using the avatar specialization.'),
('redraw','The repeated arches and closed rectangular surround read as a window or book. The saved request for a simple stone bridge is unresolved. Keep a deck, one readable arch and a minimal water cue.'),
('redraw','A thick inverted U and two drops read as a hook or shower more readily than a tap. The handle and clear spout direction have been lost. Restore a recognizable faucet silhouette and coherent water direction.'),
('route','This is an ordering arrow beside 1 and 9, not a standalone noun. Route the ordering glyph to the sub skill and keep text as text; do not certify it as a solo primitive.'),
('route','The chevron is clean and legible, but it is a directional glyph. Route to icon-sub; this review cannot certify it under the solo noun contract.'),
('route','The upward chevron is clean and mirrored, but it is a directional glyph. Route to icon-sub; its wider proportions should be intentional within that profile.'),
('route','The dashed diagonal arrow is readable, but belongs to the sub family. Re-author its dash rhythm and arrowhead on SUB32; do not scale this drawing.'),
('route','The dashed down arrow is readable but is a sub-family directional glyph. Its broad, shallow arrowhead also differs in proportion from the horizontal versions; define one coherent arrow family.'),
('route','The dashed left arrow is readable and evenly spaced, but belongs to icon-sub. Preserve the legible rhythm when authoring it on the correct profile.'),
('route','The dashed right arrow is readable and mirrors the left version, but belongs to icon-sub.'),
('route','The dashed up arrow is readable but belongs to icon-sub. Match the arrowhead construction to its directional siblings without stretching an existing icon.'),
('route','The bidirectional arrow reads clearly, but is an operator/directional glyph. Route to icon-sub and retain deliberate matching arrowheads.'),
('route','An independently meaningful outlined tag/arrow frame hosts a separate left chevron. Route through icon-making for container and sub component assessment; do not certify the combined primitive as solo.'),
('route','The drawing contains no Celsius mark: only an up arrow with a crossbar. Resolve the missing subject, then route the arrow and temperature notation appropriately.'),
('redraw','The circle overwhelms the shallow barrel and hides the carriage; the barrel/axle meeting becomes a heavy wedge at native size. Rebalance barrel, wheel and support so the field gun reads immediately.'),
('redraw','The barrel has collapsed into a small crossed tick above a house-like polygon and wheel. Restore a coherent barrel axis, readable cradle and outriggers; the current silhouette loses the artillery subject.'),
('redraw','The muzzle is an upright post with a right spur; the long barrel and recognizable rifle proportions are lost. Reconstruct stock, grip and barrel around one deliberate horizontal weapon axis.'),
('avatar','A bisected circle and wide brim read as a generic helmeted person; the source helmet and hair have been over-reduced. Restore the firefighter headwear and apply the current avatar head/body construction.'),
('avatar','The symmetrical brim reads as a broad hat rather than a riding helmet. Preserve a recognizable riding-helmet profile and rebalance the sash; apply avatar jaw and shoulder construction.'),
('avatar','The circular head is clean, but the torso is a flat-topped angular block and its crossing lapels form a heavy lower diagonal. Smooth the shoulder construction and give the gi lapels clear intentional spacing.'),
('avatar','The same flat shoulder block and heavy lapel crossing remain; the tiny hooked ponytail looks attached as an extra stroke. Integrate the hairstyle and apply the avatar construction.'),
('avatar','The hair is a bar across the face and the body is a closed trapezoid. The hairstyle and garment construction from the reference have disappeared. Rework these visible features using avatar proportions.'),
('avatar','The cap and jaw read as a small cup above detached shoulders. Preserve a recognizable cap/face relationship and tunic while applying the avatar construction; identity must come from the supplied clothing.'),
('avatar','The head has become a tilted cap-like outline with a flattened elliptical jaw (radii 8 and 6). Reconstruct a circular face and recognizable hairstyle; keep the pajamas distinct from headwear.'),
('avatar','The triangular crown and flattened jaw read as a bowl or sail shape. Restore a circular face with an independently legible police cap; no linked original is available in the gallery for direct comparison.'),
('avatar','The hat and jaw read as a cup, while the torso is an angular box with a V. Rebalance the sailor cap, circular face and smooth shoulders to preserve a readable portrait.'),
('avatar','The face and hat are merged into a teardrop outline. Hair and the cap brim are absent, and the scarf is a short diagonal slash. Restore the identifying headwear and portrait anatomy.'),
('avatar','The closed trapezoid body resembles a dress sign, and the two hair tails float from a generic circular face. Recover the apron and bob hairstyle from the source with coherent shoulders.'),
('avatar','The diagonal strap and closed lower box resemble a sash behind a counter; the source apron and bob hairstyle are lost. Rework the portrait rather than using an unrelated ponytail and diagonal.'),
('redraw','The rosette lobes use very different proportions: the top is circular, sides are wide and the bottom is shallow. Cusps and crowded ribbon attachments make the flower uneven. Build a coherent repeated-lobe outline and clear ribbon joins.'),
('redraw','The outline reads as a heavy letter A. The inner rounded arch collides visually with the pointed arch, and the wide flaring monument proportions are lost. Restore the landmark silhouette and rebalance the nested opening.'),
('good','The face, paired triangular bow loops, eyes and smile remain immediately readable in both themes. Mirrored cheeks and ears balance around x=24; the angular bow corners are deliberate, and the facial openings remain clear. The SQUARE envelope suits the broad face and bow. A head-only subject has no head-to-body gap to certify.'),
('redraw','The saved request for a circular head without ears is unresolved. The silhouette retains bumpy ears, shoulder-like lower hooks and a thick curled tuft. Reconstruct the requested circle and one clean hair curve.'),
('redraw','The tray, seat and base have collapsed into a letter-like frame with a large inner hook. It no longer reads clearly as a baby walker at 48px. Restore a recognizable seat and supporting walker structure.'),
('redraw','The figure reads as a T/Y with a floating dot head. The head sits below the long body rather than along a readable upper-torso direction; the exact neck gap is not established. Reconstruct the pose with explicit shoulder, hip and head relationships.'),
('avatar','The held glass is readable, but the shoulder becomes an angular forearm without a clear torso and the source portrait is replaced with a generic partial figure. Reconstruct the bartender anatomy and deliberate hand-to-glass contact using the human reference.'),
('route','This is a generic outlined play triangle. It is clean as a glyph, but does not establish the named brand identity. Route as a play sub-icon, or supply a complete brand reference before retaining this name.'),
('redraw','The bead loop ends beside a heavy heart with a crowded upper notch; the requested charm angle is still unresolved. Define the charm axis and attachment deliberately, then keep the bead rhythm consistent around that attachment.'),
('redraw','Only three oversized rectangular beads remain, with a dangling straight wire at left and a separate bent strand at right. The continuous beaded wire in the source is no longer clear. Rebalance repeated bead sizes and preserve one coherent wire path.'),
('good','The opposing jaws, supports, base and right-hand crank form a readable bench vise. The jaws mirror around x=21 with matching 12 by 14 arc radii; the crank intentionally extends the drawing to the right. The HRECT_L envelope accommodates the horizontal jaw/crank assembly. Structural corners are deliberate and openings remain clear at 48px.'),
('good','The paired cups, central bridge and neck ties read clearly as a bikini top. Cups share mirrored control points about x=24, with smooth rounded lower contours and deliberate pointed strap attachments. The HRECT_L envelope suits the side-by-side cups. The source also depicts the upper garment only; no bottom garment was removed in this review.')]
assert len(notes)==50
snap=json.loads((W/'snapshot.json').read_text());val={r['icon_id']:r for r in json.loads((W/'validation.json').read_text())};built={r['icon_id']:r for r in json.loads((W/'build/solo48/manifest.json').read_text())['icons']}
rows=[]
for n,(i,(kind,note)) in enumerate(zip(snap,notes),1):
 b=built[i['icon_id']];s=(W/(i['icon_id']+'.svg')).read_bytes();bs=(W/'build/solo48'/(i['icon_id']+'.svg')).read_bytes();assert s==bs
 r={'number':n,'icon_id':i['icon_id'],'verdict':'good' if kind=='good' else 'not-good','action':kind,'visual_finding':note,'keyshape':i['keyshape'],'svg_sha256':hashlib.sha256(s).hexdigest(),'basic_validation':val[i['icon_id']],'build_validation':b['validation'],'feedback':i['feedback'],'source_path':i['python_source']['path'],'original_sources':i['original_sources'],'reviewed_native_light':True,'reviewed_native_dark':True,'reviewed_centerlines':True}
 if kind=='avatar':r['human_rule']='Use icon-avatar specialization within solo. The shared human-reference currently requires circular jaws and touching head/body ink for portrait busts. These detached portrait layouts require reconstruction, not a generic MIC approval.'
 rows.append(r)
(W/'review.json').write_text(json.dumps(rows,indent=2))
esc=html.escape
def data(p):return 'data:image/svg+xml;base64,'+base64.b64encode(p.read_bytes()).decode()
counts=collections.Counter(r['action'] for r in rows)
head='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rejected solo icons · Review 01</title><style>
*{box-sizing:border-box}body{margin:0;background:#f0f2f1;color:#18332c;font:16px/1.5 system-ui,sans-serif}header,main{max-width:1250px;margin:auto;padding:34px 28px}header{padding-bottom:10px}h1{font-size:40px;line-height:1.1;margin:16px 0}.eyebrow{text-transform:uppercase;letter-spacing:.15em;font-size:12px}h2{font-size:20px;margin:0}p{margin:12px 0}.stats{display:flex;gap:18px;flex-wrap:wrap}.stat{background:white;border:1px solid #d5ddda;border-radius:14px;padding:15px 22px}.stat b{font-size:30px;display:block}.controls{position:sticky;top:0;padding:14px 0;background:#f0f2f1;display:flex;gap:10px;z-index:2}input,select{padding:12px;border:1px solid #b8c9c2;border-radius:8px;font:inherit}input{flex:1;min-width:0}article{background:white;border:1px solid #d5ddda;border-radius:16px;padding:24px;margin:18px 0}.title{display:flex;align-items:start;justify-content:space-between;gap:12px}.badge{white-space:nowrap;border-radius:30px;background:#fae7df;color:#843f26;padding:5px 12px;font-weight:650;font-size:13px}.badge.good{background:#d7eee2;color:#18523a}.views{display:flex;align-items:center;gap:30px;flex-wrap:wrap;margin:22px 0}.view{text-align:center;font-size:12px;color:#5a6b65}.large{width:144px;height:144px;display:block}.nativebox{padding:14px;display:inline-flex;background:#fff;border:1px solid #d5ddda}.nativebox.dark{background:#18181b}.nativebox img{width:48px;height:48px;display:block}.dark img{filter:brightness(0) invert(1)}.center{width:144px;height:144px;color:#087db2}.center svg{width:144px;height:144px}.center svg *{stroke-width:.45!important;stroke:#087db2!important}.center svg [fill]:not([fill="none"]){fill:#087db2!important}.small{font-size:13px;color:#5a6b65}summary{cursor:pointer;color:#326858}pre{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;background:#f1f4f2;padding:12px}a{color:#126f56}article[hidden]{display:none}.finding{font-size:17px}footer{margin:35px 0;font-size:13px;color:#5a6b65}@media(max-width:700px){header,main{padding:20px 14px}h1{font-size:30px}.views{gap:18px}.title{display:block}.badge{display:inline-block;margin:10px 0}.large,.center,.center svg{width:112px;height:112px}article{padding:18px}}
</style><header><div class="eyebrow">Pictographic · Independent visual audit · 15 September 2026</div><h1>Rejected solo icons<br>Batch 01 · Icons 1–50</h1><p>Reviewed in the rejected gallery’s displayed order, from acro-yoga-folded-balance through bikini. Every drawing was inspected enlarged, as centerlines, and at native 48px in light and dark themes, with its linked original where available.</p><div class="stats"><div class="stat"><b>3</b>Good drawings</div><div class="stat"><b>47</b>Not good under this review</div><div class="stat"><b>50 / 50</b>Fresh build passes</div></div><p><strong>A build pass does not establish drawing quality.</strong> “Good” means the current drawing is visually convincing and passes the selected icon checks. This audit does not change the gallery’s rejected status or redraw any icon.</p><p class="small">Standards: icon-solo, authoring, validation, reference triage and shared human construction. Portrait busts need the icon-avatar specialization within solo; arrows/operators need icon-sub. The current shared human guide uses touching ink for portrait heads and bodies, and exactly 4u ink clearance for detached stick figures. The old user.svg is a proportion reference and does not override that current avatar rule.</p><p class="small">Construction comparisons inspected: local Lucide aperture and bug, including atomic-debug views; shared human user.svg and full_body_ref.png. Other subjects were compared with their supplied originals and the geometric checklist. No drawing was authored in this audit.</p><p class="small" id="test-summary">TEST_SUMMARY</p></header><main><div class="controls"><input id="search" aria-label="Search icons" placeholder="Search icon or finding"><select id="filter" aria-label="Filter verdict"><option value="all">All 50</option><option value="good">Good · 3</option><option value="not-good">Needs work · 47</option></select></div>'''
parts=[head]
for i,r in zip(snap,rows):
 src=data(W/(r['icon_id']+'.svg'));svg=(W/(r['icon_id']+'.svg')).read_text();svg=svg[svg.index('<svg'):]
 orig=''
 if i['original_sources']:
  p=Path('icon_set/dist/gallery')/i['original_sources'][0]['url']
  if p.exists():orig=f'<div class="view"><img class="large" alt="Linked original" src="{data(p)}">Linked original</div>'
 else:orig='<div class="view">No linked original</div>'
 badge='GOOD' if r['verdict']=='good' else {'redraw':'NEEDS REDRAW','route':'ROUTE / SUBJECT ISSUE','avatar':'AVATAR REVISION'}[r['action']]
 feedback=''.join('<p class="small"><strong>Saved feedback:</strong> '+esc(f)+'</p>' for f in r['feedback'])
 evidence={'keyshape':r['keyshape'],'source':r['source_path'],'svg_sha256':r['svg_sha256'],'fresh_build':'valid; zero warnings; exact reviewed SVG bytes','checks_run':r['build_validation']['checks_run'],'negative_space':r['build_validation']['negative_space']['status'],'internal_spacing':r['build_validation']['internal_spacing_advisory']['status']}
 parts.append(f'<article data-verdict="{r["verdict"]}"><div class="title"><h2>{r["number"]:02d} · {esc(r["icon_id"])}</h2><span class="badge {r["verdict"]}">{badge}</span></div><div class="views"><div class="view"><img class="large" alt="Current generated drawing" src="{src}">Current drawing · enlarged</div><div class="view"><div class="center">{svg}</div>Centerlines · enlarged</div><div class="view"><div class="nativebox"><img alt="Native light" src="{src}"></div><div>48px · light</div></div><div class="view"><div class="nativebox dark"><img alt="Native dark" src="{src}"></div><div>48px · dark</div></div>{orig}</div><p class="finding">{esc(r["visual_finding"])}</p>{feedback}<p class="small">Keyshape: {esc(r["keyshape"])} · Basic validation: valid · Fresh full build: valid, zero warnings</p><details><summary>Evidence and construction notes</summary><p>{esc(r.get("human_rule",""))}</p><pre>{esc(json.dumps(evidence,indent=2))}</pre></details></article>')
parts.append('''<footer>Immutable drawing snapshots accompany this report. Re-running the library build elsewhere does not change these previews. Remaining rejected icons have not been assessed in this batch. Review decisions are in review.json; original model validation and isolated build evidence are preserved alongside it.</footer></main><script>const q=document.querySelector('#search'),f=document.querySelector('#filter');function filter(){for(const a of document.querySelectorAll('article'))a.hidden=(f.value!=='all'&&a.dataset.verdict!==f.value)||!a.textContent.toLowerCase().includes(q.value.toLowerCase());}q.addEventListener('input',filter);f.addEventListener('change',filter);</script></html>''')
summary = 'The selected 50-icon build passed with zero warnings and identical reviewed SVGs. Library-wide tests: 406 run, 7 failures, 30 sandbox server errors and 1 skip. All 30 server tests passed when rerun with localhost access. Seven library/fixture failures remain; this is not a claim that the whole library passes.'
(W/'report.html').write_text(''.join(parts).replace('TEST_SUMMARY', summary))
md=['# Rejected solo icons: batch 01','', '3 good; 47 need work. All 50 pass fresh selected build with zero warnings. No gallery review statuses or canonical drawings changed.','', '| # | Icon | Verdict | Finding |','|---|---|---|---|']
for r in rows:md.append(f'| {r["number"]} | {r["icon_id"]} | {r["verdict"]} ({r["action"]}) | {r["visual_finding"]} |')
(W/'REPORT.md').write_text('\n'.join(md)+'\n')
print(dict(counts))
