[workspace]
resolver = "2"
members = ["core", "app"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "raw_value"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
