#!/bin/bash
# Batch 53/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/teddy-bear-plush-toy-batch-017-09  source 5f26224c-ad5e-551c-9f1b-15837db228cb
#   solo/temaki-sushi-hand-roll  source 1cb48623-da6f-5eaa-9005-741acc0313b2
#   solo/temple-and-palm-tree  source 2e14f161-71b4-40a8-a538-68bc9cdb799b
#   solo/temple-under-moon-and-cloud  source 958ec275-d2c4-4051-9bda-84c178a164c4
#   solo/tennis-racquet  source 948c33c8-bc3a-4f16-89c1-33857008b047
#   solo/tennis-racquet-and-ball  source 4aa1bd09-82db-4a0a-a150-a20b946b666a
#   solo/text-5ge-text  source 4d3f552b-975a-5213-8db2-f60c0d18a007
#   solo/thai-massage-stretch  source 876d5973-30e6-5ce8-bd9e-b8d430fe7ad0
#   solo/therapist-applying-herbal-compress  source 7dc22fbf-39be-4ccf-911b-cf43b14058ef
#   solo/thermometer  source fc8dfaad-7235-42f0-b2b5-49b5793896e5
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Teddy bear plush toy batch 017 09' 5f26224c-ad5e-551c-9f1b-15837db228cb 'pictographic-primitives/kids/toys teddy bear_5f26224c-ad5e-551c-9f1b-15837db228cb.svg' \
  'Temaki sushi hand roll' 1cb48623-da6f-5eaa-9005-741acc0313b2 'pictographic-primitives/food/asian food japanese assorted seafood in seaweed cone_1cb48623-da6f-5eaa-9005-741acc0313b2.svg' \
  'Temple and Palm Tree' 2e14f161-71b4-40a8-a538-68bc9cdb799b pictographic-primitives/holidays/nyepi_2e14f161-71b4-40a8-a538-68bc9cdb799b.svg \
  'Temple under Moon and Cloud' 958ec275-d2c4-4051-9bda-84c178a164c4 'pictographic-primitives/holidays/poya day_958ec275-d2c4-4051-9bda-84c178a164c4.svg' \
  'Tennis racquet' 948c33c8-bc3a-4f16-89c1-33857008b047 'pictographic-primitives/sports/tennis racquet_948c33c8-bc3a-4f16-89c1-33857008b047.svg' \
  'Tennis racquet and ball' 4aa1bd09-82db-4a0a-a150-a20b946b666a pictographic-primitives/sports/tennis_4aa1bd09-82db-4a0a-a150-a20b946b666a.svg \
  'Text 5ge text' 4d3f552b-975a-5213-8db2-f60c0d18a007 pictographic-primitives/mobile/5ge_4d3f552b-975a-5213-8db2-f60c0d18a007.svg \
  'Thai massage stretch' 876d5973-30e6-5ce8-bd9e-b8d430fe7ad0 'pictographic-primitives/health/thai massage pose_876d5973-30e6-5ce8-bd9e-b8d430fe7ad0.svg' \
  'Therapist applying herbal compress' 7dc22fbf-39be-4ccf-911b-cf43b14058ef 'pictographic-primitives/beauty/herbal compress people_7dc22fbf-39be-4ccf-911b-cf43b14058ef.svg' \
  Thermometer fc8dfaad-7235-42f0-b2b5-49b5793896e5 'pictographic-primitives/weather/temperature thermometer_fc8dfaad-7235-42f0-b2b5-49b5793896e5.svg'
