#!/bin/bash
# Batch 64/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/woman-aviator-avatar  source 3d352ad0-cfb8-44b6-bde3-b9670d7ae257
#   solo/woman-chinese-1-avatar  source c74508b7-5e91-446d-88e9-08c52d64ab75
#   solo/woman-figure  source 945e9ef0-3098-5263-999a-e473cba0d938
#   solo/woman-graduate-avatar  source 41f44b4e-c542-4e70-ad5b-0876a3323d5c
#   solo/woman-japan-2-avatar  source 26a1c09d-ea15-43a7-9d47-728e74a2e340
#   solo/woman-nude  source f11ccece-81b6-415d-a20a-a1bdd3fceb3c
#   solo/woman-nurse-avatar  source e365094b-61bd-5f0a-a1d1-1a7c9525470b
#   solo/woman-office-avatar  source e065923b-81a0-5585-be2a-952d44fe334f
#   solo/woman-reading-a-book  source ed13ba86-a993-4e4d-b461-5ce413a5cd46
#   solo/woman-russian-avatar  source 8417c04c-fd00-4ec3-9e33-8097b4fe515d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Woman aviator avatar' 3d352ad0-cfb8-44b6-bde3-b9670d7ae257 'pictographic-primitives/avatars/woman aviator_3d352ad0-cfb8-44b6-bde3-b9670d7ae257.svg' \
  'Woman chinese 1 avatar' c74508b7-5e91-446d-88e9-08c52d64ab75 'pictographic-primitives/avatars/woman chinese_c74508b7-5e91-446d-88e9-08c52d64ab75.svg' \
  'Woman figure' 945e9ef0-3098-5263-999a-e473cba0d938 'pictographic-primitives/users/primitive symbols woman_945e9ef0-3098-5263-999a-e473cba0d938.svg' \
  'Woman graduate avatar' 41f44b4e-c542-4e70-ad5b-0876a3323d5c 'pictographic-primitives/avatars/woman graduate_41f44b4e-c542-4e70-ad5b-0876a3323d5c.svg' \
  'Woman japan 2 avatar' 26a1c09d-ea15-43a7-9d47-728e74a2e340 'pictographic-primitives/avatars/woman japan_26a1c09d-ea15-43a7-9d47-728e74a2e340.svg' \
  'Woman nude' f11ccece-81b6-415d-a20a-a1bdd3fceb3c 'pictographic-primitives/other/woman nude_f11ccece-81b6-415d-a20a-a1bdd3fceb3c.svg' \
  'Woman nurse avatar' e365094b-61bd-5f0a-a1d1-1a7c9525470b 'pictographic-primitives/avatars/woman nurse_e365094b-61bd-5f0a-a1d1-1a7c9525470b.svg' \
  'Woman office avatar' e065923b-81a0-5585-be2a-952d44fe334f 'pictographic-primitives/avatars/woman office_e065923b-81a0-5585-be2a-952d44fe334f.svg' \
  'Woman reading a book' ed13ba86-a993-4e4d-b461-5ce413a5cd46 'pictographic-primitives/content/newspaper read woman_ed13ba86-a993-4e4d-b461-5ce413a5cd46.svg' \
  'Woman russian avatar' 8417c04c-fd00-4ec3-9e33-8097b4fe515d 'pictographic-primitives/avatars/woman russian_8417c04c-fd00-4ec3-9e33-8097b4fe515d.svg'
