#!/bin/bash
# Batch 41/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/mobile-phone-headphone  source e65c555e-8915-44b9-98b2-344d81aac941
#   solo/mobile-phone-house  source 08a24aa4-c28b-421f-94e2-f810a7a98af1
#   solo/mobile-phone-mobile  source b193343f-83cb-42e1-82cf-a7eac0dd3950
#   solo/mobile-phone-phones  source 0ccd2887-dbd0-4ab5-a736-e2ba5438da4d
#   solo/mobile-phone-pin  source cd3023f2-6462-458d-9f32-0ee54bf229c9
#   solo/mobile-phone-pound-sign  source a70db137-a446-4f4c-b656-4fea14660981
#   solo/mobile-phone-qr-code-scanner  source de84ba40-054e-4737-9aee-c6a39715be64
#   solo/mobile-phone-record  source dc414e02-3cd1-4dfd-b568-2313b3f5617c
#   solo/mobile-phone-unlock  source b0d42cd4-6acc-4018-ae89-490f3eb333a9
#   solo/mobile-phone-with-lower-bezel  source 8db84bcc-f04b-4b48-8727-a0f4bef6e360
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Mobile phone headphone' e65c555e-8915-44b9-98b2-344d81aac941 'pictographic-primitives/other/mobile phone headphone_e65c555e-8915-44b9-98b2-344d81aac941.svg' \
  'Mobile phone house' 08a24aa4-c28b-421f-94e2-f810a7a98af1 'pictographic-primitives/other/mobile phone house_08a24aa4-c28b-421f-94e2-f810a7a98af1.svg' \
  'Mobile phone mobile' b193343f-83cb-42e1-82cf-a7eac0dd3950 'pictographic-primitives/mobile/mobile phone_b193343f-83cb-42e1-82cf-a7eac0dd3950.svg' \
  'Mobile phone phones' 0ccd2887-dbd0-4ab5-a736-e2ba5438da4d 'pictographic-primitives/phones/mobile phone_0ccd2887-dbd0-4ab5-a736-e2ba5438da4d.svg' \
  'Mobile phone pin' cd3023f2-6462-458d-9f32-0ee54bf229c9 'pictographic-primitives/other/mobile phone pin_cd3023f2-6462-458d-9f32-0ee54bf229c9.svg' \
  'Mobile phone pound sign' a70db137-a446-4f4c-b656-4fea14660981 'pictographic-primitives/other/mobile phone pound sign_a70db137-a446-4f4c-b656-4fea14660981.svg' \
  'Mobile phone qr code scanner' de84ba40-054e-4737-9aee-c6a39715be64 'pictographic-primitives/other/mobile phone qr code_de84ba40-054e-4737-9aee-c6a39715be64.svg' \
  'Mobile phone record' dc414e02-3cd1-4dfd-b568-2313b3f5617c 'pictographic-primitives/other/mobile phone record_dc414e02-3cd1-4dfd-b568-2313b3f5617c.svg' \
  'Mobile phone unlock' b0d42cd4-6acc-4018-ae89-490f3eb333a9 'pictographic-primitives/other/mobile phone unlock_b0d42cd4-6acc-4018-ae89-490f3eb333a9.svg' \
  'Mobile phone with lower bezel' 8db84bcc-f04b-4b48-8727-a0f4bef6e360 'pictographic-primitives/mobile/mobile phone 1_8db84bcc-f04b-4b48-8727-a0f4bef6e360.svg'
