#!/bin/bash
# Batch 15/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/couple-standing-with-hair  source 8808cfa8-f297-4bd3-a099-3c4ba3f2b025
#   solo/coworkers-with-laptop  source 8d47f316-c40a-4959-bfb4-5b4ee2cac87e
#   solo/craftsman-holding-a-hammer  source 04ebbce5-fdd2-4c6c-bc45-d497a7339082
#   solo/crane-hook  source 40e56b92-93e6-4122-b70a-f6f602cc3011
#   solo/crane-hook-beneath-tapered-block  source a48942b9-22b4-5473-bb69-75298cd6eb3f
#   solo/crane-hook-with-square-mount  source fd80bcd7-73ab-4b8e-8a28-7672b7384731
#   solo/cratered-moon-rising-behind-curved-horizon  source 3f691cb5-2291-494c-bb9b-480b4d6be086
#   solo/crawdad  source f4812ef0-fce6-4380-9124-384916ee103d
#   solo/crawling-baby  source 1d74887d-18df-5bd5-97d7-55b28bd0ed99
#   solo/crescent-head-wrench  source 47ad292e-443e-5fb5-a71a-0d263bd6ed9e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Couple standing with hair' 8808cfa8-f297-4bd3-a099-3c4ba3f2b025 'pictographic-primitives/users/multiple man woman 1_8808cfa8-f297-4bd3-a099-3c4ba3f2b025.svg' \
  'Coworkers with laptop' 8d47f316-c40a-4959-bfb4-5b4ee2cac87e 'pictographic-primitives/office/co working space team laptop_8d47f316-c40a-4959-bfb4-5b4ee2cac87e.svg' \
  'Craftsman holding a hammer' 04ebbce5-fdd2-4c6c-bc45-d497a7339082 'pictographic-primitives/_uncategorized_21/greek god hephaestus_04ebbce5-fdd2-4c6c-bc45-d497a7339082.svg' \
  'Crane hook' 40e56b92-93e6-4122-b70a-f6f602cc3011 'pictographic-primitives/shipping/crane hook_40e56b92-93e6-4122-b70a-f6f602cc3011.svg' \
  'Crane hook beneath tapered block' a48942b9-22b4-5473-bb69-75298cd6eb3f pictographic-primitives/construction/hook_a48942b9-22b4-5473-bb69-75298cd6eb3f.svg \
  'Crane hook with square mount' fd80bcd7-73ab-4b8e-8a28-7672b7384731 pictographic-primitives/construction/hook_fd80bcd7-73ab-4b8e-8a28-7672b7384731.svg \
  'Cratered moon rising behind curved horizon' 3f691cb5-2291-494c-bb9b-480b4d6be086 pictographic-primitives/_uncategorized_27/moonscape_3f691cb5-2291-494c-bb9b-480b4d6be086.svg \
  Crawdad f4812ef0-fce6-4380-9124-384916ee103d pictographic-primitives/_uncategorized_13/crawdad_f4812ef0-fce6-4380-9124-384916ee103d.svg \
  'Crawling baby' 1d74887d-18df-5bd5-97d7-55b28bd0ed99 'pictographic-primitives/babies/crawling kid_1d74887d-18df-5bd5-97d7-55b28bd0ed99.svg' \
  'Crescent head wrench' 47ad292e-443e-5fb5-a71a-0d263bd6ed9e 'pictographic-primitives/tools/tools crescent wrench_47ad292e-443e-5fb5-a71a-0d263bd6ed9e.svg'
