#!/bin/bash
# Batch 5/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/bitcoin-and-dollar-balance-scale  source 40a6f5d9-1d48-449a-9169-f46dd5fad662
#   solo/bitcoin-and-dollar-seesaw  source 45ba347e-d70c-49ad-bd22-e2ad93cdeafd
#   solo/bitcoin-and-dollar-seesaw-comparison  source ebaeb4ff-d25c-4ebd-91eb-0f8877362e5b
#   solo/bitcoin-cryptocurrency-coin  source 8fbdf83e-7f75-5f64-b826-fc7b55c55a27
#   solo/bitcoin-cryptocurrency-symbol-solo  source 056563c8-a6c4-4201-b355-6ff5f08795ea
#   solo/bitcoin-message-speech-bubble-solo  source 692b5811-84ae-4db0-8d66-219feaafec3e
#   solo/bitcoin-speech-bubble-solo  source 1b6ce2a0-ce30-49ce-99cf-a772bb04245d
#   solo/bitten-apple-with-a-detached-leaf  source 1da8830f-8f47-4740-95c5-b3e0c19b2899
#   solo/blackberry-cluster-with-a-single-leaf  source 3278a9d5-891d-4c6a-acc3-7bd972888b5c
#   solo/blazer-with-notched-lapels  source adeca2a9-4991-40c1-9620-baf03987dc2a
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Bitcoin and dollar balance scale' 40a6f5d9-1d48-449a-9169-f46dd5fad662 'pictographic-primitives/finance/crypto currency bitcoin dollar equal_40a6f5d9-1d48-449a-9169-f46dd5fad662.svg' \
  'Bitcoin and dollar seesaw' 45ba347e-d70c-49ad-bd22-e2ad93cdeafd 'pictographic-primitives/finance/crypto currency bitcoin dollar unequal_45ba347e-d70c-49ad-bd22-e2ad93cdeafd.svg' \
  'Bitcoin and dollar seesaw comparison' ebaeb4ff-d25c-4ebd-91eb-0f8877362e5b 'pictographic-primitives/finance/crypto currency bitcoin dollar unequal_ebaeb4ff-d25c-4ebd-91eb-0f8877362e5b.svg' \
  'Bitcoin cryptocurrency coin' 8fbdf83e-7f75-5f64-b826-fc7b55c55a27 'pictographic-primitives/money/crypto currency bitcoin_8fbdf83e-7f75-5f64-b826-fc7b55c55a27.svg' \
  'Bitcoin cryptocurrency symbol solo' 056563c8-a6c4-4201-b355-6ff5f08795ea 'pictographic-primitives/other/circle bitcoin_056563c8-a6c4-4201-b355-6ff5f08795ea.svg' \
  'Bitcoin message speech bubble solo' 692b5811-84ae-4db0-8d66-219feaafec3e 'pictographic-primitives/symbol/messages bubble square bitcoin_692b5811-84ae-4db0-8d66-219feaafec3e.svg' \
  'Bitcoin speech bubble solo' 1b6ce2a0-ce30-49ce-99cf-a772bb04245d 'pictographic-primitives/symbol/messages bubble round bitcoin_1b6ce2a0-ce30-49ce-99cf-a772bb04245d.svg' \
  'Bitten apple with a detached leaf' 1da8830f-8f47-4740-95c5-b3e0c19b2899 'pictographic-primitives/_uncategorized_03/apple logo_1da8830f-8f47-4740-95c5-b3e0c19b2899.svg' \
  'Blackberry cluster with a single leaf' 3278a9d5-891d-4c6a-acc3-7bd972888b5c pictographic-primitives/_uncategorized_06/blackberry_3278a9d5-891d-4c6a-acc3-7bd972888b5c.svg \
  'Blazer with notched lapels' adeca2a9-4991-40c1-9620-baf03987dc2a pictographic-primitives/clothes/blazer_adeca2a9-4991-40c1-9620-baf03987dc2a.svg
