#!/bin/bash
# Batch 16/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/crescent-moon  source 1f947813-75bf-523b-bb36-5f6abbd3d57b
#   solo/crested-penguin  source b013a26e-4b3d-4d2f-a975-ca81de5ad6ce
#   solo/cricket-batter-with-raised-bat  source 1f09cd41-0bfa-474e-aa21-4f4bf44d8ab4
#   solo/crocodile-in-water  source ca6a591c-ff28-52f1-afee-3a6b95328acd
#   solo/croissant-and-coffee  source 15142e4e-b0bd-491b-8e9e-d5620b4c6f6c
#   solo/croissant-batch-011-10  source f9e55377-8da9-5927-845b-403bea7db251
#   solo/crop-rotate  source b05e7a98-e0c7-5855-a771-4dc4b12ff639
#   solo/cross-country-skier  source 4ed29164-79b1-5c31-a787-c6eaf3105619
#   solo/crossed-fingers-with-extended-thumb-batch-021-08  source ffa5f097-3a06-4fd0-9be9-200d8a58103b
#   solo/crossed-fingers-with-folded-thumb-batch-021-07  source 05f00c7f-9195-41aa-b8b1-c15ae7c59bd3
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Crescent moon' 1f947813-75bf-523b-bb36-5f6abbd3d57b 'pictographic-primitives/culture/batch-02/astrology moon_1f947813-75bf-523b-bb36-5f6abbd3d57b.svg' \
  'Crested penguin' b013a26e-4b3d-4d2f-a975-ca81de5ad6ce 'pictographic-primitives/animals/penguin crested_b013a26e-4b3d-4d2f-a975-ca81de5ad6ce.svg' \
  'Cricket batter with raised bat' 1f09cd41-0bfa-474e-aa21-4f4bf44d8ab4 pictographic-primitives/_uncategorized_13/cricketer_1f09cd41-0bfa-474e-aa21-4f4bf44d8ab4.svg \
  'Crocodile in water' ca6a591c-ff28-52f1-afee-3a6b95328acd 'pictographic-primitives/animals/reptile crocodile water_ca6a591c-ff28-52f1-afee-3a6b95328acd.svg' \
  'Croissant and coffee' 15142e4e-b0bd-491b-8e9e-d5620b4c6f6c pictographic-primitives/symbol/croissant_15142e4e-b0bd-491b-8e9e-d5620b4c6f6c.svg \
  'Croissant batch 011 10' f9e55377-8da9-5927-845b-403bea7db251 'pictographic-primitives/food/breakfast croissant_f9e55377-8da9-5927-845b-403bea7db251.svg' \
  'Crop rotate' b05e7a98-e0c7-5855-a771-4dc4b12ff639 'pictographic-primitives/design/crop rotate_b05e7a98-e0c7-5855-a771-4dc4b12ff639.svg' \
  'Cross country skier' 4ed29164-79b1-5c31-a787-c6eaf3105619 'pictographic-primitives/sports/skiing cross country_4ed29164-79b1-5c31-a787-c6eaf3105619.svg' \
  'Crossed fingers with extended thumb batch 021 08' ffa5f097-3a06-4fd0-9be9-200d8a58103b 'pictographic-primitives/other/finger crossed_ffa5f097-3a06-4fd0-9be9-200d8a58103b.svg' \
  'Crossed fingers with folded thumb batch 021 07' 05f00c7f-9195-41aa-b8b1-c15ae7c59bd3 'pictographic-primitives/other/finger crossed 1_05f00c7f-9195-41aa-b8b1-c15ae7c59bd3.svg'
