#!/bin/bash
# Batch 57/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/two-finger-swipe-right-solo  source 7fc48e97-cf9e-4fd7-bba0-99fe9841fc3b
#   solo/two-hands-cupping-a-building  source 8788efae-9ba8-4acc-a2e4-90bca5c7c8d4
#   solo/two-kidney-beans  source c8eb6f70-a59a-410a-ab73-429758565aa2
#   solo/two-open-hands-beneath-a-heart  source 2d833c6d-7e3c-4f1d-81d3-751c131f3ff5
#   solo/two-row-shape-exchange-diagram  source e7212277-1195-4f90-a385-78a39c6d9fa9
#   solo/two-skulls-hanging-from-loop  source dc12832a-b75c-4002-ad7b-827928ab99e4
#   solo/two-slanted-segmented-strips  source c897c956-5934-483f-ac07-2cf2fa325d40
#   solo/two-standing-children  source 161a2ee8-8f26-48f5-bd6b-81fb11645a12
#   solo/two-standing-figures-with-round-heads  source 0b9cd48a-e936-49e5-8102-fd8d2a559571
#   solo/two-standing-people  source da65a8df-c40a-4960-bff3-74262390682c
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Two finger swipe right solo' 7fc48e97-cf9e-4fd7-bba0-99fe9841fc3b 'pictographic-primitives/_uncategorized_20/gesture flip right_7fc48e97-cf9e-4fd7-bba0-99fe9841fc3b.svg' \
  'Two hands cupping a building' 8788efae-9ba8-4acc-a2e4-90bca5c7c8d4 'pictographic-primitives/_uncategorized_32/real estate favorite hold building_8788efae-9ba8-4acc-a2e4-90bca5c7c8d4.svg' \
  'Two kidney beans' c8eb6f70-a59a-410a-ab73-429758565aa2 'pictographic-primitives/food/kidney bean_c8eb6f70-a59a-410a-ab73-429758565aa2.svg' \
  'Two open hands beneath a heart' 2d833c6d-7e3c-4f1d-81d3-751c131f3ff5 'pictographic-primitives/_uncategorized_33/romance pride lgbt heart protect hand gesture_2d833c6d-7e3c-4f1d-81d3-751c131f3ff5.svg' \
  'Two row shape exchange diagram' e7212277-1195-4f90-a385-78a39c6d9fa9 'pictographic-primitives/_uncategorized_02/amazon s3 tiering access pattern_e7212277-1195-4f90-a385-78a39c6d9fa9.svg' \
  'Two skulls hanging from loop' dc12832a-b75c-4002-ad7b-827928ab99e4 'pictographic-primitives/_uncategorized_18/fantasy medieval bounty hunter 1_dc12832a-b75c-4002-ad7b-827928ab99e4.svg' \
  'Two slanted segmented strips' c897c956-5934-483f-ac07-2cf2fa325d40 pictographic-primitives/crime/scene_c897c956-5934-483f-ac07-2cf2fa325d40.svg \
  'Two standing children' 161a2ee8-8f26-48f5-bd6b-81fb11645a12 'pictographic-primitives/kids/kids full body_161a2ee8-8f26-48f5-bd6b-81fb11645a12.svg' \
  'Two standing figures with round heads' 0b9cd48a-e936-49e5-8102-fd8d2a559571 pictographic-primitives/_uncategorized_17/escort_0b9cd48a-e936-49e5-8102-fd8d2a559571.svg \
  'Two standing people' da65a8df-c40a-4960-bff3-74262390682c 'pictographic-primitives/other/two persons_5e8b621f-4f10-4323-943d-1337196c6e73.svg'
