#!/bin/bash
# Batch 3/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/baby-face-with-bow  source 724c83b9-dfbc-417a-b236-a8b1fd9f3b71
#   solo/baseball-field-beneath-a-scoreboard  source 0a9ee5d8-3550-452a-b859-653ff3a8c18e
#   solo/batch-02-desktop-computer-computers  source 94bf7c3e-3c0a-4019-a95a-f28f2638320e
#   solo/batch-05-ribbon-tie  source a8df920a-b5e4-42ca-a8cb-d0665fd4de17
#   solo/bather-sitting-in-a-rounded-tub  source adb04192-9291-4a64-8bd6-a8f21d407e1b
#   solo/battery-with-medium-charge  source e4492a9c-8c97-4b9a-9c29-d08262d7e796
#   solo/bear-muzzle-face  source 8d5b656b-3421-5a09-b55b-b470ebf0175b
#   solo/bearded-gnome-in-bent-cap  source ecf9e5e2-2492-45f9-962a-2754de0f8147
#   solo/bearded-pirate-beside-cutlass  source c8320437-caa5-4ec9-8b7a-42c57db14a5f
#   solo/bearded-pirate-with-crossed-hat-mark  source 871b202b-58cd-4c8b-af66-2a006eddce86
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Baby face with bow' 724c83b9-dfbc-417a-b236-a8b1fd9f3b71 'pictographic-primitives/babies/baby girl_724c83b9-dfbc-417a-b236-a8b1fd9f3b71.svg' \
  'Baseball field beneath a scoreboard' 0a9ee5d8-3550-452a-b859-653ff3a8c18e 'pictographic-primitives/_uncategorized_05/baseball score_0a9ee5d8-3550-452a-b859-653ff3a8c18e.svg' \
  'Batch 02 desktop computer computers' 94bf7c3e-3c0a-4019-a95a-f28f2638320e 'pictographic-primitives/computers/batch-02/desktop computer_94bf7c3e-3c0a-4019-a95a-f28f2638320e.svg' \
  'Batch 05 ribbon tie' a8df920a-b5e4-42ca-a8cb-d0665fd4de17 'pictographic-primitives/accessories/batch-05/ribbon tie_a8df920a-b5e4-42ca-a8cb-d0665fd4de17.svg' \
  'Bather sitting in a rounded tub' adb04192-9291-4a64-8bd6-a8f21d407e1b 'pictographic-primitives/_uncategorized_06/bathroom tub person_adb04192-9291-4a64-8bd6-a8f21d407e1b.svg' \
  'Battery with medium charge' e4492a9c-8c97-4b9a-9c29-d08262d7e796 'pictographic-primitives/devices/charging battery almost full_e4492a9c-8c97-4b9a-9c29-d08262d7e796.svg' \
  'Bear muzzle face' 8d5b656b-3421-5a09-b55b-b470ebf0175b pictographic-primitives/animals/tiger_8d5b656b-3421-5a09-b55b-b470ebf0175b.svg \
  'Bearded gnome in bent cap' ecf9e5e2-2492-45f9-962a-2754de0f8147 pictographic-primitives/video-games/batch-04/gnome_ecf9e5e2-2492-45f9-962a-2754de0f8147.svg \
  'Bearded pirate beside cutlass' c8320437-caa5-4ec9-8b7a-42c57db14a5f pictographic-primitives/avatars/pirate_c8320437-caa5-4ec9-8b7a-42c57db14a5f.svg \
  'Bearded pirate with crossed hat mark' 871b202b-58cd-4c8b-af66-2a006eddce86 pictographic-primitives/avatars/pirate_871b202b-58cd-4c8b-af66-2a006eddce86.svg
