#!/bin/bash
# Batch 37/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/leaping-dog-with-ball  source 4796ac23-c435-44ff-88be-e29fc6d01cfc
#   solo/leftward-target-control-batch-015-12  source 13494d07-de78-47e1-ad01-183cb6251326
#   solo/light-bulb-f6100fd8-d678-44ff-9012-620f880d9c9c  source f6100fd8-d678-44ff-9012-620f880d9c9c
#   solo/location-pin-ground  source 632bbd50-870e-4274-87d8-51bc5834f214
#   solo/long-muzzled-baboon-face  source 43a539c3-82f4-4fbd-b778-c77d1e22af44
#   solo/long-rounded-tip-kitchen-knife  source 228264ac-5026-43da-8759-cb87af800439
#   solo/looped-brass-bugle  source 1c3b1dee-2c1a-4e89-91de-95172d2201db
#   solo/looped-power-cable-79eae0ea  source 79eae0ea-a0a3-48d0-a56a-a874914d50c3
#   solo/love-compatibility  source 13ea8ba1-9370-50ce-9da5-f3a7facdf796
#   solo/low-battery  source 49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Leaping dog with ball' 4796ac23-c435-44ff-88be-e29fc6d01cfc 'pictographic-primitives/pets/dog bring ball training_4796ac23-c435-44ff-88be-e29fc6d01cfc.svg' \
  'Leftward target control batch 015 12' 13494d07-de78-47e1-ad01-183cb6251326 'pictographic-primitives/interface-essential/cursor move target left_13494d07-de78-47e1-ad01-183cb6251326.svg' \
  'Light bulb f6100fd8 d678 44ff 9012 620f880d9c9c' f6100fd8-d678-44ff-9012-620f880d9c9c 'pictographic-primitives/lights/light bulb_f6100fd8-d678-44ff-9012-620f880d9c9c.svg' \
  'Location pin ground' 632bbd50-870e-4274-87d8-51bc5834f214 'pictographic-primitives/symbol/location dot_632bbd50-870e-4274-87d8-51bc5834f214.svg' \
  'Long muzzled baboon face' 43a539c3-82f4-4fbd-b778-c77d1e22af44 pictographic-primitives/_uncategorized_05/baboon_43a539c3-82f4-4fbd-b778-c77d1e22af44.svg \
  'Long rounded tip kitchen knife' 228264ac-5026-43da-8759-cb87af800439 pictographic-primitives/_uncategorized_07/blade_228264ac-5026-43da-8759-cb87af800439.svg \
  'Looped brass bugle' 1c3b1dee-2c1a-4e89-91de-95172d2201db pictographic-primitives/_uncategorized_08/brass_1c3b1dee-2c1a-4e89-91de-95172d2201db.svg \
  'Looped power cable 79eae0ea' 79eae0ea-a0a3-48d0-a56a-a874914d50c3 'pictographic-primitives/container/circle cable_79eae0ea-a0a3-48d0-a56a-a874914d50c3.svg' \
  'Love compatibility' 13ea8ba1-9370-50ce-9da5-f3a7facdf796 'pictographic-primitives/romance/love compatibility_13ea8ba1-9370-50ce-9da5-f3a7facdf796.svg' \
  'Low battery' 49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8 'pictographic-primitives/mobile/charging battery low_49b6bd6a-0b34-4b3d-ac40-03cf5a529dc8.svg'
