#!/bin/bash
# Batch 36/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/json-web-token-logo  source 25a68e69-255f-4309-949c-f73d27e485d2
#   solo/kermit-face  source 4eff967d-5df4-43e4-98a7-d78f84b1fc39
#   solo/key-and-padlock  source 1ac8d6ec-d8d0-4f95-a290-6b9afd057567
#   solo/kick-logo  source a6959b4d-8fca-4be5-b218-d5cd4e2008ba
#   solo/kissing-face-heart  source 08de5c3e-418d-4732-b0b0-0789943abce3
#   solo/knight-with-equipment  source da426a95-1cd7-478a-9e67-d0cce97ae1dd
#   solo/konjac-sponge  source 4527205d-f4e9-4989-85e1-f0ba94c4cdd5
#   solo/laptop-small-squares  source 71714a04-dd1b-4fab-90a6-dbd391dacaf5
#   solo/launching-rocket  source e0a806b8-a1ad-489e-a872-c6a7caf3c71f
#   solo/leaping-antelope-solo  source 79daad3e-b421-490c-80f2-e08549dfba1b
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Json web token logo' 25a68e69-255f-4309-949c-f73d27e485d2 'pictographic-primitives/logos/json web token logo_25a68e69-255f-4309-949c-f73d27e485d2.svg' \
  'Kermit face' 4eff967d-5df4-43e4-98a7-d78f84b1fc39 pictographic-primitives/video-games/batch-05/kermit_4eff967d-5df4-43e4-98a7-d78f84b1fc39.svg \
  'Key and padlock' 1ac8d6ec-d8d0-4f95-a290-6b9afd057567 'pictographic-primitives/symbol/key and lock_1ac8d6ec-d8d0-4f95-a290-6b9afd057567.svg' \
  'Kick logo' a6959b4d-8fca-4be5-b218-d5cd4e2008ba 'pictographic-primitives/logos/kick logo_a6959b4d-8fca-4be5-b218-d5cd4e2008ba.svg' \
  'Kissing face heart' 08de5c3e-418d-4732-b0b0-0789943abce3 'pictographic-primitives/_uncategorized_17/face kiss_08de5c3e-418d-4732-b0b0-0789943abce3.svg' \
  'Knight with equipment' da426a95-1cd7-478a-9e67-d0cce97ae1dd 'pictographic-primitives/_uncategorized_39/video game knight_da426a95-1cd7-478a-9e67-d0cce97ae1dd.svg' \
  'Konjac sponge' 4527205d-f4e9-4989-85e1-f0ba94c4cdd5 'pictographic-primitives/_uncategorized_39/vegetable konjac_4527205d-f4e9-4989-85e1-f0ba94c4cdd5.svg' \
  'Laptop small squares' 71714a04-dd1b-4fab-90a6-dbd391dacaf5 'pictographic-primitives/other/laptop small squares_71714a04-dd1b-4fab-90a6-dbd391dacaf5.svg' \
  'Launching rocket' e0a806b8-a1ad-489e-a872-c6a7caf3c71f 'pictographic-primitives/business/startup launch_e0a806b8-a1ad-489e-a872-c6a7caf3c71f.svg' \
  'Leaping antelope solo' 79daad3e-b421-490c-80f2-e08549dfba1b 'pictographic-primitives/animals/deer jump_79daad3e-b421-490c-80f2-e08549dfba1b.svg'
