#!/bin/bash
# Batch 2/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/anklet  source 83499877-9f6d-4f70-975d-59ade9b78b2f
#   solo/apple-with-upright-leaf  source 8dab56ea-1c91-48e4-9197-a2a2de0bb76d
#   solo/arabian-man  source dd92cb2d-e66d-53d1-835f-92be92e0873e
#   solo/arrow-down-rounded-outline  source 6747c5ea-98ee-4045-b34c-2a968c515c7a
#   solo/arrow-turn-right  source 90bda1dc-4ea8-4d9e-aace-a5784e398b7c
#   solo/arrow-turning-left-with-dashed-tail  source 0e26bfd0-c84a-5afd-af45-9efcb51b9f95
#   solo/athlete-pole-vaulting  source 756dc826-ac42-5822-a4ca-d5598175bce1
#   solo/athlete-running-right  source 47d26a02-2221-453b-a560-39c0733c3bec
#   solo/automatic-rifle  source 835277d4-590e-5008-a9cb-07213ea668e9
#   solo/avatar-jockey-man  source d9262e24-63e6-54ce-9aa8-9061addf48f8
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Anklet 83499877-9f6d-4f70-975d-59ade9b78b2f pictographic-primitives/_uncategorized_03/anklet_83499877-9f6d-4f70-975d-59ade9b78b2f.svg \
  'Apple with upright leaf' 8dab56ea-1c91-48e4-9197-a2a2de0bb76d pictographic-primitives/_uncategorized_12/codling_8dab56ea-1c91-48e4-9197-a2a2de0bb76d.svg \
  'Arabian man' dd92cb2d-e66d-53d1-835f-92be92e0873e 'pictographic-primitives/avatars/arabian man_dd92cb2d-e66d-53d1-835f-92be92e0873e.svg' \
  'Arrow down rounded outline' 6747c5ea-98ee-4045-b34c-2a968c515c7a 'pictographic-primitives/_uncategorized_10/caret down_6747c5ea-98ee-4045-b34c-2a968c515c7a.svg' \
  'Arrow turn right' 90bda1dc-4ea8-4d9e-aace-a5784e398b7c 'pictographic-primitives/symbol/arrow turn right_90bda1dc-4ea8-4d9e-aace-a5784e398b7c.svg' \
  'Arrow turning left with dashed tail' 0e26bfd0-c84a-5afd-af45-9efcb51b9f95 'pictographic-primitives/arrows/arrow dash corner point left_0e26bfd0-c84a-5afd-af45-9efcb51b9f95.svg' \
  'Athlete pole vaulting' 756dc826-ac42-5822-a4ca-d5598175bce1 'pictographic-primitives/sports/athletics pole vault_756dc826-ac42-5822-a4ca-d5598175bce1.svg' \
  'Athlete running right' 47d26a02-2221-453b-a560-39c0733c3bec 'pictographic-primitives/sports/athletics running 1_47d26a02-2221-453b-a560-39c0733c3bec.svg' \
  'Automatic rifle' 835277d4-590e-5008-a9cb-07213ea668e9 'pictographic-primitives/war/modern weapon machine gun_835277d4-590e-5008-a9cb-07213ea668e9.svg' \
  'Avatar jockey man' d9262e24-63e6-54ce-9aa8-9061addf48f8 'pictographic-primitives/avatars/avatar jockey man_d9262e24-63e6-54ce-9aa8-9061addf48f8.svg'
