#!/bin/bash
# Batch 25/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/full-battery-segmented  source 33faddf4-6c93-4508-bf49-bd5a27dd53af
#   solo/furby-toy  source c8ed2a82-660e-4fb3-97c4-3f6f0a34445d
#   solo/gamer-with-controller  source 04994de3-17cd-4356-ab95-14fde2baca81
#   solo/gantt-chart-with-linked-tasks  source 012ac09f-44c3-417b-a7cd-1dcaf5b7540e
#   solo/gantt-chart-with-progress-dividers  source c6f9a1df-2dbc-4ed6-a75b-2dbdfa9e9de1
#   solo/gazelle-facing-right  source ad100aeb-0efd-4518-a526-a736e51e1704
#   solo/gear-settings  source 95406251-8b85-440b-813a-359dd10112c9
#   solo/gear-with-branching-lines-batch-013  source 20a1fb0b-4458-4956-9328-ab0e436276f4
#   solo/gears-and-pins  source 6441c71e-2430-439c-b9ba-705297d8ec05
#   solo/genie  source f9d2a78b-2eb0-40a5-bcec-c567992dd9f2
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Full battery segmented' 33faddf4-6c93-4508-bf49-bd5a27dd53af 'pictographic-primitives/mobile/charging battery full_33faddf4-6c93-4508-bf49-bd5a27dd53af.svg' \
  'Furby toy' c8ed2a82-660e-4fb3-97c4-3f6f0a34445d 'pictographic-primitives/kids/toys furby_c8ed2a82-660e-4fb3-97c4-3f6f0a34445d.svg' \
  'Gamer with controller' 04994de3-17cd-4356-ab95-14fde2baca81 pictographic-primitives/recreation/gamer_04994de3-17cd-4356-ab95-14fde2baca81.svg \
  'Gantt chart with linked tasks' 012ac09f-44c3-417b-a7cd-1dcaf5b7540e 'pictographic-primitives/business/workflow gantt chart_012ac09f-44c3-417b-a7cd-1dcaf5b7540e.svg' \
  'Gantt chart with progress dividers' c6f9a1df-2dbc-4ed6-a75b-2dbdfa9e9de1 'pictographic-primitives/business/workflow gantt chart_c6f9a1df-2dbc-4ed6-a75b-2dbdfa9e9de1.svg' \
  'Gazelle facing right' ad100aeb-0efd-4518-a526-a736e51e1704 pictographic-primitives/_uncategorized_20/gazelle_ad100aeb-0efd-4518-a526-a736e51e1704.svg \
  'Gear settings' 95406251-8b85-440b-813a-359dd10112c9 'pictographic-primitives/symbol/state setting_95406251-8b85-440b-813a-359dd10112c9.svg' \
  'Gear with branching lines batch 013' 20a1fb0b-4458-4956-9328-ab0e436276f4 'pictographic-primitives/interface-essential/set factor standard_20a1fb0b-4458-4956-9328-ab0e436276f4.svg' \
  'Gears and pins' 6441c71e-2430-439c-b9ba-705297d8ec05 'pictographic-primitives/programing/internet of thing graph service setting_6441c71e-2430-439c-b9ba-705297d8ec05.svg' \
  Genie f9d2a78b-2eb0-40a5-bcec-c567992dd9f2 pictographic-primitives/_uncategorized_20/genie_f9d2a78b-2eb0-40a5-bcec-c567992dd9f2.svg
