#!/bin/bash
# Batch 63/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/winged-harpy-profile  source b87b798c-92b9-4644-b23b-705c2c8cf361
#   solo/winged-lion  source 913ea823-995f-439f-bf00-7e196c2b8d57
#   solo/winged-person  source 81bf1694-b0dd-4a9d-ba64-39817556a8cf
#   solo/winged-serpent-dragon  source 73f4cc87-427b-5322-aec8-d42d4ff0929d
#   solo/wireless-earbuds-charging-case-solo-b001-15  source 9ae8162b-1fa3-4f3e-a7f2-5375c421b45f
#   solo/wireless-mobile-yuan-payment-solo  source 54325bec-9e76-47f3-ae84-9ced16fe0a3a
#   solo/wireless-mouse-with-signal  source 49aa3ae9-4599-4f0a-839e-996103c1a778
#   solo/witch-in-pointed-hat  source 60df543d-dca5-4914-a5c9-114df422b161
#   solo/woman-and-person-profile-icons-batch-033  source f2eb39da-ca20-4f47-8b9c-8c8796ff574d
#   solo/woman-at-podium  source 764d4993-c502-42d1-9520-e7dd676c9d28
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Winged harpy profile' b87b798c-92b9-4644-b23b-705c2c8cf361 pictographic-primitives/_uncategorized_22/harpy_b87b798c-92b9-4644-b23b-705c2c8cf361.svg \
  'Winged lion' 913ea823-995f-439f-bf00-7e196c2b8d57 pictographic-primitives/animals/leopard_913ea823-995f-439f-bf00-7e196c2b8d57.svg \
  'Winged person' 81bf1694-b0dd-4a9d-ba64-39817556a8cf pictographic-primitives/_uncategorized_40/wingman_81bf1694-b0dd-4a9d-ba64-39817556a8cf.svg \
  'Winged serpent dragon' 73f4cc87-427b-5322-aec8-d42d4ff0929d 'pictographic-primitives/video-games/batch-03/fantasy amphiptere dragon_73f4cc87-427b-5322-aec8-d42d4ff0929d.svg' \
  'Wireless earbuds charging case solo b001 15' 9ae8162b-1fa3-4f3e-a7f2-5375c421b45f 'pictographic-primitives/audio/earpods charge_9ae8162b-1fa3-4f3e-a7f2-5375c421b45f.svg' \
  'Wireless mobile yuan payment solo' 54325bec-9e76-47f3-ae84-9ced16fe0a3a 'pictographic-primitives/other/mobile phone yuan sign wireless_54325bec-9e76-47f3-ae84-9ced16fe0a3a.svg' \
  'Wireless mouse with signal' 49aa3ae9-4599-4f0a-839e-996103c1a778 'pictographic-primitives/computers/batch-07/mouse remote_49aa3ae9-4599-4f0a-839e-996103c1a778.svg' \
  'Witch in pointed hat' 60df543d-dca5-4914-a5c9-114df422b161 pictographic-primitives/video-games/batch-13/witch_60df543d-dca5-4914-a5c9-114df422b161.svg \
  'Woman and person profile icons batch 033' f2eb39da-ca20-4f47-8b9c-8c8796ff574d 'pictographic-primitives/other/two users woman_f2eb39da-ca20-4f47-8b9c-8c8796ff574d.svg' \
  'Woman at podium' 764d4993-c502-42d1-9520-e7dd676c9d28 'pictographic-primitives/users/woman podium_764d4993-c502-42d1-9520-e7dd676c9d28.svg'
