#!/bin/bash
# Batch 43/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/monitor-shuttlecock  source 675d2e83-bae0-46ca-b68a-04732a2c88a9
#   solo/monitor-small-squares  source 1aef3c2a-6d0d-43a2-9616-698d70dc5298
#   solo/movie-production-clapperboard  source 7812933e-4da0-4067-9131-d948a045fef8
#   solo/necklace-bust-form  source 57cd05d6-858f-52cb-9183-c06310d44846
#   solo/number  source 1edccb27-38c1-5d49-b045-3faf028ee95b
#   solo/open-helping-hand  source 21f148ad-8725-429c-aa23-cad9257d7f13
#   solo/open-palm-hand-14e0f209-1f73-4be1-9637-df2de37b666b  source 14e0f209-1f73-4be1-9637-df2de37b666b
#   solo/open-straight-razor-with-curved-handle  source ee682589-6a41-5314-b057-2d2077e1ed8e
#   solo/overlapping-chain-rings  source f3554d59-4ee9-5ba8-bc14-5b1324691503
#   solo/oxygen-mask-in-profile-271fffbf  source 271fffbf-c0f5-4271-aa4c-60ff67604b47
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Monitor shuttlecock' 675d2e83-bae0-46ca-b68a-04732a2c88a9 'pictographic-primitives/other/monitor shuttlecock_675d2e83-bae0-46ca-b68a-04732a2c88a9.svg' \
  'Monitor small squares' 1aef3c2a-6d0d-43a2-9616-698d70dc5298 'pictographic-primitives/other/monitor small squares_1aef3c2a-6d0d-43a2-9616-698d70dc5298.svg' \
  'Movie production clapperboard' 7812933e-4da0-4067-9131-d948a045fef8 pictographic-primitives/_uncategorized_11/clapboard_7812933e-4da0-4067-9131-d948a045fef8.svg \
  'Necklace bust form' 57cd05d6-858f-52cb-9183-c06310d44846 pictographic-primitives/accessories/batch-03/necklace_57cd05d6-858f-52cb-9183-c06310d44846.svg \
  Number 1edccb27-38c1-5d49-b045-3faf028ee95b pictographic-primitives/interface-essential/number_1edccb27-38c1-5d49-b045-3faf028ee95b.svg \
  'Open helping hand' 21f148ad-8725-429c-aa23-cad9257d7f13 'pictographic-primitives/other/give hand 1_21f148ad-8725-429c-aa23-cad9257d7f13.svg' \
  'Open Palm Hand' 14e0f209-1f73-4be1-9637-df2de37b666b pictographic-primitives/holidays/hand_14e0f209-1f73-4be1-9637-df2de37b666b.svg \
  'Open straight razor with curved handle' ee682589-6a41-5314-b057-2d2077e1ed8e pictographic-primitives/crime/razor_ee682589-6a41-5314-b057-2d2077e1ed8e.svg \
  'Overlapping chain rings' f3554d59-4ee9-5ba8-bc14-5b1324691503 pictographic-primitives/interface-essential/attachment_f3554d59-4ee9-5ba8-bc14-5b1324691503.svg \
  'Oxygen mask in profile 271fffbf' 271fffbf-c0f5-4271-aa4c-60ff67604b47 'pictographic-primitives/health/oxygen mask head side_271fffbf-c0f5-4271-aa4c-60ff67604b47.svg'
