#!/bin/bash
# Batch 22/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/euro-financial-document-solo  source 36b5ce8c-0ffe-4bbc-9abc-5d99e806b0d9
#   solo/exposure-compensation  source a0943d1c-4cfd-4ede-af66-e71962ed04ec
#   solo/exposure-compensation-outlined  source 7e0c4b3a-5601-40b2-8ea5-02186da2356f
#   solo/farmer-guiding-plough  source 3bc488e9-7d66-4c76-9ac2-7bb53e9db32f
#   solo/farmer-holding-crop-and-sickle  source 1efaaba1-675b-4453-93c8-175f701635ac
#   solo/farmer-standing-beside-pitchfork  source 82d178e5-3f74-432a-987e-abc1c9057ae8
#   solo/farmer-working-long-handled-hoe  source cf3ffa48-69ee-55a9-b0f2-b59ed9778e0e
#   solo/female-teacher-beside-board-batch-022-13  source 46825186-2cd0-49e4-9bcb-dfcef97654be
#   solo/female-user-profile-icon-solo  source 7e7928dc-c2b2-4979-be45-5ca674afd12d
#   solo/file-shield  source 4b6ec7ff-fa5a-4489-9bab-e1e940ac236f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Euro financial document solo' 36b5ce8c-0ffe-4bbc-9abc-5d99e806b0d9 'pictographic-primitives/other/euro bill_36b5ce8c-0ffe-4bbc-9abc-5d99e806b0d9.svg' \
  'Exposure compensation' a0943d1c-4cfd-4ede-af66-e71962ed04ec 'pictographic-primitives/photography/light mode exposure 1_a0943d1c-4cfd-4ede-af66-e71962ed04ec.svg' \
  'Exposure compensation outlined' 7e0c4b3a-5601-40b2-8ea5-02186da2356f 'pictographic-primitives/photography/light mode exposure_7e0c4b3a-5601-40b2-8ea5-02186da2356f.svg' \
  'Farmer guiding plough' 3bc488e9-7d66-4c76-9ac2-7bb53e9db32f pictographic-primitives/_uncategorized_31/plowman_3bc488e9-7d66-4c76-9ac2-7bb53e9db32f.svg \
  'Farmer holding crop and sickle' 1efaaba1-675b-4453-93c8-175f701635ac 'pictographic-primitives/farming/farmer crops_1efaaba1-675b-4453-93c8-175f701635ac.svg' \
  'Farmer standing beside pitchfork' 82d178e5-3f74-432a-987e-abc1c9057ae8 pictographic-primitives/farming/farmer_82d178e5-3f74-432a-987e-abc1c9057ae8.svg \
  'Farmer working long handled hoe' cf3ffa48-69ee-55a9-b0f2-b59ed9778e0e 'pictographic-primitives/farming/harvest farmer_cf3ffa48-69ee-55a9-b0f2-b59ed9778e0e.svg' \
  'Female teacher beside board batch 022 13' 46825186-2cd0-49e4-9bcb-dfcef97654be 'pictographic-primitives/other/female teacher_46825186-2cd0-49e4-9bcb-dfcef97654be.svg' \
  'Female user profile icon solo' 7e7928dc-c2b2-4979-be45-5ca674afd12d 'pictographic-primitives/other/full body women_7e7928dc-c2b2-4979-be45-5ca674afd12d.svg' \
  'File shield' 4b6ec7ff-fa5a-4489-9bab-e1e940ac236f 'pictographic-primitives/other/file shield_4b6ec7ff-fa5a-4489-9bab-e1e940ac236f.svg'
