#!/bin/bash
# Batch 50/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/square-y  source 69b6ff74-9803-422f-8ad2-afd60e6ee1e0
#   solo/square-z  source 5b8e48f8-a233-4d49-8f8a-22c3df94a297
#   solo/squeeze-sides  source 8d871e7d-03c3-4f02-90aa-ec0ac69a56b5
#   solo/squid  source 6b1b950d-cc96-5942-b04e-c7eb45776f56
#   solo/stack-unstack-column  source ff75519b-afd0-4da5-b995-1999fe2b031a
#   solo/stage-microphone-on-stand  source 94f17916-461c-598b-b681-c05b07b91a3d
#   solo/standing-back-stretch  source a263476f-1a0c-4444-b3ba-5f01cb7a5e94
#   solo/standing-desktop-computer-worker  source 2fd37035-c393-4771-b96f-502ab4be6f36
#   solo/standing-hen-with-raised-tail  source a8d6f09a-0963-413b-9f3e-2fdf85be5892
#   solo/state-question  source 2e0fbeaa-154e-4e0a-860a-5b0e0542cf5f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Square y' 69b6ff74-9803-422f-8ad2-afd60e6ee1e0 'pictographic-primitives/_uncategorized_36/square y_69b6ff74-9803-422f-8ad2-afd60e6ee1e0.svg' \
  'Square z' 5b8e48f8-a233-4d49-8f8a-22c3df94a297 'pictographic-primitives/_uncategorized_36/square z_5b8e48f8-a233-4d49-8f8a-22c3df94a297.svg' \
  'Squeeze sides' 8d871e7d-03c3-4f02-90aa-ec0ac69a56b5 'pictographic-primitives/mobile/squeeze sides_8d871e7d-03c3-4f02-90aa-ec0ac69a56b5.svg' \
  Squid 6b1b950d-cc96-5942-b04e-c7eb45776f56 pictographic-primitives/animals/squid_6b1b950d-cc96-5942-b04e-c7eb45776f56.svg \
  'Stack unstack column' ff75519b-afd0-4da5-b995-1999fe2b031a 'pictographic-primitives/interface-essential/stack unstack column_ff75519b-afd0-4da5-b995-1999fe2b031a.svg' \
  'Stage microphone on stand' 94f17916-461c-598b-b681-c05b07b91a3d 'pictographic-primitives/audio/microphone stage_94f17916-461c-598b-b681-c05b07b91a3d.svg' \
  'Standing back stretch' a263476f-1a0c-4444-b3ba-5f01cb7a5e94 'pictographic-primitives/sports/yoga back stretch_a263476f-1a0c-4444-b3ba-5f01cb7a5e94.svg' \
  'Standing desktop computer worker' 2fd37035-c393-4771-b96f-502ab4be6f36 'pictographic-primitives/work/desk computer base work standing user_2fd37035-c393-4771-b96f-502ab4be6f36.svg' \
  'Standing hen with raised tail' a8d6f09a-0963-413b-9f3e-2fdf85be5892 pictographic-primitives/_uncategorized_09/capon_a8d6f09a-0963-413b-9f3e-2fdf85be5892.svg \
  'State question' 2e0fbeaa-154e-4e0a-860a-5b0e0542cf5f 'pictographic-primitives/other/state question_2e0fbeaa-154e-4e0a-860a-5b0e0542cf5f.svg'
