#!/bin/bash
# Batch 31/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hands-cupping-a-profile-head  source efd5cbb3-73a1-456c-9d82-fa7470f26ad4
#   solo/hands-gripping-wrists  source 6f5654b6-d336-40f6-84c1-e153d3ad1fc3
#   solo/hands-supporting-child  source de2a447f-9464-4dd2-8a82-6bf0842bf389
#   solo/hands-supporting-hard-hat  source 20214d85-2a10-45f3-974e-7a15e7241f74
#   solo/hanging-toilet-paper-roll-solo  source f361cec1-680c-41d1-8ef8-1055d54cab23
#   solo/happy-face-with-sideways-tongue-solo  source a2b16bc0-fda9-42be-8b90-0bef7d9dc58b
#   solo/head-medical-plus-content  source 348cbff9-1f65-4ac0-894f-5968b56f3054
#   solo/head-scarf-tie-avatar  source d91b104f-4bd1-4359-bf72-c9162bc1c67b
#   solo/heart-message-22-solo  source 2a3f04f0-a404-41db-90b7-a6ee5813413b
#   solo/heart-user  source e7e97355-bccb-465c-ae55-5037fd70d291
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hands cupping a profile head' efd5cbb3-73a1-456c-9d82-fa7470f26ad4 'pictographic-primitives/_uncategorized_33/self care 2_efd5cbb3-73a1-456c-9d82-fa7470f26ad4.svg' \
  'Hands gripping wrists' 6f5654b6-d336-40f6-84c1-e153d3ad1fc3 'pictographic-primitives/work/workflow teamwork hand lock_6f5654b6-d336-40f6-84c1-e153d3ad1fc3.svg' \
  'Hands supporting child' de2a447f-9464-4dd2-8a82-6bf0842bf389 'pictographic-primitives/kids/child care_de2a447f-9464-4dd2-8a82-6bf0842bf389.svg' \
  'Hands supporting hard hat' 20214d85-2a10-45f3-974e-7a15e7241f74 'pictographic-primitives/_uncategorized_24/labor hands action_20214d85-2a10-45f3-974e-7a15e7241f74.svg' \
  'Hanging toilet paper roll solo' f361cec1-680c-41d1-8ef8-1055d54cab23 'pictographic-primitives/wayfinding/toilet paper_f361cec1-680c-41d1-8ef8-1055d54cab23.svg' \
  'Happy face with sideways tongue solo' a2b16bc0-fda9-42be-8b90-0bef7d9dc58b 'pictographic-primitives/_uncategorized_17/face grin tongue_a2b16bc0-fda9-42be-8b90-0bef7d9dc58b.svg' \
  'Head medical plus content' 348cbff9-1f65-4ac0-894f-5968b56f3054 'pictographic-primitives/symbol/head cross_348cbff9-1f65-4ac0-894f-5968b56f3054.svg' \
  'Head scarf tie avatar' d91b104f-4bd1-4359-bf72-c9162bc1c67b 'pictographic-primitives/avatars/head scarf tie_d91b104f-4bd1-4359-bf72-c9162bc1c67b.svg' \
  'Heart message 22 solo' 2a3f04f0-a404-41db-90b7-a6ee5813413b 'pictographic-primitives/symbol/messages bubble round heart_2a3f04f0-a404-41db-90b7-a6ee5813413b.svg' \
  'Heart user' e7e97355-bccb-465c-ae55-5037fd70d291 'pictographic-primitives/other/heart user_e7e97355-bccb-465c-ae55-5037fd70d291.svg'
