#!/bin/bash
# Batch 59/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/upright-lipstick-with-angled-tip  source 422fa961-4cef-5bf4-8415-0550aee83639
#   solo/upright-measuring-dropper-with-two-ticks  source 40a7d367-6379-5988-8e14-9b14f23562eb
#   solo/upright-pencil-with-deep-point  source 3193c3dc-71cd-4671-8a64-00911463d73d
#   solo/upright-rocket-round-window  source a6e0c75c-ba38-5637-ab79-106bd4d8480d
#   solo/upright-ruler  source f455b9a8-f5df-5ef0-8c51-c9d25db58703
#   solo/urinary-system  source 919f7b7f-3788-4327-997e-bf56456e04cd
#   solo/usb  source e4b1f036-4c20-4e55-975c-b249f0a098fc
#   solo/usb-type-c  source c0a14e2a-4419-5c4d-bceb-f564e7b8279f
#   solo/user-with-gear  source c401ded5-d2e5-41aa-afc2-b65bf262fa9e
#   solo/vectors-add-anchor  source eb962df2-7d7e-4704-b588-8cea12d18d62
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Upright lipstick with angled tip' 422fa961-4cef-5bf4-8415-0550aee83639 'pictographic-primitives/beauty/make up lipstick_422fa961-4cef-5bf4-8415-0550aee83639.svg' \
  'Upright measuring dropper with two ticks' 40a7d367-6379-5988-8e14-9b14f23562eb pictographic-primitives/design/picker_40a7d367-6379-5988-8e14-9b14f23562eb.svg \
  'Upright pencil with deep point' 3193c3dc-71cd-4671-8a64-00911463d73d 'pictographic-primitives/design/design monitor pencil_3193c3dc-71cd-4671-8a64-00911463d73d.svg' \
  'Upright rocket round window' a6e0c75c-ba38-5637-ab79-106bd4d8480d 'pictographic-primitives/science/exploration apollo saturn v_a6e0c75c-ba38-5637-ab79-106bd4d8480d.svg' \
  'Upright ruler' f455b9a8-f5df-5ef0-8c51-c9d25db58703 'pictographic-primitives/tools/measure ruler_f455b9a8-f5df-5ef0-8c51-c9d25db58703.svg' \
  'Urinary system' 919f7b7f-3788-4327-997e-bf56456e04cd 'pictographic-primitives/health/urinary system_919f7b7f-3788-4327-997e-bf56456e04cd.svg' \
  Usb e4b1f036-4c20-4e55-975c-b249f0a098fc pictographic-primitives/state/usb_e4b1f036-4c20-4e55-975c-b249f0a098fc.svg \
  'Usb type c' c0a14e2a-4419-5c4d-bceb-f564e7b8279f 'pictographic-primitives/electronics/usb type c_c0a14e2a-4419-5c4d-bceb-f564e7b8279f.svg' \
  'User with gear' c401ded5-d2e5-41aa-afc2-b65bf262fa9e 'pictographic-primitives/users/settings user_c401ded5-d2e5-41aa-afc2-b65bf262fa9e.svg' \
  'Vectors add anchor' eb962df2-7d7e-4704-b588-8cea12d18d62 'pictographic-primitives/internet/vectors add anchor_eb962df2-7d7e-4704-b588-8cea12d18d62.svg'
