#!/bin/bash
# Batch 48/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/smartphone-with-lower-bezel-75ece3f4  source 75ece3f4-5568-4178-a662-3cc71bc053be
#   solo/smartwatch-euro  source ac5e07e4-9e24-406e-8500-ef19796d1933
#   solo/smartwatch-pound-symbol  source f2d45871-ff3d-44d5-84a8-774df3bd6ba3
#   solo/soundcloud-logo  source 7c396518-42a3-4878-8de7-258d42dbabd7
#   solo/square-caret-down  source 6c091ee7-51cd-4c82-a423-c503c640b0da
#   solo/square-caret-left  source 77276159-6033-45f5-86ca-f38c7e5c2f48
#   solo/square-chevron-left  source 4bd78193-76e7-4e65-b3e3-2a7e05a8553b
#   solo/square-chevron-right  source 7d2f2187-9fda-4709-9797-8fc491eb3114
#   solo/square-dollar-solo  source 48149687-aa67-49b2-9c81-78cd430cefd6
#   solo/square-down-left  source a69a3b57-2f22-4637-ba14-3f4947054026
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Smartphone with lower bezel 75ece3f4' 75ece3f4-5568-4178-a662-3cc71bc053be 'pictographic-primitives/phones/mobile phone_75ece3f4-5568-4178-a662-3cc71bc053be.svg' \
  'Smartwatch euro' ac5e07e4-9e24-406e-8500-ef19796d1933 'pictographic-primitives/other/smart watch square euro sign_ac5e07e4-9e24-406e-8500-ef19796d1933.svg' \
  'Smartwatch pound symbol' f2d45871-ff3d-44d5-84a8-774df3bd6ba3 'pictographic-primitives/other/smart watch circle pound sign_f2d45871-ff3d-44d5-84a8-774df3bd6ba3.svg' \
  'Soundcloud logo' 7c396518-42a3-4878-8de7-258d42dbabd7 'pictographic-primitives/logos/soundcloud logo_7c396518-42a3-4878-8de7-258d42dbabd7.svg' \
  'Square caret down' 6c091ee7-51cd-4c82-a423-c503c640b0da 'pictographic-primitives/_uncategorized_35/square caret down_6c091ee7-51cd-4c82-a423-c503c640b0da.svg' \
  'Square caret left' 77276159-6033-45f5-86ca-f38c7e5c2f48 'pictographic-primitives/_uncategorized_35/square caret left_77276159-6033-45f5-86ca-f38c7e5c2f48.svg' \
  'Square chevron left' 4bd78193-76e7-4e65-b3e3-2a7e05a8553b 'pictographic-primitives/_uncategorized_35/square chevron left_4bd78193-76e7-4e65-b3e3-2a7e05a8553b.svg' \
  'Square chevron right' 7d2f2187-9fda-4709-9797-8fc491eb3114 'pictographic-primitives/_uncategorized_35/square chevron right_7d2f2187-9fda-4709-9797-8fc491eb3114.svg' \
  'Square dollar solo' 48149687-aa67-49b2-9c81-78cd430cefd6 'pictographic-primitives/_uncategorized_35/square dollar_48149687-aa67-49b2-9c81-78cd430cefd6.svg' \
  'Square down left' a69a3b57-2f22-4637-ba14-3f4947054026 'pictographic-primitives/_uncategorized_35/square down left_a69a3b57-2f22-4637-ba14-3f4947054026.svg'
