#!/bin/bash
# Batch 24/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/flexed-arm-with-left-fist-batch-045  source ee5bfb94-7340-47f3-893b-14b8899829f6
#   solo/flexing-torso  source 40884d36-f762-4ecf-a351-e11189a03a5d
#   solo/flower-with-paired-leaves  source a5bb0ebe-31d7-43c2-a177-afcbf914e9b7
#   solo/flying-blimp-airship-batch-033  source 94ee19fa-6c64-4340-9c2b-4d23bc7e3842
#   solo/four-hexagonal-nanobots  source a4ac6021-31ac-4b55-8c99-d25a6ba3e475
#   solo/four-piece-jigsaw-puzzle  source cab69194-7d72-4ec5-92ef-c43974df941f
#   solo/four-playing-card-suits  source 6c01ed88-1571-4e62-904d-509e18f64c7d
#   solo/freestyle-swimmer  source 79d7b1e9-d763-4618-aea0-fb1d2e59180b
#   solo/friends-arm-on-shoulder  source fc3c63fc-721e-43dd-a5cf-cb7496abf926
#   solo/friends-embracing  source 9879b825-1a99-4cc8-b5d3-ebca82cb7300
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Flexed arm with left fist batch 045' ee5bfb94-7340-47f3-893b-14b8899829f6 pictographic-primitives/_uncategorized_19/forearm_ee5bfb94-7340-47f3-893b-14b8899829f6.svg \
  'Flexing torso' 40884d36-f762-4ecf-a351-e11189a03a5d 'pictographic-primitives/_uncategorized_38/tough guy_40884d36-f762-4ecf-a351-e11189a03a5d.svg' \
  'Flower with paired leaves' a5bb0ebe-31d7-43c2-a177-afcbf914e9b7 'pictographic-primitives/video-games/batch-04/flower enemy_a5bb0ebe-31d7-43c2-a177-afcbf914e9b7.svg' \
  'Flying blimp airship batch 033' 94ee19fa-6c64-4340-9c2b-4d23bc7e3842 pictographic-primitives/_uncategorized_01/airship_94ee19fa-6c64-4340-9c2b-4d23bc7e3842.svg \
  'Four hexagonal nanobots' a4ac6021-31ac-4b55-8c99-d25a6ba3e475 'pictographic-primitives/_uncategorized_28/nanobots 1_a4ac6021-31ac-4b55-8c99-d25a6ba3e475.svg' \
  'Four piece jigsaw puzzle' cab69194-7d72-4ec5-92ef-c43974df941f pictographic-primitives/_uncategorized_24/jigsaw_cab69194-7d72-4ec5-92ef-c43974df941f.svg \
  'Four playing card suits' 6c01ed88-1571-4e62-904d-509e18f64c7d 'pictographic-primitives/_uncategorized_10/card game symbols_6c01ed88-1571-4e62-904d-509e18f64c7d.svg' \
  'Freestyle swimmer' 79d7b1e9-d763-4618-aea0-fb1d2e59180b pictographic-primitives/sports/swimming_79d7b1e9-d763-4618-aea0-fb1d2e59180b.svg \
  'Friends arm on shoulder' fc3c63fc-721e-43dd-a5cf-cb7496abf926 'pictographic-primitives/users/user friends 2_fc3c63fc-721e-43dd-a5cf-cb7496abf926.svg' \
  'Friends embracing' 9879b825-1a99-4cc8-b5d3-ebca82cb7300 'pictographic-primitives/users/user friends_9879b825-1a99-4cc8-b5d3-ebca82cb7300.svg'
