#!/bin/bash
# Batch 4/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/bee  source 9cdca2f1-9ac1-416b-842d-6d4837d4ab87
#   solo/bee-with-drooping-wings  source 5d2f4a16-ffda-4c09-85d2-18b66770025f
#   solo/beer-mug-with-bread  source f7b3cdc5-a4f3-4160-a8d1-71f476dc0fda
#   solo/beetle-in-coiled-shell  source e6e35530-888b-4ddb-ab14-ab2f3f1591c8
#   solo/bell-with-ringing-strokes  source 4a12d6a5-374a-5c49-8bd7-4bf52793db57
#   solo/bellhop-holding-towel  source 2f063e75-85ad-52d2-8db7-bb6d3918a515
#   solo/bicycle  source e02193de-f02e-5d27-b1d4-4c69559daeda
#   solo/bicycle-parked-in-rack  source f7ac223a-3452-4084-8389-29ffab6bfcef
#   solo/bird-life  source dee6f213-07ab-4305-8dd4-d656ac7937ec
#   solo/birdwatching-telescope-beneath-three-birds-solo  source 16ec9c7e-624d-4955-83bd-4f0d8fbcba1f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Bee 9cdca2f1-9ac1-416b-842d-6d4837d4ab87 pictographic-primitives/_uncategorized_36/sting_9cdca2f1-9ac1-416b-842d-6d4837d4ab87.svg \
  'Bee with drooping wings' 5d2f4a16-ffda-4c09-85d2-18b66770025f pictographic-primitives/_uncategorized_22/honeybee_5d2f4a16-ffda-4c09-85d2-18b66770025f.svg \
  'Beer mug with bread' f7b3cdc5-a4f3-4160-a8d1-71f476dc0fda 'pictographic-primitives/video-games/batch-11/tarvern shop restuarant_f7b3cdc5-a4f3-4160-a8d1-71f476dc0fda.svg' \
  'Beetle in coiled shell' e6e35530-888b-4ddb-ab14-ab2f3f1591c8 'pictographic-primitives/animals/insect earth_e6e35530-888b-4ddb-ab14-ab2f3f1591c8.svg' \
  'Bell with ringing strokes' 4a12d6a5-374a-5c49-8bd7-4bf52793db57 'pictographic-primitives/interface-essential/alarm bell ring_4a12d6a5-374a-5c49-8bd7-4bf52793db57.svg' \
  'Bellhop Holding Towel' 2f063e75-85ad-52d2-8db7-bb6d3918a515 pictographic-primitives/hotels/staff_2f063e75-85ad-52d2-8db7-bb6d3918a515.svg \
  Bicycle e02193de-f02e-5d27-b1d4-4c69559daeda 'pictographic-primitives/sports/fitness bicycle_e02193de-f02e-5d27-b1d4-4c69559daeda.svg' \
  'Bicycle parked in rack' f7ac223a-3452-4084-8389-29ffab6bfcef 'pictographic-primitives/_uncategorized_06/bike parking 1_f7ac223a-3452-4084-8389-29ffab6bfcef.svg' \
  'Bird life' dee6f213-07ab-4305-8dd4-d656ac7937ec 'pictographic-primitives/transportation/bird life_dee6f213-07ab-4305-8dd4-d656ac7937ec.svg' \
  'Birdwatching telescope beneath three birds solo' 16ec9c7e-624d-4955-83bd-4f0d8fbcba1f 'pictographic-primitives/_uncategorized_06/bird watching 2_16ec9c7e-624d-4955-83bd-4f0d8fbcba1f.svg'
