#!/bin/bash
# Batch 52/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/swimmer-wearing-cap  source 82eb00dd-e71e-5af9-aaac-2df8ae93ad6f
#   solo/symbol-artillery  source a7e31bff-1b16-45b4-8791-44858266dfbc
#   solo/synchronize-arrows-search  source df40480b-5166-4148-8ffb-4e38ec361c58
#   solo/tags-double  source b3607490-ea3a-409f-a7b1-8386a80c0b93
#   solo/takeout-noodle-carton  source 80abcf44-2e8d-4d02-a1df-f0609a15fe42
#   solo/tall-crescent-with-three-sparkles  source 918bf38d-d107-4261-bb49-0141b95866e7
#   solo/tall-fashion-boot  source ddcdb18c-a117-4e56-9306-9336b686e788
#   solo/teapot-serving-stand  source df688f36-b5fe-4f17-ae65-8d71d00de128
#   solo/technology-ar-searching-finger-touch  source 505403c5-6a6b-4a09-8ee4-eac7ce3a505f
#   solo/technology-hand-chip  source 40415ff8-ab5e-4613-9886-33d055540f90
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Swimmer wearing cap' 82eb00dd-e71e-5af9-aaac-2df8ae93ad6f 'pictographic-primitives/sports/swimming cap_82eb00dd-e71e-5af9-aaac-2df8ae93ad6f.svg' \
  'Symbol artillery' a7e31bff-1b16-45b4-8791-44858266dfbc 'pictographic-primitives/war/symbol artillery_a7e31bff-1b16-45b4-8791-44858266dfbc.svg' \
  'Synchronize arrows search' df40480b-5166-4148-8ffb-4e38ec361c58 'pictographic-primitives/interface-essential/synchronize arrows search_df40480b-5166-4148-8ffb-4e38ec361c58.svg' \
  'Tags double' b3607490-ea3a-409f-a7b1-8386a80c0b93 'pictographic-primitives/interface-essential/tags double_b3607490-ea3a-409f-a7b1-8386a80c0b93.svg' \
  'Takeout noodle carton' 80abcf44-2e8d-4d02-a1df-f0609a15fe42 'pictographic-primitives/food/pasta noodles_80abcf44-2e8d-4d02-a1df-f0609a15fe42.svg' \
  'Tall crescent with three sparkles' 918bf38d-d107-4261-bb49-0141b95866e7 'pictographic-primitives/_uncategorized_04/astronomy moon_918bf38d-d107-4261-bb49-0141b95866e7.svg' \
  'Tall fashion boot' ddcdb18c-a117-4e56-9306-9336b686e788 'pictographic-primitives/_uncategorized_19/footwear boots female_ddcdb18c-a117-4e56-9306-9336b686e788.svg' \
  'Teapot serving stand' df688f36-b5fe-4f17-ae65-8d71d00de128 'pictographic-primitives/_uncategorized_37/tea pot 1_df688f36-b5fe-4f17-ae65-8d71d00de128.svg' \
  'Technology ar searching finger touch' 505403c5-6a6b-4a09-8ee4-eac7ce3a505f 'pictographic-primitives/_uncategorized_37/technology ar searching finger touch_505403c5-6a6b-4a09-8ee4-eac7ce3a505f.svg' \
  'Technology hand chip' 40415ff8-ab5e-4613-9886-33d055540f90 'pictographic-primitives/_uncategorized_37/technology hand chip_40415ff8-ab5e-4613-9886-33d055540f90.svg'
