#!/bin/bash
# Batch 28/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-holding-bowl-beneath-round-object  source e92a7970-9b72-4523-8caa-4f5d34540b96
#   solo/hand-holding-card  source b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe
#   solo/hand-holding-document  source 1a5b8e57-e476-5e0e-a43f-45bc8105f4e5
#   solo/hand-holding-fountain-pen  source 83ff3171-53c2-4300-a683-6306ba8fe250
#   solo/hand-holding-hammer  source 9c2e6a00-c352-4f4c-97df-5e296d00637d
#   solo/hand-holding-heart  source 045520ca-f23a-531a-b54e-ce7bc4cbf52e
#   solo/hand-holding-identity-card-batch-001-r2  source cb16642c-e584-52b6-ae9d-bff1579af112
#   solo/hand-holding-mask  source 5521723a-f61f-58b0-9d3b-7bb857fa845d
#   solo/hand-holding-megaphone  source 5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc
#   solo/hand-holding-paper-airplane  source b3f6c409-ce6d-47c9-92ed-52d3c36236bc
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand holding bowl beneath round object' e92a7970-9b72-4523-8caa-4f5d34540b96 pictographic-primitives/_uncategorized_18/feeding_e92a7970-9b72-4523-8caa-4f5d34540b96.svg \
  'Hand holding card' b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe 'pictographic-primitives/payments/credit card scan_b8b0be96-48c9-4d4f-9c4a-c278eedc3dbe.svg' \
  'Hand holding document' 1a5b8e57-e476-5e0e-a43f-45bc8105f4e5 'pictographic-primitives/websites/digital policies data breach_1a5b8e57-e476-5e0e-a43f-45bc8105f4e5.svg' \
  'Hand holding fountain pen' 83ff3171-53c2-4300-a683-6306ba8fe250 'pictographic-primitives/work/workflow coaching hand pen_83ff3171-53c2-4300-a683-6306ba8fe250.svg' \
  'Hand holding hammer' 9c2e6a00-c352-4f4c-97df-5e296d00637d 'pictographic-primitives/tools/tools hammer hold_9c2e6a00-c352-4f4c-97df-5e296d00637d.svg' \
  'Hand holding heart' 045520ca-f23a-531a-b54e-ce7bc4cbf52e 'pictographic-primitives/romance/love heart hold_045520ca-f23a-531a-b54e-ce7bc4cbf52e.svg' \
  'Hand holding identity card batch 001 r2' cb16642c-e584-52b6-ae9d-bff1579af112 'pictographic-primitives/apps/digital policies data breach user_cb16642c-e584-52b6-ae9d-bff1579af112.svg' \
  'Hand holding mask' 5521723a-f61f-58b0-9d3b-7bb857fa845d pictographic-primitives/hobbies/cosplay_5521723a-f61f-58b0-9d3b-7bb857fa845d.svg \
  'Hand holding megaphone' 5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc 'pictographic-primitives/work/labor megaphone_5587cff6-d8d9-4045-b4e0-05bcb4c1a7bc.svg' \
  'Hand holding paper airplane' b3f6c409-ce6d-47c9-92ed-52d3c36236bc pictographic-primitives/hobbies/origami_b3f6c409-ce6d-47c9-92ed-52d3c36236bc.svg
