#!/bin/bash
# Batch 18/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/curving-snake  source 2ec00ca4-5f8a-4ca6-b750-8ed6a3306564
#   solo/customer-at-information-desk  source 6c38d9c8-0e42-5dd8-a256-2b9b12046c18
#   solo/cycling  source 8d3730da-df45-48a8-9d4e-6cf0a350df28
#   solo/cyclist  source 162b8606-09be-5a25-a153-6f51561b636a
#   solo/cyclist-above-two-open-wheels  source 5d94706e-5e90-41ee-bd73-a7f28a558ba3
#   solo/cyclist-climbing-a-sloping-path-1f7ae7d3  source 1f7ae7d3-ecbe-4b15-9965-79c8913e76e0
#   solo/cylindrical-marshmallow-on-slanted-stick  source 51eb3863-a02f-4624-ba65-ff48208cd5b7
#   solo/dachshund-face  source 44442ee3-de41-53ab-af82-3e69c47a0ecc
#   solo/dalmatian-face  source fd0d9c0a-6ed5-48eb-b294-bbe6008deef9
#   solo/dancing-woman-with-music-notes  source 6c6896b3-8871-41eb-bf24-63a28db82e65
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Curving snake' 2ec00ca4-5f8a-4ca6-b750-8ed6a3306564 pictographic-primitives/_uncategorized_39/venom_2ec00ca4-5f8a-4ca6-b750-8ed6a3306564.svg \
  'Customer at information desk' 6c38d9c8-0e42-5dd8-a256-2b9b12046c18 'pictographic-primitives/companies/information desk customer_6c38d9c8-0e42-5dd8-a256-2b9b12046c18.svg' \
  Cycling 8d3730da-df45-48a8-9d4e-6cf0a350df28 pictographic-primitives/symbol/cycling_8d3730da-df45-48a8-9d4e-6cf0a350df28.svg \
  Cyclist 162b8606-09be-5a25-a153-6f51561b636a 'pictographic-primitives/sports/fitness bicycle_162b8606-09be-5a25-a153-6f51561b636a.svg' \
  'Cyclist above two open wheels' 5d94706e-5e90-41ee-bd73-a7f28a558ba3 'pictographic-primitives/_uncategorized_06/biking helmet person_5d94706e-5e90-41ee-bd73-a7f28a558ba3.svg' \
  'Cyclist climbing a sloping path 1f7ae7d3' 1f7ae7d3-ecbe-4b15-9965-79c8913e76e0 'pictographic-primitives/_uncategorized_06/biking mountain_1f7ae7d3-ecbe-4b15-9965-79c8913e76e0.svg' \
  'Cylindrical marshmallow on slanted stick' 51eb3863-a02f-4624-ba65-ff48208cd5b7 pictographic-primitives/_uncategorized_26/marshmallow_51eb3863-a02f-4624-ba65-ff48208cd5b7.svg \
  'Dachshund face' 44442ee3-de41-53ab-af82-3e69c47a0ecc pictographic-primitives/pets/dachshund_44442ee3-de41-53ab-af82-3e69c47a0ecc.svg \
  'Dalmatian face' fd0d9c0a-6ed5-48eb-b294-bbe6008deef9 pictographic-primitives/pets/dalmatian_fd0d9c0a-6ed5-48eb-b294-bbe6008deef9.svg \
  'Dancing woman with music notes' 6c6896b3-8871-41eb-bf24-63a28db82e65 'pictographic-primitives/entertainment/party music dance woman_6c6896b3-8871-41eb-bf24-63a28db82e65.svg'
