#!/bin/bash
# Batch 34/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/index-finger-touching-a-phone  source 3730401c-4d35-4b72-a477-2313ba8f23f7
#   solo/insect-head-with-antennae  source 48b9ec2f-d1e5-4c68-a4c7-5794c4616469
#   solo/insurance-card  source bf6cf58a-c4bd-55e5-b5c2-806c4c390311
#   solo/intellij-idea-logo  source f4752828-8f41-472e-a48e-c509754917dd
#   solo/intellij-idea-logo-square  source 66cf9f40-4254-4619-ba1e-7b78e0914552
#   solo/interlocking-chain-link-symbol-solo  source 55bd9f6e-12a9-4d3a-9646-c1852d270efe
#   solo/interlocking-chain-links  source 7c06efbf-f3f5-4fe4-88b2-7fb4d1d00885
#   solo/interlocking-handshake  source e18ed81a-df3e-442f-9876-54ac0d744866
#   solo/internet-archive-logo  source bee109f7-7025-4eb4-9ddc-33b7df1410c4
#   solo/invoice-in-open-envelope  source 57201c70-c002-40bb-8fad-0abd9f9ca4db
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Index finger touching a phone' 3730401c-4d35-4b72-a477-2313ba8f23f7 'pictographic-primitives/_uncategorized_06/bendable phone touch_3730401c-4d35-4b72-a477-2313ba8f23f7.svg' \
  'Insect head with antennae' 48b9ec2f-d1e5-4c68-a4c7-5794c4616469 'pictographic-primitives/animals/insect cricket_48b9ec2f-d1e5-4c68-a4c7-5794c4616469.svg' \
  'Insurance card' bf6cf58a-c4bd-55e5-b5c2-806c4c390311 'pictographic-primitives/health/insurance card_bf6cf58a-c4bd-55e5-b5c2-806c4c390311.svg' \
  'Intellij idea logo' f4752828-8f41-472e-a48e-c509754917dd 'pictographic-primitives/logos/intellijidea logo_f4752828-8f41-472e-a48e-c509754917dd.svg' \
  'Intellij idea logo square' 66cf9f40-4254-4619-ba1e-7b78e0914552 'pictographic-primitives/logos/intellij idea logo_66cf9f40-4254-4619-ba1e-7b78e0914552.svg' \
  'Interlocking chain link symbol solo' 55bd9f6e-12a9-4d3a-9646-c1852d270efe 'pictographic-primitives/other/attached file_55bd9f6e-12a9-4d3a-9646-c1852d270efe.svg' \
  'Interlocking chain links' 7c06efbf-f3f5-4fe4-88b2-7fb4d1d00885 pictographic-primitives/accessories/batch-07/chain_7c06efbf-f3f5-4fe4-88b2-7fb4d1d00885.svg \
  'Interlocking handshake' e18ed81a-df3e-442f-9876-54ac0d744866 pictographic-primitives/_uncategorized_11/clasp_e18ed81a-df3e-442f-9876-54ac0d744866.svg \
  'Internet archive logo' bee109f7-7025-4eb4-9ddc-33b7df1410c4 'pictographic-primitives/logos/internet archive logo_bee109f7-7025-4eb4-9ddc-33b7df1410c4.svg' \
  'Invoice in open envelope' 57201c70-c002-40bb-8fad-0abd9f9ca4db 'pictographic-primitives/payments/invoice mail_57201c70-c002-40bb-8fad-0abd9f9ca4db.svg'
