#!/bin/bash
# Batch 62/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/wavy-tooth-wood-saw  source cca0b3cb-f738-5bd1-a400-e64072c4b7b1
#   solo/wechat-speech-bubble-logo  source dedb14ad-fb78-47e4-8892-fb804488a007
#   solo/wedding-cake-with-couple-topper  source 199d991d-ac92-4ca6-8fab-82962d7559e7
#   solo/wedding-car-with-heart-balloon  source aa749eea-3336-52e7-9fb4-28fbeffeaa0b
#   solo/west-direction-marker  source 68aa7319-a9e3-4030-8fbb-2d42e243d96f
#   solo/wheelchair-user-at-ramp  source 9dfb6289-487a-4bfa-95e5-fdc48e5dd47a
#   solo/wheelchair-user-holding-a-flag  source 8df4cee4-a586-5de1-9d67-5a1d7d4a0bfe
#   solo/wide-ski-goggles  source dc9fedbc-8058-5e3a-8a22-47f1828e3da5
#   solo/wild-bird  source 7e1a8309-f138-49c1-a543-a29fe848c8be
#   solo/winged-female-demon  source f764c646-54bb-44f8-8f0a-660266f16f3d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Wavy tooth wood saw' cca0b3cb-f738-5bd1-a400-e64072c4b7b1 'pictographic-primitives/tools/tools wood saw_cca0b3cb-f738-5bd1-a400-e64072c4b7b1.svg' \
  'Wechat speech bubble logo' dedb14ad-fb78-47e4-8892-fb804488a007 'pictographic-primitives/logos/wechat logo_dedb14ad-fb78-47e4-8892-fb804488a007.svg' \
  'Wedding cake with couple topper' 199d991d-ac92-4ca6-8fab-82962d7559e7 'pictographic-primitives/romance/wedding cake couple_199d991d-ac92-4ca6-8fab-82962d7559e7.svg' \
  'Wedding car with heart balloon' aa749eea-3336-52e7-9fb4-28fbeffeaa0b 'pictographic-primitives/romance/wedding car heart balloon_aa749eea-3336-52e7-9fb4-28fbeffeaa0b.svg' \
  'West direction marker' 68aa7319-a9e3-4030-8fbb-2d42e243d96f 'pictographic-primitives/navigation/compass west_68aa7319-a9e3-4030-8fbb-2d42e243d96f.svg' \
  'Wheelchair user at ramp' 9dfb6289-487a-4bfa-95e5-fdc48e5dd47a 'pictographic-primitives/wayfinding/wheelchair way_9dfb6289-487a-4bfa-95e5-fdc48e5dd47a.svg' \
  'Wheelchair user holding a flag' 8df4cee4-a586-5de1-9d67-5a1d7d4a0bfe pictographic-primitives/rewards/flag_8df4cee4-a586-5de1-9d67-5a1d7d4a0bfe.svg \
  'Wide ski goggles' dc9fedbc-8058-5e3a-8a22-47f1828e3da5 'pictographic-primitives/accessories/batch-02/glasses ski_dc9fedbc-8058-5e3a-8a22-47f1828e3da5.svg' \
  'Wild bird' 7e1a8309-f138-49c1-a543-a29fe848c8be 'pictographic-primitives/animals/wild bird 2_7e1a8309-f138-49c1-a543-a29fe848c8be.svg' \
  'Winged female demon' f764c646-54bb-44f8-8f0a-660266f16f3d pictographic-primitives/video-games/batch-11/succubus_f764c646-54bb-44f8-8f0a-660266f16f3d.svg
