#!/bin/bash
# Batch 35/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/inward-arrow-with-curved-and-dashed-bounds  source 7e004778-d88c-4db0-9a9c-c9364d42ee86
#   solo/ios-logo  source 864d41bd-ddf2-4080-a8e1-009b30743624
#   solo/ipod-play  source 95b0fd3b-05a5-49bd-b7c9-29486aaf4857
#   solo/isometric-cube-with-three-circular-nodes  source a1ebcd1c-faf5-4d0c-93f2-8b0f08933387
#   solo/jasmine-logo  source 99aca13e-621b-4224-a7d5-50e282c5a5ba
#   solo/javascript-logo  source c7e5eabf-e0c2-47d6-9a2b-23487329395b
#   solo/jigsaw-light-bulb  source 8013a3c2-dcf3-475e-98f6-cb6db629e137
#   solo/jira-logo  source 725a957e-63e3-4f03-87bd-d37db9fb9241
#   solo/jira-software-logo  source 0697abc9-3868-4637-8bea-f5804a5c6af5
#   solo/json-logo  source fd2eaa4c-1430-46f4-adcf-5755852eaadf
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Inward arrow with curved and dashed bounds' 7e004778-d88c-4db0-9a9c-c9364d42ee86 'pictographic-primitives/design/transform inside_7e004778-d88c-4db0-9a9c-c9364d42ee86.svg' \
  'Ios logo' 864d41bd-ddf2-4080-a8e1-009b30743624 'pictographic-primitives/logos/ios logo_864d41bd-ddf2-4080-a8e1-009b30743624.svg' \
  'Ipod play' 95b0fd3b-05a5-49bd-b7c9-29486aaf4857 'pictographic-primitives/music/ipod play_95b0fd3b-05a5-49bd-b7c9-29486aaf4857.svg' \
  'Isometric cube with three circular nodes' a1ebcd1c-faf5-4d0c-93f2-8b0f08933387 'pictographic-primitives/design/rotate 3d_a1ebcd1c-faf5-4d0c-93f2-8b0f08933387.svg' \
  'Jasmine logo' 99aca13e-621b-4224-a7d5-50e282c5a5ba 'pictographic-primitives/logos/jasmine logo_99aca13e-621b-4224-a7d5-50e282c5a5ba.svg' \
  'Javascript logo' c7e5eabf-e0c2-47d6-9a2b-23487329395b 'pictographic-primitives/logos/java script logo_c7e5eabf-e0c2-47d6-9a2b-23487329395b.svg' \
  'Jigsaw light bulb' 8013a3c2-dcf3-475e-98f6-cb6db629e137 'pictographic-primitives/work/workflow coaching puzzle lightbulb_8013a3c2-dcf3-475e-98f6-cb6db629e137.svg' \
  'Jira logo' 725a957e-63e3-4f03-87bd-d37db9fb9241 'pictographic-primitives/logos/jira logo_725a957e-63e3-4f03-87bd-d37db9fb9241.svg' \
  'Jira software logo' 0697abc9-3868-4637-8bea-f5804a5c6af5 'pictographic-primitives/logos/jira software logo_0697abc9-3868-4637-8bea-f5804a5c6af5.svg' \
  'Json logo' fd2eaa4c-1430-46f4-adcf-5755852eaadf 'pictographic-primitives/logos/json logo_fd2eaa4c-1430-46f4-adcf-5755852eaadf.svg'
