#!/bin/bash
# Batch 17/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/crossed-fork-and-chef-knife  source aba5bfb7-5990-4b45-9606-e4cfe58ad1ea
#   solo/crossed-fork-with-spoon  source 53cd4f82-ae5a-4f7a-8ddd-de64747944f4
#   solo/crossed-guitar-microphone  source ae731560-756d-4bfe-9aa1-bcd0df250afa
#   solo/crossed-spiked-mace  source 79c8a226-7026-5ab4-a2e4-203abe5e9998
#   solo/crossed-wrench-and-screwdriver  source 8b935d53-8cae-4d27-b6e5-0fed82d9789e
#   solo/crossed-wrists-with-closed-hands  source 4d17fb6b-b370-4259-a0ce-98903c9aeaff
#   solo/currency-dollar  source 3334fbb0-436e-4762-bc8a-40fa2559c98c
#   solo/curved-bay-with-two-wave-lines  source 95af3736-8137-457c-a403-3663a17cb3af
#   solo/curved-string-of-beads  source ed4699f6-a912-4876-9b67-eba4703923e0
#   solo/curved-war-horn  source f57ae871-f8c2-531a-86e3-1e726b05c69e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Crossed fork and chef knife' aba5bfb7-5990-4b45-9606-e4cfe58ad1ea 'pictographic-primitives/food/symbol fork cross knife_aba5bfb7-5990-4b45-9606-e4cfe58ad1ea.svg' \
  'Crossed fork with spoon' 53cd4f82-ae5a-4f7a-8ddd-de64747944f4 'pictographic-primitives/food/symbol spoon cross fork_53cd4f82-ae5a-4f7a-8ddd-de64747944f4.svg' \
  'Crossed guitar microphone' ae731560-756d-4bfe-9aa1-bcd0df250afa 'pictographic-primitives/_uncategorized_30/party music_ae731560-756d-4bfe-9aa1-bcd0df250afa.svg' \
  'Crossed spiked mace' 79c8a226-7026-5ab4-a2e4-203abe5e9998 'pictographic-primitives/war/antique mace double_79c8a226-7026-5ab4-a2e4-203abe5e9998.svg' \
  'Crossed wrench and screwdriver' 8b935d53-8cae-4d27-b6e5-0fed82d9789e 'pictographic-primitives/tools/tools wrench screwdriver_8b935d53-8cae-4d27-b6e5-0fed82d9789e.svg' \
  'Crossed wrists with closed hands' 4d17fb6b-b370-4259-a0ce-98903c9aeaff 'pictographic-primitives/wayfinding/sign language love_4d17fb6b-b370-4259-a0ce-98903c9aeaff.svg' \
  'Currency dollar' 3334fbb0-436e-4762-bc8a-40fa2559c98c 'pictographic-primitives/money/currency dollar_3334fbb0-436e-4762-bc8a-40fa2559c98c.svg' \
  'Curved bay with two wave lines' 95af3736-8137-457c-a403-3663a17cb3af pictographic-primitives/_uncategorized_06/bay_95af3736-8137-457c-a403-3663a17cb3af.svg \
  'Curved string of beads' ed4699f6-a912-4876-9b67-eba4703923e0 pictographic-primitives/_uncategorized_06/bead_ed4699f6-a912-4876-9b67-eba4703923e0.svg \
  'Curved war horn' f57ae871-f8c2-531a-86e3-1e726b05c69e 'pictographic-primitives/video-games/batch-12/war horn_f57ae871-f8c2-531a-86e3-1e726b05c69e.svg'
