#!/bin/bash
# Batch 51/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/steamed-bao-bun-group  source 4ac87097-22b4-467e-8616-be55a6c4ad10
#   solo/steve-jobs-avatar  source f78afcb3-566a-5db6-a3d3-b2309ee981b6
#   solo/stovetop-kettle-with-large-arched-handle  source 3aec4ce6-41be-427b-9ebc-69adddce6b78
#   solo/studded-soccer-cleat  source 92901ffc-8850-47e1-b64c-7fd71adcc49e
#   solo/sumo-wrestler  source 9ed19462-8339-482a-a209-2c66f9e595f9
#   solo/sun-brightness-control-remote  source 7a96e3db-b58b-5891-b189-41a4ac863579
#   solo/sun-rising-over-mosque  source 5cd0e8a5-7585-4019-97b2-78a1e50f66d3
#   solo/sunbather-by-water  source 2d817056-c992-421c-aa82-7918e9bbda30
#   solo/sunbather-on-lounger  source 839f7645-d246-443b-948f-0ee346ad3a52
#   solo/support-agent-with-boom-microphone  source a796c493-db7e-58ce-9455-493c17f8705a
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Steamed bao bun group' 4ac87097-22b4-467e-8616-be55a6c4ad10 'pictographic-primitives/food/exotic food buns_4ac87097-22b4-467e-8616-be55a6c4ad10.svg' \
  'Steve jobs avatar' f78afcb3-566a-5db6-a3d3-b2309ee981b6 'pictographic-primitives/avatars/steve jobs_f78afcb3-566a-5db6-a3d3-b2309ee981b6.svg' \
  'Stovetop kettle with large arched handle' 3aec4ce6-41be-427b-9ebc-69adddce6b78 'pictographic-primitives/drinks/tea kettle 1_3aec4ce6-41be-427b-9ebc-69adddce6b78.svg' \
  'Studded soccer cleat' 92901ffc-8850-47e1-b64c-7fd71adcc49e pictographic-primitives/_uncategorized_11/cleat_92901ffc-8850-47e1-b64c-7fd71adcc49e.svg \
  'Sumo wrestler' 9ed19462-8339-482a-a209-2c66f9e595f9 pictographic-primitives/sports/sumo_9ed19462-8339-482a-a209-2c66f9e595f9.svg \
  'Sun brightness control remote' 7a96e3db-b58b-5891-b189-41a4ac863579 'pictographic-primitives/devices/settings brightness_7a96e3db-b58b-5891-b189-41a4ac863579.svg' \
  'Sun Rising over Mosque' 5cd0e8a5-7585-4019-97b2-78a1e50f66d3 'pictographic-primitives/holidays/islamic new year_5cd0e8a5-7585-4019-97b2-78a1e50f66d3.svg' \
  'Sunbather by water' 2d817056-c992-421c-aa82-7918e9bbda30 'pictographic-primitives/recreation/sunbathe activitiies_2d817056-c992-421c-aa82-7918e9bbda30.svg' \
  'Sunbather on lounger' 839f7645-d246-443b-948f-0ee346ad3a52 pictographic-primitives/recreation/sunbathe_839f7645-d246-443b-948f-0ee346ad3a52.svg \
  'Support agent with boom microphone' a796c493-db7e-58ce-9455-493c17f8705a 'pictographic-primitives/interface-essential/headphones customer support_a796c493-db7e-58ce-9455-493c17f8705a.svg'
