#!/bin/bash
# Batch 55/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/three-person-squad  source 47b5d0d4-7421-51e3-82ac-4ebeeb7bce0a
#   solo/time-clock-file-1  source e7ce785e-158f-41d6-9e8b-dcba4879acac
#   solo/tooth-with-trailing-floss  source 638d5134-5ea9-476e-996b-afb066e33fd9
#   solo/toothed-hand-saw-batch-064  source fb9e5252-41fd-4313-ae36-6711e4c93e41
#   solo/traffic-police-officer  source 37ab5a7a-3b36-4e23-875f-657b67943fc3
#   solo/trailing-hanging-planter  source 648d5f22-ccb1-4224-9894-c373442f1825
#   solo/treehouse-logo  source bf61d88d-d269-4a85-955c-a411e11583cd
#   solo/truck-medical  source c14f0462-1a4f-4fce-8591-b63fddf2fa6d
#   solo/truck-moving  source 1bdf40bf-9d96-43bd-a767-f5237c9e61eb
#   solo/truck-with-gift-box-body  source cdf1b0dc-76f6-4d8f-8160-4d7a37024792
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Three person squad' 47b5d0d4-7421-51e3-82ac-4ebeeb7bce0a 'pictographic-primitives/war/symbol squad_47b5d0d4-7421-51e3-82ac-4ebeeb7bce0a.svg' \
  'Time clock file 1' e7ce785e-158f-41d6-9e8b-dcba4879acac 'pictographic-primitives/interface-essential/time clock file 1_e7ce785e-158f-41d6-9e8b-dcba4879acac.svg' \
  'Tooth with trailing floss' 638d5134-5ea9-476e-996b-afb066e33fd9 pictographic-primitives/health/tooth_638d5134-5ea9-476e-996b-afb066e33fd9.svg \
  'Toothed hand saw batch 064' fb9e5252-41fd-4313-ae36-6711e4c93e41 pictographic-primitives/_uncategorized_22/handsaw_fb9e5252-41fd-4313-ae36-6711e4c93e41.svg \
  'Traffic police officer' 37ab5a7a-3b36-4e23-875f-657b67943fc3 pictographic-primitives/transportation/police_37ab5a7a-3b36-4e23-875f-657b67943fc3.svg \
  'Trailing hanging planter' 648d5f22-ccb1-4224-9894-c373442f1825 'pictographic-primitives/decoration/batch-02/hanging plant 3_648d5f22-ccb1-4224-9894-c373442f1825.svg' \
  'Treehouse logo' bf61d88d-d269-4a85-955c-a411e11583cd 'pictographic-primitives/logos/treehouse logo_bf61d88d-d269-4a85-955c-a411e11583cd.svg' \
  'Truck medical' c14f0462-1a4f-4fce-8591-b63fddf2fa6d 'pictographic-primitives/_uncategorized_38/truck medical_c14f0462-1a4f-4fce-8591-b63fddf2fa6d.svg' \
  'Truck moving' 1bdf40bf-9d96-43bd-a767-f5237c9e61eb 'pictographic-primitives/_uncategorized_38/truck moving_1bdf40bf-9d96-43bd-a767-f5237c9e61eb.svg' \
  'Truck with gift box body' cdf1b0dc-76f6-4d8f-8160-4d7a37024792 'pictographic-primitives/delivery/truck gift_cdf1b0dc-76f6-4d8f-8160-4d7a37024792.svg'
