#!/bin/bash
# Batch 26/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/geometric-shapes-in-rounded-square-batch-006-02  source 610733a3-dfd5-42df-9651-d396d039493b
#   solo/ghost-hand-puppet  source a6b4c9d3-7980-446c-ac11-08ac236338e8
#   solo/gift-heart  source 5862a2a1-e7c8-522a-812d-2db80570e593
#   solo/girl-full-body  source 45881775-2179-41cc-98a1-78a598c550c1
#   solo/glowing-light-bulb-564c9b27-dd9b-48b8-8f61-3945889b688c  source 564c9b27-dd9b-48b8-8f61-3945889b688c
#   solo/gprs-text  source 378a8b67-3065-5023-b054-9fccecc32c2c
#   solo/graduate-with-two-people  source 3bbdfa95-8a10-4cf0-910a-fb693fb29316
#   solo/grim-reaper-with-scythe  source 10802c86-44a5-43d2-9258-49fbaaa0c39d
#   solo/hammerhead-shark  source bdd1577c-6f14-5bee-a41f-fac2b80017a7
#   solo/hand-above-water  source 308c7b26-332e-4a63-acca-d4c8af288d7f
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Geometric shapes in rounded square batch 006 02' 610733a3-dfd5-42df-9651-d396d039493b pictographic-primitives/design/shapes_610733a3-dfd5-42df-9651-d396d039493b.svg \
  'Ghost hand puppet' a6b4c9d3-7980-446c-ac11-08ac236338e8 'pictographic-primitives/kids/toys hand ghost_a6b4c9d3-7980-446c-ac11-08ac236338e8.svg' \
  'Gift heart' 5862a2a1-e7c8-522a-812d-2db80570e593 'pictographic-primitives/rewards/gift heart_5862a2a1-e7c8-522a-812d-2db80570e593.svg' \
  'Girl full body' 45881775-2179-41cc-98a1-78a598c550c1 'pictographic-primitives/avatars/girl full body_45881775-2179-41cc-98a1-78a598c550c1.svg' \
  'Glowing light bulb 564c9b27 dd9b 48b8 8f61 3945889b688c' 564c9b27-dd9b-48b8-8f61-3945889b688c 'pictographic-primitives/lights/light bulb 1_564c9b27-dd9b-48b8-8f61-3945889b688c.svg' \
  'Gprs text' 378a8b67-3065-5023-b054-9fccecc32c2c pictographic-primitives/mobile/gprs_378a8b67-3065-5023-b054-9fccecc32c2c.svg \
  'Graduate with two people' 3bbdfa95-8a10-4cf0-910a-fb693fb29316 'pictographic-primitives/school-learning/study virtual classroom_3bbdfa95-8a10-4cf0-910a-fb693fb29316.svg' \
  'Grim reaper with scythe' 10802c86-44a5-43d2-9258-49fbaaa0c39d 'pictographic-primitives/holidays/grim reaper_10802c86-44a5-43d2-9258-49fbaaa0c39d.svg' \
  'Hammerhead shark' bdd1577c-6f14-5bee-a41f-fac2b80017a7 'pictographic-primitives/animals/shark hammer_bdd1577c-6f14-5bee-a41f-fac2b80017a7.svg' \
  'Hand above water' 308c7b26-332e-4a63-acca-d4c8af288d7f 'pictographic-primitives/wayfinding/safety drown hand_308c7b26-332e-4a63-acca-d4c8af288d7f.svg'
