#!/bin/bash
# Batch 65/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/woman-silhouette  source c30323e5-9a47-4adf-a673-a7c1c2f6a062
#   solo/woman-standing-beside-a-baby-carriage-7ef89486  source 7ef89486-f781-4238-b1ba-7f9d5858262e
#   solo/woman-swimmer-1-avatar  source 3222c125-5db2-4e54-a131-6f6cbc6dbcde
#   solo/woman-telecommunicator-1-avatar  source 2b208a3b-47e8-47f4-b99a-2f4763a0e031
#   solo/woman-thief-avatar  source 8036406b-7914-54c1-be92-c2585863d8f4
#   solo/woman-wearing-crown  source 00eb0d5d-7557-4801-bb6f-304ff4b914ce
#   solo/wooden-barrel-with-two-hoops-and-curved-staves  source d5b47441-37c4-578a-93be-e68b3ac3e6a3
#   solo/woolly-lamb-front  source 9703bb75-a343-538b-9854-1d21a9bbd1b5
#   solo/work-glove-spread-thumb  source e60f0c02-0f0a-45cd-afaa-1f3a71bcc802
#   solo/worried-face-with-cheek-droplet  source 56b8b8fb-dbc1-438c-a976-1d17d377d325
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Woman silhouette' c30323e5-9a47-4adf-a673-a7c1c2f6a062 pictographic-primitives/symbol/women_c30323e5-9a47-4adf-a673-a7c1c2f6a062.svg \
  'Woman standing beside a baby carriage 7ef89486' 7ef89486-f781-4238-b1ba-7f9d5858262e 'pictographic-primitives/_uncategorized_05/baby trolley_7ef89486-f781-4238-b1ba-7f9d5858262e.svg' \
  'Woman swimmer 1 avatar' 3222c125-5db2-4e54-a131-6f6cbc6dbcde 'pictographic-primitives/avatars/woman swimmer_3222c125-5db2-4e54-a131-6f6cbc6dbcde.svg' \
  'Woman telecommunicator 1 avatar' 2b208a3b-47e8-47f4-b99a-2f4763a0e031 'pictographic-primitives/avatars/woman telecommunicator_2b208a3b-47e8-47f4-b99a-2f4763a0e031.svg' \
  'Woman thief avatar' 8036406b-7914-54c1-be92-c2585863d8f4 'pictographic-primitives/avatars/woman thief_8036406b-7914-54c1-be92-c2585863d8f4.svg' \
  'Woman wearing crown' 00eb0d5d-7557-4801-bb6f-304ff4b914ce 'pictographic-primitives/work/workflow manager female crown_00eb0d5d-7557-4801-bb6f-304ff4b914ce.svg' \
  'Wooden barrel with two hoops and curved staves' d5b47441-37c4-578a-93be-e68b3ac3e6a3 'pictographic-primitives/drinks/wine barrel_d5b47441-37c4-578a-93be-e68b3ac3e6a3.svg' \
  'Woolly lamb front' 9703bb75-a343-538b-9854-1d21a9bbd1b5 pictographic-primitives/animals/lamb_9703bb75-a343-538b-9854-1d21a9bbd1b5.svg \
  'Work glove spread thumb' e60f0c02-0f0a-45cd-afaa-1f3a71bcc802 pictographic-primitives/farming/glove_e60f0c02-0f0a-45cd-afaa-1f3a71bcc802.svg \
  'Worried face with cheek droplet' 56b8b8fb-dbc1-438c-a976-1d17d377d325 'pictographic-primitives/_uncategorized_18/face sad sweat_56b8b8fb-dbc1-438c-a976-1d17d377d325.svg'
