#!/bin/bash
# Batch 47/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/prescription-px-square  source 83ea3f1d-dfb5-4247-948a-2314faaff6ad
#   solo/price-tag-solo  source 4c261fc0-0d1c-4e30-abc1-c55587b5e470
#   solo/raised-open-palm  source ee3c26d8-285a-439d-a9aa-3fc2353f1d6f
#   solo/rear-cargo-bicycle  source 697554f1-3afd-5c1d-87a3-50b358ece127
#   solo/rectangle-single-man-focus  source 748d6e5f-8942-4061-a602-5b499075202e
#   solo/red-indian-woman-avatar  source 6f074cd0-861a-458d-a17c-6cc25f917743
#   solo/road-bicycle  source b43a6544-1e7b-481a-aad7-01ad2bdb307d
#   solo/seated-long-eared-rabbit  source eb69e986-be04-4fec-80c4-3ab9c58a6853
#   solo/shipping-delivery-truck-solo  source ee45281c-9d60-448b-b6b0-b5db76f72c3b
#   solo/small-delivery-truck  source 1cc6a052-bd85-4786-ad57-af8947d75c17
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Prescription px square' 83ea3f1d-dfb5-4247-948a-2314faaff6ad 'pictographic-primitives/other/prescription px square_83ea3f1d-dfb5-4247-948a-2314faaff6ad.svg' \
  'Price tag solo' 4c261fc0-0d1c-4e30-abc1-c55587b5e470 pictographic-primitives/other/tag_4c261fc0-0d1c-4e30-abc1-c55587b5e470.svg \
  'Raised Open Palm' ee3c26d8-285a-439d-a9aa-3fc2353f1d6f 'pictographic-primitives/_uncategorized_24/labor hands_83c18653-4bbf-498c-80b3-a71d2a06335a.svg' \
  'Rear cargo bicycle' 697554f1-3afd-5c1d-87a3-50b358ece127 'pictographic-primitives/transportation/bike cargo back_697554f1-3afd-5c1d-87a3-50b358ece127.svg' \
  'Rectangle single man focus' 748d6e5f-8942-4061-a602-5b499075202e 'pictographic-primitives/other/rectangle single man focus_748d6e5f-8942-4061-a602-5b499075202e.svg' \
  'Red indian woman avatar' 6f074cd0-861a-458d-a17c-6cc25f917743 'pictographic-primitives/avatars/red indian woman_6f074cd0-861a-458d-a17c-6cc25f917743.svg' \
  'Road bicycle' b43a6544-1e7b-481a-aad7-01ad2bdb307d pictographic-primitives/transportation/bicycle_b43a6544-1e7b-481a-aad7-01ad2bdb307d.svg \
  'Seated long eared rabbit' eb69e986-be04-4fec-80c4-3ab9c58a6853 pictographic-primitives/_uncategorized_22/hare_eb69e986-be04-4fec-80c4-3ab9c58a6853.svg \
  'Shipping delivery truck solo' ee45281c-9d60-448b-b6b0-b5db76f72c3b pictographic-primitives/transportation/truck_ee45281c-9d60-448b-b6b0-b5db76f72c3b.svg \
  'Small delivery truck' 1cc6a052-bd85-4786-ad57-af8947d75c17 pictographic-primitives/transportation/truck_1cc6a052-bd85-4786-ad57-af8947d75c17.svg
