#!/bin/bash
# Batch 13/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/combination-pliers  source 6b9c56ef-5064-4dca-b96f-f14cdc63e5ef
#   solo/combine-harvester-front-header  source 44ee4e62-4052-5cd9-b8ce-7733bb2ccec0
#   solo/compact-car-beneath-clouds  source ee5bbd28-411f-4a8f-bec4-24171fa57174
#   solo/computer-memory-module  source e89894da-2a07-4c85-8acd-326edf5c64cf
#   solo/computer-typing-keyboard  source 6da646a1-34eb-51f2-af2d-b08aed786a57
#   solo/conductor-with-raised-baton  source 6659250b-ef9d-4624-8030-348af08008eb
#   solo/congregation-beneath-rising-sun-batch-014-04  source f7860911-157a-4fff-a6a5-f904dc8d19e7
#   solo/contactless-card-payment-dollar  source 83b7c65e-14e9-4428-b2e6-57332f20611f
#   solo/contactless-digital-wallet-solo  source adaa1f2f-b19e-47ce-a02c-05816f5de17d
#   solo/controls-rewind  source 2736daad-03fd-5c48-9a0d-f54eed191916
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Combination pliers' 6b9c56ef-5064-4dca-b96f-f14cdc63e5ef 'pictographic-primitives/tools/tools pliers_6b9c56ef-5064-4dca-b96f-f14cdc63e5ef.svg' \
  'Combine harvester front header' 44ee4e62-4052-5cd9-b8ce-7733bb2ccec0 'pictographic-primitives/farming/harvester storage_44ee4e62-4052-5cd9-b8ce-7733bb2ccec0.svg' \
  'Compact car beneath clouds' ee5bbd28-411f-4a8f-bec4-24171fa57174 'pictographic-primitives/_uncategorized_09/car clouds_ee5bbd28-411f-4a8f-bec4-24171fa57174.svg' \
  'Computer memory module' e89894da-2a07-4c85-8acd-326edf5c64cf 'pictographic-primitives/computers/batch-04/computer ram_e89894da-2a07-4c85-8acd-326edf5c64cf.svg' \
  'Computer typing keyboard' 6da646a1-34eb-51f2-af2d-b08aed786a57 pictographic-primitives/computers/batch-06/keyboard_6da646a1-34eb-51f2-af2d-b08aed786a57.svg \
  'Conductor with raised baton' 6659250b-ef9d-4624-8030-348af08008eb pictographic-primitives/_uncategorized_12/conductor_6659250b-ef9d-4624-8030-348af08008eb.svg \
  'Congregation beneath rising sun batch 014 04' f7860911-157a-4fff-a6a5-f904dc8d19e7 'pictographic-primitives/holidays/jumu ah_f7860911-157a-4fff-a6a5-f904dc8d19e7.svg' \
  'Contactless card payment dollar' 83b7c65e-14e9-4428-b2e6-57332f20611f 'pictographic-primitives/payments/contactless payment_83b7c65e-14e9-4428-b2e6-57332f20611f.svg' \
  'Contactless digital wallet solo' adaa1f2f-b19e-47ce-a02c-05816f5de17d 'pictographic-primitives/other/wallet wifi_adaa1f2f-b19e-47ce-a02c-05816f5de17d.svg' \
  'Controls rewind' 2736daad-03fd-5c48-9a0d-f54eed191916 'pictographic-primitives/video/controls rewind_2736daad-03fd-5c48-9a0d-f54eed191916.svg'
