#!/bin/bash
# Batch 56/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/tty-answer  source 91565135-36f8-42bb-b2ed-6c12f04a7eb5
#   solo/tumbling-figure-with-raised-legs  source d6f4580b-3c39-42da-abe7-0d859e33509b
#   solo/twin-peaks-inside-a-rounded-hill-emblem-7acafe9e  source 7acafe9e-8c82-4fc5-aa6b-a6d51b2fb48b
#   solo/twin-prong-nasal-device  source daac8d7c-b6f2-41d2-a661-6c4a0fb6210d
#   solo/twisting-triangle-pose  source c6536663-b340-5128-bbbb-fbd254093c96
#   solo/two-bar-battery  source 0c8f7f81-3b5e-4964-a6bc-5955f81d4007
#   solo/two-blossom-vase  source 17b4e4f0-64b5-500d-a432-783026ce580b
#   solo/two-figures-raised-arm  source 2eeb887b-b913-41a8-aaf8-0d8866ba6edb
#   solo/two-finger-left-swipe  source 0ace5426-8fa0-4fc6-9a78-a7e71dda1c5d
#   solo/two-finger-swipe-down-gesture  source a3e6d289-ee88-4de3-ba1a-d29da5c5d1e9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Tty answer' 91565135-36f8-42bb-b2ed-6c12f04a7eb5 'pictographic-primitives/_uncategorized_38/tty answer_91565135-36f8-42bb-b2ed-6c12f04a7eb5.svg' \
  'Tumbling figure with raised legs' d6f4580b-3c39-42da-abe7-0d859e33509b pictographic-primitives/_uncategorized_35/somersault_d6f4580b-3c39-42da-abe7-0d859e33509b.svg \
  'Twin peaks inside a rounded hill emblem 7acafe9e' 7acafe9e-8c82-4fc5-aa6b-a6d51b2fb48b 'pictographic-primitives/_uncategorized_05/basecamp logo_7acafe9e-8c82-4fc5-aa6b-a6d51b2fb48b.svg' \
  'Twin prong nasal device' daac8d7c-b6f2-41d2-a661-6c4a0fb6210d 'pictographic-primitives/_uncategorized_03/anti snorting device_daac8d7c-b6f2-41d2-a661-6c4a0fb6210d.svg' \
  'Twisting triangle pose' c6536663-b340-5128-bbbb-fbd254093c96 'pictographic-primitives/sports/yoga twisting triangle pose_c6536663-b340-5128-bbbb-fbd254093c96.svg' \
  'Two bar battery' 0c8f7f81-3b5e-4964-a6bc-5955f81d4007 'pictographic-primitives/mobile/charging battery two bars_0c8f7f81-3b5e-4964-a6bc-5955f81d4007.svg' \
  'Two blossom vase' 17b4e4f0-64b5-500d-a432-783026ce580b 'pictographic-primitives/decoration/batch-02/decoration cherry blossom vase_17b4e4f0-64b5-500d-a432-783026ce580b.svg' \
  'Two figures raised arm' 2eeb887b-b913-41a8-aaf8-0d8866ba6edb 'pictographic-primitives/users/pass through_2eeb887b-b913-41a8-aaf8-0d8866ba6edb.svg' \
  'Two finger left swipe' 0ace5426-8fa0-4fc6-9a78-a7e71dda1c5d 'pictographic-primitives/_uncategorized_20/gesture swipe horizontal left two fingers_0ace5426-8fa0-4fc6-9a78-a7e71dda1c5d.svg' \
  'Two finger swipe down gesture' a3e6d289-ee88-4de3-ba1a-d29da5c5d1e9 'pictographic-primitives/_uncategorized_20/gesture swipe vertical down two fingers_a3e6d289-ee88-4de3-ba1a-d29da5c5d1e9.svg'
