#!/bin/bash
# Batch 21/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/diving-block-weight  source 284b7c04-e252-4531-868f-398d3ef94159
#   solo/doctor-with-stethoscope  source 1e909a20-b59c-51ff-929f-4d51607994a7
#   solo/dollar  source 2c47b147-c2f7-4c49-8513-824a167aa784
#   solo/domed-observatory  source af83b2d3-a6c8-48f0-bf59-777e2e438dbf
#   solo/downward-reflection-diagram  source 80d9152e-7c3d-4bfe-8c06-1a9d8b17db38
#   solo/drink-glass-with-bent-straw  source b59d74df-f296-42de-9d2c-6b949b2542d4
#   solo/dripping-honey-dipper-batch-011-14  source 938032ae-5024-5ede-94da-88527f48269f
#   solo/drop-bottle  source 48eb833d-db76-44ba-9351-6d92a11f756c
#   solo/dune-buggy  source bb0b20be-48e9-58c8-a781-dea110e7df94
#   solo/eraser-school-learning  source d9ca1c49-44d0-56e4-9444-15d77da4ff5e
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Diving block weight' 284b7c04-e252-4531-868f-398d3ef94159 'pictographic-primitives/recreation/diving block weight_284b7c04-e252-4531-868f-398d3ef94159.svg' \
  'Doctor with stethoscope' 1e909a20-b59c-51ff-929f-4d51607994a7 'pictographic-primitives/avatars/man doctor_1e909a20-b59c-51ff-929f-4d51607994a7.svg' \
  Dollar 2c47b147-c2f7-4c49-8513-824a167aa784 pictographic-primitives/symbol/dollar_2c47b147-c2f7-4c49-8513-824a167aa784.svg \
  'Domed observatory' af83b2d3-a6c8-48f0-bf59-777e2e438dbf pictographic-primitives/_uncategorized_28/observatory_af83b2d3-a6c8-48f0-bf59-777e2e438dbf.svg \
  'Downward reflection diagram' 80d9152e-7c3d-4bfe-8c06-1a9d8b17db38 'pictographic-primitives/interface-essential/reflect down_80d9152e-7c3d-4bfe-8c06-1a9d8b17db38.svg' \
  'Drink glass with bent straw' b59d74df-f296-42de-9d2c-6b949b2542d4 pictographic-primitives/_uncategorized_16/drink_b59d74df-f296-42de-9d2c-6b949b2542d4.svg \
  'Dripping honey dipper batch 011 14' 938032ae-5024-5ede-94da-88527f48269f pictographic-primitives/food/honey_938032ae-5024-5ede-94da-88527f48269f.svg \
  'Drop bottle' 48eb833d-db76-44ba-9351-6d92a11f756c 'pictographic-primitives/symbol/drop bottle_48eb833d-db76-44ba-9351-6d92a11f756c.svg' \
  'Dune buggy' bb0b20be-48e9-58c8-a781-dea110e7df94 'pictographic-primitives/transportation/adventure car atv_bb0b20be-48e9-58c8-a781-dea110e7df94.svg' \
  'Eraser school learning' d9ca1c49-44d0-56e4-9444-15d77da4ff5e pictographic-primitives/school-learning/eraser_d9ca1c49-44d0-56e4-9444-15d77da4ff5e.svg
