#!/bin/bash
# Batch 6/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/blind  source 5dce7e9a-2184-434a-9e94-71138d2b612d
#   solo/boar-head  source dc49666c-c237-4598-af85-2ca17697cbe2
#   solo/board-rider-over-waves  source 31dfc8f9-9e71-491e-9f9a-e8bd904e4344
#   solo/boat-pose-upward-reach  source e0692252-7dbb-4ed1-8ecb-dd659f3bd9b0
#   solo/boat-propeller  source 4b9f4301-4746-5105-a80a-44e05e91227c
#   solo/bone  source bdd6c205-c49b-4436-8ff7-3c7c0b842d86
#   solo/bottle-opener-with-heart-notched-aperture  source 0b913234-7695-5b92-8cb9-b37fc3a45260
#   solo/bottle-opener-with-rounded-trapezoid-opening  source 7bb85302-0b29-5cf0-a28b-f3dad5fd7fa7
#   solo/bow-tied-around-finger  source cb7f5956-8d37-4c5d-be74-835813bcddcd
#   solo/bowl-with-raised-chopsticks  source 77a9a077-f1dd-4bee-b3cd-ef26744fdd63
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Blind 5dce7e9a-2184-434a-9e94-71138d2b612d pictographic-primitives/interface-essential/blind_5dce7e9a-2184-434a-9e94-71138d2b612d.svg \
  'Boar head' dc49666c-c237-4598-af85-2ca17697cbe2 'pictographic-primitives/animals/wild pig_dc49666c-c237-4598-af85-2ca17697cbe2.svg' \
  'Board rider over waves' 31dfc8f9-9e71-491e-9f9a-e8bd904e4344 pictographic-primitives/sports/skating_31dfc8f9-9e71-491e-9f9a-e8bd904e4344.svg \
  'Boat pose upward reach' e0692252-7dbb-4ed1-8ecb-dd659f3bd9b0 'pictographic-primitives/sports/yoga stretch_e0692252-7dbb-4ed1-8ecb-dd659f3bd9b0.svg' \
  'Boat propeller' 4b9f4301-4746-5105-a80a-44e05e91227c 'pictographic-primitives/transportation/boat engine blade_4b9f4301-4746-5105-a80a-44e05e91227c.svg' \
  Bone bdd6c205-c49b-4436-8ff7-3c7c0b842d86 pictographic-primitives/symbol/bone_bdd6c205-c49b-4436-8ff7-3c7c0b842d86.svg \
  'Bottle opener with heart notched aperture' 0b913234-7695-5b92-8cb9-b37fc3a45260 'pictographic-primitives/drinks/beer opener_0b913234-7695-5b92-8cb9-b37fc3a45260.svg' \
  'Bottle opener with rounded trapezoid opening' 7bb85302-0b29-5cf0-a28b-f3dad5fd7fa7 'pictographic-primitives/drinks/beer opener_7bb85302-0b29-5cf0-a28b-f3dad5fd7fa7.svg' \
  'Bow tied around finger' cb7f5956-8d37-4c5d-be74-835813bcddcd 'pictographic-primitives/holidays/raksha bandhan_cb7f5956-8d37-4c5d-be74-835813bcddcd.svg' \
  'Bowl with raised chopsticks' 77a9a077-f1dd-4bee-b3cd-ef26744fdd63 pictographic-primitives/food/soup_77a9a077-f1dd-4bee-b3cd-ef26744fdd63.svg
