#!/bin/bash
# Batch 42/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/mobile-phone-with-speaker-slot  source 9f179367-374e-503c-9e28-553a2cf59383
#   solo/mobile-phone-with-yuan-sign  source e5fc6b47-c190-46c3-8229-bcad09cb8d97
#   solo/mobile-smartphone-device-solo  source f8d70b1b-fcf7-51cb-94e5-32276b034305
#   solo/mobile-user-profile  source 07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74
#   solo/money-bag  source 6e31cce6-f749-4014-8bc4-bf1b7d5d439c
#   solo/money-message-bubble-solo  source 93c99818-8211-47c5-bf92-9fa83e3cab72
#   solo/monitor-globe  source 47d2e77c-7d13-4e49-a9d3-b0ee7dd5fe74
#   solo/monitor-letters  source dd80ecbb-13f8-47dc-9883-44bd19aa7cc6
#   solo/monitor-math  source 6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13
#   solo/monitor-painting  source 69067a56-4a6a-4f02-bdcf-fc3b45bb66ac
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Mobile phone with speaker slot' 9f179367-374e-503c-9e28-553a2cf59383 'pictographic-primitives/mobile/mobile phone_9f179367-374e-503c-9e28-553a2cf59383.svg' \
  'Mobile phone with yuan sign' e5fc6b47-c190-46c3-8229-bcad09cb8d97 'pictographic-primitives/other/mobile phone yuan sign_e5fc6b47-c190-46c3-8229-bcad09cb8d97.svg' \
  'Mobile smartphone device solo' f8d70b1b-fcf7-51cb-94e5-32276b034305 pictographic-primitives/devices/screen_f8d70b1b-fcf7-51cb-94e5-32276b034305.svg \
  'Mobile user profile' 07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74 'pictographic-primitives/other/mobile phone user_07b8f9ac-0a75-41a3-8bc5-9d1b8abe6e74.svg' \
  'Money bag' 6e31cce6-f749-4014-8bc4-bf1b7d5d439c 'pictographic-primitives/symbol/money bag_6e31cce6-f749-4014-8bc4-bf1b7d5d439c.svg' \
  'Money message bubble solo' 93c99818-8211-47c5-bf92-9fa83e3cab72 'pictographic-primitives/other/message dollar sign lines_93c99818-8211-47c5-bf92-9fa83e3cab72.svg' \
  'Monitor globe' 47d2e77c-7d13-4e49-a9d3-b0ee7dd5fe74 'pictographic-primitives/other/monitor globe_47d2e77c-7d13-4e49-a9d3-b0ee7dd5fe74.svg' \
  'Monitor letters' dd80ecbb-13f8-47dc-9883-44bd19aa7cc6 'pictographic-primitives/other/monitor letters_dd80ecbb-13f8-47dc-9883-44bd19aa7cc6.svg' \
  'Monitor math' 6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13 'pictographic-primitives/other/monitor math_6cbe1bf6-f7d0-4add-99b4-0d1a57f47f13.svg' \
  'Monitor painting' 69067a56-4a6a-4f02-bdcf-fc3b45bb66ac 'pictographic-primitives/other/monitor painting_69067a56-4a6a-4f02-bdcf-fc3b45bb66ac.svg'
