#!/bin/bash
# Batch 33/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/house-thermometer  source c6485cd4-824d-44f8-a250-201a66d4bd70
#   solo/house-with-play-button  source 7e3b79f2-dcc5-4988-ab08-8460306de315
#   solo/howling-wolf  source 02bbed8d-19bf-42c9-9539-d93fbda86791
#   solo/hydroelectric-dam  source 6411cee5-9e14-533a-9adf-d5bcd2213734
#   solo/hyperloop-pod-speed-lines  source 0b674991-fc01-44ec-9571-1f5372072662
#   solo/i-love-you-hand-gesture  source 5a3ae175-815d-4ada-bbd0-26b81be8cd4e
#   solo/ice-cream-pushcart-umbrella  source 7c387930-dc52-4c49-b9d9-34b20fc71ad1
#   solo/ichthys-fish  source 4b380f58-586b-45bc-8749-b86c9b2f3e5c
#   solo/idea-speech-bubble-solo  source 33b77e00-f537-4f70-8180-1310be0dbea9
#   solo/images  source 94993cb5-32ce-48f8-ba6f-9fe516a4704d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'House thermometer' c6485cd4-824d-44f8-a250-201a66d4bd70 'pictographic-primitives/other/house thermometer_c6485cd4-824d-44f8-a250-201a66d4bd70.svg' \
  'House with play button' 7e3b79f2-dcc5-4988-ab08-8460306de315 'pictographic-primitives/other/house with play button_7e3b79f2-dcc5-4988-ab08-8460306de315.svg' \
  'Howling wolf' 02bbed8d-19bf-42c9-9539-d93fbda86791 'pictographic-primitives/animals/wolf body howl_02bbed8d-19bf-42c9-9539-d93fbda86791.svg' \
  'Hydroelectric dam' 6411cee5-9e14-533a-9adf-d5bcd2213734 'pictographic-primitives/landmarks/batch-07/water dam_6411cee5-9e14-533a-9adf-d5bcd2213734.svg' \
  'Hyperloop pod speed lines' 0b674991-fc01-44ec-9571-1f5372072662 'pictographic-primitives/technology/hyperloop speed_0b674991-fc01-44ec-9571-1f5372072662.svg' \
  'I love you hand gesture' 5a3ae175-815d-4ada-bbd0-26b81be8cd4e 'pictographic-primitives/wayfinding/sign language love_5a3ae175-815d-4ada-bbd0-26b81be8cd4e.svg' \
  'Ice cream pushcart umbrella' 7c387930-dc52-4c49-b9d9-34b20fc71ad1 'pictographic-primitives/food/ice cream stand_7c387930-dc52-4c49-b9d9-34b20fc71ad1.svg' \
  'Ichthys fish' 4b380f58-586b-45bc-8749-b86c9b2f3e5c pictographic-primitives/animals/fish_4b380f58-586b-45bc-8749-b86c9b2f3e5c.svg \
  'Idea speech bubble solo' 33b77e00-f537-4f70-8180-1310be0dbea9 'pictographic-primitives/symbol/messages bubble with idea_33b77e00-f537-4f70-8180-1310be0dbea9.svg' \
  Images 94993cb5-32ce-48f8-ba6f-9fe516a4704d pictographic-primitives/state/images_94993cb5-32ce-48f8-ba6f-9fe516a4704d.svg
