#!/bin/bash
# Batch 10/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/canoe-paddler  source fc6689dd-a028-5cb2-b326-1fe893e5518c
#   solo/cao-dai  source 1a804c88-15f7-4476-b406-236f03484b85
#   solo/capped-delivery-rider-on-scooter  source 54079a5b-25ea-4346-8fc4-d2b5f8239da0
#   solo/capped-glue-stick  source 6640054a-f461-4b24-bad8-f2a7fd52f7fb
#   solo/capsule-switch-with-two-strokes-batch-016-14  source 5aacf220-3104-5628-83e3-8dddf6e85cbc
#   solo/car-beneath-wash-bubbles  source d7783b02-e678-4b5f-a12d-e6dd227ecdd8
#   solo/car-broken-beneath-impact-burst  source 757187c1-fd16-4577-8bb6-b25ad4df2330
#   solo/car-intersection-sensor-waves  source ab4d1610-e735-4977-967a-897386cdcc6d
#   solo/car-viewed-from-the-rear  source 2ae26408-156c-43de-9e16-97f3b148035f
#   solo/chef-knife-batch-012-04  source 88acc3ca-ec5a-4cec-af6f-f39df121e302
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Canoe paddler' fc6689dd-a028-5cb2-b326-1fe893e5518c 'pictographic-primitives/recreation/canoe person_fc6689dd-a028-5cb2-b326-1fe893e5518c.svg' \
  'Cao dai' 1a804c88-15f7-4476-b406-236f03484b85 'pictographic-primitives/religion/cao dai_1a804c88-15f7-4476-b406-236f03484b85.svg' \
  'Capped delivery rider on scooter' 54079a5b-25ea-4346-8fc4-d2b5f8239da0 'pictographic-primitives/_uncategorized_14/delivery person motorcycle_54079a5b-25ea-4346-8fc4-d2b5f8239da0.svg' \
  'Capped glue stick' 6640054a-f461-4b24-bad8-f2a7fd52f7fb 'pictographic-primitives/decoration/batch-04/paper glue_6640054a-f461-4b24-bad8-f2a7fd52f7fb.svg' \
  'Capsule switch with two strokes batch 016 14' 5aacf220-3104-5628-83e3-8dddf6e85cbc 'pictographic-primitives/interface-essential/settings off_5aacf220-3104-5628-83e3-8dddf6e85cbc.svg' \
  'Car beneath wash bubbles' d7783b02-e678-4b5f-a12d-e6dd227ecdd8 'pictographic-primitives/_uncategorized_09/car repair wash 2_d7783b02-e678-4b5f-a12d-e6dd227ecdd8.svg' \
  'Car broken beneath impact burst' 757187c1-fd16-4577-8bb6-b25ad4df2330 'pictographic-primitives/_uncategorized_09/car explode_757187c1-fd16-4577-8bb6-b25ad4df2330.svg' \
  'Car intersection sensor waves' ab4d1610-e735-4977-967a-897386cdcc6d 'pictographic-primitives/transportation/intersection assistant_ab4d1610-e735-4977-967a-897386cdcc6d.svg' \
  'Car viewed from the rear' 2ae26408-156c-43de-9e16-97f3b148035f pictographic-primitives/_uncategorized_32/rear_2ae26408-156c-43de-9e16-97f3b148035f.svg \
  'Chef knife batch 012 04' 88acc3ca-ec5a-4cec-af6f-f39df121e302 'pictographic-primitives/food/knife 1_88acc3ca-ec5a-4cec-af6f-f39df121e302.svg'
