#!/bin/bash
# Batch 7/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/bowler-approaching-a-pin  source a2a08b2a-e688-4bab-8c8e-c60515c88862
#   solo/bowling-pins-row  source d972c303-2754-4efe-82ae-c0b2f535370b
#   solo/bowling-pins-three  source 012843f4-1e2d-4bd4-8797-27a0f5f0fd46
#   solo/box-delivery-truck  source 0070eae2-79f7-4131-b3be-164ea822745d
#   solo/boxer  source c2a64d8a-ca70-53b9-b450-150287c2bfc6
#   solo/boxer-with-raised-gloves  source 7de26cb7-7475-4fc2-9562-2738e9bd49cd
#   solo/brain-circuit  source 994c360d-a3ef-411d-83b6-1227713cc09e
#   solo/brain-with-undivided-centre  source 505cc1d4-dec0-4492-aadd-1c3ba0a9d545
#   solo/breakfast-pancake-stack  source 799ea4de-0531-534a-9c5e-9d0bf37abe6f
#   solo/bridge-pose  source ed6cb660-23da-5c6d-9d87-7413118cab56
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Bowler approaching a pin' a2a08b2a-e688-4bab-8c8e-c60515c88862 'pictographic-primitives/_uncategorized_07/bowling player_a2a08b2a-e688-4bab-8c8e-c60515c88862.svg' \
  'Bowling pins row' d972c303-2754-4efe-82ae-c0b2f535370b 'pictographic-primitives/symbol/three bowlings_d972c303-2754-4efe-82ae-c0b2f535370b.svg' \
  'Bowling pins three' 012843f4-1e2d-4bd4-8797-27a0f5f0fd46 'pictographic-primitives/symbol/three bowlings_012843f4-1e2d-4bd4-8797-27a0f5f0fd46.svg' \
  'Box delivery truck' 0070eae2-79f7-4131-b3be-164ea822745d pictographic-primitives/_uncategorized_10/carrier_0070eae2-79f7-4131-b3be-164ea822745d.svg \
  Boxer c2a64d8a-ca70-53b9-b450-150287c2bfc6 pictographic-primitives/avatars/boxer_c2a64d8a-ca70-53b9-b450-150287c2bfc6.svg \
  'Boxer with raised gloves' 7de26cb7-7475-4fc2-9562-2738e9bd49cd pictographic-primitives/_uncategorized_18/fighter_7de26cb7-7475-4fc2-9562-2738e9bd49cd.svg \
  'Brain circuit' 994c360d-a3ef-411d-83b6-1227713cc09e 'pictographic-primitives/_uncategorized_07/brain circuit_994c360d-a3ef-411d-83b6-1227713cc09e.svg' \
  'Brain with undivided centre' 505cc1d4-dec0-4492-aadd-1c3ba0a9d545 'pictographic-primitives/artificial-intelligence/brain 1_505cc1d4-dec0-4492-aadd-1c3ba0a9d545.svg' \
  'Breakfast pancake stack' 799ea4de-0531-534a-9c5e-9d0bf37abe6f 'pictographic-primitives/food/exotic food oyster_799ea4de-0531-534a-9c5e-9d0bf37abe6f.svg' \
  'Bridge pose' ed6cb660-23da-5c6d-9d87-7413118cab56 'pictographic-primitives/sports/yoga bridge pose_ed6cb660-23da-5c6d-9d87-7413118cab56.svg'
