#!/bin/bash
# Batch 46/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/person-with-flared-bob  source 420efd38-3335-538c-8fe6-abc9051f9f1b
#   solo/person-with-hair-swept-behind-ears  source ff4a6b33-a236-5f2d-89ee-7f8719bc7553
#   solo/person-with-side-parted-hair-and-glasses  source 27cefc5a-49c7-5def-9ee4-e76245539d58
#   solo/person-with-wavy-hair  source 95b40f44-d1d6-5bf0-b419-318e3341e675
#   solo/physical-therapy-session-423dcab8  source 423dcab8-75b5-46fd-acba-3c2dc79a82f1
#   solo/picker-take  source b4f371c6-c5e7-45dd-8d80-8cefea43094a
#   solo/pickup-beneath-three-pines  source 6dfa119a-7ff9-4daf-b2d5-bc196f42deb1
#   solo/pie-food  source c499c017-18ac-55ef-8b3d-c050076add31
#   solo/plain-slotted-piggy-bank-dd9a8ecf  source dd9a8ecf-ec10-4cd5-8df9-6f2d1088bffa
#   solo/planet-with-diagonal-ring-solo  source d3179da3-e2e2-4329-8932-7b3c8044a535
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Person with flared bob' 420efd38-3335-538c-8fe6-abc9051f9f1b pictographic-primitives/avatars/woman_420efd38-3335-538c-8fe6-abc9051f9f1b.svg \
  'Person with hair swept behind ears' ff4a6b33-a236-5f2d-89ee-7f8719bc7553 pictographic-primitives/avatars/woman_ff4a6b33-a236-5f2d-89ee-7f8719bc7553.svg \
  'Person with side parted hair and glasses' 27cefc5a-49c7-5def-9ee4-e76245539d58 'pictographic-primitives/avatars/woman glasses_27cefc5a-49c7-5def-9ee4-e76245539d58.svg' \
  'Person with wavy hair' 95b40f44-d1d6-5bf0-b419-318e3341e675 pictographic-primitives/avatars/woman_95b40f44-d1d6-5bf0-b419-318e3341e675.svg \
  'Physical therapy session 423dcab8' 423dcab8-75b5-46fd-acba-3c2dc79a82f1 'pictographic-primitives/health/specialty rehabilitation_423dcab8-75b5-46fd-acba-3c2dc79a82f1.svg' \
  'Picker take' b4f371c6-c5e7-45dd-8d80-8cefea43094a 'pictographic-primitives/design/picker take_b4f371c6-c5e7-45dd-8d80-8cefea43094a.svg' \
  'Pickup beneath three pines' 6dfa119a-7ff9-4daf-b2d5-bc196f42deb1 'pictographic-primitives/_uncategorized_09/car truck woods_6dfa119a-7ff9-4daf-b2d5-bc196f42deb1.svg' \
  'Pie food' c499c017-18ac-55ef-8b3d-c050076add31 pictographic-primitives/food/pie_c499c017-18ac-55ef-8b3d-c050076add31.svg \
  'Plain slotted piggy bank dd9a8ecf' dd9a8ecf-ec10-4cd5-8df9-6f2d1088bffa 'pictographic-primitives/_uncategorized_30/piggy bank_dd9a8ecf-ec10-4cd5-8df9-6f2d1088bffa.svg' \
  'Planet with diagonal ring solo' d3179da3-e2e2-4329-8932-7b3c8044a535 'pictographic-primitives/_uncategorized_04/astronomy planet saturn 1_d3179da3-e2e2-4329-8932-7b3c8044a535.svg'
