#!/bin/bash
# Batch 39/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/man-wearing-bow-tie  source 991b8ae3-461f-513b-aacf-3e86a2bc7b73
#   solo/medium-battery  source 49a99532-87a4-4620-9412-a0a544789c05
#   solo/medium-battery-gauge  source b63f7e34-fcd6-4615-82e7-c5f15c2f13a5
#   solo/medium-temperature-thermometer-8ab1cb04  source 8ab1cb04-f795-4ebc-818d-6255c2998131
#   solo/merge-arrow-nodes  source e601eded-1157-4544-9970-cc41755f1439
#   solo/message-bubble-with-text  source a1a67209-da16-4d81-b455-f1e69aae865c
#   solo/microsoft-visual-studio-logo  source f23c1fcf-345a-4ef4-b844-ecdca619586a
#   solo/minimal-bicycle  source 6ce17d6f-0a53-4eaa-b433-061d444307dc
#   solo/minimal-side-chair-continuous-shell  source b869f8fd-1289-40ca-9383-12b4a73291d1
#   solo/mobile-phone-bell  source 819857f6-7191-4e86-8585-718826dd7d33
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Man wearing bow tie' 991b8ae3-461f-513b-aacf-3e86a2bc7b73 pictographic-primitives/avatars/man_991b8ae3-461f-513b-aacf-3e86a2bc7b73.svg \
  'Medium battery' 49a99532-87a4-4620-9412-a0a544789c05 'pictographic-primitives/mobile/charging battery medium_49a99532-87a4-4620-9412-a0a544789c05.svg' \
  'Medium battery gauge' b63f7e34-fcd6-4615-82e7-c5f15c2f13a5 'pictographic-primitives/mobile/charging battery medium_b63f7e34-fcd6-4615-82e7-c5f15c2f13a5.svg' \
  'Medium temperature thermometer 8ab1cb04' 8ab1cb04-f795-4ebc-818d-6255c2998131 'pictographic-primitives/health/temperature thermometer medium_8ab1cb04-f795-4ebc-818d-6255c2998131.svg' \
  'Merge arrow nodes' e601eded-1157-4544-9970-cc41755f1439 'pictographic-primitives/programing/internet of thing green grass_e601eded-1157-4544-9970-cc41755f1439.svg' \
  'Message bubble with text' a1a67209-da16-4d81-b455-f1e69aae865c 'pictographic-primitives/_uncategorized_27/messages bubble text 1_a1a67209-da16-4d81-b455-f1e69aae865c.svg' \
  'Microsoft visual studio logo' f23c1fcf-345a-4ef4-b844-ecdca619586a 'pictographic-primitives/logos/microsoft visual studio logo_f23c1fcf-345a-4ef4-b844-ecdca619586a.svg' \
  'Minimal bicycle' 6ce17d6f-0a53-4eaa-b433-061d444307dc pictographic-primitives/transportation/bicycle_6ce17d6f-0a53-4eaa-b433-061d444307dc.svg \
  'Minimal side chair continuous shell' b869f8fd-1289-40ca-9383-12b4a73291d1 'pictographic-primitives/furnitures/chair modern_b869f8fd-1289-40ca-9383-12b4a73291d1.svg' \
  'Mobile phone bell' 819857f6-7191-4e86-8585-718826dd7d33 'pictographic-primitives/other/mobile phone bell_819857f6-7191-4e86-8585-718826dd7d33.svg'
