#!/bin/bash
# Batch 27/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-carving-a-block  source 11e91124-506f-4bc4-9aa0-511ff30e500c
#   solo/hand-clapper-toys  source d14f767a-d27e-45c9-837c-e0c5f4d0ad51
#   solo/hand-docking-game-console  source fb11a30f-fb1c-4930-9aae-280bc7d071fc
#   solo/hand-drill-fire-log  source e94edbaf-c94d-4cdc-a976-817dfd2498ef
#   solo/hand-gesture-expand-screen  source 50312a29-a897-494e-b23f-8a7aa90fde0d
#   solo/hand-grabbing-square-document  source 6818d5fa-ca7b-4205-ab33-ff7acb27ba99
#   solo/hand-gripping-plain-cup  source 9264b9dc-a5f7-44e5-8956-5e45e3269681
#   solo/hand-gripping-upward-tilted-megaphone  source dade40b3-c760-4793-8539-0b7a29c7d77c
#   solo/hand-holding-axe  source 47659966-6bcc-4338-8851-46f26e9cca27
#   solo/hand-holding-banknote  source 5a88b033-48de-5da2-bd8c-9b53bb261082
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand carving a block' 11e91124-506f-4bc4-9aa0-511ff30e500c pictographic-primitives/_uncategorized_10/carving_11e91124-506f-4bc4-9aa0-511ff30e500c.svg \
  'Hand clapper toys' d14f767a-d27e-45c9-837c-e0c5f4d0ad51 'pictographic-primitives/rewards/reward claps hand stick_d14f767a-d27e-45c9-837c-e0c5f4d0ad51.svg' \
  'Hand docking game console' fb11a30f-fb1c-4930-9aae-280bc7d071fc 'pictographic-primitives/video-games/batch-11/switch dock_fb11a30f-fb1c-4930-9aae-280bc7d071fc.svg' \
  'Hand drill fire log' e94edbaf-c94d-4cdc-a976-817dfd2498ef 'pictographic-primitives/_uncategorized_29/outdoors camp fire make_e94edbaf-c94d-4cdc-a976-817dfd2498ef.svg' \
  'Hand gesture expand screen' 50312a29-a897-494e-b23f-8a7aa90fde0d 'pictographic-primitives/_uncategorized_22/hand gesture control expand_50312a29-a897-494e-b23f-8a7aa90fde0d.svg' \
  'Hand grabbing square document' 6818d5fa-ca7b-4205-ab33-ff7acb27ba99 'pictographic-primitives/interface-essential/drag drop hand_6818d5fa-ca7b-4205-ab33-ff7acb27ba99.svg' \
  'Hand gripping plain cup' 9264b9dc-a5f7-44e5-8956-5e45e3269681 'pictographic-primitives/_uncategorized_10/ceramic making_9264b9dc-a5f7-44e5-8956-5e45e3269681.svg' \
  'Hand gripping upward tilted megaphone' dade40b3-c760-4793-8539-0b7a29c7d77c 'pictographic-primitives/_uncategorized_16/election campaign 4_dade40b3-c760-4793-8539-0b7a29c7d77c.svg' \
  'Hand holding axe' 47659966-6bcc-4338-8851-46f26e9cca27 'pictographic-primitives/tools/tools axe hold_47659966-6bcc-4338-8851-46f26e9cca27.svg' \
  'Hand holding banknote' 5a88b033-48de-5da2-bd8c-9b53bb261082 'pictographic-primitives/payments/cash payment bills_5a88b033-48de-5da2-bd8c-9b53bb261082.svg'
