#!/bin/bash
# Batch 30/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-pinching-acupuncture-needle  source 219024ce-9973-4736-8ba2-b73e81755a00
#   solo/hand-pinching-chip  source 7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02
#   solo/hand-playing-yoyo  source 28a605e6-a545-47ed-ae21-f45557bb8374
#   solo/hand-pointing-up  source 6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9
#   solo/hand-reaching-for-diamond  source bce3f8f6-b015-42a5-94c3-92f3bb3be306
#   solo/hand-reaching-toward-foot  source 06de442e-575d-48bb-ae42-82d8ef6c23c5
#   solo/hand-supporting-a-heart  source 353c0a3e-5be1-4b87-8e05-ba32a7f03da8
#   solo/hand-under-running-water  source a34cf5c7-6f9d-4929-bade-fa576555a44e
#   solo/hand-with-round-wrist-ornament  source a053cd16-d4e9-4fa2-8cbc-8e8c60de043b
#   solo/handcuff-pair-with-separate-key  source 4a54478b-4849-4373-b597-046376cb8fb9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand pinching acupuncture needle' 219024ce-9973-4736-8ba2-b73e81755a00 'pictographic-primitives/_uncategorized_01/acupuncture hand_219024ce-9973-4736-8ba2-b73e81755a00.svg' \
  'Hand pinching chip' 7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02 'pictographic-primitives/programing/chip hold_7fbc0ada-902f-43f4-bdab-cc7b8ccc1b02.svg' \
  'Hand playing yoyo' 28a605e6-a545-47ed-ae21-f45557bb8374 'pictographic-primitives/kids/playing yoyo_28a605e6-a545-47ed-ae21-f45557bb8374.svg' \
  'Hand pointing up' 6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9 'pictographic-primitives/wayfinding/finger point 1_6c5ced19-9a99-46fd-9dda-dfd6ad80f1a9.svg' \
  'Hand reaching for diamond' bce3f8f6-b015-42a5-94c3-92f3bb3be306 'pictographic-primitives/finance/diamond hold_bce3f8f6-b015-42a5-94c3-92f3bb3be306.svg' \
  'Hand reaching toward foot' 06de442e-575d-48bb-ae42-82d8ef6c23c5 'pictographic-primitives/holidays/guru purnima hand_06de442e-575d-48bb-ae42-82d8ef6c23c5.svg' \
  'Hand supporting a heart' 353c0a3e-5be1-4b87-8e05-ba32a7f03da8 'pictographic-primitives/_uncategorized_33/romance pride lgbt heart hand holding_353c0a3e-5be1-4b87-8e05-ba32a7f03da8.svg' \
  'Hand under running water' a34cf5c7-6f9d-4929-bade-fa576555a44e 'pictographic-primitives/_uncategorized_25/locker room wash hands 1_a34cf5c7-6f9d-4929-bade-fa576555a44e.svg' \
  'Hand with round wrist ornament' a053cd16-d4e9-4fa2-8cbc-8e8c60de043b 'pictographic-primitives/_uncategorized_07/bracelet with hand_a053cd16-d4e9-4fa2-8cbc-8e8c60de043b.svg' \
  'Handcuff pair with separate key' 4a54478b-4849-4373-b597-046376cb8fb9 'pictographic-primitives/_uncategorized_13/crime tools shackle key_4a54478b-4849-4373-b597-046376cb8fb9.svg'
