#!/bin/bash
# Batch 9/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/bunny-holding-easter-egg  source 606ec34e-20d1-525e-a765-4f3fca8d3c47
#   solo/burger-beside-drink-cup  source 5d4383cc-7fa3-4af5-b119-dc3b67d08db0
#   solo/burrito  source b3b9d031-1b14-49cd-b640-12d78e2f90f7
#   solo/butternut-squash-vegetable-batch-010-11  source 0e2a3b90-793a-5161-aa41-5a7e08f9195c
#   solo/calendar-number-seven  source d7201890-607e-4568-916a-e843756d3ef0
#   solo/calendar-phone  source fd8eb806-4d12-4ad0-bb86-c0aaf66d08bc
#   solo/camera-drone-front  source d66af9da-0871-557c-abb0-a240e310287a
#   solo/camera-with-shaking-lines  source f5ada276-7815-4d75-9ba7-b74ca81c7919
#   solo/camper-behind-flagged-tent  source 5655244e-9c88-42c3-a2be-d90a6fab78b2
#   solo/canoe  source 2f08daf6-071b-5ac7-9717-2239ffbb2925
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Bunny holding easter egg' 606ec34e-20d1-525e-a765-4f3fca8d3c47 'pictographic-primitives/holidays/easter egg bunny_606ec34e-20d1-525e-a765-4f3fca8d3c47.svg' \
  'Burger beside drink cup' 5d4383cc-7fa3-4af5-b119-dc3b67d08db0 'pictographic-primitives/_uncategorized_18/fast food burger drink_5d4383cc-7fa3-4af5-b119-dc3b67d08db0.svg' \
  Burrito b3b9d031-1b14-49cd-b640-12d78e2f90f7 pictographic-primitives/_uncategorized_08/burrito_b3b9d031-1b14-49cd-b640-12d78e2f90f7.svg \
  'Butternut squash vegetable batch 010 11' 0e2a3b90-793a-5161-aa41-5a7e08f9195c pictographic-primitives/food/butternutsquash_0e2a3b90-793a-5161-aa41-5a7e08f9195c.svg \
  'Calendar number seven' d7201890-607e-4568-916a-e843756d3ef0 'pictographic-primitives/other/calendar number seven_d7201890-607e-4568-916a-e843756d3ef0.svg' \
  'Calendar phone' fd8eb806-4d12-4ad0-bb86-c0aaf66d08bc 'pictographic-primitives/other/calendar phone_fd8eb806-4d12-4ad0-bb86-c0aaf66d08bc.svg' \
  'Camera drone front' d66af9da-0871-557c-abb0-a240e310287a 'pictographic-primitives/technology/drone camera_d66af9da-0871-557c-abb0-a240e310287a.svg' \
  'Camera with shaking lines' f5ada276-7815-4d75-9ba7-b74ca81c7919 'pictographic-primitives/_uncategorized_09/camera settings frame 1_f5ada276-7815-4d75-9ba7-b74ca81c7919.svg' \
  'Camper behind flagged tent' 5655244e-9c88-42c3-a2be-d90a6fab78b2 'pictographic-primitives/_uncategorized_09/camping tent person_5655244e-9c88-42c3-a2be-d90a6fab78b2.svg' \
  Canoe 2f08daf6-071b-5ac7-9717-2239ffbb2925 pictographic-primitives/outdoors/canoe_2f08daf6-071b-5ac7-9717-2239ffbb2925.svg
