#!/bin/bash
# Batch 14/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/cookie-tray-in-oven  source 41472ab4-d5b7-4320-9072-c062ba84ab5d
#   solo/cord-sling-and-stone  source feb59830-d1d6-5f9b-bea2-7f92cbc04249
#   solo/corn  source dfc9df01-8144-40e0-b66d-be471956d900
#   solo/coughing-person-profile  source 70068075-fcbd-43f7-8047-bd45057d5d00
#   solo/counterclockwise-circular-arrow-batch-019-08  source 567f7df5-55ba-4b86-8f69-4c5a4f43e848
#   solo/counterclockwise-circular-refresh-arrows-batch-020-03  source 0a11ecc5-12d2-479f-ad50-bf72f2730e09
#   solo/counterclockwise-refresh-arrow  source 77f5a2c6-8120-4350-aa53-7bb00704de7d
#   solo/counterclockwise-synchronize-arrows  source bafc5d96-6820-5892-a08b-927ab58a96ff
#   solo/couple-busts  source a76c7c2d-a4c9-4c4a-8eec-dac04079bf30
#   solo/couple-standing  source 3f9770e9-9cf6-4ca7-8f89-f37f07aff7a2
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Cookie tray in oven' 41472ab4-d5b7-4320-9072-c062ba84ab5d 'pictographic-primitives/food/cooking baking tray oven_41472ab4-d5b7-4320-9072-c062ba84ab5d.svg' \
  'Cord sling and stone' feb59830-d1d6-5f9b-bea2-7f92cbc04249 'pictographic-primitives/war/antique sling_feb59830-d1d6-5f9b-bea2-7f92cbc04249.svg' \
  Corn dfc9df01-8144-40e0-b66d-be471956d900 pictographic-primitives/food/corn_dfc9df01-8144-40e0-b66d-be471956d900.svg \
  'Coughing person profile' 70068075-fcbd-43f7-8047-bd45057d5d00 'pictographic-primitives/_uncategorized_22/head side cough_70068075-fcbd-43f7-8047-bd45057d5d00.svg' \
  'Counterclockwise circular arrow batch 019 08' 567f7df5-55ba-4b86-8f69-4c5a4f43e848 'pictographic-primitives/other/go backward_567f7df5-55ba-4b86-8f69-4c5a4f43e848.svg' \
  'Counterclockwise circular refresh arrows batch 020 03' 0a11ecc5-12d2-479f-ad50-bf72f2730e09 pictographic-primitives/other/repeat_0a11ecc5-12d2-479f-ad50-bf72f2730e09.svg \
  'Counterclockwise refresh arrow' 77f5a2c6-8120-4350-aa53-7bb00704de7d 'pictographic-primitives/interface-essential/synchronize refresh arrow_77f5a2c6-8120-4350-aa53-7bb00704de7d.svg' \
  'Counterclockwise synchronize arrows' bafc5d96-6820-5892-a08b-927ab58a96ff 'pictographic-primitives/interface-essential/synchronize arrows_bafc5d96-6820-5892-a08b-927ab58a96ff.svg' \
  'Couple busts' a76c7c2d-a4c9-4c4a-8eec-dac04079bf30 pictographic-primitives/symbol/couple_a76c7c2d-a4c9-4c4a-8eec-dac04079bf30.svg \
  'Couple standing' 3f9770e9-9cf6-4ca7-8f89-f37f07aff7a2 'pictographic-primitives/users/multiple man woman_3f9770e9-9cf6-4ca7-8f89-f37f07aff7a2.svg'
