#!/bin/bash
# Batch 44/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/pacman  source ea992b74-1d7b-5d1a-9380-854e5151b7ed
#   solo/paintbrush-with-separate-ferrule-solo-b017  source 1abc0ab3-cc14-5329-b46e-3658f7db2237
#   solo/painted-wall-mural-panel  source c05f1690-f04d-460c-a834-2bdbd5877990
#   solo/palette-with-two-angular-paint-marks  source a50f4b37-52bf-57b9-a897-fe227c4018c5
#   solo/parasailing  source be90db18-f520-40cb-b813-e134392a43e1
#   solo/park-and-bike  source dfc037b7-3cf4-5183-a3ea-94c433baaa81
#   solo/pen-writing-looped-signature  source f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5
#   solo/pencil-above-writing-line  source 9831d51b-062f-5589-98b9-8768752474a6
#   solo/pencil-drawing-house-plan-solo-b003-07  source c74c88d8-5693-44d0-8cc1-01e35bd5345e
#   solo/pencil-drawn-squiggle  source 09802860-599e-4eb4-b68f-43ddebc59be7
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  Pacman ea992b74-1d7b-5d1a-9380-854e5151b7ed pictographic-primitives/video-games/batch-08/pacman_d162e891-6c21-47e5-ab18-e1fc863c5dc5.svg \
  'Paintbrush with separate ferrule solo b017' 1abc0ab3-cc14-5329-b46e-3658f7db2237 pictographic-primitives/other/brush_1abc0ab3-cc14-5329-b46e-3658f7db2237.svg \
  'Painted wall mural panel' c05f1690-f04d-460c-a834-2bdbd5877990 'pictographic-primitives/landmarks/batch-04/east side gallery berlin wall_c05f1690-f04d-460c-a834-2bdbd5877990.svg' \
  'Palette with two angular paint marks' a50f4b37-52bf-57b9-a897-fe227c4018c5 'pictographic-primitives/design/color palette sample_a50f4b37-52bf-57b9-a897-fe227c4018c5.svg' \
  Parasailing be90db18-f520-40cb-b813-e134392a43e1 'pictographic-primitives/outdoors/sport para sailing_be90db18-f520-40cb-b813-e134392a43e1.svg' \
  'Park and bike' dfc037b7-3cf4-5183-a3ea-94c433baaa81 'pictographic-primitives/transportation/park and bike_dfc037b7-3cf4-5183-a3ea-94c433baaa81.svg' \
  'Pen writing looped signature' f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5 'pictographic-primitives/files/fill and sign_f25f2fcc-8f1e-51ec-9c1c-2b8093904cb5.svg' \
  'Pencil above writing line' 9831d51b-062f-5589-98b9-8768752474a6 'pictographic-primitives/interface-essential/pencil edit_9831d51b-062f-5589-98b9-8768752474a6.svg' \
  'Pencil drawing house plan solo b003 07' c74c88d8-5693-44d0-8cc1-01e35bd5345e 'pictographic-primitives/construction/project plan pen_c74c88d8-5693-44d0-8cc1-01e35bd5345e.svg' \
  'Pencil drawn squiggle' 09802860-599e-4eb4-b68f-43ddebc59be7 'pictographic-primitives/_uncategorized_30/pen draw 2_09802860-599e-4eb4-b68f-43ddebc59be7.svg'
