#!/bin/bash
# Batch 61/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/vr-headset  source 333b76cc-b37e-568d-8fc3-aa0f76f2f559
#   solo/vr-headset-side-profile  source 019edb66-6728-4e28-ae42-b3dcaedeee84
#   solo/vr-headset-side-view  source 19d18716-03ac-5472-90fb-a05a4e989ab8
#   solo/vr-headset-video-games  source 427e8988-7e0f-4f0e-930b-42ce7a00bd27
#   solo/waiting-room-couple  source 18363920-a131-4703-9250-544ef6984fd4
#   solo/wallet-with-snap-tab  source 114ddaa5-c570-4bb4-b10e-88469985798b
#   solo/washing-hands  source b49d7989-5d86-40cf-8c72-632e8858db04
#   solo/watch-hands  source ab913828-297d-4c94-ab76-5b92952287d3
#   solo/waving-hand-with-motion-arcs  source 44669c46-5f1b-4268-ad2e-f9c53c88603f
#   solo/wavy-dollar-bill  source f112a16f-0b5c-4192-abdc-173f55e6a032
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Vr headset' 333b76cc-b37e-568d-8fc3-aa0f76f2f559 'pictographic-primitives/video-games/vr headset_333b76cc-b37e-568d-8fc3-aa0f76f2f559.svg' \
  'Vr headset side profile' 019edb66-6728-4e28-ae42-b3dcaedeee84 'pictographic-primitives/other/vr headset 1_019edb66-6728-4e28-ae42-b3dcaedeee84.svg' \
  'Vr headset side view' 19d18716-03ac-5472-90fb-a05a4e989ab8 'pictographic-primitives/technology/meta quest_19d18716-03ac-5472-90fb-a05a4e989ab8.svg' \
  'Vr headset video games' 427e8988-7e0f-4f0e-930b-42ce7a00bd27 'pictographic-primitives/video-games/vr headset_427e8988-7e0f-4f0e-930b-42ce7a00bd27.svg' \
  'Waiting room couple' 18363920-a131-4703-9250-544ef6984fd4 'pictographic-primitives/_uncategorized_39/waiting room couple_18363920-a131-4703-9250-544ef6984fd4.svg' \
  'Wallet with snap tab' 114ddaa5-c570-4bb4-b10e-88469985798b pictographic-primitives/other/wallet_114ddaa5-c570-4bb4-b10e-88469985798b.svg \
  'Washing hands' b49d7989-5d86-40cf-8c72-632e8858db04 'pictographic-primitives/wayfinding/washing hand_b49d7989-5d86-40cf-8c72-632e8858db04.svg' \
  'Watch hands' ab913828-297d-4c94-ab76-5b92952287d3 'pictographic-primitives/state/watch hands_ab913828-297d-4c94-ab76-5b92952287d3.svg' \
  'Waving hand with motion arcs' 44669c46-5f1b-4268-ad2e-f9c53c88603f 'pictographic-primitives/chat/photo motion sensor_44669c46-5f1b-4268-ad2e-f9c53c88603f.svg' \
  'Wavy dollar bill' f112a16f-0b5c-4192-abdc-173f55e6a032 'pictographic-primitives/_uncategorized_27/money bill wave_f112a16f-0b5c-4192-abdc-173f55e6a032.svg'
