#!/bin/bash
# Batch 40/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/mobile-phone-bug  source 600bc5a2-131a-4e43-b134-f5e672684c21
#   solo/mobile-phone-c4f9e2f1  source c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf
#   solo/mobile-phone-check  source 94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3
#   solo/mobile-phone-control-pause  source b4668e9a-a445-4547-ab4c-3cab57aef111
#   solo/mobile-phone-control-play  source d0012287-f904-4bd1-be94-369aca27d22a
#   solo/mobile-phone-dollar-sign  source 31035467-a6b8-4c8d-8d52-52dc236bc2c7
#   solo/mobile-phone-euro  source 1c0f91c5-ddcd-4057-9258-33ab46aaac34
#   solo/mobile-phone-eye  source 68f5ee87-964a-4acb-b5b1-78cd1710295f
#   solo/mobile-phone-fe2bd8e5  source fe2bd8e5-ec37-49f1-9a9a-636d7f1d1e8e
#   solo/mobile-phone-fingerprint  source 0ef09a66-6578-497b-817b-f821ad82e177
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Mobile phone bug' 600bc5a2-131a-4e43-b134-f5e672684c21 'pictographic-primitives/other/mobile phone bug_600bc5a2-131a-4e43-b134-f5e672684c21.svg' \
  'Mobile phone c4f9e2f1' c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf 'pictographic-primitives/phones/mobile phone_c4f9e2f1-641c-4dbb-ae42-c4ce12aafedf.svg' \
  'Mobile phone check' 94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3 'pictographic-primitives/other/mobile phone check_94d3c6cc-58a9-4369-a2d0-f4c8bcd61cc3.svg' \
  'Mobile phone control pause' b4668e9a-a445-4547-ab4c-3cab57aef111 'pictographic-primitives/state/mobile phone control pause_b4668e9a-a445-4547-ab4c-3cab57aef111.svg' \
  'Mobile phone control play' d0012287-f904-4bd1-be94-369aca27d22a 'pictographic-primitives/state/mobile phone control play_d0012287-f904-4bd1-be94-369aca27d22a.svg' \
  'Mobile phone dollar sign' 31035467-a6b8-4c8d-8d52-52dc236bc2c7 'pictographic-primitives/other/mobile phone dollar sign_31035467-a6b8-4c8d-8d52-52dc236bc2c7.svg' \
  'Mobile phone euro' 1c0f91c5-ddcd-4057-9258-33ab46aaac34 'pictographic-primitives/other/mobile phone euro sign_1c0f91c5-ddcd-4057-9258-33ab46aaac34.svg' \
  'Mobile phone eye' 68f5ee87-964a-4acb-b5b1-78cd1710295f 'pictographic-primitives/other/mobile phone eye_68f5ee87-964a-4acb-b5b1-78cd1710295f.svg' \
  'Mobile phone fe2bd8e5' fe2bd8e5-ec37-49f1-9a9a-636d7f1d1e8e 'pictographic-primitives/mobile/mobile phone_fe2bd8e5-ec37-49f1-9a9a-636d7f1d1e8e.svg' \
  'Mobile phone fingerprint' 0ef09a66-6578-497b-817b-f821ad82e177 'pictographic-primitives/other/mobile phone fingerprint_0ef09a66-6578-497b-817b-f821ad82e177.svg'
