#!/bin/bash
# Batch 60/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/vectors-pen-add-1  source 49a3ae80-8be9-4e8e-9359-748e0b24459f
#   solo/venus-astrological-symbol  source a926bc8d-1ac4-5954-820d-cc012466623f
#   solo/venus-flytrap-with-leaf  source b27bfeed-a105-4ab7-9c64-52d85a0abb70
#   solo/vertical-swipe-down-finger-gesture  source b918e243-05fb-49d7-a0ca-da68f69be04a
#   solo/video-cba8c0da  source cba8c0da-97a3-4786-8e5c-d74b9dd80be2
#   solo/video-conference-monitor  source ec2d4eb4-b488-4b60-b260-7de322e396fd
#   solo/view  source a73a3ea1-b1ee-5adb-a13b-215a290d268a
#   solo/virtual-coin-crypto-decred  source 55e973e5-31ee-4bd8-9749-f78c78d90cc1
#   solo/virtual-reality-headset-solo  source 8a515529-35b3-4547-9b35-3ae486711582
#   solo/volume-control  source f2722b0f-fff4-493b-8f5d-619316ae89e6
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Vectors pen add 1' 49a3ae80-8be9-4e8e-9359-748e0b24459f 'pictographic-primitives/_uncategorized_39/vectors pen add 1_49a3ae80-8be9-4e8e-9359-748e0b24459f.svg' \
  'Venus astrological symbol' a926bc8d-1ac4-5954-820d-cc012466623f 'pictographic-primitives/culture/batch-07/astrology venus_a926bc8d-1ac4-5954-820d-cc012466623f.svg' \
  'Venus flytrap with leaf' b27bfeed-a105-4ab7-9c64-52d85a0abb70 pictographic-primitives/_uncategorized_19/flytrap_b27bfeed-a105-4ab7-9c64-52d85a0abb70.svg \
  'Vertical swipe down finger gesture' b918e243-05fb-49d7-a0ca-da68f69be04a 'pictographic-primitives/_uncategorized_20/gesture swipe vertical down_b918e243-05fb-49d7-a0ca-da68f69be04a.svg' \
  'Video cba8c0da' cba8c0da-97a3-4786-8e5c-d74b9dd80be2 pictographic-primitives/symbol/video_cba8c0da-97a3-4786-8e5c-d74b9dd80be2.svg \
  'Video conference monitor' ec2d4eb4-b488-4b60-b260-7de322e396fd 'pictographic-primitives/other/monitor person_ec2d4eb4-b488-4b60-b260-7de322e396fd.svg' \
  View a73a3ea1-b1ee-5adb-a13b-215a290d268a pictographic-primitives/interface-essential/view_a73a3ea1-b1ee-5adb-a13b-215a290d268a.svg \
  'Virtual coin crypto decred' 55e973e5-31ee-4bd8-9749-f78c78d90cc1 'pictographic-primitives/money/virtual coin crypto decred_55e973e5-31ee-4bd8-9749-f78c78d90cc1.svg' \
  'Virtual reality headset solo' 8a515529-35b3-4547-9b35-3ae486711582 'pictographic-primitives/other/device wearable vr goggles_8a515529-35b3-4547-9b35-3ae486711582.svg' \
  'Volume control' f2722b0f-fff4-493b-8f5d-619316ae89e6 'pictographic-primitives/audio/volume control_f2722b0f-fff4-493b-8f5d-619316ae89e6.svg'
