#!/bin/bash
# Batch 12/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/cloudberry-with-paired-top-leaves  source eafdf9a0-9c6d-4a1c-8cdd-84a2ec5341c9
#   solo/cloudy-windy-night  source f236e29a-8ef1-4244-a485-206757ee3b57
#   solo/clustered-berry-with-branching-stem-batch-051  source ac0aabf7-0c09-4997-9ab6-af64655e476d
#   solo/cobra-head  source 722cb33f-03cc-5935-ab1a-86a1ade0a234
#   solo/codefactor-logo  source de32221d-3ae3-4517-b767-d8728cf1083f
#   solo/cog-dollar  source fa84ff77-a565-4df3-9360-0b7e9c3de772
#   solo/cog-double  source b484255b-2a40-40d1-9943-7e27cfb9f399
#   solo/cog-double-1  source 82c1163c-aaf6-4c80-9120-18bf38090361
#   solo/coiled-french-horn  source e0e5259b-1f4e-49b1-b4fe-796abc5994f0
#   solo/coiled-snake  source bd9f57fc-780e-5c9d-8047-c776f0b4d870
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Cloudberry with paired top leaves' eafdf9a0-9c6d-4a1c-8cdd-84a2ec5341c9 'pictographic-primitives/food/cloud berry_eafdf9a0-9c6d-4a1c-8cdd-84a2ec5341c9.svg' \
  'Cloudy windy night' f236e29a-8ef1-4244-a485-206757ee3b57 'pictographic-primitives/_uncategorized_40/weather night wind 1_f236e29a-8ef1-4244-a485-206757ee3b57.svg' \
  'Clustered berry with branching stem batch 051' ac0aabf7-0c09-4997-9ab6-af64655e476d 'pictographic-primitives/_uncategorized_20/fruit blackberry raspberry boysenberrry_ac0aabf7-0c09-4997-9ab6-af64655e476d.svg' \
  'Cobra head' 722cb33f-03cc-5935-ab1a-86a1ade0a234 'pictographic-primitives/animals/cobra head side_722cb33f-03cc-5935-ab1a-86a1ade0a234.svg' \
  'Codefactor logo' de32221d-3ae3-4517-b767-d8728cf1083f 'pictographic-primitives/logos/codefactor logo_de32221d-3ae3-4517-b767-d8728cf1083f.svg' \
  'Cog dollar' fa84ff77-a565-4df3-9360-0b7e9c3de772 'pictographic-primitives/other/cog dollar_fa84ff77-a565-4df3-9360-0b7e9c3de772.svg' \
  'Cog double' b484255b-2a40-40d1-9943-7e27cfb9f399 'pictographic-primitives/_uncategorized_12/cog double_b484255b-2a40-40d1-9943-7e27cfb9f399.svg' \
  'Cog double 1' 82c1163c-aaf6-4c80-9120-18bf38090361 'pictographic-primitives/_uncategorized_12/cog double 1_82c1163c-aaf6-4c80-9120-18bf38090361.svg' \
  'Coiled french horn' e0e5259b-1f4e-49b1-b4fe-796abc5994f0 'pictographic-primitives/_uncategorized_23/instrument french horn_e0e5259b-1f4e-49b1-b4fe-796abc5994f0.svg' \
  'Coiled snake' bd9f57fc-780e-5c9d-8047-c776f0b4d870 'pictographic-primitives/animals/reptile snake_bd9f57fc-780e-5c9d-8047-c776f0b4d870.svg'
