#!/bin/bash
# Batch 32/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hex-nut-cluster-solo  source e9326841-b6b1-432e-a99d-c2065849139b
#   solo/high-temperature-thermometer  source 1fa52957-1342-499f-9403-f3293476b96f
#   solo/home-cog  source 8e974970-0198-4484-85aa-47bb0a455f4b
#   solo/horizontal-measurement-markers-solo  source 5e331499-062d-4a4a-965e-e100d55ce756
#   solo/horizontal-ruler-with-five-top-ticks  source 8e5cf0f4-16ef-55be-9abb-2b6fd8017da3
#   solo/horizontal-telephone-receiver  source 791f3e5f-2569-40aa-92db-6d888122af9d
#   solo/horse-pulling-small-carriage  source 589093c2-50d1-4d6e-b46e-2aef2795cea3
#   solo/house-phone  source 7c7ae497-e683-4449-9d47-32e2c0e677e7
#   solo/house-power  source 95e78717-28bd-4a88-951a-54d6ae9c18e6
#   solo/house-property-value-solo  source ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hex nut cluster solo' e9326841-b6b1-432e-a99d-c2065849139b 'pictographic-primitives/programing/well architected tools_e9326841-b6b1-432e-a99d-c2065849139b.svg' \
  'High temperature thermometer' 1fa52957-1342-499f-9403-f3293476b96f 'pictographic-primitives/food/temperature thermometer high_1fa52957-1342-499f-9403-f3293476b96f.svg' \
  'Home cog' 8e974970-0198-4484-85aa-47bb0a455f4b 'pictographic-primitives/other/home cog_8e974970-0198-4484-85aa-47bb0a455f4b.svg' \
  'Horizontal measurement markers solo' 5e331499-062d-4a4a-965e-e100d55ce756 'pictographic-primitives/other/measurement markers_5e331499-062d-4a4a-965e-e100d55ce756.svg' \
  'Horizontal ruler with five top ticks' 8e5cf0f4-16ef-55be-9abb-2b6fd8017da3 pictographic-primitives/design/ruler_8e5cf0f4-16ef-55be-9abb-2b6fd8017da3.svg \
  'Horizontal telephone receiver' 791f3e5f-2569-40aa-92db-6d888122af9d 'pictographic-primitives/phones/phone horizontal_791f3e5f-2569-40aa-92db-6d888122af9d.svg' \
  'Horse pulling small carriage' 589093c2-50d1-4d6e-b46e-2aef2795cea3 pictographic-primitives/_uncategorized_10/carriage_589093c2-50d1-4d6e-b46e-2aef2795cea3.svg \
  'House phone' 7c7ae497-e683-4449-9d47-32e2c0e677e7 'pictographic-primitives/other/house phone_7c7ae497-e683-4449-9d47-32e2c0e677e7.svg' \
  'House power' 95e78717-28bd-4a88-951a-54d6ae9c18e6 'pictographic-primitives/other/house power_95e78717-28bd-4a88-951a-54d6ae9c18e6.svg' \
  'House property value solo' ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8 'pictographic-primitives/symbol/house dollar_ec996bcb-4c1a-4d3c-84fb-8218d5fa19b8.svg'
