#!/bin/bash
# Batch 66/66: 8 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/wrench-and-screwdriver  source 774bfcef-0999-44e7-9307-b99279f04ee1
#   solo/xenomorph-creature  source 4cce42f7-9a4b-47ca-8564-c6162d026735
#   solo/yen-currency-message-bubble-solo  source 16791ce0-2910-4e3b-82ee-8dcb1834e398
#   solo/yoga-tree-pose  source cd308a08-5d16-5ba7-ba3b-4c7cff751329
#   solo/yogurt-tub-with-overhanging-lid-and-blank-label  source b9010bac-03b8-4454-af17-94f86a623b1a
#   solo/zeus-with-lightning-bolt  source 339413a2-9f25-4881-9b93-a087f3da321c
#   solo/zipper-mouth-face  source 553978e0-a38a-465c-89ce-33f54387ba69
#   solo/zoom-logo  source 83306cac-34f4-4c2c-a7fe-6f53595d9c9c
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Wrench and screwdriver' 774bfcef-0999-44e7-9307-b99279f04ee1 'pictographic-primitives/_uncategorized_38/tool organizer 1_774bfcef-0999-44e7-9307-b99279f04ee1.svg' \
  'Xenomorph creature' 4cce42f7-9a4b-47ca-8564-c6162d026735 pictographic-primitives/science/xenomorph_4cce42f7-9a4b-47ca-8564-c6162d026735.svg \
  'Yen currency message bubble solo' 16791ce0-2910-4e3b-82ee-8dcb1834e398 'pictographic-primitives/other/message yuan sign lines_16791ce0-2910-4e3b-82ee-8dcb1834e398.svg' \
  'Yoga tree pose' cd308a08-5d16-5ba7-ba3b-4c7cff751329 'pictographic-primitives/sports/yoga tree pose_cd308a08-5d16-5ba7-ba3b-4c7cff751329.svg' \
  'Yogurt tub with overhanging lid and blank label' b9010bac-03b8-4454-af17-94f86a623b1a 'pictographic-primitives/drinks/snow family_b9010bac-03b8-4454-af17-94f86a623b1a.svg' \
  'Zeus with lightning bolt' 339413a2-9f25-4881-9b93-a087f3da321c pictographic-primitives/religion/zeus_339413a2-9f25-4881-9b93-a087f3da321c.svg \
  'Zipper mouth face' 553978e0-a38a-465c-89ce-33f54387ba69 pictographic-primitives/smileys/zipped_553978e0-a38a-465c-89ce-33f54387ba69.svg \
  'Zoom logo' 83306cac-34f4-4c2c-a7fe-6f53595d9c9c 'pictographic-primitives/logos/zoom logo_83306cac-34f4-4c2c-a7fe-6f53595d9c9c.svg'
