#!/bin/bash
# Batch 29/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/hand-holding-rakhi-thread  source 8b38c950-ec94-4fcb-a8d0-90a189601728
#   solo/hand-holding-smartphone-component  source 03153fc4-5884-4120-9394-75c1b95598b0
#   solo/hand-holding-snake  source cc4af31b-ad07-4519-9e2a-a3b2ee7e8834
#   solo/hand-holding-teaspoon  source d2d4de96-ee6e-420e-9d3b-ad79631d2a67
#   solo/hand-holding-two-game-cards  source 9e452a20-d223-431c-a550-2caad608f489
#   solo/hand-holding-wireless-phone  source 67fe58cc-4429-4121-a342-5bd274251e19
#   solo/hand-holding-wrench  source 80b7765d-72c2-4b01-b0bf-6a084aa9bc97
#   solo/hand-over-heat  source e2391138-4aaf-4587-83d5-f636e7ba5379
#   solo/hand-passing-capsule  source 37a4523d-3384-4c79-9494-a5cfb681f4f0
#   solo/hand-patting-dog  source ef1c856a-063a-4941-92f0-78189ee7aba9
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Hand holding rakhi thread' 8b38c950-ec94-4fcb-a8d0-90a189601728 'pictographic-primitives/holidays/raksha bandhan 1_8b38c950-ec94-4fcb-a8d0-90a189601728.svg' \
  'Hand holding smartphone component' 03153fc4-5884-4120-9394-75c1b95598b0 'pictographic-primitives/phones/squeeze sides 1_03153fc4-5884-4120-9394-75c1b95598b0.svg' \
  'Hand holding snake' cc4af31b-ad07-4519-9e2a-a3b2ee7e8834 pictographic-primitives/hobbies/herping_cc4af31b-ad07-4519-9e2a-a3b2ee7e8834.svg \
  'Hand holding teaspoon' d2d4de96-ee6e-420e-9d3b-ad79631d2a67 'pictographic-primitives/food/tea spoon_d2d4de96-ee6e-420e-9d3b-ad79631d2a67.svg' \
  'Hand holding two game cards' 9e452a20-d223-431c-a550-2caad608f489 'pictographic-primitives/_uncategorized_10/card game cards hold_9e452a20-d223-431c-a550-2caad608f489.svg' \
  'Hand holding wireless phone' 67fe58cc-4429-4121-a342-5bd274251e19 'pictographic-primitives/phones/wifi transfer hand_67fe58cc-4429-4121-a342-5bd274251e19.svg' \
  'Hand holding wrench' 80b7765d-72c2-4b01-b0bf-6a084aa9bc97 'pictographic-primitives/tools/tools wrench hold_80b7765d-72c2-4b01-b0bf-6a084aa9bc97.svg' \
  'Hand over heat' e2391138-4aaf-4587-83d5-f636e7ba5379 'pictographic-primitives/symbol/hand with flame_e2391138-4aaf-4587-83d5-f636e7ba5379.svg' \
  'Hand passing capsule' 37a4523d-3384-4c79-9494-a5cfb681f4f0 'pictographic-primitives/crime/drugs dealer_37a4523d-3384-4c79-9494-a5cfb681f4f0.svg' \
  'Hand patting dog' ef1c856a-063a-4941-92f0-78189ee7aba9 'pictographic-primitives/pets/dog side patting good_ef1c856a-063a-4941-92f0-78189ee7aba9.svg'
