#!/bin/bash
# Batch 8/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/briefcase-carrying-hailing-person  source 459ca9bc-41c3-44a7-bd18-4322e40df660
#   solo/briefcase-dollar  source 07459f9b-1db4-4f1f-aeee-4e5113b2f2f4
#   solo/broad-headphones-with-tall-rounded-earcups  source b737e5e2-78be-44b5-be8e-53fa1fe642af
#   solo/broccoli-and-carrot  source 1833535f-220e-490a-9e51-7058a14ac9db
#   solo/browser-dollar-sign-right  source 150d4701-3c3f-45a7-a26d-8c580a891da1
#   solo/browser-person  source 3a3e4d85-115c-4ccb-82d1-46fd45222b3a
#   solo/browser-with-18-plus-text  source fc5ffdff-80e9-4119-bf62-fb7c515c5aad
#   solo/browser-yuan-sign-solo  source f3a40f08-7124-46f5-9ed2-b85ee4e25e73
#   solo/bubbling-magic-cauldron  source 72f64d5e-456e-45c1-80a8-12d9cbe19516
#   solo/bunch-of-bananas-batch-010-10  source 01dfab52-1214-532b-8f84-ea5dce7a2998
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Briefcase carrying hailing person' 459ca9bc-41c3-44a7-bd18-4322e40df660 'pictographic-primitives/_uncategorized_37/taxi wave businessman_459ca9bc-41c3-44a7-bd18-4322e40df660.svg' \
  'Briefcase dollar' 07459f9b-1db4-4f1f-aeee-4e5113b2f2f4 'pictographic-primitives/other/briefcase dollar_07459f9b-1db4-4f1f-aeee-4e5113b2f2f4.svg' \
  'Broad headphones with tall rounded earcups' b737e5e2-78be-44b5-be8e-53fa1fe642af pictographic-primitives/_uncategorized_16/earmuffs_b737e5e2-78be-44b5-be8e-53fa1fe642af.svg \
  'Broccoli and carrot' 1833535f-220e-490a-9e51-7058a14ac9db 'pictographic-primitives/symbol/broccoli carrot_1833535f-220e-490a-9e51-7058a14ac9db.svg' \
  'Browser dollar sign right' 150d4701-3c3f-45a7-a26d-8c580a891da1 'pictographic-primitives/other/browser dollar sign right_150d4701-3c3f-45a7-a26d-8c580a891da1.svg' \
  'Browser person' 3a3e4d85-115c-4ccb-82d1-46fd45222b3a 'pictographic-primitives/other/browser person_3a3e4d85-115c-4ccb-82d1-46fd45222b3a.svg' \
  'Browser with 18 plus text' fc5ffdff-80e9-4119-bf62-fb7c515c5aad 'pictographic-primitives/other/browser with 18+ text_fc5ffdff-80e9-4119-bf62-fb7c515c5aad.svg' \
  'Browser yuan sign solo' f3a40f08-7124-46f5-9ed2-b85ee4e25e73 'pictographic-primitives/other/browser yuan sign right_f3a40f08-7124-46f5-9ed2-b85ee4e25e73.svg' \
  'Bubbling magic cauldron' 72f64d5e-456e-45c1-80a8-12d9cbe19516 'pictographic-primitives/video-games/batch-12/witch cauldron_72f64d5e-456e-45c1-80a8-12d9cbe19516.svg' \
  'Bunch of bananas batch 010 10' 01dfab52-1214-532b-8f84-ea5dce7a2998 pictographic-primitives/food/banana_01dfab52-1214-532b-8f84-ea5dce7a2998.svg
