#!/bin/bash
# Batch 11/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/chess-rook-wide-battlements  source 6827ce25-bda1-54bb-bc4b-11e435eb0b3f
#   solo/circle-colon  source 6a0ef6b0-613d-4883-ad08-e75fd510a4f6
#   solo/circular-rotating-arrows  source e63cb3c3-10bb-4fb1-a675-1e6b119047a5
#   solo/clenched-fist-batch-020-08  source f9cc745f-989b-5241-9fd0-090475a8c137
#   solo/clipboard-solo  source 8a44db68-8509-4e9a-b460-4143125c86a9
#   solo/clock-with-clockwise-return-arrow  source 4ae0f802-0947-49ab-948b-a13314a05022
#   solo/clock-with-counterclockwise-arrival-arrow  source 7420a5ad-20b8-4125-a020-7f6c31b74aac
#   solo/closed-fist  source 398a358b-6ba9-5507-b8f7-6dfcb7f136d1
#   solo/closed-fitness-band-with-two-display-marks  source 1cd0692c-3506-4df2-80d7-66be18de3019
#   solo/cloud-with-moon-and-lightning  source 7eb10cf4-5263-45f8-929d-49906b04ace0
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Chess rook wide battlements' 6827ce25-bda1-54bb-bc4b-11e435eb0b3f 'pictographic-primitives/hobbies/chess rook_6827ce25-bda1-54bb-bc4b-11e435eb0b3f.svg' \
  'Circle colon' 6a0ef6b0-613d-4883-ad08-e75fd510a4f6 'pictographic-primitives/other/circle colon_6a0ef6b0-613d-4883-ad08-e75fd510a4f6.svg' \
  'Circular rotating arrows' e63cb3c3-10bb-4fb1-a675-1e6b119047a5 'pictographic-primitives/_uncategorized_04/arrows spin_e63cb3c3-10bb-4fb1-a675-1e6b119047a5.svg' \
  'Clenched fist batch 020 08' f9cc745f-989b-5241-9fd0-090475a8c137 'pictographic-primitives/other/hand fist bump_f9cc745f-989b-5241-9fd0-090475a8c137.svg' \
  'Clipboard solo' 8a44db68-8509-4e9a-b460-4143125c86a9 pictographic-primitives/other/clipboard_8a44db68-8509-4e9a-b460-4143125c86a9.svg \
  'Clock with clockwise return arrow' 4ae0f802-0947-49ab-948b-a13314a05022 'pictographic-primitives/_uncategorized_34/snooze return repeat_4ae0f802-0947-49ab-948b-a13314a05022.svg' \
  'Clock with counterclockwise arrival arrow' 7420a5ad-20b8-4125-a020-7f6c31b74aac 'pictographic-primitives/_uncategorized_34/shipping logistic estimate time arrival 1_7420a5ad-20b8-4125-a020-7f6c31b74aac.svg' \
  'Closed fist' 398a358b-6ba9-5507-b8f7-6dfcb7f136d1 'pictographic-primitives/wayfinding/hand fist bump_398a358b-6ba9-5507-b8f7-6dfcb7f136d1.svg' \
  'Closed fitness band with two display marks' 1cd0692c-3506-4df2-80d7-66be18de3019 'pictographic-primitives/devices/wearable smart watch_1cd0692c-3506-4df2-80d7-66be18de3019.svg' \
  'Cloud with moon and lightning' 7eb10cf4-5263-45f8-929d-49906b04ace0 'pictographic-primitives/_uncategorized_40/weather night snow thunder_7eb10cf4-5263-45f8-929d-49906b04ace0.svg'
