#!/bin/bash
# Batch 58/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/two-teeth-with-braces  source ac9c677b-473a-4138-92bb-0d16f69a0b08
#   solo/two-tower-suspension-bridge  source 86b37e1a-0047-497f-8897-cc61b8ea2db2
#   solo/two-woman-busts  source 33f91774-80a6-484a-b389-240a82b9a4ed
#   solo/two-women-with-fringe  source a39aa19c-ac24-4e35-8e35-e653e256f2f7
#   solo/type-a-outlet-with-flattened-circular-recess  source 2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db
#   solo/type-b-outlet-with-two-slots-and-ground-hole  source 5b5a5348-95e6-489c-abb3-fe356243022b
#   solo/type-f-outlet-with-two-holes-and-earth-tabs  source a953c01a-331f-443c-b5ed-5756e2821bc2
#   solo/upper-and-lower-teeth  source 6bac9175-ec81-4a3c-8737-7515abe0d327
#   solo/upright-bullet-cartridge  source 7db2d7b5-d033-4d27-9946-8454fc7d5e75
#   solo/upright-hand-holding-chopsticks  source 3f45199b-b4b8-41dc-bf1e-5e7f32883756
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Two teeth with braces' ac9c677b-473a-4138-92bb-0d16f69a0b08 'pictographic-primitives/health/dental brace_ac9c677b-473a-4138-92bb-0d16f69a0b08.svg' \
  'Two tower suspension bridge' 86b37e1a-0047-497f-8897-cc61b8ea2db2 'pictographic-primitives/_uncategorized_08/bridge golden gate_86b37e1a-0047-497f-8897-cc61b8ea2db2.svg' \
  'Two woman busts' 33f91774-80a6-484a-b389-240a82b9a4ed 'pictographic-primitives/users/multiple woman 1_33f91774-80a6-484a-b389-240a82b9a4ed.svg' \
  'Two women with fringe' a39aa19c-ac24-4e35-8e35-e653e256f2f7 'pictographic-primitives/users/multiple woman 2_a39aa19c-ac24-4e35-8e35-e653e256f2f7.svg' \
  'Type a outlet with flattened circular recess' 2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db 'pictographic-primitives/electronics/power outlet type a_2a9c6ec5-79b6-5a6b-92b4-e35cba30a7db.svg' \
  'Type b outlet with two slots and ground hole' 5b5a5348-95e6-489c-abb3-fe356243022b 'pictographic-primitives/electronics/power outlet type b_5b5a5348-95e6-489c-abb3-fe356243022b.svg' \
  'Type f outlet with two holes and earth tabs' a953c01a-331f-443c-b5ed-5756e2821bc2 'pictographic-primitives/electronics/power outlet type f_a953c01a-331f-443c-b5ed-5756e2821bc2.svg' \
  'Upper and lower teeth' 6bac9175-ec81-4a3c-8737-7515abe0d327 'pictographic-primitives/health/dentistry tooth jaws_6bac9175-ec81-4a3c-8737-7515abe0d327.svg' \
  'Upright bullet cartridge' 7db2d7b5-d033-4d27-9946-8454fc7d5e75 pictographic-primitives/_uncategorized_03/ammunition_7db2d7b5-d033-4d27-9946-8454fc7d5e75.svg \
  'Upright hand holding chopsticks' 3f45199b-b4b8-41dc-bf1e-5e7f32883756 pictographic-primitives/food/chopstick_3f45199b-b4b8-41dc-bf1e-5e7f32883756.svg
