#!/bin/bash
# Batch 54/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/thermometer-mercury  source b9550739-2fcc-4d3f-b1da-62a62d9213f5
#   solo/thermometer-scale  source 9b762d04-fb82-4b78-b65a-738dfc7b4d64
#   solo/threaded-sewing-needle  source 132f47bc-4c0e-4882-9b9d-93439d0723ca
#   solo/three-fanned-playing-cards  source 5af5ae7c-c36a-44e3-b9a3-a6d9683548ab
#   solo/three-feather-shuttlecock  source 73d5e308-a155-41b6-a284-6bbcb4d01b7b
#   solo/three-folded-arrows-forming-recycling-loop-solo  source 5e1048c9-9d25-56a8-b734-5d83dac9ce83
#   solo/three-hole-round-power-socket  source b7b88464-3cc0-499b-ab8a-f9847d3456ba
#   solo/three-leaf-cilantro-sprig  source 9dff6770-6d28-4114-ba4d-94dc1f630b89
#   solo/three-open-recycling-arrows  source eba86955-13f5-4b0a-a78e-55e6a9fb7a6a
#   solo/three-person-organization-hierarchy  source a9dfee64-d94e-5290-9f2d-1568f42ab28b
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Thermometer mercury' b9550739-2fcc-4d3f-b1da-62a62d9213f5 pictographic-primitives/symbol/thermometer_b9550739-2fcc-4d3f-b1da-62a62d9213f5.svg \
  'Thermometer scale' 9b762d04-fb82-4b78-b65a-738dfc7b4d64 pictographic-primitives/symbol/thermometer_9b762d04-fb82-4b78-b65a-738dfc7b4d64.svg \
  'Threaded sewing needle' 132f47bc-4c0e-4882-9b9d-93439d0723ca pictographic-primitives/other/needle_132f47bc-4c0e-4882-9b9d-93439d0723ca.svg \
  'Three fanned playing cards' 5af5ae7c-c36a-44e3-b9a3-a6d9683548ab 'pictographic-primitives/_uncategorized_10/card game cards_5af5ae7c-c36a-44e3-b9a3-a6d9683548ab.svg' \
  'Three feather shuttlecock' 73d5e308-a155-41b6-a284-6bbcb4d01b7b pictographic-primitives/_uncategorized_05/badminton_73d5e308-a155-41b6-a284-6bbcb4d01b7b.svg \
  'Three folded arrows forming recycling loop solo' 5e1048c9-9d25-56a8-b734-5d83dac9ce83 'pictographic-primitives/ecology/recycling sign_5e1048c9-9d25-56a8-b734-5d83dac9ce83.svg' \
  'Three hole round power socket' b7b88464-3cc0-499b-ab8a-f9847d3456ba 'pictographic-primitives/_uncategorized_31/power outlet type k_b7b88464-3cc0-499b-ab8a-f9847d3456ba.svg' \
  'Three leaf cilantro sprig' 9dff6770-6d28-4114-ba4d-94dc1f630b89 'pictographic-primitives/food/cilantro colliander_9dff6770-6d28-4114-ba4d-94dc1f630b89.svg' \
  'Three open recycling arrows' eba86955-13f5-4b0a-a78e-55e6a9fb7a6a 'pictographic-primitives/_uncategorized_32/recycling symbol_eba86955-13f5-4b0a-a78e-55e6a9fb7a6a.svg' \
  'Three person organization hierarchy' a9dfee64-d94e-5290-9f2d-1568f42ab28b 'pictographic-primitives/companies/workflow teamwork hierarchy_a9dfee64-d94e-5290-9f2d-1568f42ab28b.svg'
