#!/bin/bash
# Batch 45/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/pencil-marking-ballot  source 8baf23d7-4390-4407-a5c3-c22b45141f27
#   solo/person-at-podium  source 1461f130-1461-5759-8ff2-8de25b9591b9
#   solo/person-holding-smartphone  source 24fc49f1-a250-5adb-b331-999bec7daf9c
#   solo/person-raising-megaphone-with-sound-rays  source 0538edcd-5de5-4e07-affe-fdfe3d69c7c7
#   solo/person-sitting-by-trash-can  source 9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce
#   solo/person-slipping-backward  source 7f0ac7d1-2c65-44de-9523-d762d29b36e3
#   solo/person-target-head  source 77a78a1e-7942-4955-a807-6a094b7b3a35
#   solo/person-wearing-headphones-in-profile  source 87b4dae7-6d5a-504e-b877-c237378af3a1
#   solo/person-with-angular-heart-torso  source 2aa1a351-da44-44d3-bef9-70273bc4350d
#   solo/person-with-close-fitting-cap  source 64e1f5f5-7795-46a5-9b85-0c64d4138046
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Pencil marking ballot' 8baf23d7-4390-4407-a5c3-c22b45141f27 pictographic-primitives/school-learning/election_8baf23d7-4390-4407-a5c3-c22b45141f27.svg \
  'Person at podium' 1461f130-1461-5759-8ff2-8de25b9591b9 'pictographic-primitives/users/neutral podium_1461f130-1461-5759-8ff2-8de25b9591b9.svg' \
  'Person holding smartphone' 24fc49f1-a250-5adb-b331-999bec7daf9c 'pictographic-primitives/work/meeting smartphone hold_24fc49f1-a250-5adb-b331-999bec7daf9c.svg' \
  'Person raising megaphone with sound rays' 0538edcd-5de5-4e07-affe-fdfe3d69c7c7 'pictographic-primitives/_uncategorized_16/election campaign 3_0538edcd-5de5-4e07-affe-fdfe3d69c7c7.svg' \
  'Person sitting by trash can' 9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce 'pictographic-primitives/users/user homeless poverty_9c6217f6-4ce5-4d83-b2e6-1f3f8e4d6fce.svg' \
  'Person slipping backward' 7f0ac7d1-2c65-44de-9523-d762d29b36e3 'pictographic-primitives/symbol/person slipping rocky_7f0ac7d1-2c65-44de-9523-d762d29b36e3.svg' \
  'Person target head' 77a78a1e-7942-4955-a807-6a094b7b3a35 'pictographic-primitives/symbol/person 1_77a78a1e-7942-4955-a807-6a094b7b3a35.svg' \
  'Person wearing headphones in profile' 87b4dae7-6d5a-504e-b877-c237378af3a1 'pictographic-primitives/audio/headphones human_87b4dae7-6d5a-504e-b877-c237378af3a1.svg' \
  'Person with angular heart torso' 2aa1a351-da44-44d3-bef9-70273bc4350d 'pictographic-primitives/romance/phone digital well being heart 1_2aa1a351-da44-44d3-bef9-70273bc4350d.svg' \
  'Person with close fitting cap' 64e1f5f5-7795-46a5-9b85-0c64d4138046 pictographic-primitives/_uncategorized_13/crewman_64e1f5f5-7795-46a5-9b85-0c64d4138046.svg
