#!/bin/bash
# Batch 49/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/square-face-smartwatch  source 5c04a7e9-5ff0-4256-a6b8-3fa7b45bce9a
#   solo/square-j  source 5b6e5baa-d86e-4627-abf5-975ed777ad4f
#   solo/square-megaphone  source 84596dd2-069a-450e-b70c-08a8dc22159b
#   solo/square-parking-slash  source 5f15564f-f916-4d99-9b2e-2bea2bc94e4b
#   solo/square-phone  source 746eedc8-eb0c-4e03-8d4c-d25625ee4a35
#   solo/square-phone-hangup  source 48b58407-6e7b-4cf9-b629-9742f8a963af
#   solo/square-right  source 4b4c4e57-da6a-4ce9-9d53-b8f095c266b7
#   solo/square-u  source 4b4ea565-bcbe-4767-b464-b357bbf9e918
#   solo/square-up-left  source 0426472c-0785-4dc2-86f3-c6d7d6107f27
#   solo/square-v  source 32c98c89-6e46-4737-9aa5-e927668b865d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Square face smartwatch' 5c04a7e9-5ff0-4256-a6b8-3fa7b45bce9a 'pictographic-primitives/other/watch 1_5c04a7e9-5ff0-4256-a6b8-3fa7b45bce9a.svg' \
  'Square j' 5b6e5baa-d86e-4627-abf5-975ed777ad4f 'pictographic-primitives/_uncategorized_35/square j_5b6e5baa-d86e-4627-abf5-975ed777ad4f.svg' \
  'Square megaphone' 84596dd2-069a-450e-b70c-08a8dc22159b 'pictographic-primitives/other/square megaphone_84596dd2-069a-450e-b70c-08a8dc22159b.svg' \
  'Square parking slash' 5f15564f-f916-4d99-9b2e-2bea2bc94e4b 'pictographic-primitives/_uncategorized_35/square parking slash_5f15564f-f916-4d99-9b2e-2bea2bc94e4b.svg' \
  'Square phone' 746eedc8-eb0c-4e03-8d4c-d25625ee4a35 'pictographic-primitives/_uncategorized_35/square phone_746eedc8-eb0c-4e03-8d4c-d25625ee4a35.svg' \
  'Square phone hangup' 48b58407-6e7b-4cf9-b629-9742f8a963af 'pictographic-primitives/_uncategorized_35/square phone hangup_48b58407-6e7b-4cf9-b629-9742f8a963af.svg' \
  'Square right' 4b4c4e57-da6a-4ce9-9d53-b8f095c266b7 'pictographic-primitives/_uncategorized_35/square right_4b4c4e57-da6a-4ce9-9d53-b8f095c266b7.svg' \
  'Square u' 4b4ea565-bcbe-4767-b464-b357bbf9e918 'pictographic-primitives/_uncategorized_35/square u_4b4ea565-bcbe-4767-b464-b357bbf9e918.svg' \
  'Square up left' 0426472c-0785-4dc2-86f3-c6d7d6107f27 'pictographic-primitives/_uncategorized_35/square up left_0426472c-0785-4dc2-86f3-c6d7d6107f27.svg' \
  'Square v' 32c98c89-6e46-4737-9aa5-e927668b865d 'pictographic-primitives/_uncategorized_36/square v_32c98c89-6e46-4737-9aa5-e927668b865d.svg'
