#!/bin/bash
# Batch 38/66: 10 icons as NAME SOURCE_ID [REFERENCE]; generated by fetch_repeat_disapproved.py.
#   solo/low-battery-level  source 058db2e8-12db-48c2-b344-337f39e8f77d
#   solo/low-battery-level-block  source d6b813e9-7593-44ac-8b7e-dc8a1b2e1275
#   solo/low-temperature-thermometer  source 5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8
#   solo/magnifier-refresh  source cddee393-b2d9-4824-86a6-013321aa73e8
#   solo/magnifying-glass-pill  source 15fc1905-26f1-420c-9167-f58df5f29604
#   solo/mail  source 75ad5383-92bd-435c-984f-c475f5f845c1
#   solo/mail-symbol  source a6d5c36b-5f72-4bbf-a205-b2d56aaf29a5
#   solo/man-doctor-avatar  source 7c323144-b65a-558b-a01d-ac1899c73509
#   solo/man-graduate-avatar  source 7764a030-9bc6-4b16-aa7c-7ad4e9ca54bc
#   solo/man-japan-avatar  source 3c937449-3b63-4517-a7b7-4088598ee58d
cd /Applications/Workspaces/pictographic/claude_skills
new-pipeline-test/run_pipeline.sh \
  'Low battery level' 058db2e8-12db-48c2-b344-337f39e8f77d 'pictographic-primitives/devices/charging battery low_058db2e8-12db-48c2-b344-337f39e8f77d.svg' \
  'Low battery level block' d6b813e9-7593-44ac-8b7e-dc8a1b2e1275 'pictographic-primitives/devices/charging battery low_d6b813e9-7593-44ac-8b7e-dc8a1b2e1275.svg' \
  'Low temperature thermometer' 5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8 'pictographic-primitives/_uncategorized_37/temperature low_5074d2b2-162c-4fd5-9c6a-c95bcbfca5d8.svg' \
  'Magnifier refresh' cddee393-b2d9-4824-86a6-013321aa73e8 'pictographic-primitives/business/seo search_cddee393-b2d9-4824-86a6-013321aa73e8.svg' \
  'Magnifying glass pill' 15fc1905-26f1-420c-9167-f58df5f29604 'pictographic-primitives/other/magnifying glass pill_15fc1905-26f1-420c-9167-f58df5f29604.svg' \
  Mail 75ad5383-92bd-435c-984f-c475f5f845c1 pictographic-primitives/symbol/mail_75ad5383-92bd-435c-984f-c475f5f845c1.svg \
  'Mail symbol' a6d5c36b-5f72-4bbf-a205-b2d56aaf29a5 pictographic-primitives/symbol/mail_a6d5c36b-5f72-4bbf-a205-b2d56aaf29a5.svg \
  'Man doctor avatar' 7c323144-b65a-558b-a01d-ac1899c73509 'pictographic-primitives/avatars/man doctor_7c323144-b65a-558b-a01d-ac1899c73509.svg' \
  'Man graduate avatar' 7764a030-9bc6-4b16-aa7c-7ad4e9ca54bc 'pictographic-primitives/avatars/man graduate_7764a030-9bc6-4b16-aa7c-7ad4e9ca54bc.svg' \
  'Man japan avatar' 3c937449-3b63-4517-a7b7-4088598ee58d 'pictographic-primitives/avatars/man japan_3c937449-3b63-4517-a7b7-4088598ee58d.svg'
