/* Saved AI judgments and immutable evidence; this page never writes approval state. */
function filterQualityIcons(icons, query, verdict, issue, batch='') {
  const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  return icons.filter(icon=>terms.every(term=>icon.icon_id.replaceAll('-',' ').includes(term.replaceAll('-',' ')))&&(!verdict||icon.final===verdict)&&(!issue||icon.group===issue)&&(!batch||String(icon.batch)===String(batch)));
}
function paginateQualityIcons(rows, requestedPage, size=25) {
  const pages=Math.max(1,Math.ceil(rows.length/size));
  const page=Math.max(1,Math.min(pages,Math.floor(Number(requestedPage))||1));
  return {page,pages,start:(page-1)*size,rows:rows.slice((page-1)*size,page*size)};
}
if(typeof module!=='undefined')module.exports={filterQualityIcons,paginateQualityIcons};
if(typeof document!=='undefined')(()=>{
  const $=id=>document.getElementById(id),base='ai-review-data/';
  const titles={concept:'Concept match',recognition:'Recognition',ambiguity:'Ambiguity',small_size:'Small-size clarity',simplicity:'Simplicity',drawing:'Drawing quality',balance:'Balance',symmetry:'Symmetry',smoothness:'Smoothness'};
  const labels={'light-native.png':'Light · native size','dark-native.png':'Dark · native size','light-large.png':'Light · enlarged','dark-large.png':'Dark · enlarged','reference.png':'Source reference','mirror.png':'Mirror comparison','centerline.png':'Centerlines & junctions','centerline-junction.png':'Corner tangent detail','focus.png':'Highlighted finding'};
  let data,selected,page=1;
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  function asset(r,name){return base+r.assets[name];}
  function picture(r,name,cls){const img=el('img',cls);img.src=asset(r,name);img.alt=r.icon_id+' — '+labels[name];img.loading='lazy';return img;}
  function pill(value){return el('span','quality-pill '+value.toLowerCase(),value);}
  function paragraph(label,text){const p=el('p');p.append(el('strong',null,label+' '),document.createTextNode(text));return p;}
  function evidenceLink(r,name){const a=el('a',name.startsWith('dark')?'evidence-dark':'');a.href=asset(r,name);a.target='_blank';a.rel='noopener';a.setAttribute('aria-label','Open '+labels[name]+' evidence for '+r.icon_id+' in a new tab');const img=picture(r,name,name.includes('native')?'native-evidence':'');if(name.includes('native')){img.width=r.native_size;img.height=r.native_size;}a.append(img,el('span',null,labels[name]+' ↗'));return a;}
  function showDetail(r){
    const target=$('qualityDetail');target.replaceChildren();target.setAttribute('aria-busy','false');
    const header=el('div','quality-detail-head'),heading=el('div');heading.append(el('div','meta',String(r.number).padStart(2,'0')+' / '+data.icons.length+' · Batch '+(r.batch||1)+' · '+r.profile+' · '+r.keyshape),el('h2',null,r.icon_id.replaceAll('-',' ')),el('div','meta','Saved review · '+data.review_date));
    const gallery=el('a',null,'Open in Icon review ↗');gallery.href='index.html?q='+encodeURIComponent(r.icon_id);header.append(heading,gallery);target.append(header);
    const conclusion=el('div','quality-conclusion '+r.final.toLowerCase());conclusion.append(el('strong',null,'Final conclusion'),el('p',null,r.final_conclusion));target.append(conclusion);
    const previews=el('div','quality-preview');for(const theme of ['light','dark']){const box=el('div','quality-theme '+theme);for(const size of ['native','large']){const f=el('figure'),img=picture(r,theme+'-'+size+'.png',size);if(size==='native'){img.width=r.native_size;img.height=r.native_size;}f.append(img,el('figcaption',null,theme.charAt(0).toUpperCase()+theme.slice(1)+' · '+(size==='native'?r.native_size+'px':'enlarged')));box.append(f);}previews.append(box);}target.append(previews,paragraph('Observed reading:',r.observed_reading));
    if(r.assets['centerline.png']){const center=el('section','quality-centerline');center.append(el('h3',null,'Centerline evidence'));const link=evidenceLink(r,'centerline.png');center.append(link,el('p','meta',r.centerline_caption));if(r.review_revision_note)center.append(el('p','quality-revision',r.review_revision_note));target.append(center);}
    const title=el('div','quality-section-heading');title.append(el('h3',null,'Analysis & evidence'),el('span',null,r.analyses.length+' checks · '+Object.values(r.checks).filter(v=>v==='NO').length+' NO'));target.append(title);
    for(const a of r.analyses){const section=el('section','quality-analysis');section.setAttribute('aria-label',titles[a.key]);const h=el('h4');h.append(pill(a.answer),document.createTextNode(titles[a.key]));const e=paragraph('Evidence:',a.evidence);e.className='evidence';section.append(h,el('p','question',a.question),e);const details=el('details');details.append(el('summary',null,'View evidence · '+a.evidence_type));const images=el('div','quality-evidence-images');for(const name of a.assets)images.append(evidenceLink(r,name));details.append(images);if(a.assets.includes('centerline.png'))details.append(el('p','meta',r.centerline_caption));if(a.assets.includes('centerline-junction.png'))details.append(el('p','meta','Corner detail: teal dashed ray = incoming curve tangent continued forward; orange dashed ray = outgoing straight tangent. Their angle is a construction measurement, not an automatic defect verdict.'));if(a.assets.includes('mirror.png'))details.append(el('p','meta','Blue = selected drawing; red = reflection. '+r.symmetry_intent+' Compare only the stated parts; other differences can be intentional.'));if(a.assets.includes('reference.png'))details.append(el('p','meta','The reference is supporting context, not the approved artwork being judged.'));section.append(details);target.append(section);}
    const guidance=el('section','quality-guidance');guidance.append(el('h3',null,r.final==='NO'?'Recommended repair':'Recommendation'),el('p',null,r.repair));if(r.final==='NO')guidance.append(el('p','meta','Suggested repair only. Compare a new candidate at native size in both themes and revalidate before accepting it.'));target.append(guidance);
    const provenance=el('details','quality-provenance');provenance.append(el('summary',null,'Artwork version & validation evidence'));provenance.append(paragraph('Selected artwork:',r.artwork_source==='use_upload'?'Uploaded SVG':r.artwork_source==='use_edited'?'Gallery-edited SVG':'Generated icon'),paragraph('Automated model QA:',r.model_qa.toUpperCase()+(r.qa_matches_selected?' — exact match to the selected artwork.':' — DIFFERENT artwork. This baseline model result does not validate the selected artwork.')),paragraph('Source reference:',r.reference.status),el('p',null,r.profile_guidance));if(r.selected_qa)provenance.append(paragraph('Exact selected-artwork QA:',r.selected_qa.toUpperCase()+' — fresh validation of the edited graph, with matching SVG fingerprint.'));const hash=el('p');hash.append(el('strong',null,'Selected artwork fingerprint: '),el('code',null,r.svg_sha256));provenance.append(hash);for(const [name,label] of [['selected.svg','Inspected SVG'],['centerline.svg','Centerline diagram'],['centerline-measurements.json','Junction measurements'],['envelope-measurements.json','Selected envelope measurements'],['model-qa.json','Full model QA evidence'],['selected-qa.json','Exact selected-artwork QA evidence']].filter(([name])=>r.assets[name])){const link=el('a',null,label+' ↗');link.href=asset(r,name);link.target='_blank';link.rel='noopener';provenance.append(link);}target.append(provenance);
  }
  function render(alignSelection=false){
    if(!data)return;const rows=filterQualityIcons(data.icons,$('qualitySearch').value,$('qualityVerdict').value,$('qualityIssue').value,$('qualityBatch').value);
    const batchIcons=data.icons.filter(r=>!$('qualityBatch').value||String(r.batch)===$('qualityBatch').value);for(const verdict of ['YES','NO']){const n=document.getElementById('qualityTotal'+verdict);if(n)n.textContent=batchIcons.filter(r=>r.final===verdict).length+' '+verdict;} $('qualityStatus').textContent=rows.length+' of '+batchIcons.length+' icons'+($('qualityBatch').value?' in batch '+$('qualityBatch').value:' across all batches');const list=$('qualityList');list.replaceChildren();
    if(alignSelection){const index=rows.findIndex(r=>r.icon_id===selected);if(index>=0)page=Math.floor(index/25)+1;}
    const paged=paginateQualityIcons(rows,page);page=paged.page;
    $('qualityPager').hidden=!rows.length;$('qualityPrevious').disabled=page===1;$('qualityNext').disabled=page===paged.pages;
    $('qualityPage').textContent='Page '+page+' of '+paged.pages;
    if(rows.length)$('qualityStatus').textContent+=' · Showing '+(paged.start+1)+'–'+(paged.start+paged.rows.length);
    if(!rows.length){$('qualityDetail').replaceChildren(el('p','quality-empty','No icons match these filters. Change the search or filters to see the review.'));return;}
    if(!paged.rows.some(r=>r.icon_id===selected))selected=paged.rows[0].icon_id;
    const url=new URL(location.href);url.searchParams.set('page',page);if($('qualityBatch').value)url.searchParams.set('batch',$('qualityBatch').value);else url.searchParams.delete('batch');url.hash=selected;history.replaceState(null,'',url);
    for(const r of paged.rows){const a=el('a','quality-icon');a.href='#'+r.icon_id;a.setAttribute('aria-current',String(r.icon_id===selected));const name=el('span','name',r.icon_id.replaceAll('-',' '));name.append(el('small',null,String(r.number).padStart(2,'0')+' · '+r.profile));a.append(picture(r,'light-native.png'),name,pill(r.final));a.onclick=event=>{event.preventDefault();selected=r.icon_id;history.replaceState(null,'','#'+selected);render();};list.append(a);}showDetail(rows.find(r=>r.icon_id===selected));
  }
  async function load(){
    $('qualityRetry').hidden=true;$('qualityStatus').textContent='Loading review evidence…';$('qualityDetail').setAttribute('aria-busy','true');
    try{const response=await fetch(base+'review.json',{cache:'no-store'});if(!response.ok)throw Error('load');data=await response.json();if(!Array.isArray(data.icons)||!data.icons.length)throw Error('empty');
      $('qualityMethod').textContent=data.methodology;$('qualityQA').textContent=data.qa_note;const totals=$('qualityTotals');totals.replaceChildren();for(const value of ['YES','NO']){const b=el('button');b.type='button';const total=el('strong',null,data.summary[value.toLowerCase()]+' '+value);total.id='qualityTotal'+value;b.append(total,el('span',null,value==='YES'?'Ready at native size':'Needs improvement'));b.onclick=()=>{$('qualityVerdict').value=value;$('qualityIssue').value='';page=1;render();};totals.append(b);}
      $('qualityScope').textContent=data.icons.length+' icons · '+(data.batches||[]).length+' batches';const batch=$('qualityBatch');batch.replaceChildren(el('option',null,'All batches'));batch.firstChild.value='';for(const b of data.batches||[]){const option=el('option',null,'Batch '+b.id+' · '+b.count+' icons');option.value=String(b.id);batch.append(option);}const requested=new URLSearchParams(location.search).get('batch');if((data.batches||[]).some(b=>String(b.id)===requested))batch.value=requested;
      for(const id of ['qualitySearch','qualityVerdict','qualityIssue','qualityBatch'])$(id).disabled=false;
      let id='';try{id=decodeURIComponent(location.hash.slice(1));}catch{}selected=data.icons.some(r=>r.icon_id===id)?id:data.icons.find(r=>r.final==='NO')?.icon_id||data.icons[0].icon_id;page=Number(new URLSearchParams(location.search).get('page'))||1;render(Boolean(id));
    }catch{$('qualityStatus').textContent='The review could not be loaded. Try again.';$('qualityRetry').hidden=false;$('qualityDetail').replaceChildren(el('p','quality-empty','Review evidence is unavailable.'));}finally{$('qualityDetail').setAttribute('aria-busy','false');}
  }
  $('qualityBatch').onchange=()=>{const url=new URL(location.href);if($('qualityBatch').value)url.searchParams.set('batch',$('qualityBatch').value);else url.searchParams.delete('batch');url.hash='';history.replaceState(null,'',url);page=1;render();};const resetPage=()=>{page=1;render();};$('qualitySearch').oninput=resetPage;$('qualityVerdict').onchange=resetPage;$('qualityIssue').onchange=resetPage;$('qualityPrevious').onclick=()=>{page--;render();$('qualityList').scrollTop=0;};$('qualityNext').onclick=()=>{page++;render();$('qualityList').scrollTop=0;};$('qualityRetry').onclick=load;
  window.addEventListener('hashchange',()=>{if(!data)return;let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}if(data.icons.some(r=>r.icon_id===id)){selected=id;const requested=data.icons.find(r=>r.icon_id===id);if($('qualityBatch').value&&String(requested.batch)!==$('qualityBatch').value)$('qualityBatch').value='';$('qualitySearch').value='';$('qualityVerdict').value='';$('qualityIssue').value='';render(true);}});load();
})();
