"""Eight rounded gear lobes generated by quarter rotation; smooth S with exposed dollar stems.
Omissions: None
Construction references: ['settings'].
"""
from ...keyshapes import Keyshape
from ._base import Solo48
SOURCE_ICON_ID='fa84ff77-a565-4df3-9360-0b7e9c3de772'
SOURCE_PATH='icon_set/work/primitive-fix-thuan/solo__cog-dollar/20260924T171046Z-thuan-mac/reference/cog dollar_fa84ff77-a565-4df3-9360-0b7e9c3de772.svg'
AUTHOR='gpt-6'

class Drawing(Solo48):
    icon_id='cog-dollar'
    keyshape=Keyshape.SQUARE
    semantic_role="MAIN"
    semantic_kind="noun"
    category = "primitives-generate"
    aliases=()
    keywords=('cog', 'dollar')

    def path(self, name, start, commands, closed=False):
        ids=[]; here=start
        for i,c in enumerate(commands):
            eid=f'{name}-{i}'; ids.append(eid)
            if c[0]=='L': self.add_line(eid,here,c[1])
            elif c[0]=='A': self.add_arc(eid,here,c[1],radius_x=c[2],radius_y=c[3],sweep=c[4],large_arc=c[5] if len(c)>5 else False)
            elif c[0]=='C': self.add_bezier(eid,here,(c[2],c[3],c[1]))
            here=c[1]
        self.add_contour(name,*ids,closed=closed)
    def circle(self,n,x,y,r):
        self.path(n,(x-r,y),[('A',(x+r,y),r,r,True),('A',(x-r,y),r,r,True)],True)
    def box(self,n,x,y,w,h,r):
        self.path(n,(x+r,y),[('L',(x+w-r,y)),('A',(x+w,y+r),r,r,True),('L',(x+w,y+h-r)),('A',(x+w-r,y+h),r,r,True),('L',(x+r,y+h)),('A',(x,y+h-r),r,r,True),('L',(x,y+r)),('A',(x+r,y),r,r,True)],True)

    def build(self):
        # One quadrant owns all repeated teeth and smooth transitions.
        quarter=[('C',(27,6),(23,6),(25,6)),('C',(30,9),(29,6),(28,9)),('C',(35,10),(32,9),(33,9)),('C',(38,13),(36,10),(38,12)),('C',(39,18),(39,15),(39,16)),('C',(42,21),(39,20),(42,19))]
        def rot(p,k):
            x,y=p[0]-24,p[1]-24
            for _ in range(k):x,y=-y,x
            return x+24,y+24
        commands=[]
        for k in range(4):
            for c in quarter:commands.append(('C',rot(c[1],k),rot(c[2],k),rot(c[3],k)))
        self.path('gear',(21,6),commands,True)
        self.path('dollar',(28,18),[('C',(24,17),(27,17),(25,17)),('C',(24,24),(17,17),(17,23)),('C',(24,31),(31,25),(31,31)),('C',(20,30),(22,31),(21,31))])
        self.add_line('stem-top',(24,15),(24,17));self.add_line('stem-bottom',(24,31),(24,33))
        self.relate('connect','dollar','stem-top');self.relate('connect','dollar','stem-bottom')
