"""Computer chip (electronics), converted from the icons-json construction graph by json_to_solo --mode fit. SQUARE keyshape; curves fitted to integer lines and arcs."""
from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = '91a0337e-3cfe-56f5-8b9d-a91954dc8ffc'
SOURCE_PATH = 'icons-json/electronics/computer chip_91a0337e-3cfe-56f5-8b9d-a91954dc8ffc.json'
AUTHOR = 'json_to_solo'

class ComputerChip(Solo48):
    icon_id = 'computer-chip'
    keyshape = Keyshape.SQUARE
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'electronics'
    aliases = ()
    keywords = ('computer', 'chip', 'electronics')

    def build(self):
        self.add_line('sym-e0', (29, 42), (29, 36))
        self.add_line('sym-e1', (29, 36), (31, 36))
        self.add_arc('sym-e2', (31, 36), (36, 32), radius_x=4, sweep=False)
        self.add_line('sym-e3', (36, 32), (36, 29))
        self.add_line('sym-e4', (36, 29), (42, 29))
        self.add_line('sym-e5', (36, 24), (36, 29))
        self.add_line('sym-e6', (29, 36), (24, 36))
        self.add_line('sym-e7', (24, 36), (19, 36))
        self.add_line('sym-e8', (19, 36), (19, 42))
        self.add_line('sym-e9', (6, 29), (12, 29))
        self.add_line('sym-e10', (12, 29), (12, 24))
        self.add_line('sym-e11', (12, 24), (12, 19))
        self.add_line('sym-e12', (12, 19), (6, 19))
        self.add_line('sym-e13', (12, 29), (12, 32))
        self.add_arc('sym-e14', (12, 32), (17, 36), radius_x=4, sweep=False)
        self.add_line('sym-e15', (17, 36), (19, 36))
        self.add_line('sym-e16', (29, 6), (29, 12))
        self.add_line('sym-e17', (29, 12), (31, 12))
        self.add_arc('sym-e18', (31, 12), (36, 16), radius_x=4)
        self.add_line('sym-e19', (36, 16), (36, 19))
        self.add_line('sym-e20', (36, 19), (42, 19))
        self.add_line('sym-e21', (36, 24), (36, 19))
        self.add_line('sym-e22', (29, 12), (24, 12))
        self.add_line('sym-e23', (24, 12), (19, 12))
        self.add_line('sym-e24', (19, 12), (19, 6))
        self.add_line('sym-e25', (12, 19), (12, 16))
        self.add_arc('sym-e26', (12, 16), (17, 12), radius_x=4)
        self.add_line('sym-e27', (17, 12), (19, 12))
        self.add_contour('sym-c0', 'sym-e0', 'sym-e1', 'sym-e2', 'sym-e3', 'sym-e4')
        self.add_contour('sym-c1', 'sym-e5')
        self.add_contour('sym-c2', 'sym-e6', 'sym-e7', 'sym-e8')
        self.add_contour('sym-c3', 'sym-e9', 'sym-e10', 'sym-e11', 'sym-e12')
        self.add_contour('sym-c4', 'sym-e13', 'sym-e14', 'sym-e15')
        self.add_contour('sym-c5', 'sym-e16', 'sym-e17', 'sym-e18', 'sym-e19', 'sym-e20')
        self.add_contour('sym-c6', 'sym-e21')
        self.add_contour('sym-c7', 'sym-e22', 'sym-e23', 'sym-e24')
        self.add_contour('sym-c8', 'sym-e25', 'sym-e26', 'sym-e27')
        self.relate('connect', 'sym-c0', 'sym-c2')
        self.relate('connect', 'sym-c0', 'sym-c1')
        self.relate('connect', 'sym-c1', 'sym-c6')
        self.relate('connect', 'sym-c2', 'sym-c4')
        self.relate('connect', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c3', 'sym-c8')
        self.relate('connect', 'sym-c5', 'sym-c7')
        self.relate('connect', 'sym-c5', 'sym-c6')
        self.relate('connect', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
        self.relate('connect', 'sym-c2', 'sym-c3', 'sym-c4')
        self.relate('connect', 'sym-c5', 'sym-c6', 'sym-c7')
        self.relate('connect', 'sym-c0', 'sym-c1', 'sym-c2')
        self.relate('connect', 'sym-c3', 'sym-c7', 'sym-c8')
