"""Element reallity kit 1 (technology), converted from the icons-json construction graph by json_to_solo --mode fit. SQUARE keyshape; curves fitted to integer lines and arcs."""
from ...keyshapes import Keyshape
from ._base import Solo48
SOURCE_ICON_ID = '00665be9-93c9-402b-9534-0f4ceba9c3b0'
SOURCE_PATH = 'pictographic-primitives/technology/element reallity kit 1_00665be9-93c9-402b-9534-0f4ceba9c3b0.svg'
AUTHOR = 'gpt-6'

class ElementReallityKit1(Solo48):
    icon_id = 'element-reallity-kit-1'
    keyshape = Keyshape.SQUARE
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'technology'
    aliases = ()
    keywords = ('element', 'reallity', 'kit', 'technology')

    def build(self):
        self.add_line('e0', (15, 42), (15, 32))
        self.add_line('e1', (15, 42), (6, 37))
        self.add_line('e3', (15, 42), (24, 37))
        self.add_line('e4', (42, 27), (42, 37))
        self.add_line('e5', (42, 37), (33, 42))
        self.add_line('e6', (42, 27), (33, 32))
        self.add_line('e7', (42, 27), (33, 22))
        self.add_line('e8', (24, 27), (15, 32))
        self.add_line('e9', (24, 27), (15, 22))
        self.add_line('e10', (33, 11), (33, 22))
        self.add_line('e11', (33, 11), (24, 16))
        self.add_line('e12', (33, 11), (24, 6))
        self.add_line('e13', (24, 6), (15, 11))
        self.add_line('e14', (15, 11), (24, 16))
        self.add_line('e15', (15, 11), (15, 22))
        self.add_line('e16', (6, 27), (15, 32))
        self.add_line('e17', (6, 27), (15, 22))
        self.add_line('e18', (33, 32), (24, 27))
        self.add_line('e19', (24, 27), (24, 37))
        self.add_line('e20', (33, 32), (33, 42))
        self.add_line('e21', (33, 42), (24, 37))
        self.add_line('e22', (33, 22), (24, 27))
        self.add_line('e23', (24, 27), (24, 16))
        self.add_line('e24', (6, 37), (6, 27))
        self.add_contour('c0', 'e0', closed=False)
        self.add_contour('c1', 'e1', 'e24', closed=False)
        self.add_contour('c2', 'e3', closed=False)
        self.add_contour('c3', 'e4', 'e5', closed=False)
        self.add_contour('c4', 'e6', closed=False)
        self.add_contour('c5', 'e7', closed=False)
        self.add_contour('c6', 'e8', closed=False)
        self.add_contour('c7', 'e9', closed=False)
        self.add_contour('c8', 'e10', closed=False)
        self.add_contour('c9', 'e11', closed=False)
        self.add_contour('c10', 'e12', 'e13', closed=False)
        self.add_contour('c11', 'e14', closed=False)
        self.add_contour('c12', 'e15', closed=False)
        self.add_contour('c13', 'e16', closed=False)
        self.add_contour('c14', 'e17', closed=False)
        self.add_contour('c15', 'e18', 'e19', closed=False)
        self.add_contour('c16', 'e20', closed=False)
        self.add_contour('c17', 'e21', closed=False)
        self.add_contour('c18', 'e22', closed=False)
        self.add_contour('c19', 'e23', closed=False)
        self.relate('connect', 'c0', 'c1')
        self.relate('connect', 'c0', 'c2')
        self.relate('connect', 'c1', 'c2')
        self.relate('connect', 'c0', 'c13')
        self.relate('connect', 'c0', 'c6')
        self.relate('connect', 'c13', 'c6')
        self.relate('connect', 'c1', 'c13')
        self.relate('connect', 'c1', 'c14')
        self.relate('connect', 'c13', 'c14')
        self.relate('connect', 'c15', 'c17')
        self.relate('connect', 'c15', 'c2')
        self.relate('connect', 'c17', 'c2')
        self.relate('connect', 'c3', 'c4')
        self.relate('connect', 'c3', 'c5')
        self.relate('connect', 'c4', 'c5')
        self.relate('connect', 'c16', 'c17')
        self.relate('connect', 'c16', 'c3')
        self.relate('connect', 'c17', 'c3')
        self.relate('connect', 'c15', 'c16')
        self.relate('connect', 'c15', 'c4')
        self.relate('connect', 'c16', 'c4')
        self.relate('connect', 'c18', 'c5')
        self.relate('connect', 'c18', 'c8')
        self.relate('connect', 'c5', 'c8')
        self.relate('connect', 'c18', 'c19')
        self.relate('connect', 'c18', 'c6')
        self.relate('connect', 'c18', 'c7')
        self.relate('connect', 'c19', 'c6')
        self.relate('connect', 'c19', 'c7')
        self.relate('connect', 'c6', 'c7')
        self.relate('connect', 'c12', 'c14')
        self.relate('connect', 'c12', 'c7')
        self.relate('connect', 'c14', 'c7')
        self.relate('connect', 'c10', 'c8')
        self.relate('connect', 'c10', 'c9')
        self.relate('connect', 'c8', 'c9')
        self.relate('connect', 'c11', 'c19')
        self.relate('connect', 'c11', 'c9')
        self.relate('connect', 'c19', 'c9')
        self.relate('connect', 'c10', 'c11')
        self.relate('connect', 'c10', 'c12')
        self.relate('connect', 'c11', 'c12')
