"""A daisy-like flower with eight rounded petals spreading around a ring at its centre.

Plan: Eight rounded lobes generated by quarter-turns of one two-lobe curve; center ring.
Keyshape: SQUARE; exact SOLO48 envelope from the contract.
Construction reference: flower-2: repeated rounded petals and central circle.
Simplification: Petal separations merge into an eight-lobed outline.
"""
from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = 'f289aab6-b93c-4599-9b13-2dec09ddb559'
SOURCE_PATH = 'pictographic-primitives/logos/icq logo_f289aab6-b93c-4599-9b13-2dec09ddb559.svg'
AUTHOR = 'gpt-6'


class IcqLogo(Solo48):
    icon_id = 'icq-logo'
    keyshape = Keyshape.SQUARE
    semantic_role = "MAIN"
    semantic_kind = "noun"
    category = "logos"
    categories = ("logos", "primitives")
    aliases = ()
    keywords = ('icq', 'messenger', 'flower', 'chat', 'logo', 'brand', 'instant-messaging')

    def build(self):
        def rot(p,n):
         x,y=p[0]-24,p[1]-24
         for _ in range(n): x,y=-y,x
         return (x+24,y+24)
        # Each quadrant uses a smooth axial lobe and diagonal lobe.
        for i in range(4):
         self.add_bezier(f'q{i}',rot((24,6),i),
          tuple(rot(p,i) for p in ((30,6),(30,10),(30,14))),
          tuple(rot(p,i) for p in ((36,6),(42,12),(34,18))),
          tuple(rot(p,i) for p in ((38,18),(42,18),(42,24))))
        self.add_contour('petals',*[f'q{i}' for i in range(4)],closed=True)
        self.add_arc('c1',(26,24),(22,24),radius_x=2)
        self.add_arc('c2',(22,24),(26,24),radius_x=2)
        self.add_contour('center','c1','c2',closed=True)
