"""Two opposite diagonal hooks generated by a 180-degree rotation. Lucide link informs coherent open curves; omit the outer circle to preserve the distinctive hooks at legal spacing."""
from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = 'e0e3abfb-c9c6-434b-a9d6-ce948b336ced'
SOURCE_PATH = 'pictographic-primitives/logos/shazam logo_e0e3abfb-c9c6-434b-a9d6-ce948b336ced.svg'
AUTHOR = 'gpt-6'

class ShazamLogo(Solo48):
    icon_id = 'shazam-logo'
    keyshape = Keyshape.SQUARE
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'logos'
    aliases = ()
    keywords = ('shazam', 'music', 'recognition', 'letter-s', 'logo', 'brand', 'audio')

    def build(self):
        # Plan: Two opposite diagonal hooks generated by a 180-degree rotation. Lucide link informs coherent open curves; omit the outer circle to preserve the distinctive hooks at legal spacing.
        # Exact keyshape ink extremes are owned by Keyshape.SQUARE on SOLO48.

        for j in range(2):
            def p(x,y):return (x,y) if j==0 else (48-x,48-y)
            self.add_line('diagonal-'+str(j),p(24,6),p(10,20))
            self.add_bezier('hook-'+str(j),p(10,20),(p(8,22),p(6,26),p(6,30)),(p(6,38),p(14,40),p(20,34)))
            self.add_line('return-'+str(j),p(20,34),p(24,30))
            self.add_contour('hook-stroke-'+str(j),'diagonal-'+str(j),'hook-'+str(j),'return-'+str(j))

