from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = '2907e972-c65a-5ccd-863c-542e656a809e'
SOURCE_PATH = 'pictographic-primitives/animals/spider web_2907e972-c65a-5ccd-863c-542e656a809e.svg'
AUTHOR = 'gpt-6'


class SpiderWeb(Solo48):
    icon_id = 'spider-web'
    keyshape = Keyshape.SQUARE
    semantic_role = "MAIN"
    semantic_kind = "noun"
    category = "nature/animals"
    aliases = ()
    keywords = ('spider', 'web', 'cobweb', 'hexagon', 'net', 'halloween', 'geometric', 'trap')

    def build(self) -> None:
        # Two hexagons linked by six spokes; extremes (2,2)-(46,46).
        self.add_line('outer-0', (24, 2), (46, 13))
        self.add_line('inner-0', (24, 14), (34, 19))
        self.add_line('spoke-outer-0', (24, 2), (24, 14))
        self.add_line('spoke-inner-0', (24, 14), (24, 24))
        self.add_line('outer-1', (46, 13), (46, 35))
        self.add_line('inner-1', (34, 19), (34, 29))
        self.add_line('spoke-outer-1', (46, 13), (34, 19))
        self.add_line('spoke-inner-1', (34, 19), (24, 24))
        self.add_line('outer-2', (46, 35), (24, 46))
        self.add_line('inner-2', (34, 29), (24, 34))
        self.add_line('spoke-outer-2', (46, 35), (34, 29))
        self.add_line('spoke-inner-2', (34, 29), (24, 24))
        self.add_line('outer-3', (24, 46), (2, 35))
        self.add_line('inner-3', (24, 34), (14, 29))
        self.add_line('spoke-outer-3', (24, 46), (24, 34))
        self.add_line('spoke-inner-3', (24, 34), (24, 24))
        self.add_line('outer-4', (2, 35), (2, 13))
        self.add_line('inner-4', (14, 29), (14, 19))
        self.add_line('spoke-outer-4', (2, 35), (14, 29))
        self.add_line('spoke-inner-4', (14, 29), (24, 24))
        self.add_line('outer-5', (2, 13), (24, 2))
        self.add_line('inner-5', (14, 19), (24, 14))
        self.add_line('spoke-outer-5', (2, 13), (14, 19))
        self.add_line('spoke-inner-5', (14, 19), (24, 24))
        self.relate("connect", 'outer-0', 'spoke-outer-0')
        self.relate("connect", 'outer-0', 'outer-1')
        self.relate("connect", 'outer-0', 'spoke-outer-1')
        self.relate("connect", 'outer-0', 'outer-5')
        self.relate("connect", 'inner-0', 'spoke-outer-0')
        self.relate("connect", 'inner-0', 'spoke-inner-0')
        self.relate("connect", 'inner-0', 'inner-1')
        self.relate("connect", 'inner-0', 'spoke-outer-1')
        self.relate("connect", 'inner-0', 'spoke-inner-1')
        self.relate("connect", 'inner-0', 'inner-5')
        self.relate("connect", 'spoke-outer-0', 'spoke-inner-0')
        self.relate("connect", 'spoke-outer-0', 'outer-5')
        self.relate("connect", 'spoke-outer-0', 'inner-5')
        self.relate("connect", 'spoke-inner-0', 'spoke-inner-1')
        self.relate("connect", 'spoke-inner-0', 'spoke-inner-2')
        self.relate("connect", 'spoke-inner-0', 'spoke-inner-3')
        self.relate("connect", 'spoke-inner-0', 'spoke-inner-4')
        self.relate("connect", 'spoke-inner-0', 'inner-5')
        self.relate("connect", 'spoke-inner-0', 'spoke-inner-5')
        self.relate("connect", 'outer-1', 'spoke-outer-1')
        self.relate("connect", 'outer-1', 'outer-2')
        self.relate("connect", 'outer-1', 'spoke-outer-2')
        self.relate("connect", 'inner-1', 'spoke-outer-1')
        self.relate("connect", 'inner-1', 'spoke-inner-1')
        self.relate("connect", 'inner-1', 'inner-2')
        self.relate("connect", 'inner-1', 'spoke-outer-2')
        self.relate("connect", 'inner-1', 'spoke-inner-2')
        self.relate("connect", 'spoke-outer-1', 'spoke-inner-1')
        self.relate("connect", 'spoke-inner-1', 'spoke-inner-2')
        self.relate("connect", 'spoke-inner-1', 'spoke-inner-3')
        self.relate("connect", 'spoke-inner-1', 'spoke-inner-4')
        self.relate("connect", 'spoke-inner-1', 'spoke-inner-5')
        self.relate("connect", 'outer-2', 'spoke-outer-2')
        self.relate("connect", 'outer-2', 'outer-3')
        self.relate("connect", 'outer-2', 'spoke-outer-3')
        self.relate("connect", 'inner-2', 'spoke-outer-2')
        self.relate("connect", 'inner-2', 'spoke-inner-2')
        self.relate("connect", 'inner-2', 'inner-3')
        self.relate("connect", 'inner-2', 'spoke-outer-3')
        self.relate("connect", 'inner-2', 'spoke-inner-3')
        self.relate("connect", 'spoke-outer-2', 'spoke-inner-2')
        self.relate("connect", 'spoke-inner-2', 'spoke-inner-3')
        self.relate("connect", 'spoke-inner-2', 'spoke-inner-4')
        self.relate("connect", 'spoke-inner-2', 'spoke-inner-5')
        self.relate("connect", 'outer-3', 'spoke-outer-3')
        self.relate("connect", 'outer-3', 'outer-4')
        self.relate("connect", 'outer-3', 'spoke-outer-4')
        self.relate("connect", 'inner-3', 'spoke-outer-3')
        self.relate("connect", 'inner-3', 'spoke-inner-3')
        self.relate("connect", 'inner-3', 'inner-4')
        self.relate("connect", 'inner-3', 'spoke-outer-4')
        self.relate("connect", 'inner-3', 'spoke-inner-4')
        self.relate("connect", 'spoke-outer-3', 'spoke-inner-3')
        self.relate("connect", 'spoke-inner-3', 'spoke-inner-4')
        self.relate("connect", 'spoke-inner-3', 'spoke-inner-5')
        self.relate("connect", 'outer-4', 'spoke-outer-4')
        self.relate("connect", 'outer-4', 'outer-5')
        self.relate("connect", 'outer-4', 'spoke-outer-5')
        self.relate("connect", 'inner-4', 'spoke-outer-4')
        self.relate("connect", 'inner-4', 'spoke-inner-4')
        self.relate("connect", 'inner-4', 'inner-5')
        self.relate("connect", 'inner-4', 'spoke-outer-5')
        self.relate("connect", 'inner-4', 'spoke-inner-5')
        self.relate("connect", 'spoke-outer-4', 'spoke-inner-4')
        self.relate("connect", 'spoke-inner-4', 'spoke-inner-5')
        self.relate("connect", 'outer-5', 'spoke-outer-5')
        self.relate("connect", 'inner-5', 'spoke-outer-5')
        self.relate("connect", 'inner-5', 'spoke-inner-5')
        self.relate("connect", 'spoke-outer-5', 'spoke-inner-5')
