"""Square Hub with Four Nodes.

Plan: Square hub with four cardinal branches and identical circular nodes, generated by quarter-turn rotation. Extremes (6,6)-(42,42).
Reduction: All four nodes remain; their circles are reduced consistently to the approved small-circle size.
Construction reference: Lucide network.
"""
from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = 'a3a3608c-3394-4285-855d-72e887204309'
SOURCE_PATH = 'pictographic-primitives/business/supply chain distributor box package_a3a3608c-3394-4285-855d-72e887204309.svg'
AUTHOR = 'gpt-6'
SOURCE_REFERENCES = (('a3a3608c-3394-4285-855d-72e887204309', 'pictographic-primitives/business/supply chain distributor box package_a3a3608c-3394-4285-855d-72e887204309.svg'),)

def _circle(icon, name, cx, cy, radius):
    left, right = (cx-radius, cy), (cx+radius, cy)
    icon.add_arc(name+'-upper', left, right, radius_x=radius)
    icon.add_arc(name+'-lower', right, left, radius_x=radius)
    icon.add_contour(name, name+'-upper', name+'-lower', closed=True)


def _box(icon, name, left, top, right, bottom, radius, attachments=()):
    # One rounded rectangle owns all corners and cardinal attachment nodes.
    cx, cy = (left+right)//2, (top+bottom)//2
    points = [(cx,top),(right-radius,top),(right,top+radius),
              (right,cy),(right,bottom-radius),(right-radius,bottom),
              (cx,bottom),(left+radius,bottom),(left,bottom-radius),
              (left,cy),(left,top+radius),(left+radius,top),(cx,top)]
    members = []
    for index, (start,end) in enumerate(zip(points,points[1:])):
        if start == end:
            continue
        member = f'{name}-{index}'
        if index in (1,4,7,10):
            icon.add_arc(member, start, end, radius_x=radius)
        else:
            dx,dy=end[0]-start[0],end[1]-start[1]
            inside=[p for p in attachments if (p[0]-start[0])*dy == (p[1]-start[1])*dx
                    and 0 < (p[0]-start[0])*dx+(p[1]-start[1])*dy < dx*dx+dy*dy]
            inside.sort(key=lambda p:(p[0]-start[0])*dx+(p[1]-start[1])*dy)
            nodes=[start]+inside+[end]
            for j,(a,b) in enumerate(zip(nodes,nodes[1:])):
                part=member+f'-split-{j}'
                icon.add_line(part,a,b)
                members.append(part)
            continue
        members.append(member)
    icon.add_contour(name, *members, closed=True)


class SquareHubWithFourNodes(Solo48):
    icon_id = 'square-hub-with-four-nodes'
    keyshape = Keyshape.SQUARE
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'business'
    aliases = ()
    keywords = ('square', 'hub', 'with', 'four', 'nodes')

    def build(self):
        self.add_polyline('hub',(18,18),(24,18),(30,18),(30,24),(30,30),(24,30),(18,30),(18,24),closed=True)
        for n in range(4):
            def p(x,y):
                x,y=x-24,y-24
                for _ in range(n):x,y=-y,x
                return (24+x,24+y)
            pts=[p(22,8),p(24,6),p(26,8),p(24,10)]
            for i,a in enumerate(pts):self.add_arc(f'node-{n}-{i}',a,pts[(i+1)%4],radius_x=2)
            self.add_contour(f'node-{n}',*[f'node-{n}-{i}' for i in range(4)],closed=True)
            self.add_line(f'branch-{n}',p(24,10),p(24,18))
            self.relate('connect',f'branch-{n}',f'node-{n}')
            self.relate('connect',f'branch-{n}','hub')
