"""Wrapped Hard Candy.

Diagonal hard candy with rounded twisted wrapper folds at opposite ends. Centerline extremes (6,6)-(42,42). The two ends are generated by 180-degree symmetry and share body seam nodes. Lucide candy informs the fold shapes; omit stripes.
"""
from ...keyshapes import Keyshape
from ._base import Solo48

SOURCE_ICON_ID = 'c3f70ce7-b515-5c42-966d-2d205fa56964'
SOURCE_PATH = '/Applications/Workspaces/pictographic/icon_simplification/pictographic-primitives/food/candy_c3f70ce7-b515-5c42-966d-2d205fa56964.svg'
AUTHOR = 'gpt-6'

class WrappedHardCandyTwistedEnds(Solo48):
    icon_id = 'wrapped-hard-candy-twisted-ends'
    keyshape = Keyshape.SQUARE
    semantic_role = 'MAIN'
    semantic_kind = 'noun'
    category = 'food'
    categories = ('primitives', 'food')
    aliases = ()
    keywords = ('wrapped', 'hard', 'candy')

    def build(self):
        # Symbol plan: Diagonal hard candy with rounded twisted wrapper folds at opposite ends. Centerline extremes (6,6)-(42,42). The two ends are generated by 180-degree symmetry and share body seam nodes. Lucide candy informs the fold shapes; omit stripes.

        def path(name, start, commands, closed=False):
            members=[]
            for i, command in enumerate(commands):
                kind,end,*args=command
                member=f'{name}-{i}'
                if kind=='L': self.add_line(member,start,end)
                elif kind=='A': self.add_arc(member,start,end,radius_x=args[0],radius_y=args[1],sweep=args[2])
                elif kind=='C': self.add_bezier(member,start,(args[0],args[1],end))
                members.append(member)
                start=end
            self.add_contour(name,*members,closed=closed)
        def oval(name,x,y,rx,ry):
            path(name,(x-rx,y),[('A',(x+rx,y),rx,ry,True),('A',(x-rx,y),rx,ry,True)],True)
        def box(name,l,t,r,b,rad=4):
            path(name,(l+rad,t),[('L',(r-rad,t)),('A',(r,t+rad),rad,rad,True),('L',(r,b-rad)),('A',(r-rad,b),rad,rad,True),('L',(l+rad,b)),('A',(l,b-rad),rad,rad,True),('L',(l,t+rad)),('A',(l+rad,t),rad,rad,True)],True)
        def bilateral(name, start, right, closed=True):
            # One half owns geometry; mirror and reverse it about the shared axis.
            axis=24
            mirror=lambda p:(2*axis-p[0],p[1])
            segments=[]
            here=start
            for kind,end,*args in right:
                segments.append((kind,here,end,args));here=end
            left=[]
            for kind,begin,end,args in reversed(segments):
                if kind=='C': left.append((kind,mirror(begin),mirror(args[1]),mirror(args[0])))
                elif kind=='A': left.append((kind,mirror(begin),*args))
                else:left.append((kind,mirror(begin)))
            if closed:path(name,start,right+left,True)
            else:path(name,mirror(here),left+right)
        line=self.add_line
        dot=self.add_dot
        join=lambda a,b:self.relate('connect',a,b)

        upper=[('C',(30,6),(26,8),(28,6)),('C',(34,8),(32,6),(32,8)),('C',(38,6),(36,8),(36,6)),('C',(42,10),(40,6),(42,8)),('C',(40,14),(42,12),(40,12)),('C',(42,18),(40,16),(42,16)),('C',(34,22),(42,22),(38,22))]
        def turn(p):return (48-p[0],48-p[1])
        lower=[(kind,turn(end),turn(c1),turn(c2)) for kind,end,c1,c2 in upper]
        path('candy',(26,14),upper+[('C',(22,34),(38,30),(30,38))]+lower+[('C',(26,14),(10,18),(18,10))],True)
        for n,a,b in [('upper',(26,14),(34,22)),('lower',(14,26),(22,34))]:
            line(f'seam-{n}',a,b);join(f'seam-{n}','candy')
