from pathlib import Path
import json,re
P=Path(__file__).parent
raw='''0|Three Tracks with Single Slider Knob|Three horizontal tracks run parallel across the image with a single circular knob on the middle track near its right end. The upper and lower tracks remain uninterrupted and bare.|slider,track,control,adjustment,settings,knob
1|Three Horizontal Sliders with Offset Knobs|Three parallel horizontal tracks each carry a round knob, with the upper knob slightly left of center. The middle knob sits farther right, while the bottom knob is near the left end.|slider,control,settings,adjustment,knob,track
2|Left-Facing Lower Leg and Foot|A bare lower leg descends into a left-facing foot with a broad rounded heel and a long flat sole. The ankle narrows above the heel, and the toes form a single rounded end.|leg,foot,ankle,heel,body,anatomy
3|Scalloped Ice Cream in Stemmed Bowl|A rounded mound of ice cream rises above a shallow bowl, with a scalloped lower edge overlapping its rim. The bowl narrows beneath the scoop and rests on a short stem and flat foot.|ice cream,sherbet,dessert,bowl,scoop,food
4|Playing Cards Protruding from Top Hat|Two tilted playing cards protrude from the open crown of a top hat with a straight brim and rounded lower corners. A horizontal hatband crosses the front, and small suit-like marks appear on the cards.|hat,cards,magic,magician,playing cards,trick
5|Open Circular Face with One Closed Eye|An almost circular face outline has a wide gap at its lower right and a single small curved closed eye above center. No mouth or second eye is visible in the reference.|face,eye,expression,circle,smiley,wink
6|Clipped-Corner SIM Card with Contact Grid|An upright SIM card has one clipped upper corner and a rounded rectangular body. Its lower contact panel contains a broad central band with smaller divided sections along the top and bottom.|sim,card,phone,chip,contact,mobile
8|Diagonal Open-End Spanner|An open-end spanner extends diagonally from a rounded handle at lower left to a broad crescent-shaped jaw at upper right. The forked head has a deep angled opening between its two tips.|spanner,wrench,tool,jaw,handle,repair
9|Upright Open Hand with Joined Fingers|An upright open hand has four long rounded fingers held together above a broad palm. The thumb angles outward on the left, and the lower palm curves into a rounded wrist edge.|hand,palm,fingers,thumb,body,gesture
10|Open Scissors with Round Finger Loops|A pair of open scissors has two large round finger loops beneath long crossing blades. The blades flare slightly near their pointed tips, forming a tall open V above the crossing point.|scissors,shears,cutting,blades,handles,tool
11|Paired Plain Shoe Sole Prints|Two elongated shoe soles stand side by side with broad rounded toes and narrower rounded heels. A straight transverse line separates the heel section on each otherwise empty sole outline.|shoe,sole,footprint,heel,pair,footwear
12|Overlapping Socks with Heel Patches|Two long socks overlap diagonally, with their toes pointing toward the lower left and straight cuffs above. Horizontal cuff seams and curved heel patches distinguish the separate parts of each sock.|socks,clothing,footwear,heel,cuff,pair
13|Profile Taking a Sip from Tilted Cup|A person's head and upper torso face right, with a small tilted cup positioned just in front of the mouth. The nose, chin, neck and sloping shoulder form a continuous plain profile.|sip,drink,cup,person,profile,mouth
16|Left-Facing Person Sneezing|A person's head faces left with a closed curved eye and an open mouth. Three short lines spread outward from the mouth, while the back of the head flows into the neck and shoulder.|sneeze,person,head,profile,breath,face
18|Small Pig in Left Profile|A small pig faces left with a long rounded body, projecting snout and one triangular ear. Two short legs descend from its flat belly, and a small curled tail extends at the rear.|pig,piglet,animal,farm,tail,snout
19|Plain Bottle with Narrow Flat Cap|An upright bottle has rounded shoulders leading into a tall rectangular body with softly rounded lower corners. A narrower flat-topped cap rises from its neck, and the bottle's front is entirely blank.|bottle,shampoo,cap,container,toiletry,packaging
20|Faceted Diamond with Broad Crown|A wide faceted diamond has a flat crown and angled outer shoulders above a pointed lower tip. Straight interior lines divide the crown into triangular facets and converge through the long tapered lower section.|diamond,gem,facets,jewel,crystal,stone
21|Two-Pane Panel with Three Right Rows|A rounded rectangular panel is split vertically into two broad panes. Three short horizontal rows occupy the right pane, while the left pane is empty and spans the full height of the frame.|panel,sidebar,layout,rows,interface,window
22|Split Panel with Two Lower Right Rows|A rounded rectangular panel has a vertical divider near its center and an empty left pane. Two short horizontal rows sit in the lower portion of the right pane with blank space above.|panel,sidebar,layout,rows,interface,window
24|Right Arrow with Raised Curving Shaft|A right-pointing arrow begins with a low horizontal shaft that curves upward through an S-shaped bend. The upper horizontal section ends in an open arrowhead pointing to the right edge.|arrow,right,curve,direction,bend,flow
25|Sealed Snack Wrapper with Wavy Mark|A tall snack packet has crimped zigzag edges at both ends and horizontal seams beneath the seals. A single shallow wavy mark crosses the center of the otherwise plain wrapper.|snack,wrapper,packet,food,packaging,seal
27|Segmented Caterpillar with Raised Head|A caterpillar has a row of round overlapping body segments leading to a raised circular head on the right. Two curved antennae rise from the head, and a curved underside joins the body below.|caterpillar,silkworm,insect,antennae,segments,animal
28|Scalloped Fleece with Plain Face Opening|A rounded fleece silhouette has a scalloped perimeter surrounding a plain central face-like opening. The opening has a straight upper edge and rounded lower corners, with no visible eyes or mouth.|fleece,wool,sheep,shearling,scallop,face
29|Shoe Resting on Open Rack|A plain shoe rests on the middle shelf of a tall rectangular rack, with its toe pointing right. Horizontal shelves span between two upright sides, and the upper and lower compartments remain empty.|shoe,rack,shelf,storage,footwear,furniture
31|Short-Sleeved Dress with V Neck|A short-sleeved dress has a deep V-shaped neckline, angled sleeves and a narrow waist seam. The skirt widens evenly below the waist to a broad straight hem with softly rounded corners.|dress,clothing,skirt,sleeves,neckline,garment
32|Domed Shower Head with Falling Streams|A domed shower head hangs from a pipe that curves down from the upper right. Three broken vertical water streams fall beneath its flat lower edge in evenly spaced columns.|shower,water,bathroom,pipe,spray,head
33|Dome Cap with Broad Folded Band|A plain cap has a high rounded dome above a broad horizontal band across its base. The band has straight sides and softly rounded lower corners, with no decoration on either section.|cap,skullcap,hat,headwear,band,clothing
34|Gabled Shelter with Arched Door|A compact house has a broad peaked roof with projecting eaves and rounded lower wall corners. A tall arched doorway rises from the center of its base, with no windows visible.|house,shelter,roof,door,building,home
35|Pointed Leaf with Curved Central Vein|A single broad leaf angles from lower left toward a sharp upper-right tip. A curved central vein runs through its rounded body and continues beyond the base as a short stem.|leaf,plant,vein,stem,nature,foliage
36|Square Shed beneath Wide Triangular Roof|A small shed has straight walls beneath a broad triangular roof whose eaves extend beyond both sides. A narrow rectangular doorway opens from the center of the otherwise plain front wall.|shed,building,roof,door,house,storage
37|Left-Facing Fish with Forked Tail|A fish faces left with a pointed head, an oval body and a broad forked tail on the right. Small triangular fins project above and below, and a curved gill mark sits behind the head.|fish,fin,tail,gill,animal,aquatic
39|Upright Snake with Curled Lower Body|A snake rises into a broad rounded head at the upper left before curving through a narrow S-shaped neck. Its lower body loops rightward and curls inward toward a blunt tapered tail.|snake,reptile,coil,tail,animal,serpent
40|Two Circles Separated by Upright Line|Two equal outlined circles sit side by side with a short upright line between them. The three elements share a horizontal center, and the circles have no internal marks or connecting strokes.|circles,line,geometric,pair,symbol,separator
41|Two-Leaf Seedling on Soil Mound|A young seedling rises from a low uneven mound of soil with a flat base. Two broad pointed leaves spread symmetrically from the top of its short central stem.|seedling,soil,plant,leaves,sprout,garden
47|Sparkle-Eyed Face with Uneven Smile|A round face contains two small four-pointed sparkle eyes above a curved smile. The mouth rises more sharply at its right end, giving the otherwise evenly arranged face an asymmetric expression.|face,smile,sparkle,eyes,expression,happy
48|Large Sparkle-Eyed Smiling Face|A circular face has two large four-pointed sparkle eyes aligned across its upper half. A broad U-shaped smile sits below them, with both ends rising evenly toward the sides.|face,smile,sparkle,eyes,expression,joy
49|Football Boot Kicking Panelled Ball|A football boot angles upward toward a panelled ball at the upper left, with a short sock rising from its ankle. Stripes cross the boot's upper, and small studs project beneath the sole.|football,boot,ball,kick,soccer,sport
50|Drink Can with Bent Straw|A tall drink can has rounded lower corners and a narrowed upper rim above its plain body. A slender drinking straw emerges from the top and bends toward the upper right.|can,drink,straw,soda,beverage,container
52|Two Offset Horizontal Sill Blocks|Two long rectangular blocks sit directly above one another, with the upper block shifted slightly to the right. Their straight shared horizontal edge creates a shallow stepped outline at both ends.|sill,blocks,step,ledge,rectangle,building
53|Wide Wine Glass with Short Stem|A wine glass has a wide flat rim above a rounded bowl that narrows smoothly toward its base. A thin upright stem connects the bowl to a short horizontal foot.|glass,wine,sherry,stem,bowl,drinkware
55|Three Rows of Scalloped Water Waves|Three parallel rows of shallow scalloped waves stretch horizontally across the image. Each row repeats three rounded troughs with pointed crests between them, and the pattern remains separate from any shoreline.|waves,water,sea,ripple,pattern,ocean
56|Three Parallel Upward Arrows|Three long upright arrows stand side by side with their open arrowheads aligned near the top. Their straight shafts extend downward independently, with equal spacing and no surrounding frame or baseline.|arrows,up,direction,parallel,vertical,group
57|Tied Shoelace Bow with Crossed Ends|A tied shoelace forms two broad rounded loops above a central crossing. Two long ends descend outward, with another pair of crossing lace segments visible just below the bow.|shoelace,bow,knot,lace,shoe,tie
58|Draped Shawl with Rounded Collar|A shawl wraps around a rounded neck opening with a broad curved collar across the front. Two long side panels hang below the collar, separated by an open central space.|shawl,scarf,clothing,collar,wrap,garment
59|Bookcase with Paired Books on Two Shelves|A tall rectangular bookcase contains two shelf compartments, each holding a pair of upright books on the left. The books have plain rectangular spines, and the right sides of both shelves remain empty.|bookcase,shelf,books,furniture,storage,library
60|Pair of Equal-Height Shoulder Busts|Two plain human busts stand side by side with separate round heads at the same height. Their broad rounded shoulders overlap slightly in the center and end along a shared horizontal base.|people,pair,bust,shoulders,siblings,group
61|Two-Storey Building with Three Upper Windows|A straight-sided building has a broad rounded roof cap above three small rectangular upper windows. A horizontal floor line separates the upper level from a tall arched entrance centered below.|building,mall,windows,entrance,store,architecture
63|Low Motor Scooter in Right Profile|A motor scooter faces right with a long low body covering part of the rear wheel and a large exposed front wheel. A raised seat, slanted steering column, curved handlebar and small headlamp complete its profile.|scooter,motorcycle,wheels,vehicle,seat,transport
65|Radio Mast beneath Three Signal Arcs|A thin upright mast ends in a small circular tip beneath three nested signal arcs. The arcs spread broadly above the mast, while their open ends remain separate on both sides.|radio,mast,signal,wireless,antenna,broadcast
66|Triangle beneath Concentric Broadcast Arcs|A broad triangular mark with rounded corners sits beneath three concentric open arcs. The arcs curve around an empty center above the triangle, and their lower ends stop on either side.|broadcast,triangle,arcs,signal,wireless,airplay
68|Long-Haired Woman in Front View|A woman faces forward with a blank face framed by shoulder-length hair and a swept side part. Her neck descends into a V-shaped neckline between two broad curved shoulders.|woman,portrait,hair,face,person,bust
75|Round Sports Ball with Curved Seams|A round ball contains a slanting seam through its center and two broad curved side panels. The left panel curves inward from the upper edge, while the right panel curls upward from below.|ball,sport,seams,round,play,equipment
76|Broad Circular Ring with Empty Center|A broad circular ring is formed by two concentric outlines surrounding an empty center. Both edges are smooth and continuous, with no opening, attachment, lettering or decoration around the band.|ring,circle,band,round,shape,outline
77|Spreadsheet Grid with Blank Header|A tall spreadsheet panel has rounded outer corners and a blank header band across the top. Below the header, three columns and four rows form an even grid of rectangular cells.|spreadsheet,table,grid,cells,rows,columns
78|Three Rounded Layers above Short Baseline|Three broad capsule-shaped layers are stacked directly above one another, with their curved ends touching at the seams. A short horizontal baseline sits separately beneath the stack, and no labels are visible.|layers,stack,capsules,baseline,shape,diagram
79|Tall Inner Rectangle in Rounded Frame|A broad rounded square frame surrounds a smaller upright rectangle with rounded corners. The inner shape sits centrally with wide open margins on all sides and contains no visible letter or other mark.|frame,rectangle,outline,panel,inset,shape
80|Soft-Cornered Nested Square Outlines|A softly rounded outer square surrounds a centered inner square with more pronounced rounded corners. The outlines remain separate, leaving a broad empty border around a completely blank central opening.|squares,frame,nested,outline,inset,shape
81|Lower Inset Square within Rounded Border|A rounded square border encloses a smaller rounded square positioned slightly below center. A wider blank margin remains above the inset than beneath it, and neither shape contains a visible character.|square,frame,inset,border,outline,shape
84|Upright Stem with Three Pairs of Leaves|A straight upright stem carries three evenly spaced pairs of pointed oval leaves. Each pair curves outward and upward from a shared joint, with the stem extending beyond the leaves at both ends.|stem,leaves,plant,spelt,foliage,sprig
87|Three-Lobed Fidget Spinner with Center Ring|A fidget spinner has three broad rounded lobes arranged around a small circular center bearing. Narrow curved waists separate the lobes, with one extending upward and two spreading toward the lower corners.|spinner,fidget,toy,bearing,lobes,handheld
91|Rounded List Panel with Short Last Row|A rounded square panel contains three horizontal rows spaced down its center. The upper two rows are equally long, while the bottom row begins at the same left edge and ends earlier.|list,panel,rows,menu,interface,text
92|Inset Two-Cell Panel within Rounded Frame|A rounded outer frame encloses a smaller straight-sided rectangular panel. One horizontal divider splits the inset into two equal stacked cells, with a broad empty margin separating it from the surrounding border.|panel,cells,frame,divider,layout,rectangle
93|Three Vertebrae along Upright Spine|Three broad rounded vertebra-like bars are arranged vertically along a thin central spine. Short exposed sections of the spine connect the bars and extend beyond the upper and lower ends.|spine,vertebrae,back,bones,anatomy,skeleton
94|Curved Spleen with Indented Inner Edge|A spleen-like organ has a broad rounded outer edge and a deeply indented left side. A shorter inner curve follows the indentation, while a narrow extension descends toward the lower left.|spleen,organ,anatomy,body,medical,abdomen
95|Broad Left Arrow with Rounded Tail|A broad outlined arrow points left with a large triangular head and a thick horizontal shaft. Its upper and lower corners soften into curves, and the right end forms a rounded cap.|arrow,left,direction,back,shaft,symbol
97|Lightning Bolt with Three Side Rays|A tall outlined lightning bolt zigzags downward through two broad angled sections to a sharp lower point. Three short rays spread to its left beside the middle of the bolt.|lightning,bolt,rays,electricity,flash,energy
98|Square Root Sign with Long Overbar|A square root sign starts with a short horizontal entry, dips to a sharp low point and rises steeply. Its upper end turns into a long straight horizontal overbar extending rightward.|square root,radical,math,operator,symbol,calculation
99|Bone-In Ham with Oval Cut Face|A ham joint lies horizontally with a broad oval cut face on the left and a narrow bone extending right. A smaller oval appears on the cut surface, and the bone ends in two rounded lobes.|ham,meat,bone,food,joint,cut
100|Open Spring with Three Broad Coils|A vertical spring has three broad horizontal coils with rounded right ends. Slanting links connect successive coils down the left side, and the lowest link trails diagonally toward the lower edge.|spring,coil,metal,mechanism,compression,spiral
101|Centered Rounded Inset with Wide Border|A rounded square enclosure surrounds a smaller centered rounded square with a broad blank margin. The inner opening has a slightly wider horizontal span than vertical span and contains no visible character.|frame,inset,square,border,panel,outline
102|Rounded Inner Panel with Even Side Margins|A large rounded square outline contains a smaller rounded panel centered between its sides. The inner panel is nearly square with soft corners, and the surrounding border remains blank and uninterrupted.|panel,frame,inset,square,border,shape
103|Small Rounded Square Low in Frame|A large rounded square frame surrounds a much smaller square with softly rounded corners. The inset sits slightly low, leaving a broad open border above it and narrower space below.|square,inset,frame,border,outline,panel
105|Plain Shorts with Broad Waistband|A pair of shorts has a broad straight waistband and gently widening outer sides. A deep rounded gap separates the two legs, which end in flat hems without visible pockets or decoration.|shorts,clothing,waistband,legs,spandex,garment
106|Tumbling Figure with Raised Legs|A plain human figure tilts headfirst toward the lower right, with a round head beside an angled torso. Two legs stretch upward in a wide V, while one arm reaches down toward the lower left.|person,tumble,somersault,acrobat,body,movement
107|Right-Facing Head with Curled Breath Lines|A plain head faces right with a projecting nose and a wide open mouth. Two curling breath lines extend outward from the mouth, while the neck descends below the rounded back of the head.|head,breath,spit,mouth,profile,person
115|Upright Rocket beside Launch Gantry|An upright pointed rocket stands beside a tall braced launch gantry on its left. Broad swept fins flare from the rocket's lower body, and a short gantry arm reaches toward its side.|rocket,gantry,launch,space,tower,spacecraft
116|Round Spectacles with Curved Bridge|A pair of spectacles has two round lens frames joined by a short upward-curving bridge. Small horizontal temple ends project from the outer sides, and both lenses are empty and unshaded.|spectacles,glasses,lenses,frames,eyewear,bridge
117|Empty Rounded Square with Broad Corners|An empty square outline has long straight sides joined by broad rounded corners. The interior is entirely blank, with no visible letter, inset panel or other mark inside the frame.|square,frame,empty,outline,border,panel
118|Five-Point Star with Softened Tips|A five-pointed star has one upright top point and two broad side points above its lower pair. All tips and inner corners are softly rounded, and its interior remains empty.|star,five point,shape,outline,spark,emblem
121|Three Equal Rows inside Rounded Panel|A rounded square panel contains three equal horizontal rows arranged at regular vertical intervals. The rows align at both ends, leaving broad blank margins between the content and the surrounding frame.|panel,list,rows,menu,interface,layout
122|Plain Rounded Square with Blank Interior|A plain square border has softly curved corners and an entirely empty interior. Its long horizontal and vertical edges form one continuous outline with no visible lettering or internal subdivisions.|square,border,frame,empty,outline,panel
123|Low Horizontal Inset in Rounded Square|A large rounded square surrounds a short horizontal inset panel placed below center. The inset has softly rounded corners and an empty interior, with substantially more space above it than below.|inset,panel,frame,rectangle,border,shape
124|Thread Spool with Broad Rounded Flanges|An upright thread spool has wide rounded flanges at the top and bottom surrounding a narrower straight-sided barrel. Two horizontal winding lines divide the exposed barrel into three broad sections.|spool,thread,sewing,barrel,flange,craft
125|Blank Rounded Square with Straight Lower Edge|A blank rounded square has long straight sides and a level lower edge joined by curved corners. The single outer border contains no visible letter, symbol or inner frame.|square,frame,blank,border,outline,panel
126|Blank Soft-Cornered Square Border|A single square border has softly rounded corners around an entirely blank center. Its upper and lower edges are straight and parallel, with no visible letter or separate mark inside.|square,border,empty,frame,outline,panel
127|Curved Soybean with Oval Hilum|A single soybean lies diagonally with a broad rounded upper end and a narrower curved lower end. A small oval hilum sits within its bean-shaped body, slightly below the center.|soybean,bean,seed,food,legume,hilum
128|Right-Facing Songbird with Long Tail|A small songbird faces right with a rounded head, pointed beak and full curved breast. Its long tail slopes down toward the left, while two short legs meet a small horizontal perch line.|songbird,bird,beak,tail,animal,perch
129|Sonic Head with Swept Spines|Sonic's head faces left with swept pointed spines extending toward the right. A broad rounded muzzle projects below a small upright eye mark, and an arched brow curves over the face.|sonic,hedgehog,character,head,spines,profile
132|Curved Soy Pod with Two Seeds|A narrow curved soy pod hangs from a short bent stem and tapers to a pointed lower tip. Two oval seeds appear one above the other inside its gently bulging body.|soy,pod,seeds,legume,plant,food
133|Upright Rocket with Round Window|An upright rocket has a pointed nose, a round window and a long curved body. A seam crosses below the nose, while two broad side fins join the lower body above its rounded base.|rocket,spacecraft,window,fins,space,ship
134|Space Station with Paired Solar Wings|A space station has a central rectangular module connected horizontally to two tall solar wings. Each wing is divided into four panels, and a smaller square module rises above the center on a short connector.|space station,solar panels,spacecraft,module,orbit,structure
135|Large Four-Point Sparkle with Smaller Companion|A large four-pointed sparkle has long concave sides meeting at sharp vertical and horizontal tips. A smaller matching sparkle floats above and to the right, separate from the larger shape.|sparkle,stars,shine,twinkle,points,light
136|Right-Facing Loudspeaker with Two Sound Waves|A loudspeaker faces right with a short rounded rear housing and a broad flared cone. Two separate curved sound waves expand outward from the cone's open front at increasing distances.|speaker,loudspeaker,sound,waves,audio,volume
137|Three-Tined Spork with Rounded Handle|A spork has a broad spoon-shaped bowl cut into three short tines at its upper edge. The bowl narrows into a straight handle with a rounded lower end.|spork,utensil,spoon,fork,tines,cutlery
153|Quarter-Circle Broadcast Arcs with Square Origin|Two nested quarter-circle broadcast arcs expand from a small rounded square near the lower left. The arcs rise above the square and curve down toward the right without any surrounding enclosure.|rss,broadcast,arcs,signal,feed,wireless
157|Diagonal Spotlight with Flared Head|A spotlight angles toward the upper right with a broad flared head attached to a short rounded housing. A small rear connector projects at lower left, and two short rays sit beside the housing.|spotlight,lamp,light,beam,housing,fixture
158|Circular Crosshair with Open Center Ring|A circular target has four straight crosshair arms extending beyond its outer rim. The arms stop at a small central ring, leaving its interior empty and dividing the surrounding circle into quarters.|crosshair,target,circle,reticle,aim,sight
161|Three-Leaf Sprig with Upright Tip|A short plant sprig has one narrow pointed leaf rising vertically above two broad side leaves. The leaves join along a central stem that continues downward beyond their rounded bases.|sprig,leaves,plant,sourwood,stem,foliage
162|Three Parallel Rightward Arrows|Three long horizontal arrows point right in evenly spaced parallel rows. Each straight shaft ends in an open angled arrowhead, with their tips aligned vertically and no enclosing frame.|arrows,right,direction,parallel,flow,group
163|Tall Sombrero with Wide Curved Brim|A sombrero has a tall tapering crown with a rounded top above a very broad brim. The brim's upper edge is straight, while its ends curve down into a shallow rounded base.|sombrero,hat,brim,crown,headwear,clothing'''
d={}
for line in raw.splitlines():
 i,n,desc,tags=line.split('|');i=int(i);d[i]=dict(index=i,concept=n,icon_id=re.sub('[^a-z0-9]+','-',n.lower()).strip('-'),family='solo',description=desc,tags=tags.split(','))
assert len(d)==100,len(d)
h=set(json.loads((P/'held-indices.json').read_text()));assert set(d)==set(range(164))-h
existing=set(json.loads((P/'existing-ids.json').read_text()));print('Collisions',[(i,x['icon_id']) for i,x in d.items() if x['icon_id'] in existing]);print('Lengths',[(i,len(x['description'].split())) for i,x in d.items() if not 25<=len(x['description'].split())<=45]);(P/'solo-drafts.json').write_text(json.dumps(d,indent=2)+'\n')
