from pathlib import Path
import json,html,sys
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from icon_set.model.icons.registry import create
from icon_set.renderers.svg import build_paths
SOURCE_ICON_ID=None
SOURCE_PATH='icon_set/work/solo-failed-batch-100/review-decisions.json'
AUTHOR='gpt-6'
W=Path(__file__).parent
rows=json.loads((W/'review-decisions.json').read_text());before=json.loads((W/'before.json').read_text())
notes={46:'Pull the curled tail clear of the back and belly.',58:'Open the head circle and clear the flag/float spacing.',70:'Open the left four and rebalance the zero to eliminate the hidden pocket.',6:'Split the m-stems at the arches and remove the duplicated downstroke.',16:'Split the bead top at the wire endpoint.',17:'Remove the duplicate support bottom; share the base and crank junctions.',18:'Remove the duplicate stone bottom; split the plinth at both walls.',24:'Split the loaf outline at both slice-seam endpoints.',28:'Use one ground edge and shared doorway endpoints.',31:'Remove the duplicate valley floor; share one continuous ground edge.',42:'Remove the duplicate grip bottom so the battery owns the seam.',54:'Remove the duplicate hat bottom; the brim owns the shared edge.',73:'Remove the duplicate hat bottom; the brim owns the shared edge.',75:'Split the reel circle at the exact film-tail attachment.',85:'Split the fork bowl at the center-tine and handle junction.',86:'Split the fork bowl at the center-tine and handle junction.',93:'Split the finger curl and outer hand at their actual contact.',26:'Open the flame valley to create one broad counter.',33:'Move the elbow one unit to open the tiny counter; lower the head one unit for the exact 4-unit body gap.'}
cards=[];md=['# Solo centerline review — batch of 100','','Reviewed the first 100 entries from the failed-build report in its displayed order. All were solo AI icons.','','- 19 reconstructed variants; original modules preserved.','- 81 retained with exact-drawing, exact-rule, exact-pair visual-review records.','- Every selected final icon is built; ordinary geometry, MIC and hole checks remain enforced.','- Light/dark native-size and enlarged centerline sheets are saved alongside this report.','','## Construction references','','Inspected local Lucide originals and atomic-debug versions of hand, drill, building, type, utensils, film and user-round; also the shared human user.svg and full_body_ref.png. All keyshapes, silhouettes and intentional asymmetry were preserved. The flame, mouse tail, diver, 404 label and chairlift include visible geometry repairs. Existing avatar head/body contact is preserved. The chairlift head now has an exact 4-unit visible gap above the seated body.','','## Validation','','Targeted 100-icon build succeeded. The 19 focused tests pass, including review invalidation on geometry/rule changes and continued blocking of certified failures. The broader suite ran 347 tests: 64 failures, 28 errors, 1 skipped; failures include other corpus models and outdated fixtures, while local-server errors include sandbox socket restrictions. See tests.log.','','## Individual decisions','']
for row in rows:
 n=row['number'];ident=row.get('replacement',row['icon_id']);icon=create(ident);paths=build_paths(icon.draw());esc=html.escape
 center='<svg viewBox="0 0 48 48" class="center" aria-label="Centerline">'
 for p in paths:center+='<path d="'+esc(p['d'],quote=True)+'" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" opacity=".17"/>'
 for p in paths:center+='<path d="'+esc(p['d'],quote=True)+'" fill="none" stroke="#4387ed" stroke-width=".45"/>'
 center+='</svg>'
 kind='reconstructed' if 'replacement' in row else 'reviewed';reason=notes[n] if n in notes else row['reason']
 row['reason']=reason
 cards.append(f'<article data-kind="{kind}"><h2>{n}. {esc(row["icon_id"])}</h2><span class="badge">{kind}</span><div class="previews">{center}<div class="light"><img width="48" height="48" src="../solo48/{ident}.svg"></div><div class="dark"><img width="48" height="48" src="../solo48/{ident}.svg"></div></div><p>{esc(reason)}</p><p class="small">{icon.keyshape.name} · <a href="../solo48/{ident}.svg">Built SVG</a> · <a href="../qa/solo/{ident}/metrics.json">Measurements</a></p></article>')
 md.append(f'### {n}. {row["icon_id"]}\n\n{kind.capitalize()}: {reason}\n\nFinal icon: `{ident}`; keyshape: `{icon.keyshape.name}`.\n')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solo centerline review — 100 icons</title><style>body{font:15px/1.5 system-ui;background:#f5f4f0;color:#222b35;margin:28px}header{max-width:1000px;margin-bottom:24px}h1{font-size:30px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}article{background:white;padding:18px;border:1px solid #ddd;border-radius:12px}h2{font-size:15px;margin:0 0 8px}.badge{font-size:12px;background:#e1f0e4;color:#285536;padding:3px 8px;border-radius:9px}.previews{display:flex;gap:14px;align-items:center;margin-top:18px}.center{width:96px;height:96px}.light,.dark{padding:8px;border-radius:5px}.dark{background:#17191d}.dark img{filter:invert(1)}.small{font-size:12px;color:#566171}select,input{padding:9px;border:1px solid #bbc1c8;border-radius:5px;font:inherit}a{color:#245fb0}[hidden]{display:none!important}</style><header><h1>100 solo icons reviewed</h1><p><strong>19 reconstructed · 81 preserved after visual review</strong></p><p>All 100 selected outputs built successfully. Blue lines show their centerlines; the two smaller previews show native 48px light and dark versions.</p><p>Preserved drawings retain their measured opposing-edge advisories and a specific review reason. Acceptance expires when the drawing, rules, or flagged pair changes. Certified spacing and hole checks remain active.</p><p>The 19 originals remain available as parents of independent revised variants, so they can still appear in Failed build.</p><label>Show <select id="filter"><option value="">All 100</option><option value="reconstructed">19 reconstructed</option><option value="reviewed">81 preserved</option></select></label> <input id="search" type="search" placeholder="Find an icon…" aria-label="Find an icon"></header><main>'''+''.join(cards)+'''</main><script>function filter(){const k=document.querySelector('#filter').value,q=document.querySelector('#search').value.toLowerCase();document.querySelectorAll('article').forEach(c=>c.hidden=!!((k&&c.dataset.kind!==k)||(q&&!c.textContent.toLowerCase().includes(q))))}document.querySelector('#filter').onchange=filter;document.querySelector('#search').oninput=filter;</script></html>'''
(ROOT/'icon_set/dist/gallery/solo-review-batch-100.html').write_text(page)
(W/'REPORT.md').write_text('\n'.join(md));(W/'review-decisions.json').write_text(json.dumps(rows,indent=2)+'\n')
print('100-icon review report saved')
