#!/usr/bin/env python3
"""Publish saved center audit evidence without recomputing or approving it."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'icon_set/work/container-center-audit'
records=json.loads((OUT/'results.json').read_text())
cards=[]
for r in records:
 name=r['container'];metrics=[]
 for title,key in [('Previous center','previous_center'),('Chosen center','center'),('Area centroid','centroid'),('Bounds midpoint','bounds_center'),('Largest-circle center','largest_circle_center'),('Center-to-zone edge (units)','center_to_zone_edge'),('Largest-circle radius (units)','largest_circle_radius'),('Candidate difference (units)','candidate_disagreement'),('Left/right/top/bottom gaps','axis_gaps'),('Mirror overlap, vertical/horizontal','symmetry_overlap'),('Confidence components','confidence_components')]:
  if key in r:metrics.append(f'<tr><th>{title}</th><td>{html.escape(str(r[key]))}</td></tr>')
 cards.append(f'<article id="{name}" data-name="{name}" data-level="{r["confidence_level"]}"><h2>{name}</h2><b>{r["confidence_level"]} confidence · {r["confidence_score"]}/100</b><div class="pictures"><img src="{name}.png" width="256" height="256" loading="lazy"><img src="{name}.png" width="64" height="64" loading="lazy"></div><p>{html.escape(r["method"])}</p><p>{html.escape(r["reason"])}</p><table>'+''.join(metrics)+f'</table><p>{html.escape(r.get("limitations","Center only; no safe-zone clearance claim."))}</p><p>{html.escape(r.get("visual_note",""))}</p><p>Visual review: {r["visual_review"]}</p><details><summary>Source identity</summary><code>{r["source_sha256"]}</code></details></article>')
(OUT/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Container center audit</title><style>body{font:14px system-ui;background:#f3f5f7;color:#1d2631;margin:28px}header{max-width:1050px}p{line-height:1.55}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(370px,1fr));gap:18px}article{background:white;padding:22px;border:1px solid #d8dee7;border-radius:12px;scroll-margin-top:20px}article:target{outline:3px solid #2563eb}h2{font-size:17px;overflow-wrap:anywhere}.pictures{display:flex;align-items:center;gap:24px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;vertical-align:top;padding:7px;border-bottom:1px solid #eee;overflow-wrap:anywhere}th{width:40%}code{overflow-wrap:anywhere}nav{margin:24px 0;display:flex;gap:12px}input,select{font:inherit;padding:10px}article[hidden]{display:none}</style><header><h1>Container center audit — 210 containers</h1>
<p><b>Blue cross:</b> chosen center. <b>Red ring:</b> previous point. <b>Purple ring:</b> center of a largest fitting circle. Coincident markers may overlap. Every card shows enlarged and native 64-unit previews.</p>
<p><b>Definition:</b> center means the balance point (area centroid) of the selected content zone, rounded to a half unit. If the centroid is outside the zone, use a largest-circle center. The purple point answers a different question: where a round sub icon could be largest. Equal-radius circle candidates are resolved toward the centroid. A large disagreement lowers confidence and calls for checking the actual paired icon.</p>
<details open><summary><b>Evidence and confidence rubric</b></summary><p>The /100 score is a transparent heuristic rating, <b>not a measured probability</b> or a user-study result. Source identity: 20; conservative raster zone clearance: 15; semantic boundary support: 20 for closed faces, 15 for manual open boundaries, capped at 12 for context-sensitive faces; agreement between centroid and largest-circle center: up to 20, minus 2 per unit of disagreement; symmetry support: 15 for two mirror axes, 10 for one, 5 otherwise; contained centroid: 10 (fallback: 4). High ≥90, Medium 75–89, Low &lt;75. Low symmetry does not itself mean bad design; it means less geometric evidence for an unambiguous center.</p><p>Center-only overlays use a separate 85/100 rationale score and claim no safe area. Zone-boundary distances are measured on saved polygons. Mirror overlap compares the zone against its reflection about its bounds midpoint; ≥98% supports an axis. Placement review is distinct from full icon-model/build QA. Source SVGs are preserved.</p></details>
<p>All polygons still require actual sub-icon vector clearance checks. Green boundaries are the previously reviewed conservative zones; this audit corrects centers, not primitive shapes.</p></header><nav><input id="q" placeholder="Find container"><select id="level"><option>All confidence levels</option><option>High</option><option>Medium</option><option>Low</option></select><span id="count"></span></nav><main>'''+''.join(cards)+'''</main><script>const q=document.querySelector('#q'),level=document.querySelector('#level');function filter(){let n=0;document.querySelectorAll('article').forEach(c=>{c.hidden=!c.dataset.name.includes(q.value.toLowerCase())||(level.selectedIndex>0&&c.dataset.level!==level.value);if(!c.hidden)n++});document.querySelector('#count').textContent=n+' shown'}q.oninput=filter;level.onchange=filter;filter();</script></html>''')
print(OUT/'index.html')
