from pathlib import Path
import sys,json,html,collections
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from icon_set.model.icons.registry import create
SOURCE_ICON_ID=None
SOURCE_PATH='icon_set/work/solo-ai-full-set/inventory.json'
AUTHOR='gpt-6'
w=Path(__file__).parent
originals=json.loads((w/'inventory.json').read_text());prior=json.loads((w/'prior-reviews.json').read_text());batch={r['parent']:r for r in json.loads((w/'batch.json').read_text())};cleanup={r['parent']:r for r in json.loads((w/'construction-cleanup.json').read_text())}
audit={r['parent']:r for r in json.loads((w/'audit.json').read_text())};checks={r['icon_id']:r for r in json.loads((w/'release-check.json').read_text())}
followup=w.parent/'solo-ai-number-arrows'
if (followup/'batch.json').exists():
 batch.update({r['parent']:r for r in json.loads((followup/'batch.json').read_text())})
 checks.update({r['icon_id']:r for r in json.loads((followup/'checks.json').read_text())})
rows=[]
for k,r in enumerate(originals):
 n=r['icon_id'];picked=batch.get(n) or prior.get(n) or cleanup.get(n);current=picked['icon_id'] if picked else n
 q=checks.get(current,{}) if n in batch else {'status':'earlier-review-preserved'} if n in prior else cleanup[n]['report'] if n in cleanup else audit[n]['report']
 status='fix' if n in batch else 'earlier' if n in prior else 'cleanup' if n in cleanup else 'retained'
 if status!='earlier' and q.get('status')!='pass':status='attention'
 notes=picked.get('plan','Original drawing retained after visual inspection.') if picked else 'Original drawing retained after visual inspection.'
 if n=='feather':notes='Preserve the broad feather and diagonal shaft; remove the cramped notch for a smooth vane.'
 rows.append(dict(number=k+1,name=n,current=current,status=status,category=r['category'],notes=notes,checks=q.get('status'),exception_requested=status=='attention',findings=q.get('errors',[])+q.get('warnings',[]),original=create(n).to_svg(),revised=create(current).to_svg()))
(w/'review-ledger.json').write_text(json.dumps([{k:v for k,v in r.items() if k not in ['original','revised']} for r in rows],indent=2))
counts=collections.Counter(r['status'] for r in rows)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solo — full set review</title>
<style>
:root{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#19222b;background:#f3f4f5;--paper:#fff;--line:#e1e4e8;--muted:#67717d;--ink:#111;--accent:#075e50}*{box-sizing:border-box}body{margin:0}body.dark{color:#e8edf3;background:#11151b;--paper:#1c222b;--line:#333b47;--muted:#a3adba;--ink:#f3f4f6;--accent:#83ddbd}header{max-width:1500px;margin:auto;padding:36px 24px 20px}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-size:11px;color:var(--accent);font-weight:700}h1{font-size:32px;margin:10px 0}p{color:var(--muted);line-height:1.5;max-width:850px;font-size:14px}.controls{position:sticky;top:0;z-index:2;background:var(--paper);border-block:1px solid var(--line);padding:16px 24px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}input,select,button{font:inherit;font-size:13px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:inherit;padding:10px 12px}input{min-width:250px;flex:1;max-width:500px}button{cursor:pointer}button:hover{border-color:var(--accent)}.count{margin-left:auto;font-size:12px;color:var(--muted)}main{max-width:1500px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(440px,1fr));gap:18px}article{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:16px}h2{font-size:14px;overflow-wrap:anywhere;margin:0 0 10px}.tag{font-size:10px;border-radius:20px;padding:4px 8px;color:var(--accent);background:color-mix(in srgb,var(--accent) 10%,transparent);display:inline-block;margin-bottom:12px}.tag.attention{color:#bd6427;background:#bd642719}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px}.drawing{height:142px;display:flex;align-items:center;justify-content:center;gap:8px;color:var(--ink)}.large svg{width:96px;height:96px;display:block}.native svg{width:48px;height:48px;display:block}.caption{font-size:11px;color:var(--muted);text-align:center}.note{font-size:12px;margin:14px 0 0;color:var(--muted);line-height:1.45}details{font-size:11px;color:var(--muted);margin-top:12px}summary{cursor:pointer}.pager{display:flex;gap:12px;align-items:center;justify-content:center;margin:24px}.empty{text-align:center;color:var(--muted);padding:60px}.counts{display:flex;flex-wrap:wrap;gap:8px}.chip{background:var(--paper);border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:12px}.notice{font-size:12px;margin-top:14px}a{color:var(--accent)}@media(max-width:600px){main{padding:14px}.controls{padding:12px}.drawing{gap:4px}.large svg{width:80px;height:80px}.grid{grid-template-columns:1fr}}
</style><header><div class="eyebrow">Pictographic · Solo 48</div><h1>The full converted set.</h1><p>Originals beside the latest drawings, shown enlarged and at their native 48 px size. Earlier refinements are preserved. New drawings remain available for your review.</p><div class="counts" id="counts"></div><p class="notice">All 1,722 originals were reviewed. New drawings are review candidates, not human approvals. Flagged candidates retain unresolved spacing findings and are withheld from release. Construction cleanup preserves the appearance; retained originals needed no change.</p></header>
<div class="controls"><input id="search" placeholder="Find an icon…" aria-label="Find an icon"><select id="filter" aria-label="Filter"><option value="all">All icons</option><option value="fix" selected>Visible fixes</option><option value="attention">Spacing review</option><option value="earlier">Earlier refinements</option><option value="cleanup">Construction cleanup</option><option value="retained">Original retained</option></select><button id="theme">Dark background</button><span class="count" id="count"></span></div><main><div class="grid" id="grid"></div><div class="pager"><button id="prev">Previous</button><span id="page"></span><button id="next">Next</button></div></main><script>
const rows=DATA;
const labels={fix:'Visible fix',earlier:'Earlier refinement',cleanup:'Construction cleanup',retained:'Original retained',attention:'Spacing review'};
const counts=COUNTS;document.getElementById('counts').innerHTML=Object.entries(counts).map(([k,n])=>`<span class="chip">${n} ${labels[k].toLowerCase()}</span>`).join('');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let page=0,size=48;const grid=document.getElementById('grid'),search=document.getElementById('search'),filter=document.getElementById('filter');
function draw(){const q=search.value.trim().toLowerCase();const found=rows.filter(r=>(filter.value==='all'||r.status===filter.value)&&(!q||`${r.name} ${r.category}`.toLowerCase().includes(q)));const pages=Math.max(1,Math.ceil(found.length/size));page=Math.min(page,pages-1);grid.innerHTML=found.slice(page*size,(page+1)*size).map(r=>`<article><h2>${r.number}. ${esc(r.name)}</h2><span class="tag ${r.status}">${labels[r.status]}</span><div class="pair"><div><div class="drawing"><span class="large">${r.original}</span><span class="native">${r.original}</span></div><div class="caption">Original</div></div><div><div class="drawing"><span class="large">${r.revised}</span><span class="native">${r.revised}</span></div><div class="caption">${r.current===r.name?'Retained':'Latest drawing'}</div></div></div><p class="note">${esc(r.notes)}</p>${r.findings.length&&r.status==='attention'?`<details><summary>Remaining checks</summary><p>${r.findings.map(esc).join('<br>')}</p></details>`:''}</article>`).join('')||'<div class="empty">No matching icons.</div>';document.getElementById('count').textContent=`${found.length} icons`;document.getElementById('page').textContent=`${page+1} / ${pages}`;document.getElementById('prev').disabled=!page;document.getElementById('next').disabled=page>=pages-1;}
search.oninput=filter.onchange=()=>{page=0;draw()};document.getElementById('prev').onclick=()=>{page--;draw();scrollTo(0,0)};document.getElementById('next').onclick=()=>{page++;draw();scrollTo(0,0)};document.getElementById('theme').onclick=()=>{document.body.classList.toggle('dark');document.getElementById('theme').textContent=document.body.classList.contains('dark')?'Light background':'Dark background'};draw();</script></html>'''
page=page.replace('DATA',json.dumps(rows).replace('<','\\u003c')).replace('COUNTS',json.dumps(counts))
(w/'review-current.html').write_text(page);(ROOT/'icon_set/dist/gallery/solo-ai-full-set.html').write_text(page)
print(dict(counts))
