from pathlib import Path
import json,re,textwrap,shutil
AUTHOR='gpt-6'
SOURCE_ICON_ID=None
SOURCE_PATH='/tmp/fix-runs.json'
ROOT=Path('icon_set/work/primitive-make-ray')
HELPERS='''
    def path(self, name, start, commands, closed=False):
        ids=[]; here=start
        for i,c in enumerate(commands):
            eid=f'{name}-{i}'; ids.append(eid)
            if c[0]=='L': self.add_line(eid,here,c[1])
            elif c[0]=='A': self.add_arc(eid,here,c[1],radius_x=c[2],radius_y=c[3],sweep=c[4],large_arc=c[5] if len(c)>5 else False)
            elif c[0]=='C': self.add_bezier(eid,here,(c[2],c[3],c[1]))
            here=c[1]
        self.add_contour(name,*ids,closed=closed)
    def circle(self,n,x,y,r):
        self.path(n,(x-r,y),[('A',(x+r,y),r,r,True),('A',(x-r,y),r,r,True)],True)
    def box(self,n,x,y,w,h,r):
        self.path(n,(x+r,y),[('L',(x+w-r,y)),('A',(x+w,y+r),r,r,True),('L',(x+w,y+h-r)),('A',(x+w-r,y+h),r,r,True),('L',(x+r,y+h)),('A',(x,y+h-r),r,r,True),('L',(x,y+r)),('A',(x+r,y),r,r,True)],True)
'''
cases={}
def case(i,key,refs,plan,body,omissions='None'):
 cases[i]=(key,refs,plan,textwrap.dedent(body),omissions)
case(1,'SQUARE',[],'Rounded basin, a hooked faucet, drain trap, and detached water drop. Plumbing remains asymmetrical.', '''
self.path('basin',(20,18),[('L',(42,18)),('C',(31,29),(42,25),(38,29)),('C',(20,18),(24,29),(20,25))],True)
self.path('faucet',(26,10),[('A',(34,10),4,4,True),('L',(34,18))])
self.relate('connect','faucet','basin')
self.path('drain',(31,29),[('L',(31,36)),('A',(39,36),4,4,False),('L',(39,33)),('L',(42,33))])
self.relate('connect','drain','basin')
self.path('drop',(12,28),[('C',(18,36),(14,31),(18,33)),('A',(6,36),6,6,True),('C',(12,28),(6,33),(10,31))],True)
''','Secondary pipe wall omitted to preserve clearance.')
case(2,'VRECT_L',['calendar'],'Calendar uses matching radius-3 corners, equal bindings, a straight header and a long diagonal seven.', '''
self.path('top',(8,17),[('L',(8,11)),('A',(11,8),3,3,True),('L',(16,8)),('L',(32,8)),('L',(37,8)),('A',(40,11),3,3,True),('L',(40,17))])
self.path('body',(40,17),[('L',(40,41)),('A',(37,44),3,3,True),('L',(11,44)),('A',(8,41),3,3,True),('L',(8,17))])
self.add_line('header',(8,17),(40,17))
for a,b in [('top','body'),('header','top'),('header','body')]:self.relate('connect',a,b)
for x in (16,32):
    self.add_line('binding-'+str(x),(x,4),(x,8));self.relate('connect','binding-'+str(x),'top')
self.add_polyline('seven',(20,26),(31,26),(24,35))
''')
case(4,'SQUARE',['refresh-cw'],'Two circular arcs and equal right-angle arrowheads related by 180-degree rotation.', '''
for name,flip in [('upper',False),('lower',True)]:
    def p(x,y):return (48-x,48-y) if flip else (x,y)
    self.path(name,p(6,26),[('A',p(24,8),18,18,True),('C',p(42,18), (p(32,8)), (p(38,12)))])
    self.add_polyline(name+'-head',p(32,18),p(42,18),p(42,6))
    self.relate('connect',name,name+'-head')
''')
case(5,'VRECT_L',['clipboard'],'Clipboard with tangent radius-4 corners and a rounded capsule clip. Page terminates at clip side nodes.', '''
self.path('clip',(20,4),[('L',(28,4)),('A',(28,12),4,4,True),('L',(20,12)),('A',(20,4),4,4,True)],True)
self.path('page',(16,8),[('L',(12,8)),('A',(8,12),4,4,False),('L',(8,40)),('A',(12,44),4,4,False),('L',(36,44)),('A',(40,40),4,4,False),('L',(40,12)),('A',(36,8),4,4,False),('L',(32,8))])
self.relate('connect','page','clip')
''')
case(6,'SQUARE',['settings'],'Eight rounded gear lobes generated by quarter rotation; smooth S with exposed dollar stems.', '''
# One quadrant owns all repeated teeth and smooth transitions.
quarter=[('C',(27,6),(23,6),(25,6)),('C',(30,11),(29,6),(28,10)),('C',(35,10),(32,12),(33,9)),('C',(38,13),(36,10),(38,12)),('C',(37,18),(39,15),(36,16)),('C',(42,21),(38,20),(42,19))]
def rot(p,k):
    x,y=p[0]-24,p[1]-24
    for _ in range(k):x,y=-y,x
    return x+24,y+24
commands=[]
for k in range(4):
    for c in quarter:commands.append(('C',rot(c[1],k),rot(c[2],k),rot(c[3],k)))
self.path('gear',(21,6),commands,True)
self.path('dollar',(28,18),[('C',(24,17),(27,17),(25,17)),('C',(24,24),(17,17),(17,23)),('C',(24,31),(31,25),(31,31)),('C',(20,30),(22,31),(21,31))])
self.add_line('stem-top',(24,14),(24,17));self.add_line('stem-bottom',(24,31),(24,34))
self.relate('connect','dollar','stem-top');self.relate('connect','dollar','stem-bottom')
''')
case(8,'VRECT_L',['shield-check'],'Mirrored shield shoulders and flowing sides, with a crisp check mark.', '''
self.path('shield',(24,4),[('C',(40,10),(30,8),(34,10)),('L',(40,19)),('C',(24,44),(40,30),(33,38)),('C',(8,19),(15,38),(8,30)),('L',(8,10)),('C',(24,4),(14,10),(18,8))],True)
self.add_polyline('check',(18,24),(23,29),(31,19))
''')
case(9,'HRECT_L',['biceps-flexed'],'Fist is rounded into a long forearm; the lower arm has a horizontal bottom tangent; muscle has one smooth inner curve.', '''
self.path('arm',(44,24),[('C',(24,27),(38,19),(29,20)),('C',(21,17),(23,24),(21,20)),('C',(27,14),(25,18),(27,16)),('C',(22,8),(27,10),(25,8)),('C',(14,12),(18,8),(16,10)),('C',(4,33),(9,19),(4,28)),('C',(24,40),(4,40),(14,40)),('C',(44,36),(32,40),(39,38))])
self.path('muscle',(24,27),[('C',(37,29),(28,33),(34,33))])
self.relate('connect','arm','muscle')
''','Small fist creases and the closed inner muscle lens reduced to one curve.')
case(10,'SQUARE',['bird'],'Flying bird with raised wing, round head, pointed beak and suspended rectangular parcel.', '''
self.path('bird',(6,6),[('C',(24,16),(15,6),(23,8)),('C',(35,11),(23,7),(31,6)),('L',(42,16)),('L',(36,19)),('C',(24,28),(35,25),(30,28)),('L',(18,28)),('L',(6,28)),('L',(12,20)),('C',(6,6),(8,18),(6,12))],True)
self.path('parcel',(18,28),[('L',(18,42)),('L',(32,42)),('L',(32,28))])
self.relate('connect','bird','parcel')
''','Parcel tape and eye omitted due to limited interior clearance.')
case(11,'HRECT_L',['flame'],'Matching smooth parentheses enclose a coherent asymmetric flame with a single inward tongue.', '''
self.path('left',(8,10),[('C',(4,24),(5,13),(4,19)),('C',(8,38),(4,29),(5,35))])
self.path('right',(40,10),[('C',(44,24),(43,13),(44,19)),('C',(40,38),(44,29),(43,35))])
self.path('flame',(24,8),[('C',(30,24),(30,14),(30,18)),('C',(34,20),(30,28),(34,25)),('C',(24,40),(39,32),(32,40)),('C',(14,30),(18,40),(14,36)),('C',(24,8),(14,22),(26,20))],True)
''','Small nested inner flame removed to keep one readable open flame.')
case(12,'VRECT_L',[],'Geisha portrait with circular jaw, broad shoulders, coiffure and symmetric hairpins. Human reference user.svg informs proportions.', '''
self.circle('head',24,21,9)
self.path('bun',(18,10),[('C',(24,4),(18,6),(21,4)),('C',(30,10),(27,4),(30,6))])
self.add_line('pin-left',(8,4),(18,10));self.add_line('pin-right',(40,4),(30,10))
for n in ('pin-left','pin-right'):self.relate('connect',n,'bun')
self.path('shoulders',(8,44),[('A',(14,38),6,6,True),('L',(34,38)),('A',(40,44),6,6,True)])
''','Kimono cross-lap and small hairline reduced at 48px; exact detached head/body centerline gap is 8.')
case(13,'VRECT_M',[],'Gherkin tower: exactly mirrored oval-taper silhouette with smooth vertical widest points and two diagonal facade lines.', '''
self.path('tower',(24,4),[('C',(38,28),(29,4),(38,17)),('C',(32,44),(38,34),(35,41)),('L',(16,44)),('C',(10,28),(13,41),(10,34)),('C',(24,4),(10,17),(19,4))],True)
self.add_line('facade-one',(15,14),(37,35))
self.add_line('facade-two',(10,28),(26,44))
self.relate('connect','tower','facade-two')
''','Two facade diagonals retained; dense glazing omitted.')
case(14,'HRECT_M',['trending-down'],'Three exact diagonal graph segments; descending legs at 45 degrees and equal arrowhead arms.', '''
self.add_polyline('trend',(4,10),(22,28),(30,20),(44,34))
self.add_polyline('arrow',(32,38),(44,38),(44,26))
self.add_line('tip-link',(44,34),(44,38))
self.relate('connect','trend','tip-link');self.relate('connect','tip-link','arrow');self.relate('connect','trend','arrow')
''')
case(15,'SQUARE',['hand','move-diagonal'],'Rounded pointing finger and thumb between three identical outward arrows and bottom-right corner.', '''
self.path('hand',(20,34),[('L',(16,27)),('C',(22,25),(14,22),(19,21)),('L',(22,18)),('A',(30,18),4,4,True),('L',(30,25)),('C',(34,27),(32,24),(34,25)),('L',(34,30)),('A',(30,34),4,4,True),('L',(20,34))],True)
for n,p in [('tl',[(13,6),(6,6),(6,13),(12,12)]),('tr',[(35,6),(42,6),(42,13),(36,12)]),('bl',[(6,35),(6,42),(13,42),(12,36)])]:
    self.add_polyline(n,*p[:3]);self.add_line(n+'-stem',p[1],p[3]);self.relate('connect',n,n+'-stem')
self.add_polyline('corner',(42,36),(42,42),(36,42))
''','Small folded-finger separations omitted.')
case(16,'HRECT_L',['hand'],'Right-pointing rounded hand, smooth contact arc and complete downward arrow.', '''
self.path('hand',(4,28),[('L',(4,20)),('L',(17,14)),('C',(20,18),(22,12),(24,17)),('L',(28,18)),('A',(28,26),4,4,True),('L',(18,26)),('L',(17,30)),('L',(8,30)),('A',(4,28),4,4,True)],True)
self.path('motion',(27,8),[('C',(44,23),(36,8),(44,14)),('C',(38,32),(44,27),(42,30))])
self.add_polyline('arrow',(20,36),(24,40),(28,36));self.add_line('shaft',(24,33),(24,40));self.relate('connect','arrow','shaft')
''')
case(17,'VRECT_L',[],'Hryvnia: smooth reversed S with horizontal extrema and two exactly parallel currency bars.', '''
self.path('currency',(14,6),[('C',(24,4),(17,4),(20,4)),('C',(35,12),(30,4),(35,7)),('C',(24,24),(35,17),(30,21)),('C',(13,36),(18,27),(13,31)),('C',(24,44),(13,41),(18,44)),('C',(34,42),(28,44),(31,44))])
for n,y in [('upper',20),('lower',28)]:
    self.add_line(n,(8,y),(40,y));self.relate('connect','currency',n)
''')
case(18,'SQUARE',[],'Gungan head: symmetric raised eye stalks, rounded muzzle, long curved ears and a small smile.', '''
self.path('face',(12,17),[('C',(17,6),(10,8),(12,6)),('C',(22,13),(21,6),(22,10)),('C',(26,13),(23,11),(25,11)),('C',(31,6),(26,10),(27,6)),('C',(36,17),(36,6),(38,8)),('C',(24,38),(37,31),(31,38)),('C',(12,17),(17,38),(11,31))],True)
for name,sgn in [('left',-1),('right',1)]:
    def p(x,y):return (24+sgn*x,y)
    self.path(name,p(12,17),[('C',p(18,42),p(17,26),p(18,35)),('L',p(10,42))])
    self.relate('connect',name,'face')
self.path('smile',(20,26),[('C',(28,26),(20,30),(28,30))])
''','Pupils and ear stripes omitted at 48px.')
case(19,'HRECT_L',['arrow-left'],'Smooth circular target boundary ending behind a circular node, with balanced left arrow.', '''
self.path('target',(10,18),[('C',(28,8),(14,11),(20,8)),('A',(44,24),16,16,True),('A',(28,40),16,16,True),('C',(10,30),(20,40),(14,37))])
self.circle('node',10,24,6);self.relate('connect','target','node')
self.add_polyline('head',(30,18),(24,24),(30,30));self.add_line('shaft',(24,24),(35,24));self.relate('connect','head','shaft')
''')
manifest=[]
for i,s in enumerate(json.loads(Path('/tmp/fix-runs.json').read_text())):
 if i not in cases:continue
 fix=Path(s);item=json.loads((fix/'claim.json').read_text())['item'];ref=next((fix/'reference').glob('*.svg'))
 match=re.search(r'(.+)_([a-f0-9-]{36})$',ref.stem);concept,uuid=match.groups()
 key,refs,plan,body,omissions=cases[i];run=ROOT/uuid/'20260924-clean-centerlines-thuan-mac';run.mkdir(parents=True,exist_ok=False)
 meta={'concept':concept,'source_uuid':uuid,'reference_path':str(ref),'icon_id':item['icon_id'],'author':AUTHOR,'plan':plan,'construction_references':refs,'omissions':omissions,'keyshape':key,'fix_dir':str(fix)}
 (run/(item['icon_id']+'.metadata.json')).write_text(json.dumps(meta,indent=2))
 shutil.copy(fix/'reference.png',run/'reference.png')
 module=run/(item['icon_id'].replace('-','_')+'_'+uuid.replace('-','_')+'.py')
 header=f'"""{plan}\nOmissions: {omissions}\nLucide construction references: {refs or "no useful match"}.\n"""\nfrom icon_set.model.keyshapes import Keyshape\nfrom icon_set.model.icons.solo._base import Solo48\nSOURCE_ICON_ID={uuid!r}\nSOURCE_PATH={str(ref)!r}\nAUTHOR={AUTHOR!r}\n\nclass Drawing(Solo48):\n    icon_id={item["icon_id"]!r}\n    keyshape=Keyshape.{key}\n    semantic_role="MAIN"\n    semantic_kind="noun"\n    category="objects"\n    aliases=()\n    keywords={tuple(concept.split())!r}\n'
 module.write_text(header+HELPERS+'\n    def build(self):\n'+textwrap.indent(body.strip()+'\n','        '))
 manifest.append({'index':i,'run':str(run),'module':str(module),**meta})
(ROOT/'fix-batch-20260924/manifest.json').write_text(json.dumps(manifest,indent=2))
