from pathlib import Path
import json,sys,html
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from icon_set.model.icons.registry import create
SOURCE_ICON_ID=None
SOURCE_PATH='icon_set/work/solo-ai-next50/selected.json'
AUTHOR='gpt-6'
WORK=Path(__file__).parent
rows=json.loads((WORK/'batch.json').read_text()); originals={r['icon_id']:r for r in json.loads((WORK/'selected.json').read_text())}
reports={r['icon_id']:r for r in json.loads((WORK/'validation.json').read_text())}
cards=[]
for j,r in enumerate(rows,1):
 before=(ROOT/'icon_set'/originals[r['parent']]['svg_path']).read_text(); after=create(r['icon_id']).to_svg()
 cards.append(f'''<article><header><span>{j:02}</span><h2>{html.escape(r['parent'])}</h2></header><div class="pair"><figure>{before}<figcaption>Original</figcaption></figure><figure>{after}<figcaption>Revised</figcaption></figure></div><details><summary>Construction notes</summary><p>{html.escape(r['plan'])}</p><p>{r['keyshape']} · {reports[r['icon_id']]['status']} · {'Lucide '+r['reference'] if r['reference'] else 'No useful exact Lucide match'}</p></details><a href="index.html?tab=icons&family=solo&view=versions&q={r['parent']}">Compare in library ↗</a></article>''')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solo icons · Next 50 AI reviews</title><style>
:root{color-scheme:light;--bg:#f4f3ef;--card:#fff;--ink:#171a1c;--muted:#657078;--line:#dfe2df}body.dark{color-scheme:dark;--bg:#14171a;--card:#1e2226;--ink:#f3f5f4;--muted:#a5afb7;--line:#353b40}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:36px 28px}h1{font-size:36px;letter-spacing:-1px;margin:8px 0}.intro{color:var(--muted);max-width:750px}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:24px 0;position:sticky;top:0;background:var(--bg);padding:12px 0;z-index:2}button,a{font:inherit;color:inherit}button{border:1px solid var(--line);border-radius:8px;padding:9px 14px;background:var(--card);cursor:pointer}a{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}article{border:1px solid var(--line);background:var(--card);border-radius:14px;padding:18px}article header{display:flex;gap:12px;align-items:baseline}header span{color:var(--muted);font-size:12px}h2{font-size:14px;font-weight:600;margin:0;overflow-wrap:anywhere}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:28px 0 16px}figure{margin:0;display:grid;justify-items:center;gap:14px;align-content:center;min-height:130px}figure svg{width:48px;height:48px;color:var(--ink)}body.large figure svg{width:96px;height:96px}figcaption{color:var(--muted);font-size:12px}details{font-size:12px;color:var(--muted);margin:12px 0}article>a{font-size:12px}.eyebrow{font-size:12px;font-weight:600;letter-spacing:2px;color:var(--muted)}
</style><body><main><div class="eyebrow">PICTOGRAPHIC / AI STROKE REVIEW</div><h1>The next 50 solo icons.</h1><p class="intro">Original conversions beside revised drawings. Consistent 4-unit strokes, smoother curves and rebalanced spacing on the 48 × 48 grid. These are review variants; the original models are preserved.</p><p class="intro">This batch runs from binoculars through buildings. Books and boxes have distinct bindings, page shapes, closures, and perspectives.</p><div class="toolbar"><button id="theme">Dark theme</button><button id="size">Enlarge to 96 px</button><span id="caption">Native size · 48 px</span><a href="index.html?tab=ai&family=solo&q=solo-ai-next50&page_size=96">Open all 50 in the library ↗</a></div><section class="grid">'''+''.join(cards)+'''</section></main><script>document.querySelector('#theme').onclick=function(){document.body.classList.toggle('dark');this.textContent=document.body.classList.contains('dark')?'Light theme':'Dark theme'};document.querySelector('#size').onclick=function(){document.body.classList.toggle('large');let large=document.body.classList.contains('large');this.textContent=large?'Return to 48 px':'Enlarge to 96 px';document.querySelector('#caption').textContent=large?'Enlarged · 96 px':'Native size · 48 px'};</script></body></html>'''
(WORK/'review.html').write_text(page)
report=['# Next 50 solo AI stroke reviews','', '50 independent variants; original Python models preserved. Author value: `gpt-6`.','', 'Selection: standalone subjects from json_to_solo ready icons; small glyphs, abstract operators, and framed devices excluded.','', 'All drawings inspected at native size in light and dark themes. Each new module records original source UUID and path.','', '| Original | Variant | Keyshape | Reference | Changes |','|---|---|---|---|---|']
for r in rows:report.append(f"| {r['parent']} | {r['icon_id']} | {r['keyshape']} | {r['reference'] or 'No useful exact match'} | {r['plan']} |")
(WORK/'README.md').write_text('\n'.join(report)+'\n')
print('Prepared review.html and README.md')
